"""Register Legal Enterprise routes (Sprint 17.0+)."""

from __future__ import annotations

from aiohttp import web

from applications.legal_enterprise.api import (
    aa_handlers,
    cm_handlers,
    cp_handlers,
    di_handlers,
    ei_handlers,
    handlers,
    ji_handlers,
    lec_handlers,
    li_handlers,
)
from applications.legal_enterprise.api.middleware import auth_middleware
from applications.legal_enterprise.config import DEFAULT_CONFIG


def register_legal_enterprise_routes(app: web.Application) -> None:
    prefix = DEFAULT_CONFIG.api_prefix
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    app.router.add_get(f"{prefix}/health", handlers.health_handler)
    app.router.add_post(f"{prefix}/bootstrap", handlers.bootstrap_handler)
    app.router.add_get(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_post(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_get(f"{prefix}/legislation", handlers.legislation_handler)
    app.router.add_post(f"{prefix}/legislation", handlers.legislation_handler)
    app.router.add_get(f"{prefix}/courts", handlers.courts_handler)
    app.router.add_post(f"{prefix}/courts", handlers.courts_handler)
    app.router.add_get(f"{prefix}/cases", handlers.cases_handler)
    app.router.add_post(f"{prefix}/cases", handlers.cases_handler)
    app.router.add_get(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_post(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_get(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_post(f"{prefix}/knowledge", handlers.knowledge_handler)

    # Sprint 17.1 — Legislation Intelligence (additive; prior routes unchanged)
    li = DEFAULT_CONFIG.legislation_intelligence_api_prefix
    app.router.add_get(f"{li}/health", li_handlers.li_health_handler)
    app.router.add_post(f"{li}/bootstrap", li_handlers.li_bootstrap_handler)
    app.router.add_get(f"{li}/repository", li_handlers.li_repository_handler)
    app.router.add_post(f"{li}/repository", li_handlers.li_repository_handler)
    app.router.add_get(f"{li}/versions", li_handlers.li_versions_handler)
    app.router.add_post(f"{li}/versions", li_handlers.li_versions_handler)
    app.router.add_get(f"{li}/regulatory", li_handlers.li_regulatory_handler)
    app.router.add_post(f"{li}/regulatory", li_handlers.li_regulatory_handler)
    app.router.add_get(f"{li}/search", li_handlers.li_search_handler)
    app.router.add_post(f"{li}/search", li_handlers.li_search_handler)
    app.router.add_get(f"{li}/cross-refs", li_handlers.li_cross_refs_handler)
    app.router.add_post(f"{li}/cross-refs", li_handlers.li_cross_refs_handler)
    app.router.add_get(f"{li}/analysis", li_handlers.li_analysis_handler)
    app.router.add_post(f"{li}/analysis", li_handlers.li_analysis_handler)
    app.router.add_get(f"{li}/dashboard", li_handlers.li_dashboard_handler)
    app.router.add_post(f"{li}/dashboard", li_handlers.li_dashboard_handler)
    app.router.add_get(f"{li}/knowledge", li_handlers.li_knowledge_handler)
    app.router.add_post(f"{li}/knowledge", li_handlers.li_knowledge_handler)

    # Sprint 17.2 — Judicial Intelligence (additive; prior routes unchanged)
    ji = DEFAULT_CONFIG.judicial_intelligence_api_prefix
    app.router.add_get(f"{ji}/health", ji_handlers.ji_health_handler)
    app.router.add_post(f"{ji}/bootstrap", ji_handlers.ji_bootstrap_handler)
    app.router.add_get(f"{ji}/repository", ji_handlers.ji_repository_handler)
    app.router.add_post(f"{ji}/repository", ji_handlers.ji_repository_handler)
    app.router.add_get(f"{ji}/search", ji_handlers.ji_search_handler)
    app.router.add_post(f"{ji}/search", ji_handlers.ji_search_handler)
    app.router.add_get(f"{ji}/case-law", ji_handlers.ji_case_law_handler)
    app.router.add_post(f"{ji}/case-law", ji_handlers.ji_case_law_handler)
    app.router.add_get(f"{ji}/judges", ji_handlers.ji_judges_handler)
    app.router.add_post(f"{ji}/judges", ji_handlers.ji_judges_handler)
    app.router.add_get(f"{ji}/analysis", ji_handlers.ji_analysis_handler)
    app.router.add_post(f"{ji}/analysis", ji_handlers.ji_analysis_handler)
    app.router.add_get(f"{ji}/analytics", ji_handlers.ji_analytics_handler)
    app.router.add_post(f"{ji}/analytics", ji_handlers.ji_analytics_handler)
    app.router.add_get(f"{ji}/dashboard", ji_handlers.ji_dashboard_handler)
    app.router.add_post(f"{ji}/dashboard", ji_handlers.ji_dashboard_handler)
    app.router.add_get(f"{ji}/knowledge", ji_handlers.ji_knowledge_handler)
    app.router.add_post(f"{ji}/knowledge", ji_handlers.ji_knowledge_handler)

    # Sprint 17.3 — Case Management Platform (additive; prior routes unchanged)
    cm = DEFAULT_CONFIG.case_management_api_prefix
    app.router.add_get(f"{cm}/health", cm_handlers.cm_health_handler)
    app.router.add_post(f"{cm}/bootstrap", cm_handlers.cm_bootstrap_handler)
    app.router.add_get(f"{cm}/cases", cm_handlers.cm_cases_handler)
    app.router.add_post(f"{cm}/cases", cm_handlers.cm_cases_handler)
    app.router.add_get(f"{cm}/calendar", cm_handlers.cm_calendar_handler)
    app.router.add_post(f"{cm}/calendar", cm_handlers.cm_calendar_handler)
    app.router.add_get(f"{cm}/deadlines", cm_handlers.cm_deadlines_handler)
    app.router.add_post(f"{cm}/deadlines", cm_handlers.cm_deadlines_handler)
    app.router.add_get(f"{cm}/tasks", cm_handlers.cm_tasks_handler)
    app.router.add_post(f"{cm}/tasks", cm_handlers.cm_tasks_handler)
    app.router.add_get(f"{cm}/documents", cm_handlers.cm_documents_handler)
    app.router.add_post(f"{cm}/documents", cm_handlers.cm_documents_handler)
    app.router.add_get(f"{cm}/ai", cm_handlers.cm_ai_handler)
    app.router.add_post(f"{cm}/ai", cm_handlers.cm_ai_handler)
    app.router.add_get(f"{cm}/dashboard", cm_handlers.cm_dashboard_handler)
    app.router.add_post(f"{cm}/dashboard", cm_handlers.cm_dashboard_handler)
    app.router.add_get(f"{cm}/knowledge", cm_handlers.cm_knowledge_handler)
    app.router.add_post(f"{cm}/knowledge", cm_handlers.cm_knowledge_handler)

    # Sprint 17.4 — Document Intelligence (additive; prior routes unchanged)
    di = DEFAULT_CONFIG.document_intelligence_api_prefix
    app.router.add_get(f"{di}/health", di_handlers.di_health_handler)
    app.router.add_post(f"{di}/bootstrap", di_handlers.di_bootstrap_handler)
    app.router.add_get(f"{di}/contracts", di_handlers.di_contracts_handler)
    app.router.add_post(f"{di}/contracts", di_handlers.di_contracts_handler)
    app.router.add_get(f"{di}/ingest", di_handlers.di_ingest_handler)
    app.router.add_post(f"{di}/ingest", di_handlers.di_ingest_handler)
    app.router.add_get(f"{di}/clauses", di_handlers.di_clauses_handler)
    app.router.add_post(f"{di}/clauses", di_handlers.di_clauses_handler)
    app.router.add_get(f"{di}/risk", di_handlers.di_risk_handler)
    app.router.add_post(f"{di}/risk", di_handlers.di_risk_handler)
    app.router.add_get(f"{di}/comparison", di_handlers.di_comparison_handler)
    app.router.add_post(f"{di}/comparison", di_handlers.di_comparison_handler)
    app.router.add_get(f"{di}/drafting", di_handlers.di_drafting_handler)
    app.router.add_post(f"{di}/drafting", di_handlers.di_drafting_handler)
    app.router.add_get(f"{di}/dashboard", di_handlers.di_dashboard_handler)
    app.router.add_post(f"{di}/dashboard", di_handlers.di_dashboard_handler)
    app.router.add_get(f"{di}/knowledge", di_handlers.di_knowledge_handler)
    app.router.add_post(f"{di}/knowledge", di_handlers.di_knowledge_handler)

    # Sprint 17.5 — Compliance Platform (additive; prior routes unchanged)
    cp = DEFAULT_CONFIG.compliance_api_prefix
    app.router.add_get(f"{cp}/health", cp_handlers.cp_health_handler)
    app.router.add_post(f"{cp}/bootstrap", cp_handlers.cp_bootstrap_handler)
    app.router.add_get(f"{cp}/governance", cp_handlers.cp_governance_handler)
    app.router.add_post(f"{cp}/governance", cp_handlers.cp_governance_handler)
    app.router.add_get(f"{cp}/compliance", cp_handlers.cp_compliance_handler)
    app.router.add_post(f"{cp}/compliance", cp_handlers.cp_compliance_handler)
    app.router.add_get(f"{cp}/licenses", cp_handlers.cp_licenses_handler)
    app.router.add_post(f"{cp}/licenses", cp_handlers.cp_licenses_handler)
    app.router.add_get(f"{cp}/counterparties", cp_handlers.cp_counterparties_handler)
    app.router.add_post(f"{cp}/counterparties", cp_handlers.cp_counterparties_handler)
    app.router.add_get(f"{cp}/aml", cp_handlers.cp_aml_handler)
    app.router.add_post(f"{cp}/aml", cp_handlers.cp_aml_handler)
    app.router.add_get(f"{cp}/risk", cp_handlers.cp_risk_handler)
    app.router.add_post(f"{cp}/risk", cp_handlers.cp_risk_handler)
    app.router.add_get(f"{cp}/ai", cp_handlers.cp_ai_handler)
    app.router.add_post(f"{cp}/ai", cp_handlers.cp_ai_handler)
    app.router.add_get(f"{cp}/dashboard", cp_handlers.cp_dashboard_handler)
    app.router.add_post(f"{cp}/dashboard", cp_handlers.cp_dashboard_handler)
    app.router.add_get(f"{cp}/knowledge", cp_handlers.cp_knowledge_handler)
    app.router.add_post(f"{cp}/knowledge", cp_handlers.cp_knowledge_handler)

    # Sprint 17.6 — AI Legal Assistant (additive; prior routes unchanged)
    aa = DEFAULT_CONFIG.ai_legal_assistant_api_prefix
    app.router.add_get(f"{aa}/health", aa_handlers.aa_health_handler)
    app.router.add_post(f"{aa}/bootstrap", aa_handlers.aa_bootstrap_handler)
    app.router.add_get(f"{aa}/assistant", aa_handlers.aa_assistant_handler)
    app.router.add_post(f"{aa}/assistant", aa_handlers.aa_assistant_handler)
    app.router.add_get(f"{aa}/research", aa_handlers.aa_research_handler)
    app.router.add_post(f"{aa}/research", aa_handlers.aa_research_handler)
    app.router.add_get(f"{aa}/analysis", aa_handlers.aa_analysis_handler)
    app.router.add_post(f"{aa}/analysis", aa_handlers.aa_analysis_handler)
    app.router.add_get(f"{aa}/opinion", aa_handlers.aa_opinion_handler)
    app.router.add_post(f"{aa}/opinion", aa_handlers.aa_opinion_handler)
    app.router.add_get(f"{aa}/documents", aa_handlers.aa_documents_handler)
    app.router.add_post(f"{aa}/documents", aa_handlers.aa_documents_handler)
    app.router.add_get(f"{aa}/knowledge", aa_handlers.aa_knowledge_handler)
    app.router.add_post(f"{aa}/knowledge", aa_handlers.aa_knowledge_handler)
    app.router.add_get(f"{aa}/explain", aa_handlers.aa_explain_handler)
    app.router.add_post(f"{aa}/explain", aa_handlers.aa_explain_handler)
    app.router.add_get(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)
    app.router.add_post(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)

    # Sprint 17.7 — Executive Legal Intelligence (additive; prior routes unchanged)
    ei = DEFAULT_CONFIG.executive_intelligence_api_prefix
    app.router.add_get(f"{ei}/health", ei_handlers.ei_health_handler)
    app.router.add_post(f"{ei}/bootstrap", ei_handlers.ei_bootstrap_handler)
    app.router.add_get(f"{ei}/executive", ei_handlers.ei_executive_handler)
    app.router.add_post(f"{ei}/executive", ei_handlers.ei_executive_handler)
    app.router.add_get(f"{ei}/analytics", ei_handlers.ei_analytics_handler)
    app.router.add_post(f"{ei}/analytics", ei_handlers.ei_analytics_handler)
    app.router.add_get(f"{ei}/risk", ei_handlers.ei_risk_handler)
    app.router.add_post(f"{ei}/risk", ei_handlers.ei_risk_handler)
    app.router.add_get(f"{ei}/forecast", ei_handlers.ei_forecast_handler)
    app.router.add_post(f"{ei}/forecast", ei_handlers.ei_forecast_handler)
    app.router.add_get(f"{ei}/decisions", ei_handlers.ei_decisions_handler)
    app.router.add_post(f"{ei}/decisions", ei_handlers.ei_decisions_handler)
    app.router.add_get(f"{ei}/ai", ei_handlers.ei_ai_handler)
    app.router.add_post(f"{ei}/ai", ei_handlers.ei_ai_handler)
    app.router.add_get(f"{ei}/alerts", ei_handlers.ei_alerts_handler)
    app.router.add_post(f"{ei}/alerts", ei_handlers.ei_alerts_handler)
    app.router.add_get(f"{ei}/knowledge", ei_handlers.ei_knowledge_handler)
    app.router.add_post(f"{ei}/knowledge", ei_handlers.ei_knowledge_handler)
    app.router.add_get(f"{ei}/dashboard", ei_handlers.ei_dashboard_handler)
    app.router.add_post(f"{ei}/dashboard", ei_handlers.ei_dashboard_handler)

    # Sprint 17.8 — Enterprise Certification (additive; prior routes unchanged)
    lec = DEFAULT_CONFIG.enterprise_certification_api_prefix
    app.router.add_get(f"{lec}/health", lec_handlers.lec_health_handler)
    app.router.add_post(f"{lec}/bootstrap", lec_handlers.lec_bootstrap_handler)
    app.router.add_get(f"{lec}/architecture", lec_handlers.lec_architecture_handler)
    app.router.add_get(f"{lec}/integration", lec_handlers.lec_integration_handler)
    app.router.add_get(f"{lec}/performance", lec_handlers.lec_performance_handler)
    app.router.add_get(f"{lec}/security", lec_handlers.lec_security_handler)
    app.router.add_get(f"{lec}/documentation", lec_handlers.lec_documentation_handler)
    app.router.add_get(f"{lec}/quality", lec_handlers.lec_quality_handler)
    app.router.add_get(f"{lec}/release", lec_handlers.lec_release_handler)
    app.router.add_get(f"{lec}/executive", lec_handlers.lec_executive_handler)
    app.router.add_get(f"{lec}/dashboard", lec_handlers.lec_dashboard_handler)
    app.router.add_post(f"{lec}/dashboard", lec_handlers.lec_dashboard_handler)

    # Sprint 51.0 — Lawyer Operator Desk (durable CRM subset)
    from applications.legal_enterprise.api import ops_handlers

    ops = "/api/legal-ops/v1"
    app.router.add_get(f"{ops}/health", ops_handlers.ops_health_handler)
    app.router.add_get(f"{ops}/roles", ops_handlers.ops_roles_handler)
    app.router.add_get(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_post(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_get(f"{ops}/clients", ops_handlers.ops_clients_handler)
    app.router.add_post(f"{ops}/clients", ops_handlers.ops_clients_handler)
    app.router.add_get(f"{ops}/cases", ops_handlers.ops_cases_handler)
    app.router.add_post(f"{ops}/cases", ops_handlers.ops_cases_handler)
    app.router.add_get(f"{ops}/cases/{{case_id}}", ops_handlers.ops_case_detail_handler)
    app.router.add_get(f"{ops}/contracts", ops_handlers.ops_contracts_handler)
    app.router.add_post(f"{ops}/contracts", ops_handlers.ops_contracts_handler)
    app.router.add_post(f"{ops}/contracts/{{contract_id}}", ops_handlers.ops_contract_update_handler)
    app.router.add_patch(f"{ops}/contracts/{{contract_id}}", ops_handlers.ops_contract_update_handler)
    app.router.add_get(f"{ops}/documents", ops_handlers.ops_documents_handler)
    app.router.add_post(f"{ops}/documents", ops_handlers.ops_documents_handler)
    app.router.add_get(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks/{{task_id}}/complete", ops_handlers.ops_task_complete_handler)
    app.router.add_get(f"{ops}/hearings", ops_handlers.ops_hearings_handler)
    app.router.add_post(f"{ops}/hearings", ops_handlers.ops_hearings_handler)
    app.router.add_get(f"{ops}/calendar", ops_handlers.ops_calendar_handler)
    app.router.add_post(f"{ops}/calendar", ops_handlers.ops_calendar_handler)
    app.router.add_post(f"{ops}/calendar/sync", ops_handlers.ops_calendar_sync_handler)
    app.router.add_get(f"{ops}/integrations/google-calendar", ops_handlers.ops_gcal_status_handler)
    app.router.add_get(f"{ops}/activity", ops_handlers.ops_activity_handler)
    app.router.add_get(f"{ops}/ai/catalog", ops_handlers.ops_ai_catalog_handler)
    app.router.add_get(f"{ops}/ai/actions", ops_handlers.ops_ai_catalog_handler)
    app.router.add_get(f"{ops}/ai/modes", ops_handlers.ops_ai_catalog_handler)
    app.router.add_get(f"{ops}/ai/context", ops_handlers.ops_ai_context_handler)
    app.router.add_post(f"{ops}/ai/context", ops_handlers.ops_ai_context_handler)
    app.router.add_post(f"{ops}/ai/analyze", ops_handlers.ops_ai_handler)
    app.router.add_post(f"{ops}/ai/lawyer/run", ops_handlers.ops_ai_lawyer_handler)
    app.router.add_get(f"{ops}/ai/analyses", ops_handlers.ops_ai_analyses_handler)
    app.router.add_get(f"{ops}/ai/analyses/{{analysis_id}}", ops_handlers.ops_ai_analysis_detail_handler)
    app.router.add_post(f"{ops}/ai/analyses/{{analysis_id}}/archive", ops_handlers.ops_ai_analysis_archive_handler)
    app.router.add_post(f"{ops}/ai/analyses/{{analysis_id}}/actions", ops_handlers.ops_ai_analysis_action_handler)
    app.router.add_post(f"{ops}/ai/drafts/{{document_id}}", ops_handlers.ops_ai_draft_update_handler)
    app.router.add_post(f"{ops}/ai/drafts/{{document_id}}/regenerate", ops_handlers.ops_ai_draft_regen_handler)
    app.router.add_get(f"{ops}/entities/{{kind}}/{{item_id}}", ops_handlers.ops_entity_get_handler)
    app.router.add_get(f"{ops}/entities/{{kind}}/{{item_id}}/related", ops_handlers.ops_related_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}", ops_handlers.ops_entity_update_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}/archive", ops_handlers.ops_entity_archive_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}/restore", ops_handlers.ops_entity_restore_handler)
    app.router.add_post(f"{ops}/cases/{{case_id}}", ops_handlers.ops_case_update_handler)
    app.router.add_get(f"{ops}/archive", ops_handlers.ops_archive_list_handler)
    app.router.add_get(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_post(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_get(f"{ops}/files/{{file_id}}/content", ops_handlers.ops_file_content_handler)
    app.router.add_post(f"{ops}/files/{{file_id}}/replace", ops_handlers.ops_file_replace_handler)
    app.router.add_post(f"{ops}/files/{{file_id}}/link", ops_handlers.ops_file_link_handler)
    app.router.add_post(f"{ops}/files/{{file_id}}/rename", ops_handlers.ops_file_rename_handler)
    app.router.add_get(f"{ops}/inbox", ops_handlers.ops_inbox_handler)
    app.router.add_get(f"{ops}/notifications", ops_handlers.ops_notifications_handler)
    app.router.add_get(f"{ops}/integrations/calendars", ops_handlers.ops_integrations_handler)
    app.router.add_post(f"{ops}/integrations/google-calendar/connect", ops_handlers.ops_gcal_connect_handler)
    app.router.add_get(f"{ops}/integrations/google-calendar/callback", ops_handlers.ops_gcal_callback_handler)
    app.router.add_post(f"{ops}/integrations/google-calendar/disconnect", ops_handlers.ops_gcal_disconnect_handler)
    app.router.add_get(f"{ops}/integrations/health", ops_handlers.ops_integrations_health_handler)
    app.router.add_get(f"{ops}/providers", ops_handlers.ops_providers_handler)
    app.router.add_get(f"{ops}/monitoring/watchlist", ops_handlers.ops_watchlist_handler)
    app.router.add_post(f"{ops}/monitoring/watchlist", ops_handlers.ops_watchlist_handler)
    app.router.add_post(f"{ops}/monitoring/watchlist/{{watchlist_id}}", ops_handlers.ops_watchlist_update_handler)
    app.router.add_post(f"{ops}/monitoring/watchlist/{{watchlist_id}}/check", ops_handlers.ops_watchlist_check_handler)
    app.router.add_get(f"{ops}/monitoring/changes", ops_handlers.ops_monitor_changes_handler)
    app.router.add_post(f"{ops}/monitoring/changes/{{change_id}}/actions", ops_handlers.ops_monitor_change_action_handler)
    app.router.add_get(f"{ops}/monitoring/enforcement", ops_handlers.ops_enforcement_handler)
    app.router.add_post(f"{ops}/monitoring/enforcement", ops_handlers.ops_enforcement_handler)
    app.router.add_post(f"{ops}/monitoring/enforcement/{{enforcement_id}}", ops_handlers.ops_enforcement_update_handler)
    app.router.add_get(f"{ops}/monitoring/settings", ops_handlers.ops_monitor_settings_handler)
    app.router.add_post(f"{ops}/monitoring/settings", ops_handlers.ops_monitor_settings_handler)
    app.router.add_post(f"{ops}/calendar/{{event_id}}/sync-google", ops_handlers.ops_calendar_sync_mapped_handler)
    app.router.add_get(f"{ops}/reminders", ops_handlers.ops_reminders_handler)
