export const webConfig = {
  application: "enterprise_web_platform",
  version: "9.4.0",
  sprint: "32.3.6",
  apiBase: import.meta.env.VITE_API_BASE || "/api",
  hubPrefix: "/api/enterprise-hub/v1",
  ewfPrefix: "/api/enterprise-ewf/v1",
  edsPrefix: "/api/enterprise-eds/v1",
  eicPrefix: "/api/enterprise-eic/v1",
  ewsPrefix: "/api/enterprise-ews/v1",
  enpPrefix: "/api/enterprise-enp/v1",
  autoPrefix: "/api/auto/v1",
  beautyOsPrefix: "/api/enterprise-bos/v1",
  beautyWorkspacePrefix: "/api/enterprise-bws/v1",
  beautyClientJourneyPrefix: "/api/enterprise-bcj/v1",
  cafeOsPrefix: "/api/enterprise-cos/v1",
  agroPrefix: "/api/agro/v1",
  agroSupplyChainPrefix: "/api/agro-supply-chain/v1",
  agroEnterprisePrefix: "/api/agro-enterprise/v1",
  agroFinancePrefix: "/api/agro-finance/v1",
  aiAgronomistPrefix: "/api/ai-agronomist/v1",
  legalEnterprisePrefix: "/api/legal-enterprise/v1",
  legalCasePrefix: "/api/legal-cm/v1",
  legalDocumentsPrefix: "/api/legal-di/v1",
  legalCompliancePrefix: "/api/legal-cp/v1",
  legalAiPrefix: "/api/legal-aa/v1",
  legalExecutivePrefix: "/api/legal-ei/v1",
  financeDigitalAssetsPrefix: "/api/finance-da/v1",
  financePaymentsPrefix: "/api/finance-pay/v1",
  financeTreasuryPrefix: "/api/finance-tr/v1",
  financeIntegrationPrefix: "/api/finance-int/v1",
  financeCfoPrefix: "/api/finance-cfo/v1",
  cryptoEnterprisePrefix: "/api/crypto-enterprise/v1",
  cryptoRiskPrefix: "/api/crypto-rm/v1",
  dronePrefix: "/api/drone/v1",
  precisionAgriculturePrefix: "/api/precision-agriculture/v1",
  aiMarketingOsPrefix: "/api/enterprise-amo/v1",
  commerceCorePrefix: "/api/enterprise-eco/v1",
  commsPrefix: "/api/enterprise-comms/v1",
  platformBuilderPrefix: "/api/platform-builder/v1",
  identityLoginPath: "/management/identity/login",
  identityRefreshPath: "/management/identity/refresh",
  /** Maps owner@* emails to platform IAM telegram id when minting JWT. */
  defaultTelegramId: Number(import.meta.env.VITE_OWNER_TELEGRAM_ID || 1208044579),
  socketUrl: import.meta.env.VITE_SOCKET_URL || "",
  defaultLocale: "en" as const,
  supportedLocales: ["en", "ru", "uk"] as const,
  multiTenant: true,
  mfaReady: true,
  /** Posts to existing Enterprise Observability — disable in offline CI if needed. */
  telemetryEnabled: import.meta.env.VITE_TELEMETRY_ENABLED !== "false",
};
