import type { MenuItem } from "../types";

const menu: MenuItem[] = [
  {
    id: "nav_workspace",
    name: "Workspace",
    icon: "workspace",
    route: "/workspace",
    module: "workspace",
    permissions: ["read"],
    status: "active",
    group: "core",
  },
  {
    id: "nav_identity",
    name: "Identity",
    icon: "security",
    route: "/identity",
    module: "identity",
    permissions: ["admin"],
    badge: "RBAC",
    status: "active",
    group: "core",
    children: [
      { id: "nav_users", name: "Users", icon: "crm", route: "/identity/users", module: "identity", permissions: ["admin"], status: "active" },
      { id: "nav_orgs", name: "Organizations", icon: "erp", route: "/identity/organizations", module: "identity", permissions: ["admin"], status: "active" },
    ],
  },
  {
    id: "nav_ai",
    name: "AI Platform",
    icon: "ai",
    route: "/workspace/dashboards/dash_ai",
    module: "ai",
    permissions: ["read"],
    status: "active",
    group: "intelligence",
    children: [
      { id: "nav_ai_agents", name: "Agents", icon: "ai", route: "/workspace/ai", module: "ai", permissions: ["read"], status: "active" },
    ],
  },
  {
    id: "nav_crm",
    name: "CRM",
    icon: "crm",
    route: "/workspace/crm",
    module: "crm",
    permissions: ["crm", "read"],
    status: "active",
    group: "business",
  },
  {
    id: "nav_erp",
    name: "ERP",
    icon: "erp",
    route: "/workspace/erp",
    module: "erp",
    permissions: ["erp", "read"],
    status: "active",
    group: "business",
  },
  {
    id: "nav_finance",
    name: "Finance",
    icon: "finance",
    route: "/workspace/finance",
    module: "finance",
    permissions: ["finance", "read"],
    status: "active",
    group: "business",
  },
  {
    id: "nav_analytics",
    name: "Analytics",
    icon: "analytics",
    route: "/workspace/analytics",
    module: "analytics",
    permissions: ["read"],
    status: "active",
    group: "intelligence",
  },
  {
    id: "nav_market",
    name: "Marketplace",
    icon: "workflow",
    route: "/platform-builder/solution-hub",
    module: "marketplace",
    permissions: ["read"],
    badge: "new",
    status: "beta",
    group: "platform",
  },
  {
    id: "nav_portals",
    name: "Portals",
    icon: "workspace",
    route: "/portals/customer",
    module: "portals",
    permissions: ["read"],
    badge: "pilot",
    status: "active",
    group: "business",
    children: [
      { id: "nav_portal_customer", name: "Customer Portal", icon: "crm", route: "/portals/customer", module: "portals", permissions: ["read"], status: "active" },
      { id: "nav_portal_employee", name: "Employee Portal", icon: "erp", route: "/portals/employee", module: "portals", permissions: ["read"], status: "active" },
      { id: "nav_portal_owner", name: "Owner Portal", icon: "analytics", route: "/portals/owner", module: "portals", permissions: ["read"], status: "active" },
      { id: "nav_portal_mission", name: "Mission Control", icon: "analytics", route: "/portals/mission-control", module: "portals", permissions: ["read"], status: "active" },
      { id: "nav_portal_pilot", name: "Pilot Dashboard", icon: "analytics", route: "/pilot", module: "portals", permissions: ["read"], status: "active" },
    ],
  },
  {
    id: "nav_ecosystems",
    name: "Business Ecosystems",
    icon: "erp",
    route: "/platform-builder/business-ecosystem",
    module: "ecosystems",
    permissions: ["read"],
    badge: "30.4",
    status: "active",
    group: "ecosystems",
    children: [
      { id: "nav_eco_auto", name: "Automotive", icon: "crm", route: "/workspace/auto", module: "auto", permissions: ["read"], status: "active" },
      { id: "nav_eco_beauty", name: "Beauty", icon: "crm", route: "/workspace/beauty", module: "beauty", permissions: ["read"], status: "active" },
      { id: "nav_eco_cafe", name: "Cafe", icon: "crm", route: "/workspace/cafe", module: "cafe", permissions: ["read"], status: "active" },
      { id: "nav_eco_agro", name: "Agriculture", icon: "erp", route: "/workspace/agro", module: "agro", permissions: ["read"], status: "active" },
      { id: "nav_eco_drone", name: "Drone", icon: "analytics", route: "/workspace/drone", module: "drone", permissions: ["read"], status: "active" },
      { id: "nav_eco_legal", name: "Legal", icon: "security", route: "/workspace/legal", module: "legal", permissions: ["read"], status: "active" },
      { id: "nav_eco_crypto", name: "Crypto (Bidex)", icon: "finance", route: "/workspace/crypto", module: "crypto", permissions: ["read"], status: "active" },
    ],
  },
  {
    id: "nav_navigation",
    name: "Navigation",
    icon: "navigation",
    route: "/navigation",
    module: "navigation",
    permissions: ["read"],
    status: "active",
    group: "platform",
  },
  {
    id: "nav_platform_builder",
    name: "Platform Builder",
    icon: "workflow",
    route: "/platform-builder",
    module: "platform_builder",
    permissions: ["read", "builder"],
    badge: "new",
    status: "active",
    group: "platform",
    children: [
      { id: "nav_pb_dash", name: "Dashboard", icon: "analytics", route: "/platform-builder", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_framework", name: "Universal Framework", icon: "workflow", route: "/platform-builder/framework", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_vertical", name: "Vertical Builder", icon: "erp", route: "/platform-builder/vertical", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_ai", name: "AI Builder", icon: "ai", route: "/platform-builder/ai", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_concierge", name: "Concierge Builder", icon: "ai", route: "/platform-builder/concierge", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_ai_team", name: "AI Team Center", icon: "ai", route: "/platform-builder/ai-team", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_collab", name: "Collaborative AI", icon: "ai", route: "/platform-builder/collaborative-ai", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_ops", name: "AI Operations Center", icon: "analytics", route: "/platform-builder/operations", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_team_map", name: "AI Team Map", icon: "ai", route: "/platform-builder/team-map", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_visual_behavior", name: "Visual Behavior", icon: "analytics", route: "/platform-builder/visual-behavior", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_rendering", name: "Visual Rendering", icon: "analytics", route: "/platform-builder/rendering", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_themes", name: "Visual Themes", icon: "analytics", route: "/platform-builder/themes", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_assets", name: "Visual Assets", icon: "analytics", route: "/platform-builder/assets", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_simulation", name: "Visual Simulation", icon: "analytics", route: "/platform-builder/simulation", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_director", name: "Visual Director", icon: "analytics", route: "/platform-builder/director", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_story", name: "Visual Stories", icon: "analytics", route: "/platform-builder/story", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_intelligence", name: "Visual Intelligence", icon: "analytics", route: "/platform-builder/intelligence", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_experience", name: "Visual Experience", icon: "analytics", route: "/platform-builder/experience", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_workspace_os", name: "Workspace OS", icon: "analytics", route: "/platform-builder/workspace-os", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_command_center", name: "Command Center OS", icon: "analytics", route: "/platform-builder/command-center", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_nav_intel", name: "Navigation Intelligence", icon: "analytics", route: "/platform-builder/navigation-intelligence", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_workflow_intel", name: "Workflow Intelligence", icon: "workflow", route: "/platform-builder/workflow-intelligence", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_digital_twin", name: "Digital Twin", icon: "analytics", route: "/platform-builder/digital-twin", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_enterprise_twin", name: "Enterprise Twin", icon: "analytics", route: "/enterprise-twin", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_integrations", name: "Integrations", icon: "settings", route: "/platform-builder/integrations", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_runtime", name: "AI Runtime", icon: "ai", route: "/platform-builder/runtime", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_data_fabric", name: "Data Fabric", icon: "analytics", route: "/platform-builder/data-fabric", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_predictive", name: "Predictive", icon: "analytics", route: "/platform-builder/predictive", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_autonomy", name: "Autonomy", icon: "ai", route: "/platform-builder/autonomy", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_control_tower", name: "Control Tower", icon: "analytics", route: "/platform-builder/control-tower", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_twin_intelligence", name: "Twin Intelligence", icon: "analytics", route: "/platform-builder/twin-intelligence", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_strategy", name: "Strategy Engine", icon: "analytics", route: "/platform-builder/strategy", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_mission_control", name: "Mission Control", icon: "analytics", route: "/platform-builder/mission-control", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_business_ecosystem", name: "Business Ecosystems", icon: "analytics", route: "/platform-builder/business-ecosystem", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_crm", name: "CRM Builder", icon: "crm", route: "/platform-builder/crm", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_erp", name: "ERP Builder", icon: "erp", route: "/platform-builder/erp", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_workflow", name: "Workflow Builder", icon: "workflow", route: "/platform-builder/workflow", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_knowledge", name: "Knowledge Builder", icon: "analytics", route: "/platform-builder/knowledge", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_automation", name: "Automation Builder", icon: "workflow", route: "/platform-builder/automation", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_dash_builder", name: "Dashboard Builder", icon: "analytics", route: "/platform-builder/dashboard-builder", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_template", name: "Template Builder", icon: "workflow", route: "/platform-builder/template", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_marketplace", name: "Marketplace Builder", icon: "workflow", route: "/platform-builder/marketplace", module: "platform_builder", permissions: ["read"], status: "beta" },
      { id: "nav_pb_academy", name: "Builder Academy 2.0", icon: "analytics", route: "/platform-builder/academy", module: "platform_builder", permissions: ["read"], status: "active" },
      { id: "nav_pb_god", name: "God Mode", icon: "security", route: "/platform-builder/god-mode", module: "platform_builder", permissions: ["platform_owner"], status: "active" },
    ],
  },
  {
    id: "nav_settings",
    name: "Settings",
    icon: "settings",
    route: "/settings",
    module: "settings",
    permissions: ["read"],
    status: "active",
    group: "core",
  },
];

function permitted(item: MenuItem, permissions: string[]): boolean {
  if (permissions.includes("admin") || permissions.includes("platform_owner")) return true;
  return item.permissions.some((p) => permissions.includes(p));
}

export const menuEngine = {
  all(): MenuItem[] {
    return structuredClone(menu);
  },
  forTenant(tenantId: string, permissions: string[]): MenuItem[] {
    const filterItem = (item: MenuItem): MenuItem | null => {
      if (item.tenantIds && !item.tenantIds.includes(tenantId)) return null;
      if (!permitted(item, permissions)) return null;
      const children = item.children?.map(filterItem).filter(Boolean) as MenuItem[] | undefined;
      return { ...item, children };
    };
    return menu.map(filterItem).filter(Boolean) as MenuItem[];
  },
  groups() {
    return [...new Set(menu.map((m) => m.group).filter(Boolean))] as string[];
  },
  nested(): MenuItem[] {
    return this.all().filter((m) => (m.children?.length || 0) > 0);
  },
  megaGroups() {
    return this.groups().map((g) => ({
      group: g,
      items: menu.filter((m) => m.group === g),
    }));
  },
};
