import type { SearchDocument } from "../types";

let documents: SearchDocument[] = [
  { id: "idx_hub_crm", category: "crm", title: "CRM · Клиенты", path: "/crm", tokens: ["crm", "клиенты", "clients", "pipeline", "module"], rankBoost: 12 },
  { id: "idx_hub_erp", category: "erp", title: "ERP", path: "/erp", tokens: ["erp", "операции", "operations", "module"], rankBoost: 12 },
  { id: "idx_hub_projects", category: "projects", title: "Проекты", path: "/projects", tokens: ["проекты", "projects", "delivery", "module"], rankBoost: 12 },
  { id: "idx_hub_ai_studio", category: "modules", title: "AI-Студия", path: "/ai-studio", tokens: ["ai", "студия", "studio", "builder"], rankBoost: 12 },
  { id: "idx_hub_ai_agents", category: "ai_agents", title: "AI-Агенты", path: "/ai-agents", tokens: ["ai", "агенты", "agents", "team"], rankBoost: 12 },
  { id: "idx_hub_knowledge", category: "knowledge", title: "База знаний", path: "/knowledge", tokens: ["знания", "knowledge", "kb", "playbooks"], rankBoost: 12 },
  { id: "idx_hub_documents", category: "documents", title: "Документы", path: "/documents", tokens: ["документы", "documents", "docs", "files"], rankBoost: 12 },
  { id: "idx_hub_analytics", category: "modules", title: "Аналитика", path: "/analytics", tokens: ["аналитика", "analytics", "kpi", "reports"], rankBoost: 12 },
  { id: "idx_hub_marketplace", category: "marketplace", title: "Маркетинг", path: "/marketplace", tokens: ["маркетинг", "marketplace", "solutions"], rankBoost: 12 },
  { id: "idx_hub_automation", category: "workflows", title: "Автоматизация", path: "/automation", tokens: ["автоматизация", "automation", "workflow"], rankBoost: 11 },
  { id: "idx_hub_integrations", category: "modules", title: "Интеграции", path: "/integrations", tokens: ["интеграции", "integrations", "providers", "mcp"], rankBoost: 11 },
  { id: "idx_hub_security", category: "modules", title: "Безопасность", path: "/security", tokens: ["безопасность", "security", "identity"], rankBoost: 11 },
  { id: "idx_hub_settings", category: "modules", title: "Настройки", path: "/settings", tokens: ["настройки", "settings", "theme", "session"], rankBoost: 11 },
  { id: "idx_hub_search", category: "commands", title: "Поиск", path: "/search", tokens: ["поиск", "search", "find", "command"], rankBoost: 11 },
  { id: "idx_cmd_create_client", category: "commands", title: "Создать клиента", path: "/crm?action=create_client", tokens: ["создать", "клиент", "create", "client", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_project", category: "commands", title: "Создать проект", path: "/projects?action=create_project", tokens: ["создать", "проект", "create", "project", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_task", category: "commands", title: "Создать задачу", path: "/tasks", tokens: ["создать", "задача", "create", "task", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_document", category: "commands", title: "Создать документ", path: "/documents?action=create_document", tokens: ["создать", "документ", "create", "document", "command"], rankBoost: 9 },
  { id: "idx_cmd_run_ai", category: "commands", title: "Запустить AI", path: "/ai-agents?action=create", tokens: ["запустить", "ai", "агент", "command"], rankBoost: 9 },
  { id: "idx_cmd_open_map", category: "commands", title: "Открыть карту", path: "/city", tokens: ["карта", "город", "map", "city", "command", "enterprise-city"], rankBoost: 9 },
  { id: "idx_cmd_open_module", category: "commands", title: "Открыть модуль", path: "/search", tokens: ["модуль", "открыть", "навигация", "command"], rankBoost: 10 },
  { id: "idx_cmd_open_client", category: "commands", title: "Открыть клиента", path: "/crm?view=clients", tokens: ["клиент", "открыть", "crm", "command"], rankBoost: 10 },
  { id: "idx_cmd_open_project", category: "commands", title: "Открыть проект", path: "/projects", tokens: ["проект", "открыть", "command"], rankBoost: 10 },
  { id: "idx_cmd_open_ai", category: "commands", title: "Открыть AI-агента", path: "/ai-agents", tokens: ["ai", "агент", "открыть", "command"], rankBoost: 10 },
  { id: "idx_hub_calendar", category: "modules", title: "Календарь", path: "/calendar", tokens: ["календарь", "calendar"], rankBoost: 11 },
  { id: "idx_hub_tasks", category: "tasks", title: "Задачи", path: "/tasks", tokens: ["задачи", "tasks"], rankBoost: 11 },
  { id: "idx_hub_notifications", category: "modules", title: "Уведомления", path: "/notifications", tokens: ["уведомления", "notifications"], rankBoost: 11 },
  { id: "idx_admin", category: "dashboards", title: "Панель администратора", path: "/admin", tokens: ["админ", "admin", "dashboard"], rankBoost: 12 },
  { id: "idx_cmd_create_agent", category: "commands", title: "Создать AI-агента", path: "/ai-agents?action=create", tokens: ["создать", "агент", "ai", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_workflow", category: "commands", title: "Создать процесс", path: "/automation?action=create_workflow", tokens: ["создать", "процесс", "workflow", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_knowledge", category: "commands", title: "Создать страницу знаний", path: "/knowledge?action=create", tokens: ["создать", "знания", "knowledge", "command"], rankBoost: 9 },
  { id: "idx_cmd_create_company", category: "commands", title: "Создать компанию", path: "/identity/organizations?action=create_company", tokens: ["создать", "компания", "company", "org", "command"], rankBoost: 9 },
  { id: "idx_mod_ws", category: "modules", title: "Рабочее пространство", path: "/workspace", tokens: ["workspace", "пространство", "home"], rankBoost: 10 },
  { id: "idx_owner", category: "dashboards", title: "Панель владельца", path: "/owner", tokens: ["владелец", "owner", "dashboard"], rankBoost: 12 },
  { id: "idx_user", category: "users", title: "Пользователи", path: "/identity/users", tokens: ["пользователи", "users"], rankBoost: 5 },
  { id: "idx_org", category: "organizations", title: "Demo Corp", path: "/identity/organizations", tokens: ["demo", "corp", "компания", "org"], rankBoost: 5 },
  { id: "idx_proj", category: "projects", title: "Enterprise Web", path: "/workspace/list", tokens: ["проект", "project", "web"], rankBoost: 4 },
  { id: "idx_doc", category: "documents", title: "Политика безопасности", path: "/workspace/docs", tokens: ["безопасность", "политика", "doc", "documents"], rankBoost: 3 },
  { id: "idx_crm", category: "crm", title: "Воронка CRM", path: "/workspace/crm", tokens: ["crm", "воронка", "pipeline", "leads"], rankBoost: 6 },
  { id: "idx_erp", category: "erp", title: "Склад ERP", path: "/workspace/erp", tokens: ["erp", "склад", "inventory"], rankBoost: 6 },
  { id: "idx_fin", category: "finance", title: "Финансы", path: "/workspace/finance", tokens: ["финансы", "finance", "billing"], rankBoost: 6 },
  { id: "idx_hr", category: "hr", title: "Рекрутинг", path: "/workspace/recruiting", tokens: ["hr", "people", "рекрутинг", "найм", "лиды", "кандидаты"], rankBoost: 8 },
  { id: "idx_ai", category: "ai_agents", title: "Ops Copilot", path: "/workspace/ai", tokens: ["ai", "copilot", "агент"], rankBoost: 8 },
  { id: "idx_wf", category: "workflows", title: "Согласование счёта", path: "/workspace/workflows/invoice", tokens: ["процесс", "workflow", "invoice"], rankBoost: 7 },
  { id: "idx_rep", category: "reports", title: "Еженедельный KPI", path: "/workspace/reports/weekly", tokens: ["отчёт", "report", "kpi", "weekly"], rankBoost: 5 },
  { id: "idx_task", category: "tasks", title: "Проверить миграцию", path: "/workspace?task=migration", tokens: ["задача", "task", "migration"], rankBoost: 4 },
  { id: "idx_dash_exec", category: "dashboards", title: "Утренний брифинг", path: "/dashboard?mode=executive", tokens: ["главная", "dashboard", "executive", "kpi", "morning", "brief", "ga"], rankBoost: 10 },
  { id: "idx_dash_main", category: "dashboards", title: "Главная", path: "/dashboard", tokens: ["главная", "dashboard", "home", "command"], rankBoost: 10 },
  { id: "idx_demo_ga", category: "applications", title: "Демо-сценарий (GA)", path: "/demo/scenario", tokens: ["demo", "scenario", "executive", "ga", "pilot", "commercial"], rankBoost: 10 },
  { id: "idx_first_entry", category: "applications", title: "Первый вход", path: "/onboarding/first-entry", tokens: ["первый", "вход", "onboarding"], rankBoost: 8 },
  { id: "idx_mission_control", category: "dashboards", title: "Мониторинг", path: "/platform-builder/mission-control", tokens: ["мониторинг", "mission", "control", "mc", "ops"], rankBoost: 10 },
  { id: "idx_enterprise_city", category: "applications", title: "Город предприятия", path: "/city", tokens: ["город", "city", "enterprise", "map", "enterprise-city"], rankBoost: 9 },
  { id: "idx_enterprise_city_alias", category: "applications", title: "Enterprise City", path: "/enterprise-city", tokens: ["город", "city", "enterprise", "map"], rankBoost: 8 },
  { id: "idx_casino_lobby", category: "applications", title: "Casino lobby", path: "/casino", tokens: ["casino", "казино", "roulette", "lobby", "play", "chips"], rankBoost: 9 },
  { id: "idx_casino_odessa_prime", category: "applications", title: "Odessa Prime Casino", path: "/casino/venues/odessa-prime", tokens: ["casino", "odessa", "prime", "venue", "roulette", "казино"], rankBoost: 9 },
  { id: "idx_builder_studio", category: "applications", title: "Студия конструктора", path: "/platform-builder/builder-studio", tokens: ["конструктор", "builder", "studio", "ai"], rankBoost: 9 },
  { id: "idx_mkt", category: "marketplace", title: "Enterprise Marketplace", path: "/platform-builder/solution-hub", tokens: ["marketplace", "solutions", "hub", "packs"], rankBoost: 8 },
  { id: "idx_twin", category: "applications", title: "Digital Twin", path: "/platform-builder/digital-twin", tokens: ["twin", "digital", "organization", "mirror", "heatmap"], rankBoost: 10 },
  { id: "idx_integrations", category: "applications", title: "Integration Hub", path: "/platform-builder/integrations", tokens: ["integrations", "telegram", "webhook", "oauth", "api"], rankBoost: 8 },
  { id: "idx_runtime", category: "ai_agents", title: "AI Runtime Center", path: "/platform-builder/runtime", tokens: ["runtime", "queue", "orchestration", "jobs"], rankBoost: 9 },
  { id: "idx_data_fabric", category: "knowledge", title: "Enterprise Data Fabric", path: "/platform-builder/data-fabric", tokens: ["data", "fabric", "graph", "lineage", "knowledge"], rankBoost: 9 },
  { id: "idx_predictive", category: "dashboards", title: "Predictive Intelligence", path: "/platform-builder/predictive", tokens: ["predictive", "forecast", "scenario", "what-if"], rankBoost: 9 },
  { id: "idx_autonomy", category: "ai_agents", title: "Autonomy Center", path: "/platform-builder/autonomy", tokens: ["autonomy", "approval", "hitl", "governance"], rankBoost: 9 },
  { id: "idx_control_tower", category: "dashboards", title: "Enterprise Control Tower", path: "/platform-builder/control-tower", tokens: ["control", "tower", "executive", "overview", "ops"], rankBoost: 10 },
  { id: "idx_learning", category: "dashboards", title: "Self-Learning Enterprise", path: "/platform-builder/learning", tokens: ["learning", "optimize", "recommendations", "self-learning", "continuous"], rankBoost: 10 },
  { id: "idx_okr", category: "dashboards", title: "OKR Intelligence", path: "/platform-builder/okr", tokens: ["okr", "goals", "strategy", "kpi", "objectives"], rankBoost: 10 },
  { id: "idx_governance", category: "dashboards", title: "Enterprise Governance", path: "/platform-builder/governance", tokens: ["governance", "compliance", "policy", "audit", "security"], rankBoost: 10 },
  { id: "idx_user_ops", category: "users", title: "Ops Manager", path: "/identity/users", tokens: ["ops", "manager", "user", "people"], rankBoost: 4 },
  { id: "idx_ai_concierge", category: "ai_agents", title: "AI Concierge", path: "/platform-builder/concierge", tokens: ["concierge", "ai", "assistant"], rankBoost: 7 },
  { id: "idx_ai_team", category: "ai_agents", title: "AI Team Center", path: "/platform-builder/ai-team", tokens: ["ai", "team", "specialists"], rankBoost: 8 },
  { id: "idx_wf_center", category: "workflows", title: "Workflow Center", path: "/platform-builder/workflow-center", tokens: ["workflow", "automation", "center"], rankBoost: 8 },
  { id: "idx_wf_builder", category: "workflows", title: "Workflow Builder", path: "/platform-builder/workflow", tokens: ["workflow", "builder", "preview"], rankBoost: 6 },
  { id: "idx_doc_kb", category: "documents", title: "Knowledge Documents", path: "/workspace/docs", tokens: ["documents", "docs", "knowledge", "files"], rankBoost: 5 },
  { id: "idx_crm_clients", category: "crm", title: "CRM Clients", path: "/workspace/crm", tokens: ["clients", "crm", "deals", "pipeline"], rankBoost: 7 },
  { id: "idx_crm_builder", category: "crm", title: "CRM Builder (Preview)", path: "/platform-builder/crm", tokens: ["crm", "builder", "preview"], rankBoost: 6 },
  { id: "idx_int_hub", category: "applications", title: "Integrations Control", path: "/platform-builder/integrations", tokens: ["integrations", "telegram", "oauth", "webhooks", "api keys"], rankBoost: 7 },
  { id: "idx_marketplace_builder", category: "marketplace", title: "Marketplace Builder (Preview)", path: "/platform-builder/marketplace", tokens: ["marketplace", "builder", "preview"], rankBoost: 6 },
  { id: "idx_org_demo", category: "organizations", title: "Organization Mirror", path: "/identity/organizations", tokens: ["organization", "tenant", "company", "org"], rankBoost: 6 },
  { id: "idx_app", category: "applications", title: "Enterprise Hub", path: "/workspace", tokens: ["hub", "application"], rankBoost: 9 },
  { id: "idx_dash", category: "dashboards", title: "Personal Dashboard", path: "/workspace/dashboards", tokens: ["dashboard"], rankBoost: 7 },
  { id: "idx_wdg", category: "widgets", title: "Recent Activity Widget", path: "/command-center#recent_activity", tokens: ["widget", "activity"], rankBoost: 4 },
  { id: "idx_kb", category: "knowledge", title: "Knowledge Base (Preview)", path: "/platform-builder/knowledge", tokens: ["knowledge", "base", "preview"], rankBoost: 6 },

  // Builder / navigation polish — key executive entry points
  { id: "idx_settings", category: "applications", title: "Settings", path: "/settings", tokens: ["settings", "profile", "preferences"], rankBoost: 10 },
  { id: "idx_builder_framework", category: "applications", title: "Universal Builder Framework", path: "/platform-builder/framework", tokens: ["builder", "framework", "universal"], rankBoost: 7 },
  { id: "idx_vertical_builder", category: "applications", title: "Vertical Builder", path: "/platform-builder/vertical", tokens: ["vertical", "builder", "industry"], rankBoost: 7 },
  { id: "idx_command_center_os", category: "applications", title: "Command Center OS", path: "/platform-builder/command-center", tokens: ["command", "center", "os"], rankBoost: 7 },
  { id: "idx_builder_academy", category: "applications", title: "Builder Academy 2.0", path: "/platform-builder/academy", tokens: ["academy", "learning", "guide"], rankBoost: 6 },
  { id: "idx_business_ecosystem", category: "applications", title: "Business Ecosystem", path: "/platform-builder/business-ecosystem", tokens: ["ecosystem", "industry", "vertical"], rankBoost: 6 },
  { id: "idx_strategy_engine", category: "dashboards", title: "Strategy Engine", path: "/platform-builder/strategy", tokens: ["strategy", "engine", "okrs"], rankBoost: 6 },
  { id: "idx_twin_intelligence", category: "dashboards", title: "Twin Intelligence", path: "/platform-builder/twin-intelligence", tokens: ["twin", "intelligence", "analytics"], rankBoost: 6 },
];

export const searchIndex = {
  list(): SearchDocument[] {
    return [...documents];
  },
  upsert(doc: SearchDocument) {
    documents = [doc, ...documents.filter((d) => d.id !== doc.id)];
    return documents.length;
  },
  refresh() {
    // simulate background index update
    documents = documents.map((d) => ({ ...d, rankBoost: d.rankBoost }));
    return { updatedAt: new Date().toISOString(), count: documents.length };
  },
  categories() {
    return [...new Set(documents.map((d) => d.category))];
  },
};
