/**
 * Sprint 42.8 — каталог вертикальных рабочих пространств (RU-first).
 * Единый шаблон: навигация · дашборд · AI-гид · специалисты · действия.
 */

import type { VerticalDef } from "./types";

function path(verticalId: string, sectionId = "home"): string {
  if (sectionId === "home") return `/vertical/${verticalId}`;
  return `/vertical/${verticalId}/${sectionId}`;
}

export const VERTICAL_WORKSPACES: VerticalDef[] = [
  {
    id: "owner",
    label: "Owner",
    purpose: "Центр управления предприятием",
    route: path("owner"),
    legacyRoute: "/dashboard",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "strategy", label: "Стратегия" },
      { id: "finance", label: "Финансы" },
      { id: "team", label: "Команда" },
      { id: "ai", label: "AI-команда" },
      { id: "reports", label: "Отчёты" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "strategy", name: "Стратег", role: "Приоритеты и цели" },
      { id: "finance", name: "Финансист", role: "Касса и прогноз" },
      { id: "ops", name: "Операции", role: "Контроль процессов" },
    ],
    stats: [
      { label: "Активные модули", value: "12" },
      { label: "Задачи сегодня", value: "7" },
      { label: "Уведомления", value: "4" },
    ],
    quickActions: [
      { label: "Открыть панель", route: "/dashboard" },
      { label: "Команда AI", route: "/platform-builder/ai-team" },
      { label: "Настройки", route: "/settings" },
    ],
    recommendations: [
      "Просмотрите сводку по вертикалям",
      "Закройте просроченные задачи руководства",
      "Проверьте статус AI Консьержа",
    ],
    primaryAction: { label: "Открыть панель управления", route: "/dashboard" },
    recentObjects: [
      { title: "Сводка недели", detail: "Готова к просмотру", route: "/dashboard" },
      { title: "Команда AI", detail: "3 специалиста онлайн", route: "/platform-builder/ai-team" },
    ],
    events: [
      { title: "Обновлена стратегия", detail: "2 часа назад" },
      { title: "Новый отчёт финансов", detail: "Сегодня" },
    ],
    tasks: [
      { title: "Утвердить приоритеты", status: "В работе" },
      { title: "Проверить кассу", status: "Ожидает" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: [
        "7 задач требуют внимания руководства",
        "4 уведомления по платформе",
        "Команда AI готова к работе",
      ],
      recommendedAction: { label: "Открыть панель управления", route: "/dashboard" },
    },
  },
  {
    id: "crm",
    label: "CRM",
    purpose: "Клиенты, сделки и коммуникации",
    route: path("crm"),
    legacyRoute: "/crm",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "clients", label: "Клиенты", href: "/crm?view=clients" },
      { id: "deals", label: "Сделки", href: "/crm?view=deals" },
      { id: "leads", label: "Лиды", href: "/crm?view=leads" },
      { id: "contacts", label: "Контакты", href: "/crm?view=contacts" },
      { id: "comms", label: "Коммуникации", href: "/crm?view=communications" },
      { id: "reports", label: "Отчёты", href: "/crm?view=reports" },
      { id: "ai", label: "AI CRM" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "sales", name: "Менеджер продаж", role: "Сделки и follow-up" },
      { id: "deals", name: "Контроль сделок", role: "Воронка и риски" },
      { id: "leads", name: "Квалификация лидов", role: "Новые обращения" },
      { id: "clients", name: "Анализ клиентов", role: "Сегменты и ценность" },
    ],
    stats: [
      { label: "Лиды", value: "5" },
      { label: "Сделки", value: "12" },
      { label: "Просрочено", value: "2" },
    ],
    quickActions: [
      { label: "Создать клиента", route: "/crm?view=clients&action=create" },
      { label: "Новая сделка", route: "/crm?view=deals&action=create" },
      { label: "Открыть лиды", route: "/crm?view=leads" },
    ],
    recommendations: [
      "Квалифицируйте 5 новых лидов",
      "Закройте 2 просроченные сделки",
      "Обновите статусы коммуникаций",
    ],
    primaryAction: { label: "Создать клиента", route: "/crm?view=clients&action=create" },
    recentObjects: [
      { title: "Acme Travel", detail: "Клиент · активен", route: "/crm?view=clients" },
      { title: "Корпоративные билеты", detail: "Лид · новый", route: "/crm?view=leads" },
    ],
    events: [
      { title: "Новый лид", detail: "Корпоративные билеты" },
      { title: "Сделка обновлена", detail: "Подписка B2B" },
    ],
    tasks: [
      { title: "Позвонить клиенту Acme", status: "Сегодня" },
      { title: "Обновить воронку", status: "На неделе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["5 новых лидов", "2 просроченные задачи", "1 договор ожидает согласования"],
      recommendedAction: { label: "Открыть лиды", route: "/crm?view=leads" },
    },
  },
  {
    id: "auto",
    label: "Auto",
    purpose: "Автомобили, импорт, продажи и VIN",
    route: path("auto"),
    legacyRoute: "/workspace/auto",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "cars", label: "Автомобили" },
      { id: "import", label: "Импорт" },
      { id: "buyers", label: "Покупатели" },
      { id: "sales", label: "Продажи" },
      { id: "vin", label: "VIN" },
      { id: "warehouse", label: "Склад" },
      { id: "docs", label: "Документы" },
      { id: "finance", label: "Финансы" },
      { id: "insurance", label: "Страхование" },
      { id: "leasing", label: "Лизинг" },
      { id: "credit", label: "Кредит" },
      { id: "ai", label: "AI Auto" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "vin", name: "Проверка VIN", role: "История и риски" },
      { id: "appraisal", name: "Оценка автомобиля", role: "Рыночная цена" },
      { id: "match", name: "Подбор автомобиля", role: "Запросы клиентов" },
      { id: "import", name: "Контроль импорта", role: "Поставки и сроки" },
      { id: "profit", name: "Расчёт прибыли", role: "Маржа и касса" },
    ],
    stats: [
      { label: "На складе", value: "48" },
      { label: "В пути", value: "6" },
      { label: "Сделки месяца", value: "11" },
    ],
    quickActions: [
      { label: "Проверить VIN", route: path("auto", "vin") },
      { label: "Добавить автомобиль", route: path("auto", "cars") },
      { label: "Открыть склад", route: path("auto", "warehouse") },
      { label: "Страхование", route: path("auto", "insurance") },
      { label: "Лизинг", route: path("auto", "leasing") },
    ],
    recommendations: [
      "Проверьте VIN у 3 новых поступлений",
      "Закройте импорт с задержкой",
      "Подготовьте подбор для горячего клиента",
    ],
    primaryAction: { label: "Проверить VIN", route: path("auto", "vin") },
    recentObjects: [
      { title: "BMW X5 · 2021", detail: "Склад · готов", route: path("auto", "cars") },
      { title: "Партия KR-08", detail: "Импорт · в пути", route: path("auto", "import") },
    ],
    events: [
      { title: "VIN проверен", detail: "Toyota Camry" },
      { title: "Оценка обновлена", detail: "Mercedes E-Class" },
    ],
    tasks: [
      { title: "Приёмка партии", status: "Сегодня" },
      { title: "Расчёт маржи", status: "В работе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: [
        "6 автомобилей в пути",
        "3 VIN без полной проверки",
        "11 продаж за месяц — выше плана",
      ],
      recommendedAction: { label: "Проверить VIN", route: path("auto", "vin") },
    },
  },
  {
    id: "beauty",
    label: "Beauty",
    purpose: "Салон красоты: клиенты, услуги, записи, мастера и продажи",
    route: path("beauty"),
    legacyRoute: "/workspace/beauty",
    nav: [
      { id: "home", label: "Главная", href: "/workspace/beauty?view=home" },
      { id: "clients", label: "Клиенты", href: "/workspace/beauty?view=clients" },
      { id: "services", label: "Услуги", href: "/workspace/beauty?view=services" },
      { id: "products", label: "Товары", href: "/workspace/beauty?view=products" },
      { id: "bookings", label: "Записи", href: "/workspace/beauty?view=bookings" },
      { id: "calendar", label: "Календарь", href: "/workspace/beauty?view=calendar" },
      { id: "staff", label: "Мастера", href: "/workspace/beauty?view=staff" },
      { id: "shifts", label: "Смены", href: "/workspace/beauty?view=shifts" },
      { id: "sales", label: "Продажи", href: "/workspace/beauty?view=sales" },
      { id: "analytics", label: "Аналитика", href: "/workspace/beauty?view=analytics" },
      { id: "marketing", label: "Маркетинг", href: "/workspace/beauty?view=marketing" },
      { id: "warehouse", label: "Склад", href: "/workspace/beauty?view=warehouse" },
      { id: "finance", label: "Финансы", href: "/workspace/beauty?view=finance" },
      { id: "settings", label: "Настройки", href: "/workspace/beauty?view=settings" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "booking", name: "Помощник записи", role: "Свободные слоты" },
      { id: "loyalty", name: "Лояльность", role: "Напоминания и бонусы" },
    ],
    stats: [
      { label: "Записи сегодня", value: "—" },
      { label: "Клиенты", value: "—" },
      { label: "Выручка", value: "—" },
    ],
    quickActions: [
      { label: "Новая запись", route: "/workspace/beauty?view=bookings" },
      { label: "Клиенты", route: "/workspace/beauty?view=clients" },
      { label: "Календарь", route: "/workspace/beauty?view=calendar" },
      { label: "Мастера", route: "/workspace/beauty?view=staff" },
    ],
    recommendations: [
      "Подтвердите записи на сегодня",
      "Проверьте смены мастеров",
      "Откройте склад при низких остатках",
    ],
    primaryAction: { label: "Открыть кабинет салона", route: "/workspace/beauty" },
    recentObjects: [
      { title: "Записи", detail: "Операционный журнал", route: "/workspace/beauty?view=bookings" },
      { title: "Клиенты", detail: "CRM салона", route: "/workspace/beauty?view=clients" },
    ],
    events: [
      { title: "Кабинет Beauty", detail: "Бизнес-режим Sprint 49.0" },
      { title: "Beauty AI", detail: "Отдельный инструмент — не замена меню" },
    ],
    tasks: [
      { title: "Подтвердить записи", status: "Сегодня" },
      { title: "Сверить кассу и продажи", status: "На неделе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать в салон.",
      bullets: [
        "Управляйте клиентами, записями и мастерами из кабинета",
        "Календарь и смены — в боковой навигации",
        "Beauty AI доступен отдельно как помощник",
      ],
      recommendedAction: { label: "Открыть кабинет салона", route: "/workspace/beauty" },
    },
  },
  {
    id: "cafe",
    label: "Cafe",
    purpose: "Заведение: заказы, меню, смены, брони и касса",
    route: path("cafe"),
    legacyRoute: "/workspace/cafe",
    nav: [
      { id: "home", label: "Главная", href: "/workspace/cafe?view=home" },
      { id: "orders", label: "Заказы", href: "/workspace/cafe?view=orders" },
      { id: "menu", label: "Меню", href: "/workspace/cafe?view=menu" },
      { id: "shifts", label: "Смены", href: "/workspace/cafe?view=shifts" },
      { id: "clients", label: "Клиенты", href: "/workspace/cafe?view=clients" },
      { id: "bookings", label: "Бронирования", href: "/workspace/cafe?view=bookings" },
      { id: "halls", label: "Залы и столы", href: "/workspace/cafe?view=halls" },
      { id: "warehouse", label: "Склад", href: "/workspace/cafe?view=warehouse" },
      { id: "cashier", label: "Касса", href: "/workspace/cafe?view=cashier" },
      { id: "staff", label: "Персонал", href: "/workspace/cafe?view=staff" },
      { id: "marketing", label: "Маркетинг", href: "/workspace/cafe?view=marketing" },
      { id: "analytics", label: "Аналитика", href: "/workspace/cafe?view=analytics" },
      { id: "settings", label: "Настройки", href: "/workspace/cafe?view=settings" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "floor", name: "Зал", role: "Столы и брони" },
      { id: "kitchen", name: "Кухня", role: "Заказы и меню" },
    ],
    stats: [
      { label: "Открытые заказы", value: "—" },
      { label: "Брони сегодня", value: "—" },
      { label: "Выручка", value: "—" },
    ],
    quickActions: [
      { label: "Новый заказ", route: "/workspace/cafe?view=orders" },
      { label: "Бронирование", route: "/workspace/cafe?view=bookings" },
      { label: "Меню", route: "/workspace/cafe?view=menu" },
      { label: "Открыть смену", route: "/workspace/cafe?view=shifts" },
    ],
    recommendations: [
      "Закройте открытые заказы смены",
      "Проверьте загрузку зала",
      "Обновите позиции меню",
    ],
    primaryAction: { label: "Открыть кабинет кафе", route: "/workspace/cafe" },
    recentObjects: [
      { title: "Заказы", detail: "Включая банкеты и мероприятия", route: "/workspace/cafe?view=orders" },
      { title: "Меню", detail: "Кухня и бар", route: "/workspace/cafe?view=menu" },
    ],
    events: [{ title: "Кабинет Cafe", detail: "Бизнес-режим Sprint 49.0" }],
    tasks: [
      { title: "Открыть смену", status: "Сегодня" },
      { title: "Сверить кассу", status: "В конце смены" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать в заведение.",
      bullets: [
        "Создавайте обычные заказы и мероприятия",
        "Управляйте меню, сменами и бронированиями",
        "Касса без фиктивного платёжного шлюза",
      ],
      recommendedAction: { label: "Открыть кабинет кафе", route: "/workspace/cafe" },
    },
  },
  {
    id: "crypto",
    label: "Crypto OTC",
    purpose: "Торговый стол OTC: пары, котировки, графики, сделки",
    route: path("crypto"),
    legacyRoute: "/workspace/crypto",
    nav: [
      { id: "home", label: "Главная", href: "/workspace/crypto?view=home" },
      { id: "markets", label: "Рынки", href: "/workspace/crypto?view=markets" },
      { id: "quotes", label: "Котировки", href: "/workspace/crypto?view=quotes" },
      { id: "charts", label: "Графики", href: "/workspace/crypto?view=charts" },
      { id: "pairs", label: "Мои пары", href: "/workspace/crypto?view=pairs" },
      { id: "analysis", label: "Анализы", href: "/workspace/crypto?view=analysis" },
      { id: "specialists", label: "AI-специалисты", href: "/workspace/crypto?view=specialists" },
      { id: "signals", label: "Сигналы", href: "/workspace/crypto?view=signals" },
      { id: "news", label: "Новости", href: "/workspace/crypto?view=news" },
      { id: "calendar", label: "Календарь", href: "/workspace/crypto?view=calendar" },
      { id: "intel_history", label: "История анализов", href: "/workspace/crypto?view=intel_history" },
      { id: "paper", label: "Бумажная торговля", href: "/workspace/crypto?view=paper" },
      { id: "journal", label: "Журнал", href: "/workspace/crypto?view=journal" },
      { id: "deals", label: "OTC-сделки", href: "/workspace/crypto?view=deals" },
      { id: "orders", label: "Ордера", href: "/workspace/crypto?view=orders" },
      { id: "wallets", label: "Кошельки", href: "/workspace/crypto?view=wallets" },
      { id: "transfers", label: "Переводы", href: "/workspace/crypto?view=transfers" },
      { id: "history", label: "История", href: "/workspace/crypto?view=history" },
      { id: "notifications", label: "Уведомления", href: "/workspace/crypto?view=notifications" },
      { id: "settings", label: "Настройки", href: "/workspace/crypto?view=settings" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "risk", name: "Контроль рисков", role: "Лимиты и алерты" },
      { id: "rates", name: "Мониторинг курсов", role: "Источник и свежесть" },
    ],
    stats: [
      { label: "Сделки сегодня", value: "—" },
      { label: "Мои пары", value: "—" },
      { label: "Ожидают", value: "—" },
    ],
    quickActions: [
      { label: "OTC-сделка", route: "/workspace/crypto?view=deals" },
      { label: "Мои пары", route: "/workspace/crypto?view=pairs" },
      { label: "Графики", route: "/workspace/crypto?view=charts" },
      { label: "Анализы", route: "/workspace/crypto?view=analysis" },
    ],
    recommendations: [
      "Настройте watchlist пар",
      "Проверьте источник котировок",
      "Не обходите antifraud подтверждения выплат",
    ],
    primaryAction: { label: "Открыть OTC-стол", route: "/workspace/crypto" },
    recentObjects: [
      { title: "Мои пары", detail: "Watchlist трейдера", route: "/workspace/crypto?view=pairs" },
      { title: "OTC-сделки", detail: "С antifraud", route: "/workspace/crypto?view=deals" },
    ],
    events: [{ title: "OTC Desk", detail: "Без матрицы чужих вертикалей" }],
    tasks: [
      { title: "Обновить watchlist", status: "Сегодня" },
      { title: "Проверить ожидающие сделки", status: "Срочно" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать на OTC-стол.",
      bullets: [
        "Настройте пары и источники котировок",
        "Графики и анализы — только с реальными данными",
        "Выплаты проходят через CryptoPayoutOrchestrator",
      ],
      recommendedAction: { label: "Открыть OTC-стол", route: "/workspace/crypto" },
    },
  },
  {
    id: "legal",
    label: "Юридический отдел",
    purpose: "CRM юриста: клиенты, дела, договоры, сроки, суды",
    route: path("legal"),
    legacyRoute: "/workspace/legal",
    nav: [
      { id: "home", label: "Главная", href: "/workspace/legal?view=home" },
      { id: "clients", label: "Клиенты", href: "/workspace/legal?view=clients" },
      { id: "cases", label: "Дела", href: "/workspace/legal?view=cases" },
      { id: "contracts", label: "Договоры", href: "/workspace/legal?view=contracts" },
      { id: "documents", label: "Документы", href: "/workspace/legal?view=documents" },
      { id: "tasks", label: "Задачи/Сроки", href: "/workspace/legal?view=tasks" },
      { id: "hearings", label: "Суды/Заседания", href: "/workspace/legal?view=hearings" },
      { id: "calendar", label: "Календарь", href: "/workspace/legal?view=calendar" },
      { id: "inbox", label: "Входящие", href: "/workspace/legal?view=inbox" },
      { id: "archive", label: "Архив", href: "/workspace/legal?view=archive" },
      { id: "ai", label: "AI-юрист", href: "/workspace/legal?view=ai" },
      { id: "activity", label: "Активность", href: "/workspace/legal?view=activity" },
      { id: "settings", label: "Настройки", href: "/workspace/legal?view=settings" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "lawyer_ai", name: "AI-юрист", role: "Анализ документов" },
      { id: "deadlines", name: "Контроль сроков", role: "Дедлайны и заседания" },
    ],
    stats: [
      { label: "Открытые дела", value: "—" },
      { label: "Сроки", value: "—" },
      { label: "Заседания сегодня", value: "—" },
    ],
    quickActions: [
      { label: "Создать клиента", route: "/workspace/legal?view=clients" },
      { label: "Создать дело", route: "/workspace/legal?view=cases" },
      { label: "Создать договор", route: "/workspace/legal?view=contracts" },
      { label: "Календарь", route: "/workspace/legal?view=calendar" },
    ],
    recommendations: [
      "Создайте клиента и дело",
      "Проверьте сроки и заседания",
      "Google Calendar подключается только с OAuth",
    ],
    primaryAction: { label: "Открыть кабинет юриста", route: "/workspace/legal" },
    recentObjects: [
      { title: "Дела", detail: "CRM дел", route: "/workspace/legal?view=cases" },
      { title: "Договоры", detail: "Согласования", route: "/workspace/legal?view=contracts" },
    ],
    events: [{ title: "Lawyer Desk 51.0", detail: "Durable legal-ops CRM" }],
    tasks: [
      { title: "Проверить сроки", status: "Сегодня" },
      { title: "Подготовить заседание", status: "На неделе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать в юридический кабинет.",
      bullets: [
        "Клиенты → дела → договоры → документы",
        "Сроки и заседания видны на главной",
        "Пилот in-memory: /workspace/legal/pilot",
      ],
      recommendedAction: { label: "Открыть кабинет юриста", route: "/workspace/legal" },
    },
  },
  {
    id: "recruiting",
    label: "Рекрутинг",
    purpose: "Лиды, кандидаты, вакансии и воронка найма",
    route: path("recruiting"),
    legacyRoute: "/workspace/recruiting",
    nav: [
      { id: "home", label: "Главная", href: "/workspace/recruiting?view=home" },
      { id: "projects", label: "Проекты", href: "/workspace/recruiting/projects" },
      { id: "leads", label: "Лиды", href: "/workspace/recruiting?view=leads" },
      { id: "candidates", label: "Кандидаты", href: "/workspace/recruiting?view=candidates" },
      { id: "vacancies", label: "Вакансии", href: "/workspace/recruiting?view=vacancies" },
      { id: "pipeline", label: "Воронка", href: "/workspace/recruiting?view=pipeline" },
      { id: "campaigns", label: "Кампании", href: "/workspace/recruiting?view=campaigns" },
      { id: "tasks", label: "Задачи", href: "/workspace/recruiting?view=tasks" },
      { id: "comms", label: "Коммуникации", href: "/workspace/recruiting?view=comms" },
      { id: "activity", label: "Активность", href: "/workspace/recruiting?view=activity" },
      { id: "analytics", label: "Аналитика", href: "/workspace/recruiting?view=analytics" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "recruiter_ai", name: "AI-рекрутер", role: "Разбор анкет и воронки" },
    ],
    stats: [
      { label: "Лиды", value: "—" },
      { label: "Кандидаты", value: "—" },
      { label: "Просроченные задачи", value: "—" },
    ],
    quickActions: [
      { label: "Открыть рекрутинг", route: "/workspace/recruiting" },
      { label: "Создать лид", route: "/workspace/recruiting?view=leads" },
      { label: "Воронка", route: "/workspace/recruiting?view=pipeline" },
    ],
    recommendations: [
      "Проверьте просроченные задачи",
      "Квалифицируйте новые лиды",
      "Не выдумывайте визиты до подключения Vanguard",
    ],
    primaryAction: { label: "Открыть кабинет рекрутера", route: "/workspace/recruiting" },
    recentObjects: [
      { title: "Лиды", detail: "Входящие заявки", route: "/workspace/recruiting?view=leads" },
      { title: "Воронка", detail: "Кандидаты", route: "/workspace/recruiting?view=pipeline" },
    ],
    events: [{ title: "Recruiting 1.0", detail: "Операционный кабинет найма" }],
    tasks: [
      { title: "Позвонить лиду", status: "Сегодня" },
      { title: "Провести интервью", status: "На неделе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать в рекрутинг.",
      bullets: [
        "Лиды → квалификация → кандидат → интервью",
        "Просроченные задачи на главной",
        "Визиты появятся после интеграции Vanguard",
      ],
      recommendedAction: { label: "Открыть кабинет рекрутера", route: "/workspace/recruiting" },
    },
  },
  {
    id: "travel",
    label: "Travel",
    purpose: "Туры, бронирования, отели и авиабилеты",
    route: path("travel"),
    nav: [
      { id: "home", label: "Обзор" },
      { id: "tours", label: "Туры" },
      { id: "bookings", label: "Бронирования" },
      { id: "clients", label: "Клиенты" },
      { id: "hotels", label: "Отели" },
      { id: "flights", label: "Авиабилеты" },
      { id: "docs", label: "Документы" },
      { id: "payments", label: "Платежи" },
      { id: "ai", label: "AI Travel" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "tour", name: "Подбор тура", role: "Маршруты и пакеты" },
      { id: "tickets", name: "Подбор билетов", role: "Авиа и стыковки" },
      { id: "hotel", name: "Подбор гостиницы", role: "Размещение" },
      { id: "docs", name: "Контроль документов", role: "Визы и пакеты" },
    ],
    stats: [
      { label: "Брони сегодня", value: "14" },
      { label: "Туры в работе", value: "6" },
      { label: "Документы", value: "3" },
    ],
    quickActions: [
      { label: "Подобрать тур", route: path("travel", "tours") },
      { label: "Новое бронирование", route: path("travel", "bookings") },
      { label: "Проверить документы", route: path("travel", "docs") },
    ],
    recommendations: [
      "Закройте 3 пакета документов",
      "Подтвердите отели на ближайшие выезды",
      "Проверьте оплату по 2 бронированиям",
    ],
    primaryAction: { label: "Подобрать тур", route: path("travel", "tours") },
    recentObjects: [
      { title: "Тур · Греция 7 ночей", detail: "Семья Ивановых", route: path("travel", "tours") },
      { title: "Бронь · Hotel Azure", detail: "Ожидает оплату", route: path("travel", "bookings") },
    ],
    events: [
      { title: "Билеты выписаны", detail: "Рейс SU 112" },
      { title: "Виза готова", detail: "Клиент Петров" },
    ],
    tasks: [
      { title: "Собрать документы", status: "Сегодня" },
      { title: "Подтвердить отель", status: "В работе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["14 бронирований сегодня", "3 пакета документов ждут проверки", "6 туров в активной сборке"],
      recommendedAction: { label: "Подобрать тур", route: path("travel", "tours") },
    },
  },
  {
    id: "drone",
    label: "Drone",
    purpose: "Проекты, аппараты, полёты и производство",
    route: path("drone"),
    legacyRoute: "/workspace/drone",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "projects", label: "Проекты" },
      { id: "units", label: "Аппараты" },
      { id: "flights", label: "Полёты" },
      { id: "missions", label: "Миссии" },
      { id: "production", label: "Производство" },
      { id: "team", label: "Команда" },
      { id: "warehouse", label: "Склад" },
      { id: "tests", label: "Испытания" },
      { id: "ai", label: "AI Drone" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "engineer", name: "Инженер", role: "Конструкции и системы" },
      { id: "designer", name: "Конструктор", role: "Чертежи и узлы" },
      { id: "architect", name: "Проектировщик", role: "Миссии и схемы" },
      { id: "prod", name: "Контроль производства", role: "Сборка и качество" },
    ],
    stats: [
      { label: "Аппараты", value: "22" },
      { label: "Миссии", value: "5" },
      { label: "Испытания", value: "3" },
    ],
    quickActions: [
      { label: "Новая миссия", route: path("drone", "missions") },
      { label: "План полёта", route: path("drone", "flights") },
      { label: "Производство", route: path("drone", "production") },
    ],
    recommendations: [
      "Завершите 3 протокола испытаний",
      "Проверьте склад комплектующих",
      "Обновите статус сборки серии D-4",
    ],
    primaryAction: { label: "Создать миссию", route: path("drone", "missions") },
    recentObjects: [
      { title: "Миссия · Картография", detail: "План готов", route: path("drone", "missions") },
      { title: "Аппарат D-4", detail: "Сборка 80%", route: path("drone", "production") },
    ],
    events: [
      { title: "Полёт завершён", detail: "Полигон Север" },
      { title: "Испытание ОК", detail: "Серия D-4" },
    ],
    tasks: [
      { title: "Протокол испытания", status: "Сегодня" },
      { title: "Комплектация склада", status: "В работе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["5 миссий в плане", "3 испытания без протокола", "Сборка D-4 на финальном этапе"],
      recommendedAction: { label: "Открыть испытания", route: path("drone", "tests") },
    },
  },
  {
    id: "agro",
    label: "Агро",
    purpose: "Торговля (закупка/продажа), поля, техника, посевы и урожай",
    route: path("agro"),
    legacyRoute: "/workspace/agro",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "goods", label: "Товары (закупка / продажа)" },
      { id: "counterparties", label: "Контрагенты" },
      { id: "contracts", label: "Контракты" },
      { id: "deals", label: "Сделки" },
      { id: "fields", label: "Поля" },
      { id: "machinery", label: "Техника" },
      { id: "crops", label: "Посевы" },
      { id: "harvest", label: "Урожай" },
      { id: "irrigation", label: "Полив" },
      { id: "warehouse", label: "Склад" },
      { id: "works", label: "Работы" },
      { id: "ai", label: "ИИ-помощник" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "agronomist", name: "Агроном", role: "Посевы и уход" },
      { id: "yield", name: "Аналитик урожая", role: "Прогноз и факты" },
      { id: "fleet", name: "Контроль техники", role: "Парк и ремонты" },
      { id: "weather", name: "Погодный помощник", role: "Окна работ" },
    ],
    stats: [
      { label: "Поля", value: "18" },
      { label: "Техника в работе", value: "7" },
      { label: "Работы сегодня", value: "4" },
    ],
    quickActions: [
      { label: "Товары (закупка / продажа)", route: path("agro", "goods") },
      { label: "План работ", route: path("agro", "works") },
      { label: "Статус полей", route: path("agro", "fields") },
      { label: "Полив", route: path("agro", "irrigation") },
    ],
    recommendations: [
      "Учтите окно полива на ближайшие 48 часов",
      "Проверьте технику перед посевной сменой",
      "Обновите прогноз урожая по южным полям",
    ],
    primaryAction: { label: "Открыть план работ", route: path("agro", "works") },
    recentObjects: [
      { title: "Поле Юг-3", detail: "Полив запланирован", route: path("agro", "fields") },
      { title: "Комбайн К-7", detail: "ТО через 2 дня", route: path("agro", "machinery") },
    ],
    events: [
      { title: "Посев завершён", detail: "Участок Север" },
      { title: "Прогноз погоды", detail: "Дождь завтра" },
    ],
    tasks: [
      { title: "Полив Юг-3", status: "Сегодня" },
      { title: "ТО комбайна", status: "На неделе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["Окно полива открыто на 48 часов", "7 единиц техники в поле", "Прогноз урожая обновлён"],
      recommendedAction: { label: "Открыть полив", route: path("agro", "irrigation") },
    },
  },
  {
    id: "construction",
    label: "Construction",
    purpose: "Объекты, сметы, подрядчики и материалы",
    route: path("construction"),
    nav: [
      { id: "home", label: "Обзор" },
      { id: "sites", label: "Объекты" },
      { id: "projects", label: "Проекты" },
      { id: "contractors", label: "Подрядчики" },
      { id: "estimates", label: "Сметы" },
      { id: "materials", label: "Материалы" },
      { id: "machinery", label: "Техника" },
      { id: "docs", label: "Документы" },
      { id: "ai", label: "AI Construction" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "foreman", name: "Прораб", role: "Объект и смена" },
      { id: "engineer", name: "Инженер", role: "Техрешения" },
      { id: "estimator", name: "Сметчик", role: "Сметы и объёмы" },
      { id: "buyer", name: "Закупщик", role: "Материалы и поставки" },
      { id: "budget", name: "Контроль бюджета", role: "Лимиты и отклонения" },
    ],
    stats: [
      { label: "Объекты", value: "9" },
      { label: "Сметы на согласовании", value: "4" },
      { label: "Отклонение бюджета", value: "−2,1%" },
    ],
    quickActions: [
      { label: "Новая смета", route: path("construction", "estimates") },
      { label: "Объекты", route: path("construction", "sites") },
      { label: "Материалы", route: path("construction", "materials") },
    ],
    recommendations: [
      "Согласуйте 4 сметы",
      "Проверьте поставку материалов на объект «Река»",
      "Сверьте бюджет по подрядчикам",
    ],
    primaryAction: { label: "Открыть сметы", route: path("construction", "estimates") },
    recentObjects: [
      { title: "Объект «Река»", detail: "Смета на согласовании", route: path("construction", "sites") },
      { title: "Подрядчик СтройМост", detail: "Акт ожидает", route: path("construction", "contractors") },
    ],
    events: [
      { title: "Поставка бетона", detail: "Объект Река" },
      { title: "Смета обновлена", detail: "Корпус B" },
    ],
    tasks: [
      { title: "Согласовать смету", status: "Срочно" },
      { title: "Приёмка материалов", status: "Сегодня" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["4 сметы ждут согласования", "Бюджет в пределах −2,1%", "Поставка на объект «Река» сегодня"],
      recommendedAction: { label: "Открыть сметы", route: path("construction", "estimates") },
    },
  },
  {
    id: "production",
    label: "Production",
    purpose: "Заказы, производство, качество и склад",
    route: path("production"),
    nav: [
      { id: "home", label: "Обзор" },
      { id: "orders", label: "Заказы" },
      { id: "factory", label: "Производство" },
      { id: "equipment", label: "Оборудование" },
      { id: "warehouse", label: "Склад" },
      { id: "quality", label: "Качество" },
      { id: "suppliers", label: "Поставщики" },
      { id: "ai", label: "AI Factory" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "prod", name: "Контроль производства", role: "Линии и смены" },
      { id: "qa", name: "Контроль качества", role: "Брак и протоколы" },
      { id: "planner", name: "Планировщик", role: "Заказы и сроки" },
      { id: "load", name: "Оптимизация загрузки", role: "Мощности" },
    ],
    stats: [
      { label: "Заказы в работе", value: "16" },
      { label: "Загрузка линий", value: "78%" },
      { label: "Брак", value: "0,4%" },
    ],
    quickActions: [
      { label: "План смены", route: path("production", "factory") },
      { label: "Заказы", route: path("production", "orders") },
      { label: "Качество", route: path("production", "quality") },
    ],
    recommendations: [
      "Сбалансируйте загрузку линии 2",
      "Закройте 3 протокола качества",
      "Проверьте поставку комплектующих",
    ],
    primaryAction: { label: "Открыть производство", route: path("production", "factory") },
    recentObjects: [
      { title: "Заказ #904", detail: "Сборка · 60%", route: path("production", "orders") },
      { title: "Линия 2", detail: "Загрузка 92%", route: path("production", "factory") },
    ],
    events: [
      { title: "Партия принята", detail: "СК-12" },
      { title: "Контроль качества", detail: "Пройден" },
    ],
    tasks: [
      { title: "План смены", status: "Сегодня" },
      { title: "Протокол качества", status: "В работе" },
    ],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["Загрузка линий 78%", "16 заказов в работе", "Брак ниже нормы"],
      recommendedAction: { label: "Открыть производство", route: path("production", "factory") },
    },
  },
  {
    id: "knowledge",
    label: "Knowledge",
    purpose: "База знаний, статьи и регламенты",
    route: path("knowledge"),
    legacyRoute: "/knowledge",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "articles", label: "Статьи", href: "/knowledge" },
      { id: "guides", label: "Регламенты" },
      { id: "search", label: "Поиск", href: "/search" },
      { id: "ai", label: "AI Knowledge" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "librarian", name: "Хранитель знаний", role: "Статьи и актуальность" },
      { id: "search", name: "Поиск по знаниям", role: "Быстрые ответы" },
    ],
    stats: [
      { label: "Статьи", value: "128" },
      { label: "Обновлено за неделю", value: "9" },
      { label: "Запросы AI", value: "34" },
    ],
    quickActions: [
      { label: "Открыть базу знаний", route: "/knowledge" },
      { label: "Поиск", route: "/search" },
    ],
    recommendations: [
      "Обновите устаревшие регламенты",
      "Добавьте ответы на частые вопросы",
    ],
    primaryAction: { label: "Открыть базу знаний", route: "/knowledge" },
    recentObjects: [
      { title: "Регламент возвратов", detail: "Обновлён вчера", route: "/knowledge" },
    ],
    events: [{ title: "Новая статья", detail: "Онбординг менеджера" }],
    tasks: [{ title: "Актуализировать FAQ", status: "На неделе" }],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["9 статей обновлены за неделю", "34 AI-запроса к базе знаний"],
      recommendedAction: { label: "Открыть базу знаний", route: "/knowledge" },
    },
  },
  {
    id: "documents",
    label: "Documents",
    purpose: "Документы, согласования и архив",
    route: path("documents"),
    legacyRoute: "/documents",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "inbox", label: "Входящие" },
      { id: "approvals", label: "Согласования" },
      { id: "archive", label: "Архив" },
      { id: "ai", label: "AI Documents" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "clerk", name: "Делопроизводитель", role: "Маршруты документов" },
      { id: "review", name: "Проверка документов", role: "Ошибки и полнота" },
    ],
    stats: [
      { label: "На согласовании", value: "8" },
      { label: "Новые сегодня", value: "5" },
      { label: "Просрочено", value: "1" },
    ],
    quickActions: [
      { label: "Согласования", route: path("documents", "approvals") },
      { label: "Архив", route: path("documents", "archive") },
    ],
    recommendations: [
      "Закройте 1 просроченное согласование",
      "Разберите входящие за сегодня",
    ],
    primaryAction: { label: "Открыть согласования", route: path("documents", "approvals") },
    recentObjects: [
      { title: "Договор поставки", detail: "Ожидает подписи", route: path("documents", "approvals") },
    ],
    events: [{ title: "Документ согласован", detail: "Акт выполненных работ" }],
    tasks: [{ title: "Подписать договор", status: "Срочно" }],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["8 документов на согласовании", "1 просроченное согласование"],
      recommendedAction: { label: "Открыть согласования", route: path("documents", "approvals") },
    },
  },
  {
    id: "marketplace",
    label: "Marketplace",
    purpose: "Магазин решений и установки",
    route: path("marketplace"),
    legacyRoute: "/marketplace",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "catalog", label: "Каталог", href: "/marketplace" },
      { id: "installed", label: "Установлено" },
      { id: "ai", label: "AI Marketplace" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "curator", name: "Куратор решений", role: "Подбор модулей" },
    ],
    stats: [
      { label: "Доступно", value: "24" },
      { label: "Установлено", value: "7" },
    ],
    quickActions: [
      { label: "Открыть магазин", route: "/marketplace" },
    ],
    recommendations: [
      "Просмотрите рекомендованные решения для вашей отрасли",
    ],
    primaryAction: { label: "Открыть магазин решений", route: "/marketplace" },
    recentObjects: [
      { title: "Пакет CRM+", detail: "Рекомендован", route: "/marketplace" },
    ],
    events: [{ title: "Установлен модуль", detail: "Аналитика продаж" }],
    tasks: [{ title: "Оценить пакет CRM+", status: "На неделе" }],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["24 решения доступны", "7 уже установлены"],
      recommendedAction: { label: "Открыть магазин", route: "/marketplace" },
    },
  },
  {
    id: "ai_studio",
    label: "AI Studio",
    purpose: "Создание и настройка AI-команды",
    route: path("ai_studio"),
    legacyRoute: "/platform-builder/builder-studio",
    nav: [
      { id: "home", label: "Обзор" },
      { id: "concierge", label: "AI Консьерж", href: "/platform-builder/concierge" },
      { id: "team", label: "Команда AI", href: "/platform-builder/ai-team" },
      { id: "wizard", label: "Мастер агента", href: "/platform-builder/builder-studio?mode=wizard" },
      { id: "ai", label: "Студия" },
    ],
    agents: [
      { id: "concierge", name: "AI Консьерж", role: "Главный помощник" },
      { id: "builder", name: "Конструктор агентов", role: "Сборка специалистов" },
      { id: "trainer", name: "Наставник", role: "Стили и навыки" },
    ],
    stats: [
      { label: "Агенты", value: "8" },
      { label: "Активны", value: "6" },
      { label: "На паузе", value: "2" },
    ],
    quickActions: [
      { label: "Создать агента", route: "/platform-builder/builder-studio?mode=wizard" },
      { label: "Настроить консьержа", route: "/platform-builder/concierge" },
      { label: "Команда AI", route: "/platform-builder/ai-team" },
    ],
    recommendations: [
      "Завершите настройку AI Консьержа",
      "Добавьте специалиста для активной вертикали",
    ],
    primaryAction: {
      label: "Открыть студию AI",
      route: "/platform-builder/builder-studio",
    },
    recentObjects: [
      {
        title: "AI Консьерж",
        detail: "Готов к работе",
        route: "/platform-builder/concierge",
      },
    ],
    events: [{ title: "Агент создан", detail: "Менеджер продаж" }],
    tasks: [{ title: "Настроить права агента", status: "В работе" }],
    aiGuide: {
      greeting: "Добро пожаловать.",
      bullets: ["8 агентов в организации", "Консьерж готов помогать", "2 специалиста на паузе"],
      recommendedAction: {
        label: "Открыть студию AI",
        route: "/platform-builder/builder-studio",
      },
    },
  },
];

export const VERTICAL_BY_ID: Record<string, VerticalDef> = Object.fromEntries(
  VERTICAL_WORKSPACES.map((v) => [v.id, v]),
);

export function getVertical(id: string): VerticalDef | undefined {
  return VERTICAL_BY_ID[id];
}

export function verticalHomePath(id: string): string {
  return getVertical(id)?.route || `/vertical/${id}`;
}

export function sectionPath(verticalId: string, sectionId: string): string {
  const v = getVertical(verticalId);
  const item = v?.nav.find((n) => n.id === sectionId);
  if (item?.href) return item.href;
  return path(verticalId, sectionId);
}
