"""Creative Factory engine — Sprint 36.9.

Studio generation, media providers with failover, campaigns, brand center,
content library (versioning + semantic search), publishing hub.
"""

from __future__ import annotations

import hashlib
import math
import time
from typing import Any

from platform_ai.creative_models import (
    AssetStatus,
    BrandProfile,
    Campaign,
    CampaignStatus,
    CreativeAsset,
    CreativeProject,
    CreativeTemplate,
    CreativeType,
    HistoryEntry,
    MediaItem,
    MediaModality,
    PublishChannel,
    PublishJob,
    new_id,
)

DEFAULT_MEDIA_FALLBACK = {
    MediaModality.TEXT.value: ["openai_text", "anthropic_text", "local_text"],
    MediaModality.IMAGE.value: ["openai_image", "stability_image", "local_image"],
    MediaModality.VIDEO.value: ["runway_video", "local_video"],
    MediaModality.VOICE.value: ["elevenlabs_voice", "openai_voice", "local_voice"],
    MediaModality.STT.value: ["whisper_stt", "local_stt"],
    MediaModality.TTS.value: ["openai_tts", "local_tts"],
}


def _embed(text: str, dims: int = 16) -> list[float]:
    digest = hashlib.sha256((text or "").encode("utf-8")).digest()
    vals = [((digest[i % len(digest)] / 255.0) * 2 - 1) for i in range(dims)]
    norm = math.sqrt(sum(v * v for v in vals)) or 1.0
    return [v / norm for v in vals]


def _cosine(a: list[float], b: list[float]) -> float:
    if not a or not b:
        return 0.0
    n = min(len(a), len(b))
    return sum(a[i] * b[i] for i in range(n))


class MediaProviderManager:
    def __init__(self) -> None:
        self.providers: dict[str, dict[str, Any]] = {}
        self.fallback = {k: list(v) for k, v in DEFAULT_MEDIA_FALLBACK.items()}
        self._seed()

    def _seed(self) -> None:
        specs = [
            ("openai_text", "text", True),
            ("anthropic_text", "text", True),
            ("local_text", "text", True),
            ("openai_image", "image", True),
            ("stability_image", "image", True),
            ("local_image", "image", True),
            ("runway_video", "video", True),
            ("local_video", "video", True),
            ("elevenlabs_voice", "voice", True),
            ("openai_voice", "voice", True),
            ("local_voice", "voice", True),
            ("whisper_stt", "speech_to_text", True),
            ("local_stt", "speech_to_text", True),
            ("openai_tts", "text_to_speech", True),
            ("local_tts", "text_to_speech", True),
        ]
        for pid, modality, available in specs:
            self.providers[pid] = {
                "provider_id": pid,
                "modality": modality,
                "available": available,
                "label": pid.replace("_", " ").title(),
            }

    def reset(self) -> None:
        self.providers.clear()
        self.fallback = {k: list(v) for k, v in DEFAULT_MEDIA_FALLBACK.items()}
        self._seed()

    def set_available(self, provider_id: str, available: bool) -> None:
        if provider_id in self.providers:
            self.providers[provider_id]["available"] = available

    def list_providers(self, *, modality: str | None = None) -> list[dict[str, Any]]:
        rows = list(self.providers.values())
        if modality:
            rows = [p for p in rows if p["modality"] == modality]
        return rows

    async def generate(
        self,
        modality: str,
        prompt: str,
        *,
        preferred: str | None = None,
        brand: BrandProfile | None = None,
    ) -> dict[str, Any]:
        order: list[str] = []
        if preferred:
            order.append(preferred)
        for pid in self.fallback.get(modality, []):
            if pid not in order:
                order.append(pid)
        errors: list[str] = []
        for pid in order:
            p = self.providers.get(pid)
            if not p or not p.get("available"):
                errors.append(f"{pid}: unavailable")
                continue
            tone = brand.tone_of_voice if brand else "professional"
            colors = brand.colors if brand else {}
            content = self._mock_output(modality, prompt, tone=tone, colors=colors, provider=pid)
            return {
                "provider_id": pid,
                "modality": modality,
                "content": content,
                "media_url": f"media://{pid}/{hashlib.md5(prompt.encode()).hexdigest()[:10]}",
                "failover_used": preferred is not None and pid != preferred,
            }
        raise RuntimeError("all media providers failed: " + "; ".join(errors))

    def _mock_output(self, modality: str, prompt: str, *, tone: str, colors: dict, provider: str) -> str:
        accent = colors.get("primary", "#0F172A")
        if modality == "text":
            return f"[{tone}] {prompt.strip()}\n\n— generated by {provider}"
        if modality == "image":
            return f"image:{provider}:{accent}:{prompt[:80]}"
        if modality == "video":
            return f"video:{provider}:15s:{prompt[:60]}"
        if modality in ("voice", "text_to_speech"):
            return f"audio:{provider}:tts:{prompt[:60]}"
        if modality == "speech_to_text":
            return f"transcript from {provider}: {prompt or 'hello world'}"
        return f"{modality}:{provider}:{prompt[:80]}"


class CreativeFactoryEngine:
    def __init__(self) -> None:
        self.media = MediaProviderManager()
        self.brands: dict[str, BrandProfile] = {}
        self.templates: dict[str, CreativeTemplate] = {}
        self.projects: dict[str, CreativeProject] = {}
        self.assets: dict[str, CreativeAsset] = {}
        self.media_library: dict[str, MediaItem] = {}
        self.campaigns: dict[str, Campaign] = {}
        self.publish_jobs: dict[str, PublishJob] = {}
        self.history: list[HistoryEntry] = []
        self._stats = {
            "generations": 0,
            "campaigns": 0,
            "publishes": 0,
            "searches": 0,
            "reviews": 0,
        }
        self._seeded = False

    def reset(self) -> None:
        self.media.reset()
        self.brands.clear()
        self.templates.clear()
        self.projects.clear()
        self.assets.clear()
        self.media_library.clear()
        self.campaigns.clear()
        self.publish_jobs.clear()
        self.history.clear()
        self._stats = {k: 0 for k in self._stats}
        self._seeded = False

    def _log(self, action: str, entity_type: str, entity_id: str, details: dict | None = None) -> None:
        self.history.append(
            HistoryEntry(
                history_id=new_id("chist"),
                action=action,
                entity_type=entity_type,
                entity_id=entity_id,
                details=details or {},
            )
        )
        self.history = self.history[-5000:]

    def ensure_seed(self) -> None:
        if self._seeded:
            return
        brand = BrandProfile(
            brand_id="brand_ados",
            name="ADOS Enterprise",
            logos=["logo://ados/primary.svg"],
            colors={"primary": "#0B3D5C", "accent": "#E8A838", "bg": "#F7F4EF"},
            typography={"display": "Söhne", "body": "IBM Plex Sans"},
            tone_of_voice="confident concise bilingual",
            templates=[],
            assets=[],
        )
        self.brands[brand.brand_id] = brand
        for ct in CreativeType:
            tpl = CreativeTemplate(
                template_id=new_id("ctpl"),
                name=f"{ct.value.replace('_', ' ').title()} Template",
                creative_type=ct,
                prompt=f"Create a {ct.value.replace('_', ' ')} about {{topic}} for {{audience}}",
                brand_id=brand.brand_id,
                channels=["telegram", "linkedin"],
                variables=["topic", "audience"],
            )
            self.templates[tpl.template_id] = tpl
            brand.templates.append(tpl.template_id)
        project = CreativeProject(
            project_id="cproj_demo",
            name="Q3 Growth Creative",
            brand_id=brand.brand_id,
        )
        self.projects[project.project_id] = project
        self._seeded = True

    # --- Brand Center ---

    def list_brands(self) -> list[BrandProfile]:
        self.ensure_seed()
        return list(self.brands.values())

    def upsert_brand(self, body: dict[str, Any]) -> BrandProfile:
        self.ensure_seed()
        brand_id = str(body.get("brand_id") or new_id("brand"))
        brand = BrandProfile(
            brand_id=brand_id,
            name=str(body.get("name") or "Brand"),
            logos=list(body.get("logos") or []),
            colors=dict(body.get("colors") or {}),
            typography=dict(body.get("typography") or {}),
            tone_of_voice=str(body.get("tone_of_voice") or "professional"),
            templates=list(body.get("templates") or []),
            assets=list(body.get("assets") or []),
            metadata=dict(body.get("metadata") or {}),
        )
        self.brands[brand_id] = brand
        self._log("brand_upsert", "brand", brand_id)
        return brand

    def get_brand(self, brand_id: str) -> BrandProfile:
        self.ensure_seed()
        brand = self.brands.get(brand_id)
        if brand is None:
            raise KeyError(f"brand not found: {brand_id}")
        return brand

    # --- Templates / Projects ---

    def list_templates(self, *, creative_type: str | None = None) -> list[CreativeTemplate]:
        self.ensure_seed()
        rows = list(self.templates.values())
        if creative_type:
            rows = [
                t
                for t in rows
                if (t.creative_type.value if isinstance(t.creative_type, CreativeType) else t.creative_type)
                == creative_type
            ]
        return rows

    def create_project(self, body: dict[str, Any]) -> CreativeProject:
        self.ensure_seed()
        project = CreativeProject(
            project_id=new_id("cproj"),
            name=str(body.get("name") or "Creative Project"),
            brand_id=body.get("brand_id") or "brand_ados",
            metadata=dict(body.get("metadata") or {}),
        )
        self.projects[project.project_id] = project
        self._log("project_create", "project", project.project_id)
        return project

    def list_projects(self) -> list[CreativeProject]:
        self.ensure_seed()
        return sorted(self.projects.values(), key=lambda p: p.updated_at, reverse=True)

    # --- Creative Studio ---

    async def generate(self, body: dict[str, Any]) -> CreativeAsset:
        self.ensure_seed()
        ctype = CreativeType(str(body.get("creative_type") or CreativeType.SOCIAL_POST.value))
        modality = MediaModality(str(body.get("modality") or MediaModality.TEXT.value))
        brand_id = body.get("brand_id") or "brand_ados"
        brand = self.brands.get(brand_id)
        topic = str(body.get("topic") or body.get("prompt") or "enterprise growth")
        audience = str(body.get("audience") or "decision makers")
        template_id = body.get("template_id")
        prompt = str(body.get("prompt") or "")
        if template_id and template_id in self.templates:
            tpl = self.templates[template_id]
            prompt = tpl.prompt.replace("{topic}", topic).replace("{audience}", audience)
            ctype = tpl.creative_type if isinstance(tpl.creative_type, CreativeType) else CreativeType(tpl.creative_type)
        if not prompt:
            prompt = f"Create a {ctype.value.replace('_', ' ')} about {topic} for {audience}"

        media_out = await self.media.generate(
            modality.value,
            prompt,
            preferred=body.get("provider_id"),
            brand=brand,
        )
        asset = CreativeAsset(
            asset_id=new_id("casset"),
            title=str(body.get("title") or f"{ctype.value}: {topic[:40]}"),
            creative_type=ctype,
            content=str(media_out.get("content") or ""),
            modality=modality,
            project_id=body.get("project_id"),
            brand_id=brand_id,
            template_id=template_id,
            status=AssetStatus.DRAFT,
            media_url=media_out.get("media_url"),
            prompt=prompt,
            provider_id=media_out.get("provider_id"),
            tags=list(body.get("tags") or [ctype.value, modality.value]),
            embedding=_embed(f"{prompt} {media_out.get('content')}"),
            metadata={"failover_used": media_out.get("failover_used"), **dict(body.get("metadata") or {})},
        )
        self.assets[asset.asset_id] = asset
        if asset.project_id and asset.project_id in self.projects:
            self.projects[asset.project_id].asset_ids.append(asset.asset_id)
            self.projects[asset.project_id].updated_at = time.time()
        # library entry
        item = MediaItem(
            media_id=new_id("cmedia"),
            title=asset.title,
            modality=modality,
            url=asset.media_url or f"asset://{asset.asset_id}",
            prompt=prompt,
            tags=list(asset.tags),
            embedding=list(asset.embedding),
            metadata={"asset_id": asset.asset_id},
        )
        self.media_library[item.media_id] = item
        self._stats["generations"] += 1
        self._log("generate", "asset", asset.asset_id, {"type": ctype.value, "provider": asset.provider_id})
        return asset

    def list_assets(self, *, creative_type: str | None = None, status: str | None = None) -> list[CreativeAsset]:
        self.ensure_seed()
        rows = list(self.assets.values())
        if creative_type:
            rows = [
                a
                for a in rows
                if (a.creative_type.value if isinstance(a.creative_type, CreativeType) else a.creative_type)
                == creative_type
            ]
        if status:
            rows = [
                a for a in rows if (a.status.value if isinstance(a.status, AssetStatus) else a.status) == status
            ]
        return sorted(rows, key=lambda a: a.updated_at, reverse=True)

    def get_asset(self, asset_id: str) -> CreativeAsset:
        asset = self.assets.get(asset_id)
        if asset is None:
            raise KeyError(f"asset not found: {asset_id}")
        return asset

    def review_asset(self, asset_id: str, *, approve: bool = True, notes: str = "") -> CreativeAsset:
        asset = self.get_asset(asset_id)
        asset.status = AssetStatus.APPROVED if approve else AssetStatus.REVIEW
        asset.updated_at = time.time()
        asset.metadata["review_notes"] = notes
        self._stats["reviews"] += 1
        self._log("review", "asset", asset_id, {"approve": approve})
        return asset

    def version_asset(self, asset_id: str, body: dict[str, Any]) -> CreativeAsset:
        asset = self.get_asset(asset_id)
        asset.version += 1
        if body.get("content") is not None:
            asset.content = str(body["content"])
        if body.get("title"):
            asset.title = str(body["title"])
        asset.embedding = _embed(f"{asset.prompt} {asset.content}")
        asset.updated_at = time.time()
        self._log("version", "asset", asset_id, {"version": asset.version})
        return asset

    # --- Content Library ---

    def list_media(self, *, modality: str | None = None) -> list[MediaItem]:
        self.ensure_seed()
        rows = list(self.media_library.values())
        if modality:
            rows = [
                m
                for m in rows
                if (m.modality.value if isinstance(m.modality, MediaModality) else m.modality) == modality
            ]
        return sorted(rows, key=lambda m: m.created_at, reverse=True)

    def store_media(self, body: dict[str, Any]) -> MediaItem:
        self.ensure_seed()
        title = str(body.get("title") or "Media")
        prompt = str(body.get("prompt") or title)
        item = MediaItem(
            media_id=new_id("cmedia"),
            title=title,
            modality=str(body.get("modality") or MediaModality.IMAGE.value),
            url=str(body.get("url") or f"media://local/{new_id('file')}"),
            prompt=prompt,
            tags=list(body.get("tags") or []),
            embedding=_embed(prompt + " " + title),
            metadata=dict(body.get("metadata") or {}),
        )
        self.media_library[item.media_id] = item
        self._log("media_store", "media", item.media_id)
        return item

    def search(self, query: str, *, limit: int = 10) -> list[dict[str, Any]]:
        self.ensure_seed()
        q = _embed(query)
        self._stats["searches"] += 1
        hits: list[dict[str, Any]] = []
        for asset in self.assets.values():
            score = _cosine(q, asset.embedding)
            kw = 0.2 if query.lower() in (asset.title + " " + asset.content).lower() else 0.0
            hits.append({"kind": "asset", "id": asset.asset_id, "title": asset.title, "score": round(score + kw, 4)})
        for media in self.media_library.values():
            score = _cosine(q, media.embedding)
            hits.append({"kind": "media", "id": media.media_id, "title": media.title, "score": round(score, 4)})
        hits.sort(key=lambda h: h["score"], reverse=True)
        return hits[:limit]

    # --- Campaign Builder ---

    def create_campaign(self, body: dict[str, Any]) -> Campaign:
        self.ensure_seed()
        campaign = Campaign(
            campaign_id=new_id("camp"),
            name=str(body.get("name") or "Campaign"),
            objective=str(body.get("objective") or "awareness"),
            audience=str(body.get("audience") or "general"),
            channels=list(body.get("channels") or ["telegram", "linkedin"]),
            budget=float(body.get("budget") or 0),
            creative_ids=list(body.get("creative_ids") or []),
            schedule_at=body.get("schedule_at"),
            status=CampaignStatus.SCHEDULED if body.get("schedule_at") else CampaignStatus.DRAFT,
            brand_id=body.get("brand_id") or "brand_ados",
            project_id=body.get("project_id"),
            analytics={"impressions": 0, "clicks": 0, "conversions": 0},
            metadata=dict(body.get("metadata") or {}),
        )
        self.campaigns[campaign.campaign_id] = campaign
        if campaign.project_id and campaign.project_id in self.projects:
            self.projects[campaign.project_id].campaign_ids.append(campaign.campaign_id)
        self._stats["campaigns"] += 1
        self._log("campaign_create", "campaign", campaign.campaign_id)
        return campaign

    def list_campaigns(self) -> list[Campaign]:
        self.ensure_seed()
        return sorted(self.campaigns.values(), key=lambda c: c.updated_at, reverse=True)

    def get_campaign(self, campaign_id: str) -> Campaign:
        campaign = self.campaigns.get(campaign_id)
        if campaign is None:
            raise KeyError(f"campaign not found: {campaign_id}")
        return campaign

    def attach_creative(self, campaign_id: str, asset_id: str) -> Campaign:
        campaign = self.get_campaign(campaign_id)
        self.get_asset(asset_id)
        if asset_id not in campaign.creative_ids:
            campaign.creative_ids.append(asset_id)
        campaign.updated_at = time.time()
        return campaign

    def campaign_analytics(self, campaign_id: str, body: dict[str, Any] | None = None) -> dict[str, Any]:
        campaign = self.get_campaign(campaign_id)
        body = body or {}
        for key in ("impressions", "clicks", "conversions"):
            if key in body:
                campaign.analytics[key] = int(body[key])
        if not any(k in body for k in ("impressions", "clicks", "conversions")):
            # synthetic progress for active campaigns
            campaign.analytics["impressions"] = int(campaign.analytics.get("impressions") or 0) + 100
            campaign.analytics["clicks"] = int(campaign.analytics.get("clicks") or 0) + 7
        campaign.updated_at = time.time()
        return {"campaign_id": campaign_id, "analytics": dict(campaign.analytics), "status": campaign.status.value if isinstance(campaign.status, CampaignStatus) else campaign.status}

    # --- Publishing Hub ---

    async def publish(self, body: dict[str, Any]) -> PublishJob:
        self.ensure_seed()
        channel = PublishChannel(str(body.get("channel") or PublishChannel.TELEGRAM.value))
        asset_id = str(body.get("asset_id") or "")
        asset = self.get_asset(asset_id)
        scheduled_at = body.get("scheduled_at")
        job = PublishJob(
            job_id=new_id("cpub"),
            channel=channel,
            asset_id=asset_id,
            campaign_id=body.get("campaign_id"),
            status="scheduled" if scheduled_at and float(scheduled_at) > time.time() else "publishing",
            scheduled_at=float(scheduled_at) if scheduled_at else None,
        )
        if job.status == "publishing":
            job.status = "published"
            job.published_at = time.time()
            job.external_id = f"{channel.value}_{asset_id[-8:]}"
            asset.status = AssetStatus.PUBLISHED
            asset.updated_at = time.time()
            self._stats["publishes"] += 1
        self.publish_jobs[job.job_id] = job
        self._log("publish", "publish_job", job.job_id, {"channel": channel.value, "status": job.status})
        return job

    def list_publish_jobs(self) -> list[PublishJob]:
        self.ensure_seed()
        return sorted(self.publish_jobs.values(), key=lambda j: j.job_id, reverse=True)

    def run_scheduled(self) -> list[dict[str, Any]]:
        now = time.time()
        done = []
        for job in self.publish_jobs.values():
            if job.status == "scheduled" and job.scheduled_at and job.scheduled_at <= now:
                job.status = "published"
                job.published_at = now
                job.external_id = f"{job.channel.value if isinstance(job.channel, PublishChannel) else job.channel}_{job.asset_id[-8:]}"
                if job.asset_id in self.assets:
                    self.assets[job.asset_id].status = AssetStatus.PUBLISHED
                self._stats["publishes"] += 1
                done.append(job.to_dict())
        return done

    def statistics(self) -> dict[str, Any]:
        self.ensure_seed()
        return {
            **self._stats,
            "brands": len(self.brands),
            "templates": len(self.templates),
            "projects": len(self.projects),
            "assets": len(self.assets),
            "media": len(self.media_library),
            "campaigns": len(self.campaigns),
            "publish_jobs": len(self.publish_jobs),
            "providers": len(self.media.providers),
            "creative_types": [c.value for c in CreativeType],
            "channels": [c.value for c in PublishChannel],
        }

    def timeline(self, *, limit: int = 100) -> list[dict[str, Any]]:
        return [h.to_dict() for h in sorted(self.history, key=lambda x: x.created_at, reverse=True)[:limit]]

    def analytics_dashboard(self) -> dict[str, Any]:
        self.ensure_seed()
        by_type: dict[str, int] = {}
        for a in self.assets.values():
            k = a.creative_type.value if isinstance(a.creative_type, CreativeType) else str(a.creative_type)
            by_type[k] = by_type.get(k, 0) + 1
        return {
            "statistics": self.statistics(),
            "assets_by_type": by_type,
            "campaigns": [
                {
                    "campaign_id": c.campaign_id,
                    "name": c.name,
                    "analytics": c.analytics,
                    "status": c.status.value if isinstance(c.status, CampaignStatus) else c.status,
                }
                for c in self.list_campaigns()
            ],
            "providers": self.media.list_providers(),
        }


creative_factory_engine = CreativeFactoryEngine()
