"""Register Recruiting Ops routes (Sprint Recruiting 1.0)."""

from __future__ import annotations

from aiohttp import web

from applications.recruiting_enterprise.api import ops_handlers
from applications.recruiting_enterprise.api.middleware import recruiting_auth_middleware
from applications.recruiting_enterprise.config import DEFAULT_CONFIG


def register_recruiting_enterprise_routes(app: web.Application) -> None:
    if recruiting_auth_middleware not in app.middlewares:
        app.middlewares.append(recruiting_auth_middleware)
    ops = DEFAULT_CONFIG.api_prefix
    app.router.add_get(f"{ops}/health", ops_handlers.ops_health_handler)
    app.router.add_get(f"{ops}/ops/diagnostics", ops_handlers.ops_diagnostics_handler)
    app.router.add_get(f"{ops}/roles", ops_handlers.ops_roles_handler)
    app.router.add_get(f"{ops}/catalogs", ops_handlers.ops_catalogs_handler)
    app.router.add_get(f"{ops}/vanguard/contract", ops_handlers.ops_vanguard_contract_handler)
    app.router.add_get(f"{ops}/ads/foundation", ops_handlers.ops_ads_foundation_handler)
    app.router.add_get(f"{ops}/ads/control-center", ops_handlers.ops_ads_control_center_handler)
    app.router.add_get(f"{ops}/providers", ops_handlers.ops_providers_handler)
    app.router.add_get(f"{ops}/oauth/{{provider}}/callback", ops_handlers.ops_oauth_callback_handler)
    app.router.add_get(f"{ops}/providers/{{provider}}/oauth/start", ops_handlers.ops_oauth_start_handler)
    app.router.add_post(f"{ops}/providers/{{provider}}/test-connection", ops_handlers.ops_provider_test_handler)
    app.router.add_post(f"{ops}/providers/{{provider}}/sync-metrics", ops_handlers.ops_provider_sync_metrics_handler)
    app.router.add_post(f"{ops}/providers/{{provider}}/sync-campaigns", ops_handlers.ops_provider_sync_campaigns_handler)
    app.router.add_get(f"{ops}/providers/{{provider}}/wizard", ops_handlers.ops_provider_wizard_handler)
    app.router.add_post(f"{ops}/providers/{{provider}}/configure", ops_handlers.ops_provider_configure_handler)
    app.router.add_post(f"{ops}/providers/{{provider}}/{{action}}", ops_handlers.ops_provider_action_handler)
    app.router.add_post(f"{ops}/providers/leads", ops_handlers.ops_provider_leads_handler)
    app.router.add_get(f"{ops}/webhooks/whatsapp", ops_handlers.ops_whatsapp_webhook_handler)
    app.router.add_post(f"{ops}/webhooks/whatsapp", ops_handlers.ops_whatsapp_webhook_handler)
    app.router.add_post(f"{ops}/campaign-writes", ops_handlers.ops_campaign_write_create_handler)
    app.router.add_post(f"{ops}/campaign-writes/{{write_id}}/decision", ops_handlers.ops_campaign_write_decide_handler)
    app.router.add_post(f"{ops}/messages", ops_handlers.ops_outbound_create_handler)
    app.router.add_post(f"{ops}/messages/{{message_id}}/decision", ops_handlers.ops_outbound_decide_handler)
    app.router.add_get(f"{ops}/automation/rules", ops_handlers.ops_automation_list_handler)
    app.router.add_post(f"{ops}/automation/rules", ops_handlers.ops_automation_create_handler)
    app.router.add_post(f"{ops}/automation/rules/{{rule_id}}/run", ops_handlers.ops_automation_run_handler)
    app.router.add_get(f"{ops}/ai/recommendations", ops_handlers.ops_ai_list_handler)
    app.router.add_post(f"{ops}/ai/recommendations", ops_handlers.ops_ai_create_handler)
    app.router.add_post(f"{ops}/ai/recommendations/{{rec_id}}/decision", ops_handlers.ops_ai_decide_handler)
    app.router.add_post(f"{ops}/tracking/retries", ops_handlers.ops_tracking_retries_handler)
    app.router.add_post(f"{ops}/tracking/recover", ops_handlers.ops_tracking_recover_handler)
    app.router.add_post(f"{ops}/vanguard/leads", ops_handlers.ops_vanguard_ingest_handler)
    app.router.add_get(f"{ops}/projects", ops_handlers.ops_projects_handler)
    app.router.add_get(f"{ops}/projects/{{project_key}}", ops_handlers.ops_project_overview_handler)
    app.router.add_get(f"{ops}/projects/{{project_key}}/integration", ops_handlers.ops_project_integration_handler)
    app.router.add_post(f"{ops}/projects/{{project_key}}/integration", ops_handlers.ops_project_integration_handler)
    app.router.add_post(f"{ops}/projects/{{project_key}}/integration/check", ops_handlers.ops_project_integration_handler)
    app.router.add_get(f"{ops}/lookup", ops_handlers.ops_lookup_handler)
    app.router.add_get(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_post(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_get(f"{ops}/analytics", ops_handlers.ops_analytics_handler)
    app.router.add_get(f"{ops}/activity", ops_handlers.ops_activity_handler)
    app.router.add_get(f"{ops}/leads", ops_handlers.ops_leads_handler)
    app.router.add_post(f"{ops}/leads", ops_handlers.ops_leads_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/assign", ops_handlers.ops_lead_assign_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/notes", ops_handlers.ops_lead_note_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/qualify", ops_handlers.ops_lead_qualify_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/convert", ops_handlers.ops_lead_convert_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/status", ops_handlers.ops_lead_status_handler)
    app.router.add_post(f"{ops}/leads/{{lead_id}}/vacancy", ops_handlers.ops_lead_vacancy_handler)
    app.router.add_get(f"{ops}/candidates", ops_handlers.ops_candidates_handler)
    app.router.add_post(f"{ops}/candidates", ops_handlers.ops_candidates_handler)
    app.router.add_post(f"{ops}/candidates/{{candidate_id}}/stage", ops_handlers.ops_candidate_stage_handler)
    app.router.add_get(f"{ops}/candidates/{{candidate_id}}/emails", ops_handlers.ops_candidate_emails_handler)
    app.router.add_post(f"{ops}/candidates/{{candidate_id}}/email", ops_handlers.ops_candidate_email_send_handler)
    app.router.add_get(f"{ops}/whatsapp/conversations", ops_handlers.ops_whatsapp_conversations_handler)
    app.router.add_get(f"{ops}/whatsapp/templates", ops_handlers.ops_whatsapp_templates_handler)
    app.router.add_post(f"{ops}/whatsapp/ai-draft", ops_handlers.ops_whatsapp_ai_draft_handler)
    app.router.add_post(f"{ops}/candidates/{{candidate_id}}/whatsapp", ops_handlers.ops_candidate_whatsapp_send_handler)
    app.router.add_get(f"{ops}/email/templates", ops_handlers.ops_email_templates_handler)
    app.router.add_post(f"{ops}/email/preview", ops_handlers.ops_email_preview_handler)
    app.router.add_post(f"{ops}/email/suppression", ops_handlers.ops_email_suppression_handler)
    app.router.add_get(f"{ops}/vacancies", ops_handlers.ops_vacancies_handler)
    app.router.add_post(f"{ops}/vacancies", ops_handlers.ops_vacancies_handler)
    app.router.add_post(f"{ops}/vacancies/{{vacancy_id}}", ops_handlers.ops_vacancy_update_handler)
    app.router.add_get(f"{ops}/campaigns", ops_handlers.ops_campaigns_handler)
    app.router.add_post(f"{ops}/campaigns", ops_handlers.ops_campaigns_handler)
    app.router.add_post(f"{ops}/campaigns/{{campaign_id}}", ops_handlers.ops_campaign_update_handler)
    app.router.add_get(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks/{{task_id}}/complete", ops_handlers.ops_task_complete_handler)
    app.router.add_get(f"{ops}/communications", ops_handlers.ops_communications_handler)
    app.router.add_post(f"{ops}/communications", ops_handlers.ops_communications_handler)
