"""Register Finance Enterprise routes (Sprint 18.0)."""

from __future__ import annotations

from aiohttp import web

from applications.finance_enterprise.api import (
    bil_handlers,
    cfo_handlers,
    da_handlers,
    fec_handlers,
    handlers,
    int_handlers,
    pay_handlers,
    rpt_handlers,
    tr_handlers,
)
from applications.finance_enterprise.api.middleware import auth_middleware
from applications.finance_enterprise.config import DEFAULT_CONFIG


def register_finance_enterprise_routes(app: web.Application) -> None:
    prefix = DEFAULT_CONFIG.api_prefix
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    app.router.add_get(f"{prefix}/health", handlers.health_handler)
    app.router.add_post(f"{prefix}/bootstrap", handlers.bootstrap_handler)
    app.router.add_get(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_post(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_get(f"{prefix}/ledger", handlers.ledger_handler)
    app.router.add_post(f"{prefix}/ledger", handlers.ledger_handler)
    app.router.add_get(f"{prefix}/currency", handlers.currency_handler)
    app.router.add_post(f"{prefix}/currency", handlers.currency_handler)
    app.router.add_get(f"{prefix}/architecture", handlers.architecture_handler)
    app.router.add_post(f"{prefix}/architecture", handlers.architecture_handler)
    app.router.add_get(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_post(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_get(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_post(f"{prefix}/knowledge", handlers.knowledge_handler)

    # Sprint 18.1 — Payments Platform (additive; prior routes unchanged)
    pay = DEFAULT_CONFIG.payments_api_prefix
    app.router.add_get(f"{pay}/health", pay_handlers.pay_health_handler)
    app.router.add_post(f"{pay}/bootstrap", pay_handlers.pay_bootstrap_handler)
    app.router.add_get(f"{pay}/banking", pay_handlers.pay_banking_handler)
    app.router.add_post(f"{pay}/banking", pay_handlers.pay_banking_handler)
    app.router.add_get(f"{pay}/wallets", pay_handlers.pay_wallets_handler)
    app.router.add_post(f"{pay}/wallets", pay_handlers.pay_wallets_handler)
    app.router.add_get(f"{pay}/payments", pay_handlers.pay_payments_handler)
    app.router.add_post(f"{pay}/payments", pay_handlers.pay_payments_handler)
    app.router.add_get(f"{pay}/cash", pay_handlers.pay_cash_handler)
    app.router.add_post(f"{pay}/cash", pay_handlers.pay_cash_handler)
    app.router.add_get(f"{pay}/processing", pay_handlers.pay_processing_handler)
    app.router.add_post(f"{pay}/processing", pay_handlers.pay_processing_handler)
    app.router.add_get(f"{pay}/controls", pay_handlers.pay_controls_handler)
    app.router.add_post(f"{pay}/controls", pay_handlers.pay_controls_handler)
    app.router.add_get(f"{pay}/dashboard", pay_handlers.pay_dashboard_handler)
    app.router.add_post(f"{pay}/dashboard", pay_handlers.pay_dashboard_handler)
    app.router.add_get(f"{pay}/knowledge", pay_handlers.pay_knowledge_handler)
    app.router.add_post(f"{pay}/knowledge", pay_handlers.pay_knowledge_handler)

    # Sprint 18.2 — Billing Platform (additive; prior routes unchanged)
    bil = DEFAULT_CONFIG.billing_api_prefix
    app.router.add_get(f"{bil}/health", bil_handlers.bil_health_handler)
    app.router.add_post(f"{bil}/bootstrap", bil_handlers.bil_bootstrap_handler)
    app.router.add_get(f"{bil}/invoices", bil_handlers.bil_invoices_handler)
    app.router.add_post(f"{bil}/invoices", bil_handlers.bil_invoices_handler)
    app.router.add_get(f"{bil}/quotations", bil_handlers.bil_quotations_handler)
    app.router.add_post(f"{bil}/quotations", bil_handlers.bil_quotations_handler)
    app.router.add_get(f"{bil}/receivables", bil_handlers.bil_receivables_handler)
    app.router.add_post(f"{bil}/receivables", bil_handlers.bil_receivables_handler)
    app.router.add_get(f"{bil}/payables", bil_handlers.bil_payables_handler)
    app.router.add_post(f"{bil}/payables", bil_handlers.bil_payables_handler)
    app.router.add_get(f"{bil}/tax", bil_handlers.bil_tax_handler)
    app.router.add_post(f"{bil}/tax", bil_handlers.bil_tax_handler)
    app.router.add_get(f"{bil}/cashflow", bil_handlers.bil_cashflow_handler)
    app.router.add_post(f"{bil}/cashflow", bil_handlers.bil_cashflow_handler)
    app.router.add_get(f"{bil}/ai", bil_handlers.bil_ai_handler)
    app.router.add_post(f"{bil}/ai", bil_handlers.bil_ai_handler)
    app.router.add_get(f"{bil}/dashboard", bil_handlers.bil_dashboard_handler)
    app.router.add_post(f"{bil}/dashboard", bil_handlers.bil_dashboard_handler)
    app.router.add_get(f"{bil}/knowledge", bil_handlers.bil_knowledge_handler)
    app.router.add_post(f"{bil}/knowledge", bil_handlers.bil_knowledge_handler)

    # Sprint 18.3 — Treasury Platform (additive; prior routes unchanged)
    tr = DEFAULT_CONFIG.treasury_api_prefix
    app.router.add_get(f"{tr}/health", tr_handlers.tr_health_handler)
    app.router.add_post(f"{tr}/bootstrap", tr_handlers.tr_bootstrap_handler)
    app.router.add_get(f"{tr}/treasury", tr_handlers.tr_treasury_handler)
    app.router.add_post(f"{tr}/treasury", tr_handlers.tr_treasury_handler)
    app.router.add_get(f"{tr}/reconciliation", tr_handlers.tr_reconciliation_handler)
    app.router.add_post(f"{tr}/reconciliation", tr_handlers.tr_reconciliation_handler)
    app.router.add_get(f"{tr}/budgets", tr_handlers.tr_budgets_handler)
    app.router.add_post(f"{tr}/budgets", tr_handlers.tr_budgets_handler)
    app.router.add_get(f"{tr}/planning", tr_handlers.tr_planning_handler)
    app.router.add_post(f"{tr}/planning", tr_handlers.tr_planning_handler)
    app.router.add_get(f"{tr}/forecast", tr_handlers.tr_forecast_handler)
    app.router.add_post(f"{tr}/forecast", tr_handlers.tr_forecast_handler)
    app.router.add_get(f"{tr}/variance", tr_handlers.tr_variance_handler)
    app.router.add_post(f"{tr}/variance", tr_handlers.tr_variance_handler)
    app.router.add_get(f"{tr}/ai", tr_handlers.tr_ai_handler)
    app.router.add_post(f"{tr}/ai", tr_handlers.tr_ai_handler)
    app.router.add_get(f"{tr}/dashboard", tr_handlers.tr_dashboard_handler)
    app.router.add_post(f"{tr}/dashboard", tr_handlers.tr_dashboard_handler)
    app.router.add_get(f"{tr}/knowledge", tr_handlers.tr_knowledge_handler)
    app.router.add_post(f"{tr}/knowledge", tr_handlers.tr_knowledge_handler)

    # Sprint 18.4 — Digital Asset Treasury (additive; prior routes unchanged)
    da = DEFAULT_CONFIG.digital_assets_api_prefix
    app.router.add_get(f"{da}/health", da_handlers.da_health_handler)
    app.router.add_post(f"{da}/bootstrap", da_handlers.da_bootstrap_handler)
    app.router.add_get(f"{da}/registry", da_handlers.da_registry_handler)
    app.router.add_post(f"{da}/registry", da_handlers.da_registry_handler)
    app.router.add_get(f"{da}/wallets", da_handlers.da_wallets_handler)
    app.router.add_post(f"{da}/wallets", da_handlers.da_wallets_handler)
    app.router.add_get(f"{da}/accounting", da_handlers.da_accounting_handler)
    app.router.add_post(f"{da}/accounting", da_handlers.da_accounting_handler)
    app.router.add_get(f"{da}/operations", da_handlers.da_operations_handler)
    app.router.add_post(f"{da}/operations", da_handlers.da_operations_handler)
    app.router.add_get(f"{da}/exchange", da_handlers.da_exchange_handler)
    app.router.add_post(f"{da}/exchange", da_handlers.da_exchange_handler)
    app.router.add_get(f"{da}/ai", da_handlers.da_ai_handler)
    app.router.add_post(f"{da}/ai", da_handlers.da_ai_handler)
    app.router.add_get(f"{da}/dashboard", da_handlers.da_dashboard_handler)
    app.router.add_post(f"{da}/dashboard", da_handlers.da_dashboard_handler)
    app.router.add_get(f"{da}/knowledge", da_handlers.da_knowledge_handler)
    app.router.add_post(f"{da}/knowledge", da_handlers.da_knowledge_handler)

    # Sprint 18.5 — Financial Reporting & BI (additive; prior routes unchanged)
    rpt = DEFAULT_CONFIG.reporting_api_prefix
    app.router.add_get(f"{rpt}/health", rpt_handlers.rpt_health_handler)
    app.router.add_post(f"{rpt}/bootstrap", rpt_handlers.rpt_bootstrap_handler)
    app.router.add_get(f"{rpt}/statements", rpt_handlers.rpt_statements_handler)
    app.router.add_post(f"{rpt}/statements", rpt_handlers.rpt_statements_handler)
    app.router.add_get(f"{rpt}/management", rpt_handlers.rpt_management_handler)
    app.router.add_post(f"{rpt}/management", rpt_handlers.rpt_management_handler)
    app.router.add_get(f"{rpt}/intelligence", rpt_handlers.rpt_intelligence_handler)
    app.router.add_post(f"{rpt}/intelligence", rpt_handlers.rpt_intelligence_handler)
    app.router.add_get(f"{rpt}/consolidation", rpt_handlers.rpt_consolidation_handler)
    app.router.add_post(f"{rpt}/consolidation", rpt_handlers.rpt_consolidation_handler)
    app.router.add_get(f"{rpt}/forecast", rpt_handlers.rpt_forecast_handler)
    app.router.add_post(f"{rpt}/forecast", rpt_handlers.rpt_forecast_handler)
    app.router.add_get(f"{rpt}/ai", rpt_handlers.rpt_ai_handler)
    app.router.add_post(f"{rpt}/ai", rpt_handlers.rpt_ai_handler)
    app.router.add_get(f"{rpt}/dashboard", rpt_handlers.rpt_dashboard_handler)
    app.router.add_post(f"{rpt}/dashboard", rpt_handlers.rpt_dashboard_handler)
    app.router.add_get(f"{rpt}/knowledge", rpt_handlers.rpt_knowledge_handler)
    app.router.add_post(f"{rpt}/knowledge", rpt_handlers.rpt_knowledge_handler)

    # Sprint 18.6 — AI CFO & Decision Support (additive; prior routes unchanged)
    cfo = DEFAULT_CONFIG.ai_cfo_api_prefix
    app.router.add_get(f"{cfo}/health", cfo_handlers.cfo_health_handler)
    app.router.add_post(f"{cfo}/bootstrap", cfo_handlers.cfo_bootstrap_handler)
    app.router.add_get(f"{cfo}/workspace", cfo_handlers.cfo_workspace_handler)
    app.router.add_post(f"{cfo}/workspace", cfo_handlers.cfo_workspace_handler)
    app.router.add_get(f"{cfo}/performance", cfo_handlers.cfo_performance_handler)
    app.router.add_post(f"{cfo}/performance", cfo_handlers.cfo_performance_handler)
    app.router.add_get(f"{cfo}/strategy", cfo_handlers.cfo_strategy_handler)
    app.router.add_post(f"{cfo}/strategy", cfo_handlers.cfo_strategy_handler)
    app.router.add_get(f"{cfo}/modeling", cfo_handlers.cfo_modeling_handler)
    app.router.add_post(f"{cfo}/modeling", cfo_handlers.cfo_modeling_handler)
    app.router.add_get(f"{cfo}/risk", cfo_handlers.cfo_risk_handler)
    app.router.add_post(f"{cfo}/risk", cfo_handlers.cfo_risk_handler)
    app.router.add_get(f"{cfo}/decisions", cfo_handlers.cfo_decisions_handler)
    app.router.add_post(f"{cfo}/decisions", cfo_handlers.cfo_decisions_handler)
    app.router.add_get(f"{cfo}/executive", cfo_handlers.cfo_executive_handler)
    app.router.add_post(f"{cfo}/executive", cfo_handlers.cfo_executive_handler)
    app.router.add_get(f"{cfo}/dashboard", cfo_handlers.cfo_dashboard_handler)
    app.router.add_post(f"{cfo}/dashboard", cfo_handlers.cfo_dashboard_handler)
    app.router.add_get(f"{cfo}/knowledge", cfo_handlers.cfo_knowledge_handler)
    app.router.add_post(f"{cfo}/knowledge", cfo_handlers.cfo_knowledge_handler)

    # Sprint 18.7 — Enterprise Financial Integration (additive; prior routes unchanged)
    integ = DEFAULT_CONFIG.integration_api_prefix
    app.router.add_get(f"{integ}/health", int_handlers.int_health_handler)
    app.router.add_post(f"{integ}/bootstrap", int_handlers.int_bootstrap_handler)
    app.router.add_get(f"{integ}/events", int_handlers.int_events_handler)
    app.router.add_post(f"{integ}/events", int_handlers.int_events_handler)
    app.router.add_get(f"{integ}/platforms", int_handlers.int_platforms_handler)
    app.router.add_post(f"{integ}/platforms", int_handlers.int_platforms_handler)
    app.router.add_get(f"{integ}/intelligence", int_handlers.int_intelligence_handler)
    app.router.add_post(f"{integ}/intelligence", int_handlers.int_intelligence_handler)
    app.router.add_get(f"{integ}/ai", int_handlers.int_ai_handler)
    app.router.add_post(f"{integ}/ai", int_handlers.int_ai_handler)
    app.router.add_get(f"{integ}/dashboard", int_handlers.int_dashboard_handler)
    app.router.add_post(f"{integ}/dashboard", int_handlers.int_dashboard_handler)
    app.router.add_get(f"{integ}/knowledge", int_handlers.int_knowledge_handler)
    app.router.add_post(f"{integ}/knowledge", int_handlers.int_knowledge_handler)

    # Sprint 18.8 — Enterprise Certification (additive; prior routes unchanged)
    fec = DEFAULT_CONFIG.enterprise_certification_api_prefix
    app.router.add_get(f"{fec}/health", fec_handlers.fec_health_handler)
    app.router.add_post(f"{fec}/bootstrap", fec_handlers.fec_bootstrap_handler)
    app.router.add_get(f"{fec}/architecture", fec_handlers.fec_architecture_handler)
    app.router.add_get(f"{fec}/integration", fec_handlers.fec_integration_handler)
    app.router.add_get(f"{fec}/performance", fec_handlers.fec_performance_handler)
    app.router.add_get(f"{fec}/security", fec_handlers.fec_security_handler)
    app.router.add_get(f"{fec}/integrity", fec_handlers.fec_integrity_handler)
    app.router.add_get(f"{fec}/documentation", fec_handlers.fec_documentation_handler)
    app.router.add_get(f"{fec}/quality", fec_handlers.fec_quality_handler)
    app.router.add_get(f"{fec}/release", fec_handlers.fec_release_handler)
    app.router.add_get(f"{fec}/executive", fec_handlers.fec_executive_handler)
    app.router.add_get(f"{fec}/dashboard", fec_handlers.fec_dashboard_handler)
    app.router.add_post(f"{fec}/dashboard", fec_handlers.fec_dashboard_handler)
