import type { CommandItem } from "../types";

/** Sprint 30.7 — Russian command catalog (Ctrl/Cmd+K). Every route opens a real module. */
export const COMMAND_CATALOG: CommandItem[] = [
  { id: "cmd_ws", kind: "navigate", action: "open_workspace", label: "Открыть рабочий стол", route: "/desktop", keywords: ["workspace", "рабочий", "стол", "home"] },
  { id: "cmd_cc", kind: "navigate", action: "open_command_center", label: "Командный центр", route: "/command-center", keywords: ["command", "палитра", "productivity"] },
  { id: "cmd_id", kind: "open_module", action: "open_identity", label: "Центр идентичности", route: "/identity", keywords: ["identity", "rbac", "пользователи"] },
  { id: "cmd_nav", kind: "open_module", action: "open_navigation", label: "Навигация", route: "/navigation", keywords: ["navigation", "навигация"] },
  { id: "act_open_module", kind: "navigate", action: "open_module", label: "Открыть модуль", route: "/search", keywords: ["модуль", "открыть", "навигация"] },
  { id: "act_open_client", kind: "open", action: "open_client", label: "Открыть клиента", route: "/crm?view=clients", keywords: ["клиент", "открыть", "crm"] },
  { id: "act_open_project", kind: "open", action: "open_project", label: "Открыть проект", route: "/projects", keywords: ["проект", "открыть"] },
  { id: "act_open_ai_agent", kind: "open", action: "open_ai_agent", label: "Открыть AI-агента", route: "/ai-agents", keywords: ["ai", "агент", "открыть"] },
  { id: "act_open_crm", kind: "open", action: "open_crm", label: "Открыть CRM", route: "/crm", keywords: ["crm"] },
  { id: "act_open_erp", kind: "open", action: "open_erp", label: "Открыть ERP", route: "/erp", keywords: ["erp"] },
  { id: "act_open_marketplace", kind: "open", action: "open_marketplace", label: "Открыть маркетплейс", route: "/marketplace", keywords: ["marketplace", "маркетплейс", "hub"] },
  { id: "act_open_ai_studio", kind: "open", action: "open_ai_studio", label: "Открыть AI-Студию", route: "/ai-studio", keywords: ["ai", "студия", "studio"] },
  { id: "act_open_documents", kind: "open", action: "open_documents", label: "Открыть документы", route: "/documents", keywords: ["документы", "documents", "docs"] },
  { id: "act_open_knowledge", kind: "open", action: "open_knowledge", label: "Открыть знания", route: "/knowledge", keywords: ["знания", "knowledge"] },
  { id: "act_open_analytics", kind: "open", action: "open_analytics", label: "Открыть аналитику", route: "/analytics", keywords: ["аналитика", "analytics"] },
  { id: "act_open_calendar", kind: "open", action: "open_calendar", label: "Открыть календарь", route: "/calendar", keywords: ["календарь", "calendar"] },
  { id: "act_open_tasks", kind: "open", action: "open_tasks", label: "Открыть задачи", route: "/tasks", keywords: ["задачи", "tasks"] },
  { id: "act_open_notifications", kind: "open", action: "open_notifications", label: "Открыть уведомления", route: "/notifications", keywords: ["уведомления", "notifications"] },
  { id: "act_open_finance", kind: "open", action: "open_finance", label: "Открыть финансы", route: "/workspace/finance", keywords: ["финансы", "finance"] },
  { id: "act_open_users", kind: "open", action: "open_users", label: "Открыть пользователей", route: "/identity/users", keywords: ["пользователи", "users"] },
  { id: "act_open_settings", kind: "open_settings", action: "open_settings", label: "Открыть настройки", route: "/settings", keywords: ["настройки", "settings"] },
  { id: "act_open_admin", kind: "open", action: "open_admin", label: "Панель администратора", route: "/admin", keywords: ["админ", "admin"] },
  { id: "act_open_owner", kind: "open", action: "open_owner", label: "Панель владельца", route: "/owner", keywords: ["владелец", "owner"] },
  { id: "act_search", kind: "navigate", action: "open_search", label: "Глобальный поиск", route: "/search", keywords: ["поиск", "search", "find"] },
  { id: "act_create_client", kind: "create", action: "create_client", label: "Создать клиента", route: "/crm?action=create_client", keywords: ["создать", "клиент", "create", "client"] },
  { id: "act_create_project", kind: "create", action: "create_project", label: "Создать проект", route: "/projects?action=create_project", keywords: ["создать", "проект", "create", "project"] },
  { id: "act_create_task", kind: "create", action: "create_task", label: "Создать задачу", route: "/tasks", keywords: ["создать", "задача", "create", "task"] },
  { id: "act_create_document", kind: "create", action: "create_document", label: "Создать документ", route: "/documents?action=create_document", keywords: ["создать", "документ", "create", "document"] },
  { id: "act_create_ai_agent", kind: "create", action: "create_ai_agent", label: "Создать AI-агента", route: "/ai-agents?action=create", keywords: ["создать", "агент", "create", "agent"] },
  { id: "act_create_knowledge", kind: "create", action: "create_knowledge", label: "Создать знание", route: "/knowledge?action=create", keywords: ["создать", "знания", "create", "knowledge"] },
  { id: "act_create_workflow", kind: "create", action: "create_workflow", label: "Создать процесс", route: "/automation?action=create_workflow", keywords: ["создать", "процесс", "create", "workflow"] },
  { id: "act_create_company", kind: "create", action: "create_company", label: "Создать компанию", route: "/identity/organizations?action=create_company", keywords: ["создать", "компания", "create", "company", "org"] },
  { id: "act_open_mission_control", kind: "open", action: "open_mission_control", label: "Открыть мониторинг", route: "/health", keywords: ["mission", "control", "мониторинг", "здоровье"] },
  { id: "act_open_enterprise_city", kind: "open", action: "open_enterprise_city", label: "Открыть город", route: "/city", keywords: ["город", "city", "enterprise", "карта"] },
  { id: "act_open_production", kind: "open", action: "open_production", label: "Открыть продакшн", route: "/production-studio", keywords: ["продакшн", "production"] },
  { id: "act_open_enterprise_twin", kind: "open", action: "open_enterprise_twin", label: "Открыть Digital Twin", route: "/platform-builder/digital-twin", keywords: ["twin", "digital", "organization"] },
  { id: "act_open_integrations", kind: "open", action: "open_integrations", label: "Открыть интеграции", route: "/platform-builder/integrations", keywords: ["integrations", "интеграции", "telegram", "webhook", "oauth"] },
  { id: "act_open_runtime", kind: "open", action: "open_runtime", label: "Открыть AI Runtime", route: "/platform-builder/runtime", keywords: ["runtime", "queue", "orchestration"] },
  { id: "act_open_data_fabric", kind: "open", action: "open_data_fabric", label: "Открыть Data Fabric", route: "/platform-builder/data-fabric", keywords: ["data", "fabric", "graph", "lineage"] },
  { id: "act_open_predictive", kind: "open", action: "open_predictive", label: "Предиктивный интеллект", route: "/platform-builder/predictive", keywords: ["predictive", "forecast", "scenario"] },
  { id: "act_open_autonomy", kind: "open", action: "open_autonomy", label: "Центр автономии", route: "/platform-builder/autonomy", keywords: ["autonomy", "approval", "hitl"] },
  { id: "act_open_control_tower", kind: "open", action: "open_control_tower", label: "Control Tower", route: "/platform-builder/control-tower", keywords: ["control", "tower", "executive"] },
  { id: "act_open_learning", kind: "open", action: "open_learning", label: "Центр обучения", route: "/platform-builder/learning", keywords: ["learning", "optimize", "recommendations"] },
  { id: "act_open_okr", kind: "open", action: "open_okr", label: "OKR Intelligence", route: "/platform-builder/okr", keywords: ["okr", "goals", "strategy", "kpi"] },
  { id: "act_open_governance", kind: "open", action: "open_governance", label: "Центр аудита", route: "/platform-builder/governance", keywords: ["governance", "compliance", "policy", "audit", "аудит"] },
  { id: "act_open_workflow_center", kind: "open", action: "open_workflow_center", label: "Центр процессов", route: "/platform-builder/workflow-center", keywords: ["workflow", "automation"] },
  { id: "act_open_builder_studio", kind: "open", action: "open_builder_studio", label: "AI Builder Studio", route: "/platform-builder/builder-studio", keywords: ["builder", "studio", "ai"] },
  { id: "act_open_concierge", kind: "open", action: "open_concierge", label: "AI-консьерж", route: "/platform-builder/concierge", keywords: ["concierge", "ai", "консьерж"] },
  { id: "act_open_ai_team", kind: "open", action: "open_ai_team", label: "AI-команда", route: "/platform-builder/ai-team", keywords: ["ai", "team", "команда"] },
  { id: "act_open_god", kind: "open", action: "open_god_mode", label: "God Mode", route: "/platform-builder/god-mode", keywords: ["god", "mode", "владелец"] },
  { id: "act_open_dashboard_exec", kind: "open", action: "open_dashboard", label: "Утренний брифинг", route: "/dashboard?mode=executive", keywords: ["dashboard", "executive", "брифинг"] },
  { id: "ai_recommendations", kind: "ai_execute", action: "ai_recommendations", label: "AI: рекомендации", route: "/dashboard", keywords: ["ai", "recommend", "рекомендации"] },
  { id: "ai_open_beauty", kind: "ai_execute", action: "open_beauty", label: "AI: Beauty", route: "/workspace/beauty", keywords: ["ai", "beauty"] },
  { id: "ai_open_auto", kind: "ai_execute", action: "open_auto", label: "AI: Auto", route: "/workspace/auto", keywords: ["ai", "auto"] },
  { id: "ai_open_agro", kind: "ai_execute", action: "open_agro", label: "ИИ: Агро", route: "/workspace/agro", keywords: ["ai", "agro", "агро"] },
  { id: "ai_weekly", kind: "ai_execute", action: "generate_weekly_report", label: "AI: недельный отчёт", route: "/workspace/reports/weekly", keywords: ["ai", "weekly", "report", "отчёт"] },
  { id: "ai_summarize", kind: "ai_execute", action: "summarize_workspace", label: "AI: сводка workspace", route: "/workspace", keywords: ["ai", "summarize", "сводка"] },
  { id: "ai_invoice", kind: "ai_execute", action: "create_invoice", label: "AI: создать счёт", route: "/workspace?action=create_invoice", keywords: ["ai", "invoice", "счёт"] },
  { id: "wf_run", kind: "run_workflow", action: "launch_workflow", label: "Запустить процесс", route: "/workspace/workflows/invoice", keywords: ["workflow", "launch", "процесс"] },
  { id: "auto_run", kind: "run_automation", action: "run_automation", label: "Запустить автоматизацию", route: "/workspace?action=run_automation", keywords: ["automation", "автоматизация"] },
];

export const quickActionsEngine = {
  list(): CommandItem[] {
    return [...COMMAND_CATALOG];
  },
  byAction(action: string): CommandItem | undefined {
    return COMMAND_CATALOG.find((c) => c.action === action || c.id === action);
  },
};
