/**
 * Sprint 27.2 — Enterprise module catalog (clean URLs + activation metadata).
 * Sprint 35.1 — UI module metadata projection only (NOT menu/navigation SoR).
 * Platform navigation SoR: platform_registry MENU_CATALOG / navigation API.
 * Hub pages always render; deepLinks open existing operational surfaces.
 */

export type ModuleReadiness = "ga" | "beta" | "preview" | "coming_soon";

export type ModuleQuickAction = {
  id: string;
  label: string;
  route: string;
};

export type EnterpriseModuleDef = {
  id: string;
  slug: string;
  /** Canonical clean URL, e.g. /crm */
  route: string;
  label: string;
  description: string;
  statusLabel: string;
  readiness: ModuleReadiness;
  readinessPct: number;
  icon: string;
  recentActions: string[];
  roadmap: string[];
  quickActions: ModuleQuickAction[];
  /** Legacy / deep operational paths kept working via redirects & links */
  aliases?: string[];
  deepLink?: string;
};

export const ENTERPRISE_MODULES: EnterpriseModuleDef[] = [
  {
    id: "dashboard",
    slug: "dashboard",
    route: "/dashboard",
    label: "Dashboard",
    description: "Enterprise Command Center — morning brief, KPIs, and module hubs.",
    statusLabel: "Operational",
    readiness: "ga",
    readinessPct: 96,
    icon: "dashboard",
    recentActions: ["Morning Brief refreshed", "KPI pulse synced", "Executive mode toggled"],
    roadmap: ["Live Runtime stream", "Personalized home layout", "Cross-module alerts"],
    quickActions: [
      { id: "exec", label: "Executive Mode", route: "/dashboard?mode=executive" },
      { id: "tower", label: "Control Tower", route: "/platform-builder/control-tower" },
      { id: "mission", label: "Mission Control", route: "/platform-builder/mission-control" },
    ],
  },
  {
    id: "crm",
    slug: "crm",
    route: "/crm",
    label: "CRM",
    description: "Clients, pipeline, deals, and relationship intelligence.",
    statusLabel: "Operational CRM",
    readiness: "beta",
    readinessPct: 88,
    icon: "crm",
    recentActions: ["CRM module opened", "Clients synced", "Pipeline updated"],
    roadmap: ["Deal stages automation", "AI follow-up agents", "Attachment blob store"],
    quickActions: [
      { id: "clients", label: "Клиенты", route: "/crm?view=clients" },
      { id: "leads", label: "Лиды", route: "/crm?view=leads" },
      { id: "pipeline", label: "Воронка", route: "/crm?view=pipelines" },
      { id: "ai", label: "Sales AI Team", route: "/platform-builder/ai-team" },
    ],
    aliases: ["/workspace/crm"],
    deepLink: "/crm?view=clients",
  },
  {
    id: "erp",
    slug: "erp",
    route: "/erp",
    label: "ERP",
    description: "Operations, inventory, fulfillment, and enterprise resources.",
    statusLabel: "Module hub active",
    readiness: "beta",
    readinessPct: 68,
    icon: "erp",
    recentActions: ["ERP shell opened", "Order board preview", "SLA check (local)"],
    roadmap: ["Inventory sync", "Procurement workflows", "Plant floor connectors"],
    quickActions: [
      { id: "ws", label: "Workspace ERP", route: "/workspace/erp" },
      { id: "builder", label: "ERP Builder", route: "/platform-builder/erp" },
      { id: "mission", label: "Mission Control", route: "/platform-builder/mission-control" },
    ],
    aliases: ["/workspace/erp"],
    deepLink: "/workspace/erp",
  },
  {
    id: "projects",
    slug: "projects",
    route: "/projects",
    label: "Projects",
    description: "Delivery workspaces, milestones, and cross-team execution.",
    statusLabel: "Projects operational",
    readiness: "beta",
    readinessPct: 80,
    icon: "projects",
    recentActions: ["Projects opened", "Kanban updated", "Task advanced"],
    roadmap: ["Resource allocation", "AI delivery coach", "Platform Project entity"],
    quickActions: [
      { id: "list", label: "Проекты", route: "/projects?view=projects" },
      { id: "kanban", label: "Канбан", route: "/projects?view=kanban" },
      { id: "tasks", label: "Задачи", route: "/projects?view=tasks" },
      { id: "wf", label: "Workflow Center", route: "/platform-builder/workflow-center" },
    ],
    aliases: ["/workspace"],
    deepLink: "/projects?view=projects",
  },
  {
    id: "production_studio",
    slug: "production-studio",
    route: "/production-studio",
    label: "AI Production Center",
    description: "Creative studios · pipelines · prompts · media · publish — Adobe/Figma-class production OS.",
    statusLabel: "Production Center Core live",
    readiness: "ga",
    readinessPct: 72,
    icon: "projects",
    recentActions: ["Studio opened", "Pipeline advanced", "Prompt reused"],
    roadmap: ["Real generation providers", "Render farm", "Social API publish"],
    quickActions: [
      { id: "home", label: "Open Production Center", route: "/production-studio" },
      { id: "pipeline", label: "Pipelines", route: "/production-studio?tab=pipeline" },
      { id: "prompts", label: "Prompt Library", route: "/production-studio?tab=prompts" },
      { id: "city", label: "Production District", route: "/enterprise-city" },
    ],
    aliases: ["/production"],
    deepLink: "/production-studio",
  },
  {
    id: "ai_studio",
    slug: "ai-studio",
    route: "/ai-studio",
    label: "AI Studio",
    description: "Visual AI content studio — image, video, audio, voice, avatar, prompts.",
    statusLabel: "Runtime-backed studio",
    readiness: "ga",
    readinessPct: 84,
    icon: "ai_studio",
    recentActions: ["Studio workbench", "Prompt collections", "Project dashboard"],
    roadmap: ["Backend generation adapters", "Streaming previews", "Eval harness"],
    quickActions: [
      { id: "studio", label: "Open AI Studio", route: "/ai-studio" },
      { id: "production", label: "Production Center", route: "/production-studio" },
      { id: "builder", label: "Builder Studio", route: "/platform-builder/builder-studio" },
    ],
    aliases: ["/platform-builder/builder-studio"],
    deepLink: "/ai-studio",
  },
  {
    id: "service_builder",
    slug: "service-builder",
    route: "/service-builder",
    label: "Service Builder",
    description: "Install, version, deploy and manage platform services without modifying Core.",
    statusLabel: "Enterprise Service Builder",
    readiness: "ga",
    readinessPct: 90,
    icon: "builder",
    recentActions: ["Catalog opened", "Service started", "Health probed"],
    roadmap: ["Marketplace publish", "Hot-reload plugins", "Multi-tenant sandboxes"],
    quickActions: [
      { id: "catalog", label: "Service Catalog", route: "/platform-builder/service-builder" },
      { id: "health", label: "Health Monitor", route: "/platform-builder/service-builder?section=health" },
    ],
    aliases: ["/platform-builder/service-builder"],
    deepLink: "/platform-builder/service-builder",
  },
  {
    id: "ai_agents",
    slug: "ai-agents",
    route: "/ai-agents",
    label: "AI Agents",
    description: "Running specialists, queues, and collaborative AI teams.",
    statusLabel: "AI Agent Center",
    readiness: "ga",
    readinessPct: 92,
    icon: "ai_agents",
    recentActions: ["Agent roster viewed", "Queue snapshot", "Task launched"],
    roadmap: ["Multi-agent handoffs", "SLA policies", "Cost controls"],
    quickActions: [
      { id: "center", label: "AI Agent Center", route: "/ai-agents" },
      { id: "team", label: "AI Team Center", route: "/platform-builder/ai-team" },
      { id: "runtime", label: "AI Runtime", route: "/platform-builder/runtime" },
    ],
    aliases: ["/platform-builder/ai-team"],
    deepLink: "/ai-agents",
  },
  {
    id: "knowledge",
    slug: "knowledge",
    route: "/knowledge",
    label: "Knowledge Base",
    description: "Enterprise memory, playbooks, and searchable knowledge graph.",
    statusLabel: "Knowledge operational",
    readiness: "beta",
    readinessPct: 82,
    icon: "knowledge",
    recentActions: ["KB opened", "Search run", "Wiki page saved"],
    roadmap: ["RAG connectors", "Policy packs", "Citation UI"],
    quickActions: [
      { id: "kb", label: "База знаний", route: "/knowledge?view=kb" },
      { id: "search", label: "Поиск", route: "/knowledge?view=search" },
      { id: "graph", label: "Граф", route: "/platform-builder/knowledge" },
      { id: "docs", label: "Документы", route: "/documents" },
    ],
    aliases: ["/platform-builder/knowledge"],
    deepLink: "/knowledge?view=kb",
  },
  {
    id: "documents",
    slug: "documents",
    route: "/documents",
    label: "Documents",
    description: "Document workspace, contracts, and collaborative files.",
    statusLabel: "Drive operational",
    readiness: "beta",
    readinessPct: 78,
    icon: "documents",
    recentActions: ["Drive opened", "File registered", "Preview opened"],
    roadmap: ["Versioning", "eSign hooks", "AI summarization"],
    quickActions: [
      { id: "browser", label: "Файлы", route: "/documents?view=browser" },
      { id: "upload", label: "Загрузка", route: "/documents?view=upload" },
      { id: "kb", label: "Знания", route: "/knowledge" },
      { id: "search", label: "Поиск", route: "/documents?view=search" },
    ],
    aliases: ["/workspace/docs"],
    deepLink: "/documents?view=browser",
  },
  {
    id: "analytics",
    slug: "analytics",
    route: "/analytics",
    label: "Analytics",
    description: "KPIs, executive views, and predictive intelligence.",
    statusLabel: "Analytics hub active",
    readiness: "beta",
    readinessPct: 74,
    icon: "analytics",
    recentActions: ["Analytics hub opened", "KPI cards loaded", "Predictive strip"],
    roadmap: ["Live warehouse", "Custom dashboards", "Alert routing"],
    quickActions: [
      { id: "ws", label: "Workspace Analytics", route: "/workspace/analytics" },
      { id: "intel", label: "Intelligence", route: "/platform-builder/intelligence" },
      { id: "pred", label: "Predictive", route: "/platform-builder/predictive" },
    ],
    aliases: ["/workspace/analytics"],
    deepLink: "/workspace/analytics",
  },
  {
    id: "marketplace",
    slug: "marketplace",
    route: "/marketplace",
    label: "Marketplace",
    description: "Solutions, templates, and installable enterprise packs.",
    statusLabel: "Marketplace operational",
    readiness: "ga",
    readinessPct: 90,
    icon: "marketplace",
    recentActions: ["Marketplace opened", "Module installed", "Details viewed"],
    roadmap: ["Billing hooks", "Private catalogs", "Version pinning"],
    quickActions: [
      { id: "available", label: "Доступные", route: "/marketplace?view=available" },
      { id: "installed", label: "Установленные", route: "/marketplace?view=installed" },
      { id: "hub", label: "Solution Hub", route: "/platform-builder/solution-hub" },
    ],
    aliases: ["/platform-builder/solution-hub"],
    deepLink: "/marketplace?view=available",
  },
  {
    id: "business_network",
    slug: "business-network",
    route: "/business-network",
    label: "Business Network",
    description: "Enterprise relationship layer — profiles, partners, graph, verified docs.",
    statusLabel: "EBN Foundation linked",
    readiness: "beta",
    readinessPct: 62,
    icon: "marketplace",
    recentActions: ["Business Network opened", "Partner graph probe", "City facade load"],
    roadmap: ["Partner District UI", "Reputation engine", "OCR document verify"],
    quickActions: [
      { id: "ebn", label: "Business Network", route: "/business-network" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
      { id: "auto", label: "Automation", route: "/automation" },
    ],
    aliases: ["/ebn", "/partners"],
    deepLink: "/business-network",
  },
  {
    id: "digital_citizens",
    slug: "digital-citizens",
    route: "/digital-citizens",
    label: "Digital Citizens",
    description: "Human layer — citizen profiles, membership, presence, personal AI, workspace.",
    statusLabel: "EDC Foundation linked",
    readiness: "beta",
    readinessPct: 58,
    icon: "hr",
    recentActions: ["Citizens opened", "Presence probe", "AI assignment"],
    roadmap: ["City avatars", "Deep HR sync", "Meeting rooms"],
    quickActions: [
      { id: "citizens", label: "Digital Citizens", route: "/digital-citizens" },
      { id: "ebn", label: "Business Network", route: "/business-network" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
    ],
    aliases: ["/citizens", "/people"],
    deepLink: "/digital-citizens",
  },
  {
    id: "life_engine",
    slug: "life-engine",
    route: "/life-engine",
    label: "Life Engine",
    description: "Living ecosystem — occupancy, movement, meetings, timelines over real runtime.",
    statusLabel: "Life Engine linked",
    readiness: "beta",
    readinessPct: 55,
    icon: "city",
    recentActions: ["Life Engine opened", "Occupancy sync", "Meeting started"],
    roadmap: ["Vehicle fleet viz", "City avatar paths", "Durable event store"],
    quickActions: [
      { id: "life", label: "Life Engine", route: "/life-engine" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
      { id: "citizens", label: "Digital Citizens", route: "/digital-citizens" },
    ],
    aliases: ["/life"],
    deepLink: "/life-engine",
  },
  {
    id: "assets",
    slug: "assets",
    route: "/assets",
    label: "Asset Runtime",
    description: "Managed enterprise assets — ownership, location, lifecycle, City inventory.",
    statusLabel: "Asset Runtime linked",
    readiness: "beta",
    readinessPct: 52,
    icon: "erp",
    recentActions: ["Assets opened", "Transfer probe", "City inventory"],
    roadmap: ["Accounting hooks", "Maintenance SLA", "Monetization"],
    quickActions: [
      { id: "assets", label: "Asset Runtime", route: "/assets" },
      { id: "life", label: "Life Engine", route: "/life-engine" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
    ],
    aliases: ["/asset-runtime", "/inventory"],
    deepLink: "/assets",
  },
  {
    id: "spatial",
    slug: "spatial",
    route: "/spatial",
    label: "Spatial Runtime",
    description: "Odessa Digital Twin spatial foundation — hierarchy, locations, districts, routing.",
    statusLabel: "Spatial Runtime linked",
    readiness: "beta",
    readinessPct: 50,
    icon: "city",
    recentActions: ["Spatial opened", "Route probe", "District query"],
    roadmap: ["Traffic layer", "Vehicle modes", "3D twin consume"],
    quickActions: [
      { id: "spatial", label: "Spatial Runtime", route: "/spatial" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
      { id: "assets", label: "Asset Runtime", route: "/assets" },
    ],
    aliases: ["/spatial-runtime", "/odessa"],
    deepLink: "/spatial",
  },
  {
    id: "city_visualization",
    slug: "city-visualization",
    route: "/city-visualization",
    label: "City Visualization",
    description: "Runtime bridge for Digital Twin clients — building, district, citizen, asset visual state.",
    statusLabel: "City Visualization linked",
    readiness: "beta",
    readinessPct: 48,
    icon: "city",
    recentActions: ["Scene rebuilt", "LOD probe", "Visible query"],
    roadmap: ["2D client consume", "3D twin consume", "Traffic layer live"],
    quickActions: [
      { id: "city_viz", label: "City Visualization", route: "/city-visualization" },
      { id: "spatial", label: "Spatial Runtime", route: "/spatial" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
    ],
    aliases: ["/city-viz", "/visualization"],
    deepLink: "/city-visualization",
  },
  {
    id: "interactions",
    slug: "interactions",
    route: "/interactions",
    label: "Interaction Runtime",
    description: "Runtime interaction layer — selection, context actions, search, navigation across the living City.",
    statusLabel: "Interaction Runtime linked",
    readiness: "beta",
    readinessPct: 46,
    icon: "city",
    recentActions: ["Object selected", "Action executed", "Quick jump"],
    roadmap: ["Mobile client", "3D twin gestures", "Voice commands"],
    quickActions: [
      { id: "interactions", label: "Interactions", route: "/interactions" },
      { id: "city_viz", label: "City Visualization", route: "/city-visualization" },
      { id: "city", label: "Enterprise City", route: "/enterprise-city" },
    ],
    aliases: ["/interaction-runtime", "/city-interactions"],
    deepLink: "/interactions",
  },
  {
    id: "intelligence",
    slug: "intelligence",
    route: "/intelligence",
    label: "Intelligence Runtime",
    description: "Advisory insights, recommendations, risks and trends — no autonomous execution.",
    statusLabel: "Intelligence Runtime linked",
    readiness: "beta",
    readinessPct: 45,
    icon: "analytics",
    recentActions: ["Cycle analyzed", "Risk advisory", "Recommendation created"],
    roadmap: ["Executive brief feed", "Approval handoff UX", "Trend forecasting"],
    quickActions: [
      { id: "intelligence", label: "Intelligence", route: "/intelligence" },
      { id: "interactions", label: "Interactions", route: "/interactions" },
      { id: "dashboard", label: "Command Center", route: "/dashboard" },
    ],
    aliases: ["/intelligence-runtime", "/insights"],
    deepLink: "/intelligence",
  },
  {
    id: "orchestrator",
    slug: "orchestrator",
    route: "/orchestrator",
    label: "Orchestrator",
    description: "Central coordination of enterprise runtimes — registry, health, dependencies, schedule.",
    statusLabel: "Orchestrator linked",
    readiness: "beta",
    readinessPct: 50,
    icon: "integrations",
    recentActions: ["Platform health probe", "Dependency order", "Event routed"],
    roadmap: ["Cross-runtime policies", "Failover orchestration", "SLA dashboards"],
    quickActions: [
      { id: "orchestrator", label: "Orchestrator", route: "/orchestrator" },
      { id: "intelligence", label: "Intelligence", route: "/intelligence" },
      { id: "interactions", label: "Interactions", route: "/interactions" },
    ],
    aliases: ["/orchestrator-runtime", "/runtime-orchestrator"],
    deepLink: "/orchestrator",
  },
  {
    id: "kernel",
    slug: "kernel",
    route: "/kernel",
    label: "Enterprise Kernel",
    description: "Platform bootstrap, lifecycle, diagnostics and recovery — no business logic.",
    statusLabel: "Kernel linked",
    readiness: "beta",
    readinessPct: 55,
    icon: "integrations",
    recentActions: ["Boot completed", "Health probe", "Diagnostics collected"],
    roadmap: ["License enforcement", "HA failover", "Remote diagnostics"],
    quickActions: [
      { id: "kernel", label: "Kernel", route: "/kernel" },
      { id: "orchestrator", label: "Orchestrator", route: "/orchestrator" },
      { id: "intelligence", label: "Intelligence", route: "/intelligence" },
    ],
    aliases: ["/enterprise-kernel", "/platform-kernel"],
    deepLink: "/kernel",
  },
  {
    id: "automation",
    slug: "automation",
    route: "/automation",
    label: "Automation",
    description: "Workflows, triggers, and unattended enterprise processes.",
    statusLabel: "Automation Engine linked",
    readiness: "beta",
    readinessPct: 82,
    icon: "automation",
    recentActions: ["Automation Center opened", "Queue probe", "Policy validation"],
    roadmap: ["Durable queue store", "Webhook signatures", "Distributed workers"],
    quickActions: [
      { id: "center", label: "Automation Center", route: "/automation" },
      { id: "auto", label: "Automation Builder", route: "/platform-builder/automation" },
      { id: "wf", label: "Workflow Center", route: "/platform-builder/workflow-center" },
      { id: "runtime", label: "Workflow Runtime", route: "/workflow-runtime" },
    ],
    aliases: ["/platform-builder/automation", "/automation-center", "/automation-hub"],
    deepLink: "/automation",
  },
  {
    id: "integrations",
    slug: "integrations",
    route: "/integrations",
    label: "Integrations",
    description: "Providers, connectors, MCP, and external system bridges.",
    statusLabel: "Integration Hub linked",
    readiness: "beta",
    readinessPct: 69,
    icon: "integrations",
    recentActions: ["Integrations hub opened", "Provider list (local)", "MCP status probe"],
    roadmap: ["OAuth vault", "Webhook console", "Health SLAs"],
    quickActions: [
      { id: "int", label: "Integrations", route: "/platform-builder/integrations" },
      { id: "runtime", label: "AI Runtime", route: "/platform-builder/runtime" },
      { id: "mission", label: "Mission Control", route: "/platform-builder/mission-control" },
    ],
    aliases: ["/platform-builder/integrations"],
    deepLink: "/platform-builder/integrations",
  },
  {
    id: "security",
    slug: "security",
    route: "/security",
    label: "Security",
    description: "Identity, sessions, MFA, roles, and governance controls.",
    statusLabel: "Security Center linked",
    readiness: "ga",
    readinessPct: 92,
    icon: "security",
    recentActions: ["Security hub opened", "Session list", "Role resolve"],
    roadmap: ["SSO connectors", "Device trust", "Audit vault UI"],
    quickActions: [
      { id: "sec", label: "Security Center", route: "/identity/security" },
      { id: "users", label: "Users", route: "/identity/users" },
      { id: "gov", label: "Governance", route: "/platform-builder/governance" },
    ],
    aliases: ["/identity/security"],
    deepLink: "/identity/security",
  },
  {
    id: "city",
    slug: "city",
    route: "/enterprise-city",
    label: "Enterprise City",
    description: "Visual enterprise map — primary navigation space over Desktop OS.",
    statusLabel: "City Core live · Desktop integrated",
    readiness: "ga",
    readinessPct: 78,
    icon: "city",
    recentActions: ["City Core opened", "District jump", "Building entered"],
    roadmap: ["3D horizon", "Multi-space desktops", "Deep occupancy"],
    quickActions: [
      { id: "city", label: "Open Enterprise City", route: "/enterprise-city" },
      { id: "desktop", label: "Desktop OS", route: "/desktop" },
      { id: "dash", label: "Dashboard", route: "/dashboard" },
      { id: "twin", label: "Digital Twin", route: "/platform-builder/digital-twin" },
    ],
    aliases: ["/city"],
    deepLink: "/enterprise-city",
  },
  {
    id: "settings",
    slug: "settings",
    route: "/settings",
    label: "Settings",
    description: "Theme, locale, tenant preferences, and platform configuration.",
    statusLabel: "Settings page active",
    readiness: "ga",
    readinessPct: 94,
    icon: "settings",
    recentActions: ["Settings opened", "Theme cycled", "Locale updated"],
    roadmap: ["Org policies", "Notification prefs", "API keys UI"],
    quickActions: [
      { id: "settings", label: "Open Settings", route: "/settings" },
      { id: "profile", label: "Profile", route: "/identity/profile" },
      { id: "theme", label: "Identity Center", route: "/identity" },
    ],
  },
];

const bySlug = new Map(ENTERPRISE_MODULES.map((m) => [m.slug, m]));
const byRoute = new Map(ENTERPRISE_MODULES.map((m) => [m.route, m]));
const byId = new Map(ENTERPRISE_MODULES.map((m) => [m.id, m]));

export function getModuleBySlug(slug: string): EnterpriseModuleDef | undefined {
  return bySlug.get(slug) || byId.get(slug);
}

export function getModuleByRoute(pathname: string): EnterpriseModuleDef | undefined {
  const exact = byRoute.get(pathname);
  if (exact) return exact;
  return ENTERPRISE_MODULES.find(
    (m) => pathname === m.route || pathname.startsWith(`${m.route}/`) || m.aliases?.includes(pathname),
  );
}

/** Sidebar-facing nav derived from catalog (Enterprise City stays Coming Soon). */
export function shellNavFromCatalog() {
  return ENTERPRISE_MODULES.filter((m) => m.id !== "dashboard" || true).map((m) => ({
    id: m.id,
    label: m.label,
    route: m.route,
    icon: m.icon,
    badge: m.readiness === "coming_soon" ? "Soon" : undefined,
    comingSoon: m.readiness === "coming_soon",
  }));
}
