"""Register Enterprise Hub routes (Sprint 19.0)."""

from __future__ import annotations

from aiohttp import web

from applications.enterprise_hub.api import aa_handlers, handlers, kg_handlers, orch_handlers
from applications.enterprise_hub.api.middleware import auth_middleware
from applications.enterprise_hub.communications import api as comm_api
from applications.enterprise_hub.config import DEFAULT_CONFIG
from applications.enterprise_hub.integrations import api as eip_api
from applications.enterprise_hub.workflow import api as wf_api


def register_enterprise_hub_routes(app: web.Application) -> None:
    prefix = DEFAULT_CONFIG.api_prefix
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    app.router.add_get(f"{prefix}/health", handlers.health_handler)
    app.router.add_post(f"{prefix}/bootstrap", handlers.bootstrap_handler)
    app.router.add_get(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_post(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_get(f"{prefix}/integration", handlers.integration_handler)
    app.router.add_post(f"{prefix}/integration", handlers.integration_handler)
    app.router.add_get(f"{prefix}/identity", handlers.identity_handler)
    app.router.add_post(f"{prefix}/identity", handlers.identity_handler)
    app.router.add_get(f"{prefix}/configuration", handlers.configuration_handler)
    app.router.add_post(f"{prefix}/configuration", handlers.configuration_handler)
    app.router.add_get(f"{prefix}/events", handlers.events_handler)
    app.router.add_post(f"{prefix}/events", handlers.events_handler)
    app.router.add_get(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_post(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_get(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_post(f"{prefix}/knowledge", handlers.knowledge_handler)

    # Sprint 19.1 — AI Orchestrator (additive; prior routes unchanged)
    orch = DEFAULT_CONFIG.orchestrator_api_prefix
    app.router.add_get(f"{orch}/health", orch_handlers.orch_health_handler)
    app.router.add_post(f"{orch}/bootstrap", orch_handlers.orch_bootstrap_handler)
    app.router.add_get(f"{orch}/core", orch_handlers.orch_core_handler)
    app.router.add_post(f"{orch}/core", orch_handlers.orch_core_handler)
    app.router.add_get(f"{orch}/intent", orch_handlers.orch_intent_handler)
    app.router.add_post(f"{orch}/intent", orch_handlers.orch_intent_handler)
    app.router.add_get(f"{orch}/workflow", orch_handlers.orch_workflow_handler)
    app.router.add_post(f"{orch}/workflow", orch_handlers.orch_workflow_handler)
    app.router.add_get(f"{orch}/routing", orch_handlers.orch_routing_handler)
    app.router.add_post(f"{orch}/routing", orch_handlers.orch_routing_handler)
    app.router.add_get(f"{orch}/decisions", orch_handlers.orch_decisions_handler)
    app.router.add_post(f"{orch}/decisions", orch_handlers.orch_decisions_handler)
    app.router.add_get(f"{orch}/monitoring", orch_handlers.orch_monitoring_handler)
    app.router.add_post(f"{orch}/monitoring", orch_handlers.orch_monitoring_handler)
    app.router.add_get(f"{orch}/explain", orch_handlers.orch_explain_handler)
    app.router.add_post(f"{orch}/explain", orch_handlers.orch_explain_handler)
    app.router.add_get(f"{orch}/dashboard", orch_handlers.orch_dashboard_handler)
    app.router.add_post(f"{orch}/dashboard", orch_handlers.orch_dashboard_handler)
    app.router.add_get(f"{orch}/knowledge", orch_handlers.orch_knowledge_handler)
    app.router.add_post(f"{orch}/knowledge", orch_handlers.orch_knowledge_handler)

    # Sprint 19.2 — Unified Knowledge Graph (additive; prior routes unchanged)
    kg = DEFAULT_CONFIG.knowledge_graph_api_prefix
    app.router.add_get(f"{kg}/health", kg_handlers.kg_health_handler)
    app.router.add_post(f"{kg}/bootstrap", kg_handlers.kg_bootstrap_handler)
    app.router.add_get(f"{kg}/graph", kg_handlers.kg_graph_handler)
    app.router.add_post(f"{kg}/graph", kg_handlers.kg_graph_handler)
    app.router.add_get(f"{kg}/memory", kg_handlers.kg_memory_handler)
    app.router.add_post(f"{kg}/memory", kg_handlers.kg_memory_handler)
    app.router.add_get(f"{kg}/semantic", kg_handlers.kg_semantic_handler)
    app.router.add_post(f"{kg}/semantic", kg_handlers.kg_semantic_handler)
    app.router.add_get(f"{kg}/context", kg_handlers.kg_context_handler)
    app.router.add_post(f"{kg}/context", kg_handlers.kg_context_handler)
    app.router.add_get(f"{kg}/ai", kg_handlers.kg_ai_handler)
    app.router.add_post(f"{kg}/ai", kg_handlers.kg_ai_handler)
    app.router.add_get(f"{kg}/sync", kg_handlers.kg_sync_handler)
    app.router.add_post(f"{kg}/sync", kg_handlers.kg_sync_handler)
    app.router.add_get(f"{kg}/dashboard", kg_handlers.kg_dashboard_handler)
    app.router.add_post(f"{kg}/dashboard", kg_handlers.kg_dashboard_handler)
    app.router.add_get(f"{kg}/meta", kg_handlers.kg_meta_handler)
    app.router.add_post(f"{kg}/meta", kg_handlers.kg_meta_handler)

    # Sprint 19.3 — Enterprise AI Agents (additive; prior routes unchanged)
    aa = DEFAULT_CONFIG.ai_agents_api_prefix
    app.router.add_get(f"{aa}/health", aa_handlers.aa_health_handler)
    app.router.add_post(f"{aa}/bootstrap", aa_handlers.aa_bootstrap_handler)
    app.router.add_get(f"{aa}/registry", aa_handlers.aa_registry_handler)
    app.router.add_post(f"{aa}/registry", aa_handlers.aa_registry_handler)
    app.router.add_get(f"{aa}/execution", aa_handlers.aa_execution_handler)
    app.router.add_post(f"{aa}/execution", aa_handlers.aa_execution_handler)
    app.router.add_get(f"{aa}/collaboration", aa_handlers.aa_collaboration_handler)
    app.router.add_post(f"{aa}/collaboration", aa_handlers.aa_collaboration_handler)
    app.router.add_get(f"{aa}/automation", aa_handlers.aa_automation_handler)
    app.router.add_post(f"{aa}/automation", aa_handlers.aa_automation_handler)
    app.router.add_get(f"{aa}/intelligence", aa_handlers.aa_intelligence_handler)
    app.router.add_post(f"{aa}/intelligence", aa_handlers.aa_intelligence_handler)
    app.router.add_get(f"{aa}/governance", aa_handlers.aa_governance_handler)
    app.router.add_post(f"{aa}/governance", aa_handlers.aa_governance_handler)
    app.router.add_get(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)
    app.router.add_post(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)
    app.router.add_get(f"{aa}/meta", aa_handlers.aa_meta_handler)
    app.router.add_post(f"{aa}/meta", aa_handlers.aa_meta_handler)

    # Sprint 19.4 — Enterprise Communications (additive; prior routes unchanged)
    cm = DEFAULT_CONFIG.communications_api_prefix
    app.router.add_get(f"{cm}/health", comm_api.comm_health_handler)
    app.router.add_post(f"{cm}/bootstrap", comm_api.comm_bootstrap_handler)
    app.router.add_get(f"{cm}/center", comm_api.comm_center_handler)
    app.router.add_post(f"{cm}/center", comm_api.comm_center_handler)
    app.router.add_get(f"{cm}/router", comm_api.comm_router_handler)
    app.router.add_post(f"{cm}/router", comm_api.comm_router_handler)
    app.router.add_get(f"{cm}/queue", comm_api.comm_queue_handler)
    app.router.add_post(f"{cm}/queue", comm_api.comm_queue_handler)
    app.router.add_get(f"{cm}/delivery", comm_api.comm_delivery_handler)
    app.router.add_post(f"{cm}/delivery", comm_api.comm_delivery_handler)
    app.router.add_get(f"{cm}/priority", comm_api.comm_priority_handler)
    app.router.add_post(f"{cm}/priority", comm_api.comm_priority_handler)
    app.router.add_get(f"{cm}/templates", comm_api.comm_templates_handler)
    app.router.add_post(f"{cm}/templates", comm_api.comm_templates_handler)
    app.router.add_get(f"{cm}/chat", comm_api.comm_chat_handler)
    app.router.add_post(f"{cm}/chat", comm_api.comm_chat_handler)
    app.router.add_get(f"{cm}/audit", comm_api.comm_audit_handler)
    app.router.add_post(f"{cm}/audit", comm_api.comm_audit_handler)
    app.router.add_get(f"{cm}/dashboard", comm_api.comm_dashboard_handler)
    app.router.add_post(f"{cm}/dashboard", comm_api.comm_dashboard_handler)

    # Sprint 19.5 — Enterprise Workflow Engine (additive; prior routes unchanged)
    wf = DEFAULT_CONFIG.workflow_api_prefix
    app.router.add_get(f"{wf}/health", wf_api.wf_health_handler)
    app.router.add_post(f"{wf}/bootstrap", wf_api.wf_bootstrap_handler)
    app.router.add_get(f"{wf}/manager", wf_api.wf_manager_handler)
    app.router.add_post(f"{wf}/manager", wf_api.wf_manager_handler)
    app.router.add_get(f"{wf}/engine", wf_api.wf_engine_handler)
    app.router.add_post(f"{wf}/engine", wf_api.wf_engine_handler)
    app.router.add_get(f"{wf}/scheduler", wf_api.wf_scheduler_handler)
    app.router.add_post(f"{wf}/scheduler", wf_api.wf_scheduler_handler)
    app.router.add_get(f"{wf}/templates", wf_api.wf_templates_handler)
    app.router.add_post(f"{wf}/templates", wf_api.wf_templates_handler)
    app.router.add_get(f"{wf}/history", wf_api.wf_history_handler)
    app.router.add_post(f"{wf}/history", wf_api.wf_history_handler)
    app.router.add_get(f"{wf}/events", wf_api.wf_events_handler)
    app.router.add_post(f"{wf}/events", wf_api.wf_events_handler)
    app.router.add_get(f"{wf}/optimization", wf_api.wf_optimization_handler)
    app.router.add_post(f"{wf}/optimization", wf_api.wf_optimization_handler)
    app.router.add_get(f"{wf}/validator", wf_api.wf_validator_handler)
    app.router.add_post(f"{wf}/validator", wf_api.wf_validator_handler)
    app.router.add_get(f"{wf}/dashboard", wf_api.wf_dashboard_handler)
    app.router.add_post(f"{wf}/dashboard", wf_api.wf_dashboard_handler)

    # Sprint 19.6 — Enterprise Integration Platform (additive; prior routes unchanged)
    eip = DEFAULT_CONFIG.eip_api_prefix
    app.router.add_get(f"{eip}/health", eip_api.eip_health_handler)
    app.router.add_post(f"{eip}/bootstrap", eip_api.eip_bootstrap_handler)
    app.router.add_get(f"{eip}/manager", eip_api.eip_manager_handler)
    app.router.add_post(f"{eip}/manager", eip_api.eip_manager_handler)
    app.router.add_get(f"{eip}/engine", eip_api.eip_engine_handler)
    app.router.add_post(f"{eip}/engine", eip_api.eip_engine_handler)
    app.router.add_get(f"{eip}/mapping", eip_api.eip_mapping_handler)
    app.router.add_post(f"{eip}/mapping", eip_api.eip_mapping_handler)
    app.router.add_get(f"{eip}/security", eip_api.eip_security_handler)
    app.router.add_post(f"{eip}/security", eip_api.eip_security_handler)
    app.router.add_get(f"{eip}/monitor", eip_api.eip_monitor_handler)
    app.router.add_post(f"{eip}/monitor", eip_api.eip_monitor_handler)
    app.router.add_get(f"{eip}/scheduler", eip_api.eip_scheduler_handler)
    app.router.add_post(f"{eip}/scheduler", eip_api.eip_scheduler_handler)
    app.router.add_get(f"{eip}/ai", eip_api.eip_ai_handler)
    app.router.add_post(f"{eip}/ai", eip_api.eip_ai_handler)
    app.router.add_get(f"{eip}/dashboard", eip_api.eip_dashboard_handler)
    app.router.add_post(f"{eip}/dashboard", eip_api.eip_dashboard_handler)
