"""Register Enterprise Hub routes (Sprint 19.0)."""

from __future__ import annotations

from aiohttp import web

from applications.enterprise_hub.api import aa_handlers, handlers, kg_handlers, orch_handlers
from applications.enterprise_hub.api.middleware import auth_middleware
from applications.enterprise_hub.communications import api as comm_api
from applications.enterprise_hub.config import DEFAULT_CONFIG
from applications.enterprise_hub.data_platform import api as edp_api
from applications.enterprise_hub.integrations import api as eip_api
from applications.enterprise_hub.ai_orchestrator import api as aop_api
from applications.enterprise_hub.ai_os import api as aios_api
from applications.enterprise_hub.ai_tools import api as ats_api
from applications.enterprise_hub.event_platform import api as evp_api
from applications.enterprise_hub.developer_platform import api as sdp_api
from applications.enterprise_hub.data_fabric import api as edf_api
from applications.enterprise_hub.digital_twin import api as edt_api
from applications.enterprise_hub.simulation_engine import api as esi_api
from applications.enterprise_hub.process_mining import api as epm_api
from applications.enterprise_hub.business_capabilities import api as ebc_api
from applications.enterprise_hub.command_center import api as ecc_api
from applications.enterprise_hub.api_standardization import api as eas_api
from applications.enterprise_hub.data_contracts import api as edc_api
from applications.enterprise_hub.security_hardening import api as esh_api
from applications.enterprise_hub.quality_assurance import api as eqa_api
from applications.enterprise_hub.documentation_platform import api as edo_api
from applications.enterprise_hub.performance_platform import api as epf_api
from applications.enterprise_hub.release_platform import api as erl_api
from applications.enterprise_hub.knowledge_platform import api as ekp_api
from applications.enterprise_hub.observability import api as obs_api
from applications.enterprise_hub.security import api as isam_api
from applications.enterprise_hub.tenancy import api as tenancy_api
from applications.enterprise_hub.workflow import api as wf_api


def register_enterprise_hub_routes(app: web.Application) -> None:
    prefix = DEFAULT_CONFIG.api_prefix
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    app.router.add_get(f"{prefix}/health", handlers.health_handler)
    app.router.add_post(f"{prefix}/bootstrap", handlers.bootstrap_handler)
    app.router.add_get(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_post(f"{prefix}/registry", handlers.registry_handler)
    app.router.add_get(f"{prefix}/integration", handlers.integration_handler)
    app.router.add_post(f"{prefix}/integration", handlers.integration_handler)
    app.router.add_get(f"{prefix}/identity", handlers.identity_handler)
    app.router.add_post(f"{prefix}/identity", handlers.identity_handler)
    app.router.add_get(f"{prefix}/configuration", handlers.configuration_handler)
    app.router.add_post(f"{prefix}/configuration", handlers.configuration_handler)
    app.router.add_get(f"{prefix}/events", handlers.events_handler)
    app.router.add_post(f"{prefix}/events", handlers.events_handler)
    app.router.add_get(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_post(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_get(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_post(f"{prefix}/knowledge", handlers.knowledge_handler)

    # Sprint 19.1 — AI Orchestrator (additive; prior routes unchanged)
    orch = DEFAULT_CONFIG.orchestrator_api_prefix
    app.router.add_get(f"{orch}/health", orch_handlers.orch_health_handler)
    app.router.add_post(f"{orch}/bootstrap", orch_handlers.orch_bootstrap_handler)
    app.router.add_get(f"{orch}/core", orch_handlers.orch_core_handler)
    app.router.add_post(f"{orch}/core", orch_handlers.orch_core_handler)
    app.router.add_get(f"{orch}/intent", orch_handlers.orch_intent_handler)
    app.router.add_post(f"{orch}/intent", orch_handlers.orch_intent_handler)
    app.router.add_get(f"{orch}/workflow", orch_handlers.orch_workflow_handler)
    app.router.add_post(f"{orch}/workflow", orch_handlers.orch_workflow_handler)
    app.router.add_get(f"{orch}/routing", orch_handlers.orch_routing_handler)
    app.router.add_post(f"{orch}/routing", orch_handlers.orch_routing_handler)
    app.router.add_get(f"{orch}/decisions", orch_handlers.orch_decisions_handler)
    app.router.add_post(f"{orch}/decisions", orch_handlers.orch_decisions_handler)
    app.router.add_get(f"{orch}/monitoring", orch_handlers.orch_monitoring_handler)
    app.router.add_post(f"{orch}/monitoring", orch_handlers.orch_monitoring_handler)
    app.router.add_get(f"{orch}/explain", orch_handlers.orch_explain_handler)
    app.router.add_post(f"{orch}/explain", orch_handlers.orch_explain_handler)
    app.router.add_get(f"{orch}/dashboard", orch_handlers.orch_dashboard_handler)
    app.router.add_post(f"{orch}/dashboard", orch_handlers.orch_dashboard_handler)
    app.router.add_get(f"{orch}/knowledge", orch_handlers.orch_knowledge_handler)
    app.router.add_post(f"{orch}/knowledge", orch_handlers.orch_knowledge_handler)

    # Sprint 19.2 — Unified Knowledge Graph (additive; prior routes unchanged)
    kg = DEFAULT_CONFIG.knowledge_graph_api_prefix
    app.router.add_get(f"{kg}/health", kg_handlers.kg_health_handler)
    app.router.add_post(f"{kg}/bootstrap", kg_handlers.kg_bootstrap_handler)
    app.router.add_get(f"{kg}/graph", kg_handlers.kg_graph_handler)
    app.router.add_post(f"{kg}/graph", kg_handlers.kg_graph_handler)
    app.router.add_get(f"{kg}/memory", kg_handlers.kg_memory_handler)
    app.router.add_post(f"{kg}/memory", kg_handlers.kg_memory_handler)
    app.router.add_get(f"{kg}/semantic", kg_handlers.kg_semantic_handler)
    app.router.add_post(f"{kg}/semantic", kg_handlers.kg_semantic_handler)
    app.router.add_get(f"{kg}/context", kg_handlers.kg_context_handler)
    app.router.add_post(f"{kg}/context", kg_handlers.kg_context_handler)
    app.router.add_get(f"{kg}/ai", kg_handlers.kg_ai_handler)
    app.router.add_post(f"{kg}/ai", kg_handlers.kg_ai_handler)
    app.router.add_get(f"{kg}/sync", kg_handlers.kg_sync_handler)
    app.router.add_post(f"{kg}/sync", kg_handlers.kg_sync_handler)
    app.router.add_get(f"{kg}/dashboard", kg_handlers.kg_dashboard_handler)
    app.router.add_post(f"{kg}/dashboard", kg_handlers.kg_dashboard_handler)
    app.router.add_get(f"{kg}/meta", kg_handlers.kg_meta_handler)
    app.router.add_post(f"{kg}/meta", kg_handlers.kg_meta_handler)

    # Sprint 19.3 — Enterprise AI Agents (additive; prior routes unchanged)
    aa = DEFAULT_CONFIG.ai_agents_api_prefix
    app.router.add_get(f"{aa}/health", aa_handlers.aa_health_handler)
    app.router.add_post(f"{aa}/bootstrap", aa_handlers.aa_bootstrap_handler)
    app.router.add_get(f"{aa}/registry", aa_handlers.aa_registry_handler)
    app.router.add_post(f"{aa}/registry", aa_handlers.aa_registry_handler)
    app.router.add_get(f"{aa}/execution", aa_handlers.aa_execution_handler)
    app.router.add_post(f"{aa}/execution", aa_handlers.aa_execution_handler)
    app.router.add_get(f"{aa}/collaboration", aa_handlers.aa_collaboration_handler)
    app.router.add_post(f"{aa}/collaboration", aa_handlers.aa_collaboration_handler)
    app.router.add_get(f"{aa}/automation", aa_handlers.aa_automation_handler)
    app.router.add_post(f"{aa}/automation", aa_handlers.aa_automation_handler)
    app.router.add_get(f"{aa}/intelligence", aa_handlers.aa_intelligence_handler)
    app.router.add_post(f"{aa}/intelligence", aa_handlers.aa_intelligence_handler)
    app.router.add_get(f"{aa}/governance", aa_handlers.aa_governance_handler)
    app.router.add_post(f"{aa}/governance", aa_handlers.aa_governance_handler)
    app.router.add_get(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)
    app.router.add_post(f"{aa}/dashboard", aa_handlers.aa_dashboard_handler)
    app.router.add_get(f"{aa}/meta", aa_handlers.aa_meta_handler)
    app.router.add_post(f"{aa}/meta", aa_handlers.aa_meta_handler)

    # Sprint 19.4 — Enterprise Communications (additive; prior routes unchanged)
    cm = DEFAULT_CONFIG.communications_api_prefix
    app.router.add_get(f"{cm}/health", comm_api.comm_health_handler)
    app.router.add_post(f"{cm}/bootstrap", comm_api.comm_bootstrap_handler)
    app.router.add_get(f"{cm}/center", comm_api.comm_center_handler)
    app.router.add_post(f"{cm}/center", comm_api.comm_center_handler)
    app.router.add_get(f"{cm}/router", comm_api.comm_router_handler)
    app.router.add_post(f"{cm}/router", comm_api.comm_router_handler)
    app.router.add_get(f"{cm}/queue", comm_api.comm_queue_handler)
    app.router.add_post(f"{cm}/queue", comm_api.comm_queue_handler)
    app.router.add_get(f"{cm}/delivery", comm_api.comm_delivery_handler)
    app.router.add_post(f"{cm}/delivery", comm_api.comm_delivery_handler)
    app.router.add_get(f"{cm}/priority", comm_api.comm_priority_handler)
    app.router.add_post(f"{cm}/priority", comm_api.comm_priority_handler)
    app.router.add_get(f"{cm}/templates", comm_api.comm_templates_handler)
    app.router.add_post(f"{cm}/templates", comm_api.comm_templates_handler)
    app.router.add_get(f"{cm}/chat", comm_api.comm_chat_handler)
    app.router.add_post(f"{cm}/chat", comm_api.comm_chat_handler)
    app.router.add_get(f"{cm}/audit", comm_api.comm_audit_handler)
    app.router.add_post(f"{cm}/audit", comm_api.comm_audit_handler)
    app.router.add_get(f"{cm}/dashboard", comm_api.comm_dashboard_handler)
    app.router.add_post(f"{cm}/dashboard", comm_api.comm_dashboard_handler)

    # Sprint 19.5 — Enterprise Workflow Engine (additive; prior routes unchanged)
    wf = DEFAULT_CONFIG.workflow_api_prefix
    app.router.add_get(f"{wf}/health", wf_api.wf_health_handler)
    app.router.add_post(f"{wf}/bootstrap", wf_api.wf_bootstrap_handler)
    app.router.add_get(f"{wf}/manager", wf_api.wf_manager_handler)
    app.router.add_post(f"{wf}/manager", wf_api.wf_manager_handler)
    app.router.add_get(f"{wf}/engine", wf_api.wf_engine_handler)
    app.router.add_post(f"{wf}/engine", wf_api.wf_engine_handler)
    app.router.add_get(f"{wf}/scheduler", wf_api.wf_scheduler_handler)
    app.router.add_post(f"{wf}/scheduler", wf_api.wf_scheduler_handler)
    app.router.add_get(f"{wf}/templates", wf_api.wf_templates_handler)
    app.router.add_post(f"{wf}/templates", wf_api.wf_templates_handler)
    app.router.add_get(f"{wf}/history", wf_api.wf_history_handler)
    app.router.add_post(f"{wf}/history", wf_api.wf_history_handler)
    app.router.add_get(f"{wf}/events", wf_api.wf_events_handler)
    app.router.add_post(f"{wf}/events", wf_api.wf_events_handler)
    app.router.add_get(f"{wf}/optimization", wf_api.wf_optimization_handler)
    app.router.add_post(f"{wf}/optimization", wf_api.wf_optimization_handler)
    app.router.add_get(f"{wf}/validator", wf_api.wf_validator_handler)
    app.router.add_post(f"{wf}/validator", wf_api.wf_validator_handler)
    app.router.add_get(f"{wf}/dashboard", wf_api.wf_dashboard_handler)
    app.router.add_post(f"{wf}/dashboard", wf_api.wf_dashboard_handler)

    # Sprint 19.6 — Enterprise Integration Platform (additive; prior routes unchanged)
    eip = DEFAULT_CONFIG.eip_api_prefix
    app.router.add_get(f"{eip}/health", eip_api.eip_health_handler)
    app.router.add_post(f"{eip}/bootstrap", eip_api.eip_bootstrap_handler)
    app.router.add_get(f"{eip}/manager", eip_api.eip_manager_handler)
    app.router.add_post(f"{eip}/manager", eip_api.eip_manager_handler)
    app.router.add_get(f"{eip}/engine", eip_api.eip_engine_handler)
    app.router.add_post(f"{eip}/engine", eip_api.eip_engine_handler)
    app.router.add_get(f"{eip}/mapping", eip_api.eip_mapping_handler)
    app.router.add_post(f"{eip}/mapping", eip_api.eip_mapping_handler)
    app.router.add_get(f"{eip}/security", eip_api.eip_security_handler)
    app.router.add_post(f"{eip}/security", eip_api.eip_security_handler)
    app.router.add_get(f"{eip}/monitor", eip_api.eip_monitor_handler)
    app.router.add_post(f"{eip}/monitor", eip_api.eip_monitor_handler)
    app.router.add_get(f"{eip}/scheduler", eip_api.eip_scheduler_handler)
    app.router.add_post(f"{eip}/scheduler", eip_api.eip_scheduler_handler)
    app.router.add_get(f"{eip}/ai", eip_api.eip_ai_handler)
    app.router.add_post(f"{eip}/ai", eip_api.eip_ai_handler)
    app.router.add_get(f"{eip}/dashboard", eip_api.eip_dashboard_handler)
    app.router.add_post(f"{eip}/dashboard", eip_api.eip_dashboard_handler)

    # Sprint 19.7 — Enterprise Data Platform & MDM (additive; prior routes unchanged)
    edp = DEFAULT_CONFIG.edp_api_prefix
    app.router.add_get(f"{edp}/health", edp_api.edp_health_handler)
    app.router.add_post(f"{edp}/bootstrap", edp_api.edp_bootstrap_handler)
    app.router.add_get(f"{edp}/master", edp_api.edp_master_handler)
    app.router.add_post(f"{edp}/master", edp_api.edp_master_handler)
    app.router.add_get(f"{edp}/catalog", edp_api.edp_catalog_handler)
    app.router.add_post(f"{edp}/catalog", edp_api.edp_catalog_handler)
    app.router.add_get(f"{edp}/metadata", edp_api.edp_metadata_handler)
    app.router.add_post(f"{edp}/metadata", edp_api.edp_metadata_handler)
    app.router.add_get(f"{edp}/quality", edp_api.edp_quality_handler)
    app.router.add_post(f"{edp}/quality", edp_api.edp_quality_handler)
    app.router.add_get(f"{edp}/governance", edp_api.edp_governance_handler)
    app.router.add_post(f"{edp}/governance", edp_api.edp_governance_handler)
    app.router.add_get(f"{edp}/lineage", edp_api.edp_lineage_handler)
    app.router.add_post(f"{edp}/lineage", edp_api.edp_lineage_handler)
    app.router.add_get(f"{edp}/versioning", edp_api.edp_versioning_handler)
    app.router.add_post(f"{edp}/versioning", edp_api.edp_versioning_handler)
    app.router.add_get(f"{edp}/ai", edp_api.edp_ai_handler)
    app.router.add_post(f"{edp}/ai", edp_api.edp_ai_handler)
    app.router.add_get(f"{edp}/analytics", edp_api.edp_analytics_handler)
    app.router.add_post(f"{edp}/analytics", edp_api.edp_analytics_handler)
    app.router.add_get(f"{edp}/dashboard", edp_api.edp_dashboard_handler)
    app.router.add_post(f"{edp}/dashboard", edp_api.edp_dashboard_handler)

    # Sprint 19.8 — Enterprise ISAM (additive; prior routes unchanged)
    isam = DEFAULT_CONFIG.isam_api_prefix
    app.router.add_get(f"{isam}/health", isam_api.isam_health_handler)
    app.router.add_post(f"{isam}/bootstrap", isam_api.isam_bootstrap_handler)
    app.router.add_get(f"{isam}/identity", isam_api.isam_identity_handler)
    app.router.add_post(f"{isam}/identity", isam_api.isam_identity_handler)
    app.router.add_get(f"{isam}/auth", isam_api.isam_auth_handler)
    app.router.add_post(f"{isam}/auth", isam_api.isam_auth_handler)
    app.router.add_get(f"{isam}/roles", isam_api.isam_roles_handler)
    app.router.add_post(f"{isam}/roles", isam_api.isam_roles_handler)
    app.router.add_get(f"{isam}/sessions", isam_api.isam_session_handler)
    app.router.add_post(f"{isam}/sessions", isam_api.isam_session_handler)
    app.router.add_get(f"{isam}/tokens", isam_api.isam_token_handler)
    app.router.add_post(f"{isam}/tokens", isam_api.isam_token_handler)
    app.router.add_get(f"{isam}/mfa", isam_api.isam_mfa_handler)
    app.router.add_post(f"{isam}/mfa", isam_api.isam_mfa_handler)
    app.router.add_get(f"{isam}/policies", isam_api.isam_policy_handler)
    app.router.add_post(f"{isam}/policies", isam_api.isam_policy_handler)
    app.router.add_get(f"{isam}/monitor", isam_api.isam_monitor_handler)
    app.router.add_post(f"{isam}/monitor", isam_api.isam_monitor_handler)
    app.router.add_get(f"{isam}/audit", isam_api.isam_audit_handler)
    app.router.add_post(f"{isam}/audit", isam_api.isam_audit_handler)
    app.router.add_get(f"{isam}/dashboard", isam_api.isam_dashboard_handler)
    app.router.add_post(f"{isam}/dashboard", isam_api.isam_dashboard_handler)

    # Sprint 19.9 — Enterprise Observability (additive; prior routes unchanged)
    obs = DEFAULT_CONFIG.observability_api_prefix
    app.router.add_get(f"{obs}/health", obs_api.obs_health_handler)
    app.router.add_post(f"{obs}/bootstrap", obs_api.obs_bootstrap_handler)
    app.router.add_get(f"{obs}/metrics", obs_api.obs_metrics_handler)
    app.router.add_post(f"{obs}/metrics", obs_api.obs_metrics_handler)
    app.router.add_get(f"{obs}/healthcheck", obs_api.obs_healthcheck_handler)
    app.router.add_post(f"{obs}/healthcheck", obs_api.obs_healthcheck_handler)
    app.router.add_get(f"{obs}/services", obs_api.obs_services_handler)
    app.router.add_post(f"{obs}/services", obs_api.obs_services_handler)
    app.router.add_get(f"{obs}/logs", obs_api.obs_logs_handler)
    app.router.add_post(f"{obs}/logs", obs_api.obs_logs_handler)
    app.router.add_get(f"{obs}/tracing", obs_api.obs_tracing_handler)
    app.router.add_post(f"{obs}/tracing", obs_api.obs_tracing_handler)
    app.router.add_get(f"{obs}/alerts", obs_api.obs_alerts_handler)
    app.router.add_post(f"{obs}/alerts", obs_api.obs_alerts_handler)
    app.router.add_get(f"{obs}/incidents", obs_api.obs_incidents_handler)
    app.router.add_post(f"{obs}/incidents", obs_api.obs_incidents_handler)
    app.router.add_get(f"{obs}/diagnostics", obs_api.obs_diagnostics_handler)
    app.router.add_post(f"{obs}/diagnostics", obs_api.obs_diagnostics_handler)
    app.router.add_get(f"{obs}/monitoring", obs_api.obs_monitoring_handler)
    app.router.add_post(f"{obs}/monitoring", obs_api.obs_monitoring_handler)
    app.router.add_get(f"{obs}/dashboard", obs_api.obs_dashboard_handler)
    app.router.add_post(f"{obs}/dashboard", obs_api.obs_dashboard_handler)

    # Sprint 20.0 — Multi-Tenant Platform (additive; prior routes unchanged)
    tn = DEFAULT_CONFIG.tenancy_api_prefix
    app.router.add_get(f"{tn}/health", tenancy_api.tenancy_health_handler)
    app.router.add_post(f"{tn}/bootstrap", tenancy_api.tenancy_bootstrap_handler)
    app.router.add_get(f"{tn}/tenants", tenancy_api.tenancy_tenants_handler)
    app.router.add_post(f"{tn}/tenants", tenancy_api.tenancy_tenants_handler)
    app.router.add_get(f"{tn}/organizations", tenancy_api.tenancy_organizations_handler)
    app.router.add_post(f"{tn}/organizations", tenancy_api.tenancy_organizations_handler)
    app.router.add_get(f"{tn}/workspaces", tenancy_api.tenancy_workspaces_handler)
    app.router.add_post(f"{tn}/workspaces", tenancy_api.tenancy_workspaces_handler)
    app.router.add_get(f"{tn}/isolation", tenancy_api.tenancy_isolation_handler)
    app.router.add_post(f"{tn}/isolation", tenancy_api.tenancy_isolation_handler)
    app.router.add_get(f"{tn}/routing", tenancy_api.tenancy_routing_handler)
    app.router.add_post(f"{tn}/routing", tenancy_api.tenancy_routing_handler)
    app.router.add_get(f"{tn}/provisioning", tenancy_api.tenancy_provisioning_handler)
    app.router.add_post(f"{tn}/provisioning", tenancy_api.tenancy_provisioning_handler)
    app.router.add_get(f"{tn}/branding", tenancy_api.tenancy_branding_handler)
    app.router.add_post(f"{tn}/branding", tenancy_api.tenancy_branding_handler)
    app.router.add_get(f"{tn}/licensing", tenancy_api.tenancy_licensing_handler)
    app.router.add_post(f"{tn}/licensing", tenancy_api.tenancy_licensing_handler)
    app.router.add_get(f"{tn}/billing", tenancy_api.tenancy_billing_handler)
    app.router.add_post(f"{tn}/billing", tenancy_api.tenancy_billing_handler)
    app.router.add_get(f"{tn}/onboarding", tenancy_api.tenancy_onboarding_handler)
    app.router.add_post(f"{tn}/onboarding", tenancy_api.tenancy_onboarding_handler)
    app.router.add_get(f"{tn}/migration", tenancy_api.tenancy_migration_handler)
    app.router.add_post(f"{tn}/migration", tenancy_api.tenancy_migration_handler)
    app.router.add_get(f"{tn}/analytics", tenancy_api.tenancy_analytics_handler)
    app.router.add_post(f"{tn}/analytics", tenancy_api.tenancy_analytics_handler)

    # Sprint 20.1 — AI Orchestration Platform (additive; prior routes unchanged)
    aop = DEFAULT_CONFIG.ai_orchestrator_api_prefix
    app.router.add_get(f"{aop}/health", aop_api.aop_health_handler)
    app.router.add_post(f"{aop}/bootstrap", aop_api.aop_bootstrap_handler)
    app.router.add_get(f"{aop}/agents", aop_api.aop_agents_handler)
    app.router.add_post(f"{aop}/agents", aop_api.aop_agents_handler)
    app.router.add_get(f"{aop}/tasks", aop_api.aop_tasks_handler)
    app.router.add_post(f"{aop}/tasks", aop_api.aop_tasks_handler)
    app.router.add_post(f"{aop}/orchestrate", aop_api.aop_orchestrate_handler)
    app.router.add_get(f"{aop}/plan", aop_api.aop_plan_handler)
    app.router.add_post(f"{aop}/plan", aop_api.aop_plan_handler)
    app.router.add_get(f"{aop}/dispatch", aop_api.aop_dispatch_handler)
    app.router.add_post(f"{aop}/dispatch", aop_api.aop_dispatch_handler)
    app.router.add_get(f"{aop}/execute", aop_api.aop_execute_handler)
    app.router.add_post(f"{aop}/execute", aop_api.aop_execute_handler)
    app.router.add_get(f"{aop}/context", aop_api.aop_context_handler)
    app.router.add_post(f"{aop}/context", aop_api.aop_context_handler)
    app.router.add_get(f"{aop}/memory", aop_api.aop_memory_handler)
    app.router.add_post(f"{aop}/memory", aop_api.aop_memory_handler)
    app.router.add_get(f"{aop}/aggregate", aop_api.aop_aggregate_handler)
    app.router.add_post(f"{aop}/aggregate", aop_api.aop_aggregate_handler)
    app.router.add_get(f"{aop}/policy", aop_api.aop_policy_handler)
    app.router.add_post(f"{aop}/policy", aop_api.aop_policy_handler)
    app.router.add_get(f"{aop}/analytics", aop_api.aop_analytics_handler)
    app.router.add_post(f"{aop}/analytics", aop_api.aop_analytics_handler)

    # Sprint 20.2 — AI Tools & Skills (additive; prior routes unchanged)
    ats = DEFAULT_CONFIG.ai_tools_api_prefix
    app.router.add_get(f"{ats}/health", ats_api.ats_health_handler)
    app.router.add_post(f"{ats}/bootstrap", ats_api.ats_bootstrap_handler)
    app.router.add_get(f"{ats}/tools", ats_api.ats_tools_handler)
    app.router.add_post(f"{ats}/tools", ats_api.ats_tools_handler)
    app.router.add_post(f"{ats}/execute", ats_api.ats_execute_handler)
    app.router.add_get(f"{ats}/skills", ats_api.ats_skills_handler)
    app.router.add_post(f"{ats}/skills", ats_api.ats_skills_handler)
    app.router.add_get(f"{ats}/policy", ats_api.ats_policy_handler)
    app.router.add_post(f"{ats}/policy", ats_api.ats_policy_handler)
    app.router.add_get(f"{ats}/marketplace", ats_api.ats_marketplace_handler)
    app.router.add_post(f"{ats}/marketplace", ats_api.ats_marketplace_handler)
    app.router.add_get(f"{ats}/audit", ats_api.ats_audit_handler)
    app.router.add_post(f"{ats}/audit", ats_api.ats_audit_handler)
    app.router.add_get(f"{ats}/analytics", ats_api.ats_analytics_handler)
    app.router.add_post(f"{ats}/analytics", ats_api.ats_analytics_handler)
    app.router.add_get(f"{ats}/sandbox", ats_api.ats_sandbox_handler)
    app.router.add_post(f"{ats}/sandbox", ats_api.ats_sandbox_handler)

    # Sprint 20.3 — Knowledge Platform (additive; prior routes unchanged)
    ekp = DEFAULT_CONFIG.knowledge_platform_api_prefix
    app.router.add_get(f"{ekp}/health", ekp_api.ekp_health_handler)
    app.router.add_post(f"{ekp}/bootstrap", ekp_api.ekp_bootstrap_handler)
    app.router.add_get(f"{ekp}/documents", ekp_api.ekp_documents_handler)
    app.router.add_post(f"{ekp}/documents", ekp_api.ekp_documents_handler)
    app.router.add_post(f"{ekp}/index", ekp_api.ekp_index_handler)
    app.router.add_post(f"{ekp}/rag", ekp_api.ekp_rag_handler)
    app.router.add_get(f"{ekp}/search", ekp_api.ekp_search_handler)
    app.router.add_post(f"{ekp}/search", ekp_api.ekp_search_handler)
    app.router.add_get(f"{ekp}/graph", ekp_api.ekp_graph_handler)
    app.router.add_post(f"{ekp}/graph", ekp_api.ekp_graph_handler)
    app.router.add_get(f"{ekp}/memory", ekp_api.ekp_memory_handler)
    app.router.add_post(f"{ekp}/memory", ekp_api.ekp_memory_handler)
    app.router.add_get(f"{ekp}/analytics", ekp_api.ekp_analytics_handler)
    app.router.add_post(f"{ekp}/analytics", ekp_api.ekp_analytics_handler)
    app.router.add_get(f"{ekp}/governance", ekp_api.ekp_governance_handler)
    app.router.add_post(f"{ekp}/governance", ekp_api.ekp_governance_handler)

    # Sprint 20.4 — Autonomous AIOS (additive; prior routes unchanged)
    aios = DEFAULT_CONFIG.aios_api_prefix
    app.router.add_get(f"{aios}/health", aios_api.aios_health_handler)
    app.router.add_post(f"{aios}/bootstrap", aios_api.aios_bootstrap_handler)
    app.router.add_get(f"{aios}/goals", aios_api.aios_goals_handler)
    app.router.add_post(f"{aios}/goals", aios_api.aios_goals_handler)
    app.router.add_post(f"{aios}/run", aios_api.aios_run_handler)
    app.router.add_get(f"{aios}/plan", aios_api.aios_plan_handler)
    app.router.add_post(f"{aios}/plan", aios_api.aios_plan_handler)
    app.router.add_post(f"{aios}/execute", aios_api.aios_execute_handler)
    app.router.add_get(f"{aios}/supervise", aios_api.aios_supervise_handler)
    app.router.add_post(f"{aios}/supervise", aios_api.aios_supervise_handler)
    app.router.add_post(f"{aios}/recover", aios_api.aios_recover_handler)
    app.router.add_get(f"{aios}/governance", aios_api.aios_governance_handler)
    app.router.add_post(f"{aios}/governance", aios_api.aios_governance_handler)
    app.router.add_get(f"{aios}/dashboard", aios_api.aios_dashboard_handler)
    app.router.add_post(f"{aios}/dashboard", aios_api.aios_dashboard_handler)
    app.router.add_get(f"{aios}/analytics", aios_api.aios_analytics_handler)
    app.router.add_post(f"{aios}/analytics", aios_api.aios_analytics_handler)

    # Sprint 20.5 — Event Platform (additive; prior routes unchanged)
    evp = DEFAULT_CONFIG.event_platform_api_prefix
    app.router.add_get(f"{evp}/health", evp_api.evp_health_handler)
    app.router.add_post(f"{evp}/bootstrap", evp_api.evp_bootstrap_handler)
    app.router.add_post(f"{evp}/publish", evp_api.evp_publish_handler)
    app.router.add_get(f"{evp}/subscribe", evp_api.evp_subscribe_handler)
    app.router.add_post(f"{evp}/subscribe", evp_api.evp_subscribe_handler)
    app.router.add_get(f"{evp}/events", evp_api.evp_events_handler)
    app.router.add_post(f"{evp}/events", evp_api.evp_events_handler)
    app.router.add_post(f"{evp}/replay", evp_api.evp_replay_handler)
    app.router.add_get(f"{evp}/dlq", evp_api.evp_dlq_handler)
    app.router.add_get(f"{evp}/schemas", evp_api.evp_schemas_handler)
    app.router.add_post(f"{evp}/schemas", evp_api.evp_schemas_handler)
    app.router.add_get(f"{evp}/dashboard", evp_api.evp_dashboard_handler)
    app.router.add_post(f"{evp}/dashboard", evp_api.evp_dashboard_handler)
    app.router.add_get(f"{evp}/analytics", evp_api.evp_analytics_handler)
    app.router.add_post(f"{evp}/analytics", evp_api.evp_analytics_handler)

    # Sprint 20.6 — Developer Platform (additive; prior routes unchanged)
    sdp = DEFAULT_CONFIG.developer_platform_api_prefix
    app.router.add_get(f"{sdp}/health", sdp_api.sdp_health_handler)
    app.router.add_post(f"{sdp}/bootstrap", sdp_api.sdp_bootstrap_handler)
    app.router.add_get(f"{sdp}/plugins", sdp_api.sdp_plugins_handler)
    app.router.add_post(f"{sdp}/plugins", sdp_api.sdp_plugins_handler)
    app.router.add_post(f"{sdp}/lifecycle", sdp_api.sdp_lifecycle_handler)
    app.router.add_get(f"{sdp}/extensions", sdp_api.sdp_extensions_handler)
    app.router.add_post(f"{sdp}/extensions", sdp_api.sdp_extensions_handler)
    app.router.add_get(f"{sdp}/sdk", sdp_api.sdp_sdk_handler)
    app.router.add_post(f"{sdp}/sdk", sdp_api.sdp_sdk_handler)
    app.router.add_get(f"{sdp}/marketplace", sdp_api.sdp_marketplace_handler)
    app.router.add_post(f"{sdp}/marketplace", sdp_api.sdp_marketplace_handler)
    app.router.add_get(f"{sdp}/packages", sdp_api.sdp_packages_handler)
    app.router.add_post(f"{sdp}/packages", sdp_api.sdp_packages_handler)
    app.router.add_get(f"{sdp}/console", sdp_api.sdp_console_handler)
    app.router.add_post(f"{sdp}/console", sdp_api.sdp_console_handler)
    app.router.add_get(f"{sdp}/analytics", sdp_api.sdp_analytics_handler)
    app.router.add_post(f"{sdp}/analytics", sdp_api.sdp_analytics_handler)
    app.router.add_get(f"{sdp}/docs", sdp_api.sdp_docs_handler)
    app.router.add_post(f"{sdp}/docs", sdp_api.sdp_docs_handler)

    # Sprint 20.7 — Data Fabric (additive; prior routes unchanged)
    edf = DEFAULT_CONFIG.data_fabric_api_prefix
    app.router.add_get(f"{edf}/health", edf_api.edf_health_handler)
    app.router.add_post(f"{edf}/bootstrap", edf_api.edf_bootstrap_handler)
    app.router.add_get(f"{edf}/catalog", edf_api.edf_catalog_handler)
    app.router.add_post(f"{edf}/catalog", edf_api.edf_catalog_handler)
    app.router.add_post(f"{edf}/query", edf_api.edf_query_handler)
    app.router.add_post(f"{edf}/federation", edf_api.edf_federation_handler)
    app.router.add_get(f"{edf}/governance", edf_api.edf_governance_handler)
    app.router.add_post(f"{edf}/governance", edf_api.edf_governance_handler)
    app.router.add_get(f"{edf}/lineage", edf_api.edf_lineage_handler)
    app.router.add_post(f"{edf}/lineage", edf_api.edf_lineage_handler)
    app.router.add_get(f"{edf}/quality", edf_api.edf_quality_handler)
    app.router.add_post(f"{edf}/quality", edf_api.edf_quality_handler)
    app.router.add_get(f"{edf}/dashboard", edf_api.edf_dashboard_handler)
    app.router.add_post(f"{edf}/dashboard", edf_api.edf_dashboard_handler)
    app.router.add_get(f"{edf}/analytics", edf_api.edf_analytics_handler)
    app.router.add_post(f"{edf}/analytics", edf_api.edf_analytics_handler)

    # Sprint 20.8 — Digital Twin (additive; prior routes unchanged)
    edt = DEFAULT_CONFIG.digital_twin_api_prefix
    app.router.add_get(f"{edt}/health", edt_api.edt_health_handler)
    app.router.add_post(f"{edt}/bootstrap", edt_api.edt_bootstrap_handler)
    app.router.add_get(f"{edt}/twins", edt_api.edt_twins_handler)
    app.router.add_post(f"{edt}/twins", edt_api.edt_twins_handler)
    app.router.add_post(f"{edt}/state", edt_api.edt_state_handler)
    app.router.add_get(f"{edt}/relationships", edt_api.edt_relationships_handler)
    app.router.add_post(f"{edt}/relationships", edt_api.edt_relationships_handler)
    app.router.add_post(f"{edt}/sync", edt_api.edt_sync_handler)
    app.router.add_get(f"{edt}/timeline", edt_api.edt_timeline_handler)
    app.router.add_post(f"{edt}/timeline", edt_api.edt_timeline_handler)
    app.router.add_get(f"{edt}/snapshots", edt_api.edt_snapshots_handler)
    app.router.add_post(f"{edt}/snapshots", edt_api.edt_snapshots_handler)
    app.router.add_get(f"{edt}/visualize", edt_api.edt_visualize_handler)
    app.router.add_post(f"{edt}/visualize", edt_api.edt_visualize_handler)
    app.router.add_get(f"{edt}/analytics", edt_api.edt_analytics_handler)
    app.router.add_post(f"{edt}/analytics", edt_api.edt_analytics_handler)
    app.router.add_post(f"{edt}/prediction", edt_api.edt_prediction_handler)

    # Sprint 20.9 — Simulation & Decision Intelligence (additive; prior routes unchanged)
    esi = DEFAULT_CONFIG.simulation_engine_api_prefix
    app.router.add_get(f"{esi}/health", esi_api.esi_health_handler)
    app.router.add_post(f"{esi}/bootstrap", esi_api.esi_bootstrap_handler)
    app.router.add_get(f"{esi}/scenarios", esi_api.esi_scenarios_handler)
    app.router.add_post(f"{esi}/scenarios", esi_api.esi_scenarios_handler)
    app.router.add_post(f"{esi}/decisions", esi_api.esi_decisions_handler)
    app.router.add_post(f"{esi}/forecasts", esi_api.esi_forecasts_handler)
    app.router.add_post(f"{esi}/optimize", esi_api.esi_optimize_handler)
    app.router.add_post(f"{esi}/risk", esi_api.esi_risk_handler)
    app.router.add_post(f"{esi}/monte-carlo", esi_api.esi_monte_carlo_handler)
    app.router.add_post(f"{esi}/sensitivity", esi_api.esi_sensitivity_handler)
    app.router.add_get(f"{esi}/dashboard", esi_api.esi_dashboard_handler)
    app.router.add_post(f"{esi}/dashboard", esi_api.esi_dashboard_handler)
    app.router.add_get(f"{esi}/analytics", esi_api.esi_analytics_handler)
    app.router.add_post(f"{esi}/analytics", esi_api.esi_analytics_handler)
    app.router.add_post(f"{esi}/recommendations", esi_api.esi_recommendations_handler)
    app.router.add_get(f"{esi}/schedule", esi_api.esi_schedule_handler)
    app.router.add_post(f"{esi}/schedule", esi_api.esi_schedule_handler)

    # Sprint 20.10 — Process Mining (additive; prior routes unchanged)
    epm = DEFAULT_CONFIG.process_mining_api_prefix
    app.router.add_get(f"{epm}/health", epm_api.epm_health_handler)
    app.router.add_post(f"{epm}/bootstrap", epm_api.epm_bootstrap_handler)
    app.router.add_get(f"{epm}/events", epm_api.epm_events_handler)
    app.router.add_post(f"{epm}/events", epm_api.epm_events_handler)
    app.router.add_post(f"{epm}/discover", epm_api.epm_discover_handler)
    app.router.add_post(f"{epm}/conformance", epm_api.epm_conformance_handler)
    app.router.add_post(f"{epm}/bottlenecks", epm_api.epm_bottlenecks_handler)
    app.router.add_post(f"{epm}/optimize", epm_api.epm_optimize_handler)
    app.router.add_get(f"{epm}/dashboard", epm_api.epm_dashboard_handler)
    app.router.add_post(f"{epm}/dashboard", epm_api.epm_dashboard_handler)
    app.router.add_get(f"{epm}/analytics", epm_api.epm_analytics_handler)
    app.router.add_post(f"{epm}/analytics", epm_api.epm_analytics_handler)

    # Sprint 20.11 — Business Capabilities (additive; prior routes unchanged)
    ebc = DEFAULT_CONFIG.business_capabilities_api_prefix
    app.router.add_get(f"{ebc}/health", ebc_api.ebc_health_handler)
    app.router.add_post(f"{ebc}/bootstrap", ebc_api.ebc_bootstrap_handler)
    app.router.add_get(f"{ebc}/capabilities", ebc_api.ebc_capabilities_handler)
    app.router.add_post(f"{ebc}/capabilities", ebc_api.ebc_capabilities_handler)
    app.router.add_get(f"{ebc}/hierarchy", ebc_api.ebc_hierarchy_handler)
    app.router.add_post(f"{ebc}/hierarchy", ebc_api.ebc_hierarchy_handler)
    app.router.add_get(f"{ebc}/dependencies", ebc_api.ebc_dependencies_handler)
    app.router.add_post(f"{ebc}/dependencies", ebc_api.ebc_dependencies_handler)
    app.router.add_get(f"{ebc}/maturity", ebc_api.ebc_maturity_handler)
    app.router.add_post(f"{ebc}/maturity", ebc_api.ebc_maturity_handler)
    app.router.add_post(f"{ebc}/impact", ebc_api.ebc_impact_handler)
    app.router.add_post(f"{ebc}/advise", ebc_api.ebc_advise_handler)
    app.router.add_get(f"{ebc}/roadmap", ebc_api.ebc_roadmap_handler)
    app.router.add_post(f"{ebc}/roadmap", ebc_api.ebc_roadmap_handler)
    app.router.add_get(f"{ebc}/dashboard", ebc_api.ebc_dashboard_handler)
    app.router.add_post(f"{ebc}/dashboard", ebc_api.ebc_dashboard_handler)
    app.router.add_get(f"{ebc}/analytics", ebc_api.ebc_analytics_handler)
    app.router.add_post(f"{ebc}/analytics", ebc_api.ebc_analytics_handler)

    # Sprint 20.12 — Command Center (additive; prior routes unchanged)
    ecc = DEFAULT_CONFIG.command_center_api_prefix
    app.router.add_get(f"{ecc}/health", ecc_api.ecc_health_handler)
    app.router.add_post(f"{ecc}/bootstrap", ecc_api.ecc_bootstrap_handler)
    app.router.add_get(f"{ecc}/dashboards", ecc_api.ecc_dashboards_handler)
    app.router.add_post(f"{ecc}/dashboards", ecc_api.ecc_dashboards_handler)
    app.router.add_get(f"{ecc}/executive", ecc_api.ecc_executive_handler)
    app.router.add_post(f"{ecc}/executive", ecc_api.ecc_executive_handler)
    app.router.add_get(f"{ecc}/enterprise-health", ecc_api.ecc_enterprise_health_handler)
    app.router.add_post(f"{ecc}/enterprise-health", ecc_api.ecc_enterprise_health_handler)
    app.router.add_get(f"{ecc}/situation", ecc_api.ecc_situation_handler)
    app.router.add_post(f"{ecc}/situation", ecc_api.ecc_situation_handler)
    app.router.add_post(f"{ecc}/assistant", ecc_api.ecc_assistant_handler)
    app.router.add_get(f"{ecc}/alerts", ecc_api.ecc_alerts_handler)
    app.router.add_post(f"{ecc}/alerts", ecc_api.ecc_alerts_handler)
    app.router.add_get(f"{ecc}/actions", ecc_api.ecc_actions_handler)
    app.router.add_post(f"{ecc}/actions", ecc_api.ecc_actions_handler)
    app.router.add_post(f"{ecc}/command", ecc_api.ecc_command_handler)
    app.router.add_get(f"{ecc}/realtime", ecc_api.ecc_realtime_handler)
    app.router.add_get(f"{ecc}/map", ecc_api.ecc_map_handler)
    app.router.add_get(f"{ecc}/analytics", ecc_api.ecc_analytics_handler)
    app.router.add_post(f"{ecc}/analytics", ecc_api.ecc_analytics_handler)

    # Sprint 21.2 — API Standardization (additive; prior routes unchanged)
    eas = DEFAULT_CONFIG.api_standardization_api_prefix
    app.router.add_get(f"{eas}/health", eas_api.eas_health_handler)
    app.router.add_post(f"{eas}/bootstrap", eas_api.eas_bootstrap_handler)
    app.router.add_get(f"{eas}/inventory", eas_api.eas_inventory_handler)
    app.router.add_post(f"{eas}/inventory", eas_api.eas_inventory_handler)
    app.router.add_get(f"{eas}/registry", eas_api.eas_registry_handler)
    app.router.add_post(f"{eas}/registry", eas_api.eas_registry_handler)
    app.router.add_get(f"{eas}/rest", eas_api.eas_rest_handler)
    app.router.add_post(f"{eas}/rest", eas_api.eas_rest_handler)
    app.router.add_get(f"{eas}/versioning", eas_api.eas_versioning_handler)
    app.router.add_get(f"{eas}/auth", eas_api.eas_auth_handler)
    app.router.add_post(f"{eas}/auth", eas_api.eas_auth_handler)
    app.router.add_get(f"{eas}/websocket", eas_api.eas_websocket_handler)
    app.router.add_get(f"{eas}/events", eas_api.eas_events_handler)
    app.router.add_post(f"{eas}/events", eas_api.eas_events_handler)
    app.router.add_get(f"{eas}/openapi", eas_api.eas_openapi_handler)
    app.router.add_post(f"{eas}/openapi", eas_api.eas_openapi_handler)
    app.router.add_get(f"{eas}/docs", eas_api.eas_docs_handler)
    app.router.add_get(f"{eas}/gateway", eas_api.eas_gateway_handler)
    app.router.add_post(f"{eas}/gateway", eas_api.eas_gateway_handler)
    app.router.add_get(f"{eas}/governance", eas_api.eas_governance_handler)
    app.router.add_post(f"{eas}/governance", eas_api.eas_governance_handler)

    # Sprint 21.3 — Data Contracts (additive; prior routes unchanged)
    edc = DEFAULT_CONFIG.data_contracts_api_prefix
    app.router.add_get(f"{edc}/health", edc_api.edc_health_handler)
    app.router.add_post(f"{edc}/bootstrap", edc_api.edc_bootstrap_handler)
    app.router.add_get(f"{edc}/dtos", edc_api.edc_dtos_handler)
    app.router.add_post(f"{edc}/dtos", edc_api.edc_dtos_handler)
    app.router.add_get(f"{edc}/schemas", edc_api.edc_schemas_handler)
    app.router.add_post(f"{edc}/schemas", edc_api.edc_schemas_handler)
    app.router.add_post(f"{edc}/validate", edc_api.edc_validate_handler)
    app.router.add_post(f"{edc}/serialize", edc_api.edc_serialize_handler)
    app.router.add_post(f"{edc}/map", edc_api.edc_map_handler)
    app.router.add_post(f"{edc}/tests", edc_api.edc_tests_handler)
    app.router.add_get(f"{edc}/docs", edc_api.edc_docs_handler)

    # Sprint 21.4 — Security Hardening (additive; prior routes unchanged)
    esh = DEFAULT_CONFIG.security_hardening_api_prefix
    app.router.add_get(f"{esh}/health", esh_api.esh_health_handler)
    app.router.add_post(f"{esh}/bootstrap", esh_api.esh_bootstrap_handler)
    app.router.add_post(f"{esh}/authenticate", esh_api.esh_authenticate_handler)
    app.router.add_post(f"{esh}/authorize", esh_api.esh_authorize_handler)
    app.router.add_get(f"{esh}/zero-trust", esh_api.esh_zero_trust_handler)
    app.router.add_post(f"{esh}/zero-trust", esh_api.esh_zero_trust_handler)
    app.router.add_get(f"{esh}/secrets", esh_api.esh_secrets_handler)
    app.router.add_post(f"{esh}/secrets", esh_api.esh_secrets_handler)
    app.router.add_get(f"{esh}/compliance", esh_api.esh_compliance_handler)
    app.router.add_post(f"{esh}/compliance", esh_api.esh_compliance_handler)
    app.router.add_post(f"{esh}/tests", esh_api.esh_tests_handler)
    app.router.add_get(f"{esh}/dashboard", esh_api.esh_dashboard_handler)

    # Sprint 21.5 — Quality Assurance (additive; prior routes unchanged)
    eqa = DEFAULT_CONFIG.quality_assurance_api_prefix
    app.router.add_get(f"{eqa}/health", eqa_api.eqa_health_handler)
    app.router.add_post(f"{eqa}/bootstrap", eqa_api.eqa_bootstrap_handler)
    app.router.add_get(f"{eqa}/suites", eqa_api.eqa_suites_handler)
    app.router.add_post(f"{eqa}/suites", eqa_api.eqa_suites_handler)
    app.router.add_get(f"{eqa}/coverage", eqa_api.eqa_coverage_handler)
    app.router.add_post(f"{eqa}/coverage", eqa_api.eqa_coverage_handler)
    app.router.add_get(f"{eqa}/fixtures", eqa_api.eqa_fixtures_handler)
    app.router.add_post(f"{eqa}/fixtures", eqa_api.eqa_fixtures_handler)
    app.router.add_get(f"{eqa}/dashboard", eqa_api.eqa_dashboard_handler)
    app.router.add_post(f"{eqa}/certify", eqa_api.eqa_certify_handler)

    # Sprint 21.6 — Documentation Platform (additive; prior routes unchanged)
    edo = DEFAULT_CONFIG.documentation_platform_api_prefix
    app.router.add_get(f"{edo}/health", edo_api.edo_health_handler)
    app.router.add_post(f"{edo}/bootstrap", edo_api.edo_bootstrap_handler)
    app.router.add_get(f"{edo}/docs", edo_api.edo_docs_handler)
    app.router.add_post(f"{edo}/docs", edo_api.edo_docs_handler)
    app.router.add_get(f"{edo}/search", edo_api.edo_search_handler)
    app.router.add_post(f"{edo}/search", edo_api.edo_search_handler)
    app.router.add_post(f"{edo}/generate", edo_api.edo_generate_handler)
    app.router.add_post(f"{edo}/publish", edo_api.edo_publish_handler)
    app.router.add_get(f"{edo}/quality", edo_api.edo_quality_handler)
    app.router.add_post(f"{edo}/quality", edo_api.edo_quality_handler)
    app.router.add_get(f"{edo}/dashboard", edo_api.edo_dashboard_handler)

    # Sprint 21.7 — Performance Platform (additive; prior routes unchanged)
    epf = DEFAULT_CONFIG.performance_platform_api_prefix
    app.router.add_get(f"{epf}/health", epf_api.epf_health_handler)
    app.router.add_post(f"{epf}/bootstrap", epf_api.epf_bootstrap_handler)
    app.router.add_get(f"{epf}/profile", epf_api.epf_profile_handler)
    app.router.add_post(f"{epf}/profile", epf_api.epf_profile_handler)
    app.router.add_post(f"{epf}/benchmark", epf_api.epf_benchmark_handler)
    app.router.add_post(f"{epf}/load", epf_api.epf_load_handler)
    app.router.add_post(f"{epf}/stress", epf_api.epf_stress_handler)
    app.router.add_post(f"{epf}/cache", epf_api.epf_cache_handler)
    app.router.add_get(f"{epf}/dashboard", epf_api.epf_dashboard_handler)
    app.router.add_post(f"{epf}/certify", epf_api.epf_certify_handler)

    # Sprint 21.8 — Release Platform (additive; prior routes unchanged)
    erl = DEFAULT_CONFIG.release_platform_api_prefix
    app.router.add_get(f"{erl}/health", erl_api.erl_health_handler)
    app.router.add_post(f"{erl}/bootstrap", erl_api.erl_bootstrap_handler)
    app.router.add_post(f"{erl}/certify", erl_api.erl_certify_handler)
    app.router.add_post(f"{erl}/validate", erl_api.erl_validate_handler)
    app.router.add_post(f"{erl}/migrate", erl_api.erl_migrate_handler)
    app.router.add_post(f"{erl}/disaster-recovery", erl_api.erl_dr_handler)
    app.router.add_get(f"{erl}/release-notes", erl_api.erl_notes_handler)
    app.router.add_post(f"{erl}/approve", erl_api.erl_approve_handler)
    app.router.add_get(f"{erl}/manifest", erl_api.erl_manifest_handler)

