"""Enterprise Business Ecosystem Foundation catalogs — Sprint 30.2."""

from __future__ import annotations

from typing import Any


WIZARD_STEPS = [
    {"id": "framework", "title": "Business Ecosystem Framework", "index": 1},
    {"id": "modules", "title": "Universal Modules", "index": 2},
    {"id": "extensions", "title": "Extension Model", "index": 3},
    {"id": "registry", "title": "Business Ecosystem Registry", "index": 4},
    {"id": "automotive", "title": "Automotive Capabilities", "index": 5},
    {"id": "agriculture", "title": "Agriculture Capabilities", "index": 6},
    {"id": "beauty_cafe", "title": "Beauty & Cafe Capabilities", "index": 7},
    {"id": "crypto_legal_drone", "title": "Crypto · Legal · Drone", "index": 8},
    {"id": "compatibility", "title": "Architecture Compatibility", "index": 9},
    {"id": "create", "title": "Create", "index": 10},
]

FRAMEWORK_COMPONENTS = (
    "Business Ecosystem Framework",
    "Business Template Registry",
    "Reusable Module Registry",
    "Industry Extension Engine",
    "Industry Capability Registry",
    "Industry Configuration Layer",
    "Industry Feature Loader",
    "Industry Metadata Registry",
    "Industry Navigation Registry",
)

GLOBAL_PLATFORM_CORES = (
    "Mission Control",
    "Digital Twin",
    "Workflow Engine",
    "Knowledge Graph",
    "AI OS",
    "Builder Studio",
)

UNIVERSAL_MODULES = (
    "CRM",
    "Customer Portal",
    "Employee Portal",
    "Owner Dashboard",
    "Mission Control",
    "Workspace",
    "Calendar",
    "Tasks",
    "Booking",
    "Documents",
    "Knowledge",
    "Workflow",
    "Analytics",
    "Finance",
    "Notifications",
    "Chat",
    "Email",
    "Telegram",
    "WhatsApp",
    "Mobile App",
    "Marketing",
    "Advertising",
    "AI Agents",
    "Automation",
    "Digital Twin",
    "Reporting",
)

MODULE_EXTENSION_POINTS = (
    "industry extensions",
    "custom workflows",
    "custom AI agents",
    "custom UI",
    "custom permissions",
    "custom navigation",
    "custom reports",
    "custom automation",
)

ECOSYSTEM_REGISTRY = (
    "Automotive",
    "Agriculture",
    "Beauty",
    "Cafe",
    "Crypto",
    "Legal",
    "Drone",
    "Manufacturing",
    "Retail",
    "Education",
    "Logistics",
    "Government",
    "Custom Industry",
)

AUTOMOTIVE_CAPABILITIES = (
    "Dealer",
    "Showroom",
    "Vehicle Sales",
    "Used Cars",
    "Trade-In",
    "Vehicle Marketplace",
    "Insurance",
    "Leasing",
    "Financing",
    "Service",
    "Workshop",
    "Tire Service",
    "Car Wash",
    "Detailing",
    "Diagnostics",
    "VIN",
    "Warehouse",
    "Parts",
    "Marketing",
    "Lead Management",
    "CRM",
    "AI Sales",
    "AI Service Advisor",
    "AI Marketing",
    "Customer Portal",
    "Dealer Portal",
    "Owner Dashboard",
)

AGRICULTURE_CAPABILITIES = (
    "Farm Management",
    "Field Management",
    "Livestock",
    "Equipment",
    "IoT",
    "Weather",
    "Satellite",
    "Drone Operations",
    "Commodity Trading",
    "Buy Grain",
    "Sell Grain",
    "Export",
    "Import",
    "Freight",
    "Sea Freight",
    "Container Tracking",
    "Port Operations",
    "Warehouse",
    "Certificates",
    "Bills of Lading",
    "Customs Documents",
    "Origin Certificates",
    "Logistics Marketplace",
    "Trader Portal",
    "Farmer Portal",
    "Buyer Portal",
    "AI Trader",
    "AI Agronomist",
    "AI Logistics",
)

BEAUTY_CAPABILITIES = (
    "Beauty Salon",
    "Cosmetology",
    "Massage",
    "SPA",
    "Appointments",
    "Masters",
    "Clients",
    "CRM",
    "Telegram",
    "Marketing",
    "Advertising",
    "Loyalty",
    "Gift Cards",
    "Subscriptions",
    "AI Reception",
    "AI Cosmetologist",
    "Owner Dashboard",
)

CAFE_CAPABILITIES = (
    "Cafe",
    "Restaurant",
    "Bar",
    "Kitchen",
    "Menu",
    "QR Menu",
    "Delivery",
    "Reservations",
    "CRM",
    "Marketing",
    "Loyalty",
    "Kitchen Display",
    "Cashier",
    "AI Waiter",
    "AI Administrator",
    "Owner Dashboard",
)

CRYPTO_CAPABILITIES = (
    "Bidex Core",
    "Wallet",
    "Payments",
    "Exchange",
    "OTC",
    "P2P",
    "AML",
    "KYC",
    "Partners",
    "Cash Desks",
    "Transfers",
    "Reporting",
    "Risk Engine",
    "Treasury",
    "AI Trader",
    "AI Compliance",
)

LEGAL_CAPABILITIES = (
    "Lawyer CRM",
    "Cases",
    "Clients",
    "Contracts",
    "Court Calendar",
    "Hearings",
    "Documents",
    "Templates",
    "Electronic Signature",
    "Billing",
    "Client Portal",
    "AI Lawyer",
    "AI Assistant",
    "Legal Knowledge",
)

DRONE_CAPABILITIES = (
    "R&D",
    "Manufacturing",
    "Fleet",
    "Mission Control",
    "Telemetry",
    "Ground Stations",
    "Maintenance",
    "Warehouse",
    "Production",
    "Testing",
    "Payloads",
    "Digital Twin",
    "AI Flight Analysis",
)

ARCHITECTURE_PRINCIPLES = (
    "Every Business Ecosystem uses the same platform core",
    "Every ecosystem extends the Platform",
    "Nothing is copied",
    "Everything is reusable",
    "Every future business must be configurable",
    "Mission Control remains global",
    "Digital Twin remains global",
    "Workflow Engine remains global",
    "Knowledge Graph remains global",
    "AI OS remains global",
    "Builder Studio remains global",
    "Industry modules only extend functionality",
)

UI_SURFACES = (
    "Ecosystem Foundation Center",
    "Universal Module Catalog",
    "Industry Registry",
    "Capability Catalog",
    "Extension Map",
    "Architecture Compatibility Board",
)


def full_catalog() -> dict[str, Any]:
    return {
        "steps": WIZARD_STEPS,
        "components": list(FRAMEWORK_COMPONENTS),
        "global_platform_cores": list(GLOBAL_PLATFORM_CORES),
        "universal_modules": list(UNIVERSAL_MODULES),
        "module_extension_points": list(MODULE_EXTENSION_POINTS),
        "ecosystem_registry": list(ECOSYSTEM_REGISTRY),
        "automotive_capabilities": list(AUTOMOTIVE_CAPABILITIES),
        "agriculture_capabilities": list(AGRICULTURE_CAPABILITIES),
        "beauty_capabilities": list(BEAUTY_CAPABILITIES),
        "cafe_capabilities": list(CAFE_CAPABILITIES),
        "crypto_capabilities": list(CRYPTO_CAPABILITIES),
        "legal_capabilities": list(LEGAL_CAPABILITIES),
        "drone_capabilities": list(DRONE_CAPABILITIES),
        "architecture_principles": list(ARCHITECTURE_PRINCIPLES),
        "ui_surfaces": list(UI_SURFACES),
        "does_not_remove_existing_functionality": True,
        "does_not_replace_existing_modules": True,
        "does_not_break_existing_apis": True,
        "does_not_duplicate_existing_logic": True,
        "industry_modules_only_extend": True,
    }
