import type { AcademyMode, BuilderDef, HelpContent } from "../types";
import {
  AI_BUILDER_STEPS,
  CONCIERGE_STEPS,
  GENERIC_STEPS,
  UNIVERSAL_FRAMEWORK_STEPS,
  VERTICAL_STEPS,
} from "../types";

export const BUILDER_CATALOG: BuilderDef[] = [
  { id: "dashboard", name: "Панель управления", route: "/platform-builder", kind: "hub", status: "operational" },
  { id: "universal_framework", name: "Универсальный каркас конструктора", route: "/platform-builder/framework", kind: "hub", status: "operational", steps: UNIVERSAL_FRAMEWORK_STEPS, purpose: "One common architecture for every Platform Builder." },
  { id: "vertical", name: "Конструктор вертикалей", route: "/platform-builder/vertical", kind: "builder", status: "operational", steps: VERTICAL_STEPS, frameOnly: false, purpose: "Visually create complete Enterprise Вертикали without programming." },
  { id: "ai", name: "Студия AI-конструктора", route: "/platform-builder/builder-studio", kind: "builder", status: "operational", steps: AI_BUILDER_STEPS, frameOnly: false, purpose: "Compose AI agent teams, workflows, skills and templates as a constructor." },
  { id: "builder_studio", name: "Студия AI-конструктора", route: "/platform-builder/builder-studio", kind: "hub", status: "operational", purpose: "Unified constructor for AI Team, Сценарий, Skills, Prompts and Шаблоны." },
  { id: "concierge", name: "Конструктор AI Консьержа", route: "/platform-builder/concierge", kind: "builder", status: "operational", steps: CONCIERGE_STEPS, frameOnly: false, purpose: "Configure the single organizational Concierge assistant.", constraints: { onePerOrganization: true, separateFromAiAgents: true } },
  { id: "ai_team", name: "Центр команды AI", route: "/platform-builder/ai-team", kind: "hub", status: "operational", purpose: "Monitor and manage all AI Specialists for the organization." },
  { id: "collaborative_ai", name: "Совместная работа AI", route: "/platform-builder/collaborative-ai", kind: "builder", status: "operational", purpose: "Coordinate AI Specialists via Concierge for collective intelligence." },
  { id: "operations_center", name: "Центр операций AI", route: "/platform-builder/operations", kind: "hub", status: "operational", purpose: "Real-time visual control room for the AI Организация." },
  { id: "team_map", name: "Карта команды AI", route: "/platform-builder/team-map", kind: "hub", status: "operational", purpose: "Live Карта организации with Visual Event Bus and relationship engine." },
  { id: "visual_behavior", name: "Движок визуального поведения", route: "/platform-builder/visual-behavior", kind: "hub", status: "operational", purpose: "Event-bus-driven visual behaviors and animations — no business logic." },
  { id: "rendering", name: "Движок визуализации", route: "/platform-builder/rendering", kind: "hub", status: "operational", purpose: "GPU-friendly rendering with LOD, viewport culling, and layer system." },
  { id: "themes", name: "Движок визуальных тем", route: "/platform-builder/themes", kind: "hub", status: "operational", purpose: "Enterprise visual identity, branding, and live theme switching — appearance only." },
  { id: "assets", name: "Реестр визуальных активов", route: "/platform-builder/assets", kind: "hub", status: "operational", purpose: "Store, version, optimize, and browse visual assets — separated from business logic." },
  { id: "simulation", name: "Движок визуальной симуляции", route: "/platform-builder/simulation", kind: "hub", status: "operational", purpose: "Live enterprise simulation from Visual Event Bus only — never creates fake events." },
  { id: "director", name: "Движок визуальной режиссуры", route: "/platform-builder/director", kind: "hub", status: "operational", purpose: "Scene orchestration and focus/attention direction — presentation only, no business events." },
  { id: "story", name: "Движок визуальных историй", route: "/platform-builder/story", kind: "hub", status: "operational", purpose: "Enterprise storytelling from verified Visual Event Bus events — never creates or reorders business events." },
  { id: "intelligence", name: "Движок визуальной аналитики", route: "/platform-builder/intelligence", kind: "hub", status: "operational", purpose: "Visual analytics and recommendations from verified events — no business logic changes or business events." },
  { id: "experience", name: "Движок визуального опыта", route: "/platform-builder/experience", kind: "hub", status: "operational", purpose: "Unified enterprise UX coordinating all visual subsystems — presentation only, no business logic." },
  { id: "workspace_os", name: "ОС рабочего пространства", route: "/platform-builder/workspace-os", kind: "hub", status: "operational", purpose: "Unified operating environment for every module with multi-workspace contexts — role aware." },
  { id: "command_center", name: "Центр управления", route: "/platform-builder/command-center", kind: "hub", status: "operational", purpose: "Universal command interface for modules, AI, workspaces and services — interaction orchestration only." },
  { id: "navigation_intelligence", name: "Интеллект навигации", route: "/platform-builder/navigation-intelligence", kind: "hub", status: "operational", purpose: "Predicts and simplifies navigation from verified context — never executes business logic." },
  { id: "workflow_intelligence", name: "ОС интеллекта сценариев", route: "/platform-builder/workflow-intelligence", kind: "hub", status: "operational", purpose: "Сценарий visibility, dependency analysis and recommendations — never executes business logic." },
  { id: "workflow_center", name: "Центр сценариев", route: "/platform-builder/workflow-center", kind: "hub", status: "operational", purpose: "Business workflow automation templates — no new Сценарий Engine." },
  { id: "enterprise_city", name: "Корпоративный город", route: "/enterprise-city", kind: "hub", status: "operational", purpose: "Spatial enterprise map over existing modules." },
  { id: "digital_twin", name: "Цифровой двойник предприятия", route: "/platform-builder/digital-twin", kind: "hub", status: "operational", purpose: "Living organization mirror — org map, heatmap, impact, timeline over existing services." },
  { id: "digital_twin_studio", name: "Студия цифрового двойника", route: "/platform-builder/digital-twin?studio=1", kind: "hub", status: "operational", purpose: "Classic session-based twin studio — read-only verified state." },
  { id: "integration_hub", name: "Центр интеграций", route: "/platform-builder/integrations", kind: "hub", status: "operational", purpose: "Unified control of external integrations — no new Integration Engine." },
  { id: "ai_runtime", name: "Среда выполнения AI", route: "/platform-builder/runtime", kind: "hub", status: "operational", purpose: "Live AI job queue and orchestration view — no new Исполнение Engine." },
  { id: "data_fabric", name: "Корпоративная шина данных", route: "/platform-builder/data-fabric", kind: "hub", status: "operational", purpose: "Unified related data model and lineage — no new Database Engine." },
  { id: "predictive", name: "Предиктивный интеллект", route: "/platform-builder/predictive", kind: "hub", status: "operational", purpose: "Forecasts and What-If scenarios — no new Prediction Engine." },
  { id: "autonomy", name: "Автономное предприятие", route: "/platform-builder/autonomy", kind: "hub", status: "operational", purpose: "Managed autonomy with human-in-the-loop approvals — no new Автоматизация Engine." },
  { id: "control_tower", name: "Диспетчерская предприятия", route: "/platform-builder/control-tower", kind: "hub", status: "operational", purpose: "Executive home composing Mission Control, Twin, Исполнение, Predictive, Autonomy — no new Панель управления Engine." },
  { id: "self_learning", name: "Самообучающееся предприятие", route: "/platform-builder/learning", kind: "hub", status: "operational", purpose: "Continuous optimization recommendations over EI / Исполнение / Сценарий / База знаний — no new Learning Engine." },
  { id: "okr_intelligence", name: "Стратегия и OKR", route: "/platform-builder/okr", kind: "hub", status: "operational", purpose: "Company goals and OKR alignment over EI / Learning / Predictive — no new Стратегия Engine." },
  { id: "governance", name: "Управление и комплаенс", route: "/platform-builder/governance", kind: "hub", status: "operational", purpose: "Policies, compliance, audit, AI control over Autonomy / RBAC — no new Security Engine." },
  { id: "twin_intelligence", name: "Интеллект цифрового двойника", route: "/platform-builder/twin-intelligence", kind: "hub", status: "operational", purpose: "Analyzes verified Digital Twin data — never changes state or executes workflows." },
  { id: "strategy_engine", name: "Движок стратегии предприятия", route: "/platform-builder/strategy", kind: "hub", status: "operational", purpose: "Strategic analysis and executive recommendations — never executes business logic." },
  { id: "mission_control", name: "Миссион-контроль предприятия", route: "/platform-builder/mission-control", kind: "hub", status: "operational", purpose: "Unified executive operating center — aggregates existing services, never replaces modules." },
  { id: "business_ecosystem", name: "Фундамент бизнес-экосистем", route: "/platform-builder/business-ecosystem", kind: "hub", status: "operational", purpose: "Reusable industry extension architecture — ecosystems extend platform core, never copy it." },
  {
    id: "crm",
    name: "Конструктор CRM",
    route: "/platform-builder/crm",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Configure CRM composition in the CRM workspace shell.",
    openWorkspaceRoute: "/workspace/crm",
  },
  {
    id: "erp",
    name: "Конструктор ERP",
    route: "/platform-builder/erp",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Open ERP module shell to continue composition.",
    openWorkspaceRoute: "/workspace/erp",
  },
  {
    id: "workflow",
    name: "Конструктор сценариев",
    route: "/platform-builder/workflow",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Use Центр сценариев for operational workflows.",
    openWorkspaceRoute: "/platform-builder/workflow-center",
  },
  {
    id: "knowledge",
    name: "Конструктор базы знаний",
    route: "/platform-builder/knowledge",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Open Documents / База знаний shell.",
    openWorkspaceRoute: "/workspace/docs",
  },
  {
    id: "automation",
    name: "Конструктор автоматизации",
    route: "/platform-builder/automation",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Manage automations in the workspace.",
    openWorkspaceRoute: "/workspace",
  },
  {
    id: "dashboard_builder",
    name: "Конструктор панелей",
    route: "/platform-builder/dashboard-builder",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Customize dashboards in Workspace Панели управления.",
    openWorkspaceRoute: "/workspace/dashboards",
  },
  {
    id: "template",
    name: "Конструктор шаблонов",
    route: "/platform-builder/template",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Open Workspace Layout for templates.",
    openWorkspaceRoute: "/workspace/layout",
  },
  {
    id: "marketplace",
    name: "Конструктор магазина решений",
    route: "/platform-builder/marketplace",
    kind: "builder",
    status: "frame",
    steps: GENERIC_STEPS,
    frameOnly: true,
    purpose: "Предпросмотр only — Скоро. Install packs in the Маркетплейс Solution Hub.",
    openWorkspaceRoute: "/platform-builder/solution-hub",
  },
  { id: "solution_hub", name: "Корпоративный магазин решений", route: "/platform-builder/solution-hub", kind: "hub", status: "operational", purpose: "One-click solutions over Builder Studio catalogs — no new Маркетплейс Engine." },
  { id: "academy", name: "Академия конструктора 2.0", route: "/platform-builder/academy", kind: "academy", status: "operational", purpose: "Interactive learning, AI Guide, and adaptive builder guidance." },
  { id: "god_mode", name: "Режим владельца", route: "/platform-builder/god-mode", kind: "god_mode", status: "operational", requiresRole: "platform_owner" },
];

export function getBuilder(id: string): BuilderDef | undefined {
  return BUILDER_CATALOG.find((b) => b.id === id);
}

export function buildersForMenu(isPlatformOwner: boolean): BuilderDef[] {
  return BUILDER_CATALOG.filter((b) => b.requiresRole !== "platform_owner" || isPlatformOwner);
}

export function helpFor(item: string, builderName: string): HelpContent {
  return {
    shortDescription: `${item} — ${builderName}`,
    detailedExplanation: `${item} помогает настроить объект в «${builderName}». Каждый выбор влияет на поведение на платформе.`,
    example: `Пример: настройте «${item}» под ритм работы вашей команды.`,
    popup: { title: item, body: `Используйте «${item}», чтобы задать основы для «${builderName}».` },
    tooltip: `Справка: ${item}`,
    purpose: "Для чего нужен этот параметр",
    benefits: "Как это помогает организации",
    typicalUse: "Где команды обычно применяют это",
    businessValue: "Какой бизнес-результат поддерживает",
  };
}

export const ACADEMY_MODES: { id: AcademyMode; name: string; description: string }[] = [
  { id: "quick_start", name: "Быстрый старт", description: "Пройдите основные шаги с краткими подсказками." },
  { id: "guided_learning", name: "Обучение с подсказками", description: "На каждом экране — назначение, польза и примеры." },
  { id: "expert", name: "Режим эксперта", description: "Минимум подсказок для опытных администраторов." },
];