export const GOD_CAPABILITIES = [
  "edit_any_object",
  "edit_any_vertical",
  "edit_any_application",
  "edit_any_ai",
  "edit_any_organization",
  "edit_any_workflow",
  "edit_any_knowledge_base",
  "edit_any_dashboard",
  "edit_any_automation",
  "edit_any_api",
  "edit_any_template",
  "edit_any_builder",
  "system_diagnostics",
  "architecture_management",
  "developer_console",
  "version_history",
  "rollback_manager",
] as const;
