"""automotive_procurement_engine_v1

Revision ID: 042bf97aa37b
Revises: bab0e9908d23
Create Date: 2026-07-12 20:18:45.296315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042bf97aa37b'
down_revision: Union[str, None] = 'bab0e9908d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_procurement_v1_purchase_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('year >= 1900', name='ck_automotive_procurement_v1_po_year'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number', name='uq_automotive_procurement_v1_purchase_orders_order_number')
    )
    op.create_index('ix_automotive_procurement_v1_po_partner_id', 'automotive_procurement_v1_purchase_orders', ['partner_id'], unique=False)
    op.create_index('ix_automotive_procurement_v1_po_source', 'automotive_procurement_v1_purchase_orders', ['source'], unique=False)
    op.create_index('ix_automotive_procurement_v1_po_status', 'automotive_procurement_v1_purchase_orders', ['status'], unique=False)
    op.create_index('ix_automotive_procurement_v1_po_vehicle_id', 'automotive_procurement_v1_purchase_orders', ['vehicle_id'], unique=False)
    op.create_table('automotive_procurement_v1_auction_lots',
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('external_lot_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('yard_location', sa.String(length=255), nullable=True),
    sa.Column('current_bid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('buy_now_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('winning_bid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('auction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('year >= 1900', name='ck_automotive_procurement_v1_lot_year'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['automotive_procurement_v1_purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_procurement_v1_lots_auction_date', 'automotive_procurement_v1_auction_lots', ['auction_date'], unique=False)
    op.create_index('ix_automotive_procurement_v1_lots_po_id', 'automotive_procurement_v1_auction_lots', ['purchase_order_id'], unique=False)
    op.create_index('ix_automotive_procurement_v1_lots_source', 'automotive_procurement_v1_auction_lots', ['source'], unique=False)
    op.create_index('ix_automotive_procurement_v1_lots_status', 'automotive_procurement_v1_auction_lots', ['status'], unique=False)
    op.create_table('automotive_procurement_v1_suppliers_offers',
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['automotive_procurement_v1_purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_procurement_v1_offers_partner_id', 'automotive_procurement_v1_suppliers_offers', ['partner_id'], unique=False)
    op.create_index('ix_automotive_procurement_v1_offers_po_id', 'automotive_procurement_v1_suppliers_offers', ['purchase_order_id'], unique=False)
    op.create_index('ix_automotive_procurement_v1_offers_source', 'automotive_procurement_v1_suppliers_offers', ['source'], unique=False)
    op.create_index('ix_automotive_procurement_v1_offers_status', 'automotive_procurement_v1_suppliers_offers', ['status'], unique=False)
    op.create_table('automotive_procurement_v1_vehicle_sources',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('supplier_offer_id', sa.UUID(), nullable=True),
    sa.Column('auction_lot_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_lot_id'], ['automotive_procurement_v1_auction_lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['automotive_procurement_v1_purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_offer_id'], ['automotive_procurement_v1_suppliers_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_procurement_v1_vs_po_id', 'automotive_procurement_v1_vehicle_sources', ['purchase_order_id'], unique=False)
    op.create_index('ix_automotive_procurement_v1_vs_source', 'automotive_procurement_v1_vehicle_sources', ['source'], unique=False)
    op.create_index('ix_automotive_procurement_v1_vs_vehicle_id', 'automotive_procurement_v1_vehicle_sources', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automotive_procurement_v1_vs_vehicle_id', table_name='automotive_procurement_v1_vehicle_sources')
    op.drop_index('ix_automotive_procurement_v1_vs_source', table_name='automotive_procurement_v1_vehicle_sources')
    op.drop_index('ix_automotive_procurement_v1_vs_po_id', table_name='automotive_procurement_v1_vehicle_sources')
    op.drop_table('automotive_procurement_v1_vehicle_sources')
    op.drop_index('ix_automotive_procurement_v1_offers_status', table_name='automotive_procurement_v1_suppliers_offers')
    op.drop_index('ix_automotive_procurement_v1_offers_source', table_name='automotive_procurement_v1_suppliers_offers')
    op.drop_index('ix_automotive_procurement_v1_offers_po_id', table_name='automotive_procurement_v1_suppliers_offers')
    op.drop_index('ix_automotive_procurement_v1_offers_partner_id', table_name='automotive_procurement_v1_suppliers_offers')
    op.drop_table('automotive_procurement_v1_suppliers_offers')
    op.drop_index('ix_automotive_procurement_v1_lots_status', table_name='automotive_procurement_v1_auction_lots')
    op.drop_index('ix_automotive_procurement_v1_lots_source', table_name='automotive_procurement_v1_auction_lots')
    op.drop_index('ix_automotive_procurement_v1_lots_po_id', table_name='automotive_procurement_v1_auction_lots')
    op.drop_index('ix_automotive_procurement_v1_lots_auction_date', table_name='automotive_procurement_v1_auction_lots')
    op.drop_table('automotive_procurement_v1_auction_lots')
    op.drop_index('ix_automotive_procurement_v1_po_vehicle_id', table_name='automotive_procurement_v1_purchase_orders')
    op.drop_index('ix_automotive_procurement_v1_po_status', table_name='automotive_procurement_v1_purchase_orders')
    op.drop_index('ix_automotive_procurement_v1_po_source', table_name='automotive_procurement_v1_purchase_orders')
    op.drop_index('ix_automotive_procurement_v1_po_partner_id', table_name='automotive_procurement_v1_purchase_orders')
    op.drop_table('automotive_procurement_v1_purchase_orders')
    # ### end Alembic commands ###
