"""recommendation_engine_v1

Revision ID: 0b0c0c734d6e
Revises: 1eadc101eebb
Create Date: 2026-07-13 13:18:20.915414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b0c0c734d6e'
down_revision: Union[str, None] = '1eadc101eebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_engine_v1_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sales_lead_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('previous_interactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max', name='ck_recommendation_engine_v1_profiles_budget'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_lead_id'], ['ai_sales_agent_v1_sales_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_engine_v1_profiles_company', 'recommendation_engine_v1_profiles', ['company_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_profiles_sales_lead', 'recommendation_engine_v1_profiles', ['sales_lead_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_profiles_tenant', 'recommendation_engine_v1_profiles', ['tenant_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_profiles_user', 'recommendation_engine_v1_profiles', ['user_id'], unique=False)
    op.create_table('recommendation_engine_v1_history',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=40), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_recommendation_engine_v1_history_confidence'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['recommendation_engine_v1_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_engine_v1_history_profile', 'recommendation_engine_v1_history', ['profile_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_history_tenant', 'recommendation_engine_v1_history', ['tenant_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_history_type', 'recommendation_engine_v1_history', ['recommendation_type'], unique=False)
    op.create_table('recommendation_engine_v1_feedback',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_recommendation_engine_v1_feedback_rating'),
    sa.ForeignKeyConstraint(['history_id'], ['recommendation_engine_v1_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['recommendation_engine_v1_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', 'created_by', name='uq_recommendation_engine_v1_feedback_history_user')
    )
    op.create_index('ix_recommendation_engine_v1_feedback_history', 'recommendation_engine_v1_feedback', ['history_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_feedback_profile', 'recommendation_engine_v1_feedback', ['profile_id'], unique=False)
    op.create_index('ix_recommendation_engine_v1_feedback_tenant', 'recommendation_engine_v1_feedback', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_engine_v1_feedback_tenant', table_name='recommendation_engine_v1_feedback')
    op.drop_index('ix_recommendation_engine_v1_feedback_profile', table_name='recommendation_engine_v1_feedback')
    op.drop_index('ix_recommendation_engine_v1_feedback_history', table_name='recommendation_engine_v1_feedback')
    op.drop_table('recommendation_engine_v1_feedback')
    op.drop_index('ix_recommendation_engine_v1_history_type', table_name='recommendation_engine_v1_history')
    op.drop_index('ix_recommendation_engine_v1_history_tenant', table_name='recommendation_engine_v1_history')
    op.drop_index('ix_recommendation_engine_v1_history_profile', table_name='recommendation_engine_v1_history')
    op.drop_table('recommendation_engine_v1_history')
    op.drop_index('ix_recommendation_engine_v1_profiles_user', table_name='recommendation_engine_v1_profiles')
    op.drop_index('ix_recommendation_engine_v1_profiles_tenant', table_name='recommendation_engine_v1_profiles')
    op.drop_index('ix_recommendation_engine_v1_profiles_sales_lead', table_name='recommendation_engine_v1_profiles')
    op.drop_index('ix_recommendation_engine_v1_profiles_company', table_name='recommendation_engine_v1_profiles')
    op.drop_table('recommendation_engine_v1_profiles')
    # ### end Alembic commands ###
