"""treasury_engine_foundation

Revision ID: 0d20fc677b5d
Revises: 6b20bbb2d338
Create Date: 2026-07-12 17:34:55.406399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d20fc677b5d'
down_revision: Union[str, None] = '6b20bbb2d338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_engine_accounts',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reserved_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_treasury_engine_accounts_balance'),
    sa.CheckConstraint('reserved_balance <= balance', name='ck_treasury_engine_accounts_reserved_lte_balance'),
    sa.CheckConstraint('reserved_balance >= 0', name='ck_treasury_engine_accounts_reserved_balance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'asset', name='uq_treasury_engine_accounts_code_asset')
    )
    op.create_index('ix_treasury_engine_accounts_asset', 'treasury_engine_accounts', ['asset'], unique=False)
    op.create_index('ix_treasury_engine_accounts_status', 'treasury_engine_accounts', ['status'], unique=False)
    op.create_table('treasury_engine_liquidity_reservations',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_treasury_engine_reservations_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['treasury_engine_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treasury_engine_reservations_account_id', 'treasury_engine_liquidity_reservations', ['account_id'], unique=False)
    op.create_index('ix_treasury_engine_reservations_deal_id', 'treasury_engine_liquidity_reservations', ['deal_id'], unique=False)
    op.create_index('ix_treasury_engine_reservations_status', 'treasury_engine_liquidity_reservations', ['status'], unique=False)
    op.create_table('treasury_engine_transfers',
    sa.Column('from_account_id', sa.UUID(), nullable=False),
    sa.Column('to_account_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transfer_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_treasury_engine_transfers_amount'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_account_id'], ['treasury_engine_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['treasury_engine_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treasury_engine_transfers_deal_id', 'treasury_engine_transfers', ['deal_id'], unique=False)
    op.create_index('ix_treasury_engine_transfers_from_account_id', 'treasury_engine_transfers', ['from_account_id'], unique=False)
    op.create_index('ix_treasury_engine_transfers_status', 'treasury_engine_transfers', ['status'], unique=False)
    op.create_index('ix_treasury_engine_transfers_to_account_id', 'treasury_engine_transfers', ['to_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treasury_engine_transfers_to_account_id', table_name='treasury_engine_transfers')
    op.drop_index('ix_treasury_engine_transfers_status', table_name='treasury_engine_transfers')
    op.drop_index('ix_treasury_engine_transfers_from_account_id', table_name='treasury_engine_transfers')
    op.drop_index('ix_treasury_engine_transfers_deal_id', table_name='treasury_engine_transfers')
    op.drop_table('treasury_engine_transfers')
    op.drop_index('ix_treasury_engine_reservations_status', table_name='treasury_engine_liquidity_reservations')
    op.drop_index('ix_treasury_engine_reservations_deal_id', table_name='treasury_engine_liquidity_reservations')
    op.drop_index('ix_treasury_engine_reservations_account_id', table_name='treasury_engine_liquidity_reservations')
    op.drop_table('treasury_engine_liquidity_reservations')
    op.drop_index('ix_treasury_engine_accounts_status', table_name='treasury_engine_accounts')
    op.drop_index('ix_treasury_engine_accounts_asset', table_name='treasury_engine_accounts')
    op.drop_table('treasury_engine_accounts')
    # ### end Alembic commands ###
