"""ai_skill_engine_v1

Revision ID: 0f9ead96c805
Revises: ac3f059af508
Create Date: 2026-07-13 11:07:26.321542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f9ead96c805'
down_revision: Union[str, None] = 'ac3f059af508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_skill_engine_v1_handoffs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('session_ref', sa.String(length=120), nullable=True),
    sa.Column('skill_code', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_skill_engine_v1_handoffs_manager', 'ai_skill_engine_v1_handoffs', ['manager_id'], unique=False)
    op.create_index('ix_ai_skill_engine_v1_handoffs_status', 'ai_skill_engine_v1_handoffs', ['status'], unique=False)
    op.create_index('ix_ai_skill_engine_v1_handoffs_tenant', 'ai_skill_engine_v1_handoffs', ['tenant_id'], unique=False)
    op.create_table('ai_skill_engine_v1_skill_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('skill_code', sa.String(length=40), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'skill_code', name='uq_ai_skill_engine_v1_skill_configs_tenant_code')
    )
    op.create_index('ix_ai_skill_engine_v1_skill_configs_code', 'ai_skill_engine_v1_skill_configs', ['skill_code'], unique=False)
    op.create_index('ix_ai_skill_engine_v1_skill_configs_tenant', 'ai_skill_engine_v1_skill_configs', ['tenant_id'], unique=False)
    op.create_table('ai_skill_engine_v1_tenant_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('dealership_name', sa.String(length=255), nullable=False),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.Column('escalation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manager_handoff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_ai_skill_engine_v1_profiles_tenant')
    )
    op.create_index('ix_ai_skill_engine_v1_profiles_company', 'ai_skill_engine_v1_tenant_profiles', ['company_id'], unique=False)
    op.create_table('ai_skill_engine_v1_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('skill_code', sa.String(length=40), nullable=False),
    sa.Column('session_ref', sa.String(length=120), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('handoff_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handoff_id'], ['ai_skill_engine_v1_handoffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_skill_engine_v1_executions_session', 'ai_skill_engine_v1_executions', ['session_ref'], unique=False)
    op.create_index('ix_ai_skill_engine_v1_executions_skill', 'ai_skill_engine_v1_executions', ['skill_code'], unique=False)
    op.create_index('ix_ai_skill_engine_v1_executions_tenant', 'ai_skill_engine_v1_executions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_skill_engine_v1_executions_tenant', table_name='ai_skill_engine_v1_executions')
    op.drop_index('ix_ai_skill_engine_v1_executions_skill', table_name='ai_skill_engine_v1_executions')
    op.drop_index('ix_ai_skill_engine_v1_executions_session', table_name='ai_skill_engine_v1_executions')
    op.drop_table('ai_skill_engine_v1_executions')
    op.drop_index('ix_ai_skill_engine_v1_profiles_company', table_name='ai_skill_engine_v1_tenant_profiles')
    op.drop_table('ai_skill_engine_v1_tenant_profiles')
    op.drop_index('ix_ai_skill_engine_v1_skill_configs_tenant', table_name='ai_skill_engine_v1_skill_configs')
    op.drop_index('ix_ai_skill_engine_v1_skill_configs_code', table_name='ai_skill_engine_v1_skill_configs')
    op.drop_table('ai_skill_engine_v1_skill_configs')
    op.drop_index('ix_ai_skill_engine_v1_handoffs_tenant', table_name='ai_skill_engine_v1_handoffs')
    op.drop_index('ix_ai_skill_engine_v1_handoffs_status', table_name='ai_skill_engine_v1_handoffs')
    op.drop_index('ix_ai_skill_engine_v1_handoffs_manager', table_name='ai_skill_engine_v1_handoffs')
    op.drop_table('ai_skill_engine_v1_handoffs')
    # ### end Alembic commands ###
