"""marketing_automation_engine_v1

Revision ID: 15a5b4ac7814
Revises: 6d3b487773e2
Create Date: 2026-07-13 09:45:04.299538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15a5b4ac7814'
down_revision: Union[str, None] = '6d3b487773e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_automation_engine_v1_campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('auto_marketing_campaign_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auto_marketing_campaign_id'], ['auto_marketing_engine_v1_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_automation_engine_v1_campaigns_car', 'marketing_automation_engine_v1_campaigns', ['car_id'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_campaigns_owner', 'marketing_automation_engine_v1_campaigns', ['owner_user_id'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_campaigns_status', 'marketing_automation_engine_v1_campaigns', ['status'], unique=False)
    op.create_table('marketing_automation_engine_v1_repost_rules',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('source_media_path', sa.String(length=500), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('max_reposts', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=False),
    sa.Column('optimize_images', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_reposted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_repost_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_automation_engine_v1_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_automation_engine_v1_repost_active', 'marketing_automation_engine_v1_repost_rules', ['is_active'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_repost_campaign', 'marketing_automation_engine_v1_repost_rules', ['campaign_id'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_repost_next', 'marketing_automation_engine_v1_repost_rules', ['next_repost_at'], unique=False)
    op.create_table('marketing_automation_engine_v1_scheduled_posts',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('repost_rule_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_media_path', sa.String(length=500), nullable=True),
    sa.Column('processed_media_path', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('repost_generation', sa.Integer(), nullable=False),
    sa.Column('target_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_automation_engine_v1_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publication_id'], ['auto_marketing_engine_v1_publications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repost_rule_id'], ['marketing_automation_engine_v1_repost_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_automation_engine_v1_posts_campaign', 'marketing_automation_engine_v1_scheduled_posts', ['campaign_id'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_posts_car', 'marketing_automation_engine_v1_scheduled_posts', ['car_id'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_posts_channel', 'marketing_automation_engine_v1_scheduled_posts', ['channel'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_posts_scheduled', 'marketing_automation_engine_v1_scheduled_posts', ['scheduled_at'], unique=False)
    op.create_index('ix_marketing_automation_engine_v1_posts_status', 'marketing_automation_engine_v1_scheduled_posts', ['status'], unique=False)
    op.create_table('marketing_automation_engine_v1_processed_media',
    sa.Column('scheduled_post_id', sa.UUID(), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=False),
    sa.Column('watermark_applied', sa.Boolean(), nullable=False),
    sa.Column('optimized', sa.Boolean(), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=True),
    sa.Column('processed_size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_post_id'], ['marketing_automation_engine_v1_scheduled_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_automation_engine_v1_media_post', 'marketing_automation_engine_v1_processed_media', ['scheduled_post_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_marketing_automation_engine_v1_media_post', table_name='marketing_automation_engine_v1_processed_media')
    op.drop_table('marketing_automation_engine_v1_processed_media')
    op.drop_index('ix_marketing_automation_engine_v1_posts_status', table_name='marketing_automation_engine_v1_scheduled_posts')
    op.drop_index('ix_marketing_automation_engine_v1_posts_scheduled', table_name='marketing_automation_engine_v1_scheduled_posts')
    op.drop_index('ix_marketing_automation_engine_v1_posts_channel', table_name='marketing_automation_engine_v1_scheduled_posts')
    op.drop_index('ix_marketing_automation_engine_v1_posts_car', table_name='marketing_automation_engine_v1_scheduled_posts')
    op.drop_index('ix_marketing_automation_engine_v1_posts_campaign', table_name='marketing_automation_engine_v1_scheduled_posts')
    op.drop_table('marketing_automation_engine_v1_scheduled_posts')
    op.drop_index('ix_marketing_automation_engine_v1_repost_next', table_name='marketing_automation_engine_v1_repost_rules')
    op.drop_index('ix_marketing_automation_engine_v1_repost_campaign', table_name='marketing_automation_engine_v1_repost_rules')
    op.drop_index('ix_marketing_automation_engine_v1_repost_active', table_name='marketing_automation_engine_v1_repost_rules')
    op.drop_table('marketing_automation_engine_v1_repost_rules')
    op.drop_index('ix_marketing_automation_engine_v1_campaigns_status', table_name='marketing_automation_engine_v1_campaigns')
    op.drop_index('ix_marketing_automation_engine_v1_campaigns_owner', table_name='marketing_automation_engine_v1_campaigns')
    op.drop_index('ix_marketing_automation_engine_v1_campaigns_car', table_name='marketing_automation_engine_v1_campaigns')
    op.drop_table('marketing_automation_engine_v1_campaigns')
    # ### end Alembic commands ###
