"""vin_engine_v1

Revision ID: 16a1147c7485
Revises: aada79cbcac2
Create Date: 2026-07-13 09:14:36.293598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16a1147c7485'
down_revision: Union[str, None] = 'aada79cbcac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vin_engine_v1_vin_reports',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('decoded_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vehicle_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auction_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', name='uq_vin_engine_v1_vin_reports_vin')
    )
    op.create_index('ix_vin_engine_v1_vin_reports_car', 'vin_engine_v1_vin_reports', ['car_id'], unique=False)
    op.create_index('ix_vin_engine_v1_vin_reports_valid', 'vin_engine_v1_vin_reports', ['is_valid'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_vin_engine_v1_vin_reports_valid', table_name='vin_engine_v1_vin_reports')
    op.drop_index('ix_vin_engine_v1_vin_reports_car', table_name='vin_engine_v1_vin_reports')
    op.drop_table('vin_engine_v1_vin_reports')
    # ### end Alembic commands ###
