"""automotive_analytics_engine_v1

Revision ID: 187d936210b5
Revises: 85c051138273
Create Date: 2026-07-12 22:54:53.674031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187d936210b5'
down_revision: Union[str, None] = '85c051138273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_analytics_v1_sales_metrics',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('new_leads', sa.Integer(), nullable=False),
    sa.Column('contacted_count', sa.Integer(), nullable=False),
    sa.Column('test_drive_count', sa.Integer(), nullable=False),
    sa.Column('negotiation_count', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('contract_signed_count', sa.Integer(), nullable=False),
    sa.Column('paid_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('total_pipeline_budget', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_analytics_v1_sm_metric_date', 'automotive_analytics_v1_sales_metrics', ['metric_date'], unique=False)
    op.create_table('automotive_analytics_v1_inventory_metrics',
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('days_in_inventory', sa.Integer(), nullable=True),
    sa.Column('aging_bucket', sa.String(length=20), nullable=True),
    sa.Column('vehicle_status', sa.String(length=30), nullable=True),
    sa.Column('inventory_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('in_stock_count', sa.Integer(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_analytics_v1_im_aging_bucket', 'automotive_analytics_v1_inventory_metrics', ['aging_bucket'], unique=False)
    op.create_index('ix_automotive_analytics_v1_im_metric_date', 'automotive_analytics_v1_inventory_metrics', ['metric_date'], unique=False)
    op.create_index('ix_automotive_analytics_v1_im_vehicle_id', 'automotive_analytics_v1_inventory_metrics', ['vehicle_id'], unique=False)
    op.create_table('automotive_analytics_v1_profitability_metrics',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('margin_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('roi_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('margin_percent >= -100', name='ck_automotive_analytics_v1_pm_margin'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_analytics_v1_pm_metric_date', 'automotive_analytics_v1_profitability_metrics', ['metric_date'], unique=False)
    op.create_index('ix_automotive_analytics_v1_pm_vehicle_id', 'automotive_analytics_v1_profitability_metrics', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automotive_analytics_v1_pm_vehicle_id', table_name='automotive_analytics_v1_profitability_metrics')
    op.drop_index('ix_automotive_analytics_v1_pm_metric_date', table_name='automotive_analytics_v1_profitability_metrics')
    op.drop_table('automotive_analytics_v1_profitability_metrics')
    op.drop_index('ix_automotive_analytics_v1_im_vehicle_id', table_name='automotive_analytics_v1_inventory_metrics')
    op.drop_index('ix_automotive_analytics_v1_im_metric_date', table_name='automotive_analytics_v1_inventory_metrics')
    op.drop_index('ix_automotive_analytics_v1_im_aging_bucket', table_name='automotive_analytics_v1_inventory_metrics')
    op.drop_table('automotive_analytics_v1_inventory_metrics')
    op.drop_index('ix_automotive_analytics_v1_sm_metric_date', table_name='automotive_analytics_v1_sales_metrics')
    op.drop_table('automotive_analytics_v1_sales_metrics')
    # ### end Alembic commands ###
