"""ai_sales_assistant_v1

Revision ID: 1c972a907102
Revises: 15a5b4ac7814
Create Date: 2026-07-13 09:51:56.177112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c972a907102'
down_revision: Union[str, None] = '15a5b4ac7814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sales_assistant_v1_sessions',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('contact_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduling_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('last_intent', sa.String(length=50), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_assistant_v1_sessions_car', 'ai_sales_assistant_v1_sessions', ['car_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_sessions_lead', 'ai_sales_assistant_v1_sessions', ['lead_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_sessions_manager', 'ai_sales_assistant_v1_sessions', ['assigned_manager_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_sessions_status', 'ai_sales_assistant_v1_sessions', ['status'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_sessions_telegram', 'ai_sales_assistant_v1_sessions', ['telegram_user_id'], unique=False)
    op.create_table('ai_sales_assistant_v1_handoffs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sales_assistant_v1_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_assistant_v1_handoffs_manager', 'ai_sales_assistant_v1_handoffs', ['manager_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_handoffs_session', 'ai_sales_assistant_v1_handoffs', ['session_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_handoffs_status', 'ai_sales_assistant_v1_handoffs', ['status'], unique=False)
    op.create_table('ai_sales_assistant_v1_meetings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sales_assistant_v1_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_assistant_v1_meetings_scheduled', 'ai_sales_assistant_v1_meetings', ['scheduled_at'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_meetings_session', 'ai_sales_assistant_v1_meetings', ['session_id'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_meetings_status', 'ai_sales_assistant_v1_meetings', ['status'], unique=False)
    op.create_table('ai_sales_assistant_v1_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sales_assistant_v1_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_assistant_v1_messages_role', 'ai_sales_assistant_v1_messages', ['role'], unique=False)
    op.create_index('ix_ai_sales_assistant_v1_messages_session', 'ai_sales_assistant_v1_messages', ['session_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_ai_sales_assistant_v1_messages_session', table_name='ai_sales_assistant_v1_messages')
    op.drop_index('ix_ai_sales_assistant_v1_messages_role', table_name='ai_sales_assistant_v1_messages')
    op.drop_table('ai_sales_assistant_v1_messages')
    op.drop_index('ix_ai_sales_assistant_v1_meetings_status', table_name='ai_sales_assistant_v1_meetings')
    op.drop_index('ix_ai_sales_assistant_v1_meetings_session', table_name='ai_sales_assistant_v1_meetings')
    op.drop_index('ix_ai_sales_assistant_v1_meetings_scheduled', table_name='ai_sales_assistant_v1_meetings')
    op.drop_table('ai_sales_assistant_v1_meetings')
    op.drop_index('ix_ai_sales_assistant_v1_handoffs_status', table_name='ai_sales_assistant_v1_handoffs')
    op.drop_index('ix_ai_sales_assistant_v1_handoffs_session', table_name='ai_sales_assistant_v1_handoffs')
    op.drop_index('ix_ai_sales_assistant_v1_handoffs_manager', table_name='ai_sales_assistant_v1_handoffs')
    op.drop_table('ai_sales_assistant_v1_handoffs')
    op.drop_index('ix_ai_sales_assistant_v1_sessions_telegram', table_name='ai_sales_assistant_v1_sessions')
    op.drop_index('ix_ai_sales_assistant_v1_sessions_status', table_name='ai_sales_assistant_v1_sessions')
    op.drop_index('ix_ai_sales_assistant_v1_sessions_manager', table_name='ai_sales_assistant_v1_sessions')
    op.drop_index('ix_ai_sales_assistant_v1_sessions_lead', table_name='ai_sales_assistant_v1_sessions')
    op.drop_index('ix_ai_sales_assistant_v1_sessions_car', table_name='ai_sales_assistant_v1_sessions')
    op.drop_table('ai_sales_assistant_v1_sessions')
    # ### end Alembic commands ###
