"""ai_sales_agent_v1

Revision ID: 1eadc101eebb
Revises: d7506c3a0146
Create Date: 2026-07-13 13:04:20.284111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eadc101eebb'
down_revision: Union[str, None] = 'd7506c3a0146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sales_agent_v1_sales_leads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('automation_lead_id', sa.UUID(), nullable=True),
    sa.Column('marketplace_listing_id', sa.UUID(), nullable=True),
    sa.Column('recommended_car_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('assigned_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qualification_score >= 0 AND qualification_score <= 100', name='ck_ai_sales_agent_v1_lead_qualification_score'),
    sa.ForeignKeyConstraint(['automation_lead_id'], ['lead_automation_engine_v1_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketplace_listing_id'], ['lead_marketplace_engine_v1_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_agent_v1_leads_automation', 'ai_sales_agent_v1_sales_leads', ['automation_lead_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_company', 'ai_sales_agent_v1_sales_leads', ['company_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_follow_up', 'ai_sales_agent_v1_sales_leads', ['next_follow_up_at'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_manager', 'ai_sales_agent_v1_sales_leads', ['assigned_manager_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_marketplace', 'ai_sales_agent_v1_sales_leads', ['marketplace_listing_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_status', 'ai_sales_agent_v1_sales_leads', ['status'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_leads_tenant', 'ai_sales_agent_v1_sales_leads', ['tenant_id'], unique=False)
    op.create_table('ai_sales_agent_v1_customer_preferences',
    sa.Column('sales_lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('preferred_makes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_year', sa.Integer(), nullable=True),
    sa.Column('max_year', sa.Integer(), nullable=True),
    sa.Column('max_mileage', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_year IS NULL OR max_year IS NULL OR min_year <= max_year', name='ck_ai_sales_agent_v1_prefs_year'),
    sa.ForeignKeyConstraint(['sales_lead_id'], ['ai_sales_agent_v1_sales_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_lead_id', name='uq_ai_sales_agent_v1_prefs_lead')
    )
    op.create_index('ix_ai_sales_agent_v1_prefs_tenant', 'ai_sales_agent_v1_customer_preferences', ['tenant_id'], unique=False)
    op.create_table('ai_sales_agent_v1_sales_conversations',
    sa.Column('sales_lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('intent_detected', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_lead_id'], ['ai_sales_agent_v1_sales_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_agent_v1_conversations_lead', 'ai_sales_agent_v1_sales_conversations', ['sales_lead_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_conversations_tenant', 'ai_sales_agent_v1_sales_conversations', ['tenant_id'], unique=False)
    op.create_table('ai_sales_agent_v1_sales_offers',
    sa.Column('sales_lead_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('offer_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_ai_sales_agent_v1_offer_discount'),
    sa.CheckConstraint('offer_price >= 0', name='ck_ai_sales_agent_v1_offer_price'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document_engine_v1_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_lead_id'], ['ai_sales_agent_v1_sales_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_sales_agent_v1_offers_car', 'ai_sales_agent_v1_sales_offers', ['car_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_offers_document', 'ai_sales_agent_v1_sales_offers', ['document_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_offers_lead', 'ai_sales_agent_v1_sales_offers', ['sales_lead_id'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_offers_status', 'ai_sales_agent_v1_sales_offers', ['status'], unique=False)
    op.create_index('ix_ai_sales_agent_v1_offers_tenant', 'ai_sales_agent_v1_sales_offers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_sales_agent_v1_offers_tenant', table_name='ai_sales_agent_v1_sales_offers')
    op.drop_index('ix_ai_sales_agent_v1_offers_status', table_name='ai_sales_agent_v1_sales_offers')
    op.drop_index('ix_ai_sales_agent_v1_offers_lead', table_name='ai_sales_agent_v1_sales_offers')
    op.drop_index('ix_ai_sales_agent_v1_offers_document', table_name='ai_sales_agent_v1_sales_offers')
    op.drop_index('ix_ai_sales_agent_v1_offers_car', table_name='ai_sales_agent_v1_sales_offers')
    op.drop_table('ai_sales_agent_v1_sales_offers')
    op.drop_index('ix_ai_sales_agent_v1_conversations_tenant', table_name='ai_sales_agent_v1_sales_conversations')
    op.drop_index('ix_ai_sales_agent_v1_conversations_lead', table_name='ai_sales_agent_v1_sales_conversations')
    op.drop_table('ai_sales_agent_v1_sales_conversations')
    op.drop_index('ix_ai_sales_agent_v1_prefs_tenant', table_name='ai_sales_agent_v1_customer_preferences')
    op.drop_table('ai_sales_agent_v1_customer_preferences')
    op.drop_index('ix_ai_sales_agent_v1_leads_tenant', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_status', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_marketplace', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_manager', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_follow_up', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_company', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_index('ix_ai_sales_agent_v1_leads_automation', table_name='ai_sales_agent_v1_sales_leads')
    op.drop_table('ai_sales_agent_v1_sales_leads')
    # ### end Alembic commands ###
