"""commission_engine_foundation

Revision ID: 1ff9e7e214f5
Revises: caddeea0c765
Create Date: 2026-07-12 17:03:07.439087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff9e7e214f5'
down_revision: Union[str, None] = 'caddeea0c765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_engine_commissions',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_id', sa.BigInteger(), nullable=True),
    sa.Column('commission_type', sa.String(length=30), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_commission_engine_amount_non_negative'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_engine_deal_id', 'commission_engine_commissions', ['deal_id'], unique=False)
    op.create_index('ix_commission_engine_manager_id', 'commission_engine_commissions', ['manager_id'], unique=False)
    op.create_index('ix_commission_engine_partner_id', 'commission_engine_commissions', ['partner_id'], unique=False)
    op.create_index('ix_commission_engine_status', 'commission_engine_commissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commission_engine_status', table_name='commission_engine_commissions')
    op.drop_index('ix_commission_engine_partner_id', table_name='commission_engine_commissions')
    op.drop_index('ix_commission_engine_manager_id', table_name='commission_engine_commissions')
    op.drop_index('ix_commission_engine_deal_id', table_name='commission_engine_commissions')
    op.drop_table('commission_engine_commissions')
    # ### end Alembic commands ###
