"""otc_matching_engine_v1

Revision ID: 2cd3604be971
Revises: 9658b0f2b04c
Create Date: 2026-07-12 20:10:54.538264

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "2cd3604be971"
down_revision: Union[str, None] = "9658b0f2b04c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("otc.order.created", "Emit or subscribe to OTC order created events"),
    ("otc.quote.received", "Emit or subscribe to OTC quote received events"),
    ("otc.match.created", "Emit or subscribe to OTC match created events"),
    ("otc.order.filled", "Emit or subscribe to OTC order filled events"),
    ("otc.execution.failed", "Emit or subscribe to OTC execution failed events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ACCOUNTANT": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
}


def _seed_otc_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otc_v1_orders',
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_limit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('matching_strategy', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_otc_v1_orders_amount'),
    sa.CheckConstraint('filled_amount >= 0', name='ck_otc_v1_orders_filled'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_otc_v1_orders_remaining'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otc_v1_orders_asset', 'otc_v1_orders', ['asset'], unique=False)
    op.create_index('ix_otc_v1_orders_deal_id', 'otc_v1_orders', ['deal_id'], unique=False)
    op.create_index('ix_otc_v1_orders_order_type', 'otc_v1_orders', ['order_type'], unique=False)
    op.create_index('ix_otc_v1_orders_partner_id', 'otc_v1_orders', ['partner_id'], unique=False)
    op.create_index('ix_otc_v1_orders_status', 'otc_v1_orders', ['status'], unique=False)
    op.create_table('otc_v1_quotes',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_otc_v1_quotes_amount'),
    sa.CheckConstraint('price > 0', name='ck_otc_v1_quotes_price'),
    sa.ForeignKeyConstraint(['order_id'], ['otc_v1_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otc_v1_quotes_order_id', 'otc_v1_quotes', ['order_id'], unique=False)
    op.create_index('ix_otc_v1_quotes_partner_id', 'otc_v1_quotes', ['partner_id'], unique=False)
    op.create_index('ix_otc_v1_quotes_status', 'otc_v1_quotes', ['status'], unique=False)
    op.create_table('otc_v1_matches',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('matched_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('matched_amount > 0', name='ck_otc_v1_matches_amount'),
    sa.CheckConstraint('matched_price > 0', name='ck_otc_v1_matches_price'),
    sa.ForeignKeyConstraint(['order_id'], ['otc_v1_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['otc_v1_quotes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otc_v1_matches_order_id', 'otc_v1_matches', ['order_id'], unique=False)
    op.create_index('ix_otc_v1_matches_partner_id', 'otc_v1_matches', ['partner_id'], unique=False)
    op.create_index('ix_otc_v1_matches_quote_id', 'otc_v1_matches', ['quote_id'], unique=False)
    op.create_index('ix_otc_v1_matches_status', 'otc_v1_matches', ['status'], unique=False)
    op.create_table('otc_v1_execution_routes',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('liquidity_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_otc_v1_execution_routes_amount'),
    sa.ForeignKeyConstraint(['match_id'], ['otc_v1_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['otc_v1_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otc_v1_execution_routes_order_id', 'otc_v1_execution_routes', ['order_id'], unique=False)
    op.create_index('ix_otc_v1_execution_routes_partner_id', 'otc_v1_execution_routes', ['partner_id'], unique=False)
    op.create_index('ix_otc_v1_execution_routes_status', 'otc_v1_execution_routes', ['status'], unique=False)
    op.create_index('ix_otc_v1_execution_routes_step_order', 'otc_v1_execution_routes', ['step_order'], unique=False)
    op.create_table('otc_v1_fill_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('fill_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fill_amount > 0', name='ck_otc_v1_fill_history_amount'),
    sa.ForeignKeyConstraint(['match_id'], ['otc_v1_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['otc_v1_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['otc_v1_execution_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otc_v1_fill_history_match_id', 'otc_v1_fill_history', ['match_id'], unique=False)
    op.create_index('ix_otc_v1_fill_history_order_id', 'otc_v1_fill_history', ['order_id'], unique=False)
    op.create_index('ix_otc_v1_fill_history_partner_id', 'otc_v1_fill_history', ['partner_id'], unique=False)
    op.create_index('ix_otc_v1_fill_history_route_id', 'otc_v1_fill_history', ['route_id'], unique=False)
    _seed_otc_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otc_v1_fill_history_route_id', table_name='otc_v1_fill_history')
    op.drop_index('ix_otc_v1_fill_history_partner_id', table_name='otc_v1_fill_history')
    op.drop_index('ix_otc_v1_fill_history_order_id', table_name='otc_v1_fill_history')
    op.drop_index('ix_otc_v1_fill_history_match_id', table_name='otc_v1_fill_history')
    op.drop_table('otc_v1_fill_history')
    op.drop_index('ix_otc_v1_execution_routes_step_order', table_name='otc_v1_execution_routes')
    op.drop_index('ix_otc_v1_execution_routes_status', table_name='otc_v1_execution_routes')
    op.drop_index('ix_otc_v1_execution_routes_partner_id', table_name='otc_v1_execution_routes')
    op.drop_index('ix_otc_v1_execution_routes_order_id', table_name='otc_v1_execution_routes')
    op.drop_table('otc_v1_execution_routes')
    op.drop_index('ix_otc_v1_matches_status', table_name='otc_v1_matches')
    op.drop_index('ix_otc_v1_matches_quote_id', table_name='otc_v1_matches')
    op.drop_index('ix_otc_v1_matches_partner_id', table_name='otc_v1_matches')
    op.drop_index('ix_otc_v1_matches_order_id', table_name='otc_v1_matches')
    op.drop_table('otc_v1_matches')
    op.drop_index('ix_otc_v1_quotes_status', table_name='otc_v1_quotes')
    op.drop_index('ix_otc_v1_quotes_partner_id', table_name='otc_v1_quotes')
    op.drop_index('ix_otc_v1_quotes_order_id', table_name='otc_v1_quotes')
    op.drop_table('otc_v1_quotes')
    op.drop_index('ix_otc_v1_orders_status', table_name='otc_v1_orders')
    op.drop_index('ix_otc_v1_orders_partner_id', table_name='otc_v1_orders')
    op.drop_index('ix_otc_v1_orders_order_type', table_name='otc_v1_orders')
    op.drop_index('ix_otc_v1_orders_deal_id', table_name='otc_v1_orders')
    op.drop_index('ix_otc_v1_orders_asset', table_name='otc_v1_orders')
    op.drop_table('otc_v1_orders')
    # ### end Alembic commands ###
