"""deal_engine_foundation

Revision ID: 2d87a4df926e
Revises: 411b8f2abda8
Create Date: 2026-07-12 16:54:07.967099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d87a4df926e'
down_revision: Union[str, None] = '411b8f2abda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_engine_deals',
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_in_type', sa.String(length=20), nullable=True),
    sa.Column('asset_in_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('asset_out_type', sa.String(length=20), nullable=True),
    sa.Column('asset_out_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('commission_currency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_engine_deals_client_id', 'deal_engine_deals', ['client_id'], unique=False)
    op.create_index('ix_deal_engine_deals_manager_id', 'deal_engine_deals', ['manager_id'], unique=False)
    op.create_index('ix_deal_engine_deals_partner_id', 'deal_engine_deals', ['partner_id'], unique=False)
    op.create_index('ix_deal_engine_deals_status', 'deal_engine_deals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deal_engine_deals_status', table_name='deal_engine_deals')
    op.drop_index('ix_deal_engine_deals_partner_id', table_name='deal_engine_deals')
    op.drop_index('ix_deal_engine_deals_manager_id', table_name='deal_engine_deals')
    op.drop_index('ix_deal_engine_deals_client_id', table_name='deal_engine_deals')
    op.drop_table('deal_engine_deals')
    # ### end Alembic commands ###
