"""initial_postgres_schema

Revision ID: 37dc2741863e
Revises: 
Create Date: 2026-07-12 15:21:48.062849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37dc2741863e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ai_agents_code')
    )
    op.create_index('ix_ai_agents_active', 'ai_agents', ['active'], unique=False)
    op.create_index('ix_ai_agents_code', 'ai_agents', ['code'], unique=False)
    op.create_table('commission_rules',
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('commission_type', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('rate_type', sa.String(length=16), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_rules_active', 'commission_rules', ['active'], unique=False)
    op.create_index('ix_commission_rules_type', 'commission_rules', ['commission_type'], unique=False)
    op.create_table('finance_accounts',
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_accounts_status', 'finance_accounts', ['status'], unique=False)
    op.create_index('ix_finance_accounts_type', 'finance_accounts', ['account_type'], unique=False)
    op.create_table('rbac_permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('parent_code', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['rbac_permissions.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_rbac_permissions_level', 'rbac_permissions', ['level'], unique=False)
    op.create_index('ix_rbac_permissions_module', 'rbac_permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', name='uq_roles_role_name')
    )
    op.create_index('ix_roles_role_name', 'roles', ['role_name'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('ai_agent_memory',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'agent_id', 'memory_key')
    )
    op.create_index('ix_ai_agent_memory_user_id', 'ai_agent_memory', ['user_id'], unique=False)
    op.create_table('ai_agent_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('context_depth', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'agent_id')
    )
    op.create_index('ix_ai_agent_settings_user_id', 'ai_agent_settings', ['user_id'], unique=False)
    op.create_table('ai_dialogs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_dialogs_agent_id', 'ai_dialogs', ['agent_id'], unique=False)
    op.create_index('ix_ai_dialogs_user_id', 'ai_dialogs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_module', 'audit_logs', ['module'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('end_time', sa.String(length=32), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('remind_before', sa.Integer(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('repeat_rule', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_calendar_events_creator_id', 'calendar_events', ['creator_id'], unique=False)
    op.create_index('ix_calendar_events_department', 'calendar_events', ['department'], unique=False)
    op.create_index('ix_calendar_events_module', 'calendar_events', ['module'], unique=False)
    op.create_index('ix_calendar_events_owner_id', 'calendar_events', ['owner_id'], unique=False)
    op.create_index('ix_calendar_events_public_id', 'calendar_events', ['public_id'], unique=True)
    op.create_index('ix_calendar_events_start', 'calendar_events', ['start_datetime'], unique=False)
    op.create_index('ix_calendar_events_status', 'calendar_events', ['status'], unique=False)
    op.create_index('ix_calendar_events_visibility', 'calendar_events', ['visibility'], unique=False)
    op.create_table('deals',
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('deal_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('partner_user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('legacy_ref_type', sa.String(length=64), nullable=True),
    sa.Column('legacy_ref_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_deals_legacy_ref', 'deals', ['legacy_ref_type', 'legacy_ref_id'], unique=False)
    op.create_index('ix_deals_manager_id', 'deals', ['manager_id'], unique=False)
    op.create_index('ix_deals_module', 'deals', ['module'], unique=False)
    op.create_index('ix_deals_owner_id', 'deals', ['owner_id'], unique=False)
    op.create_index('ix_deals_public_id', 'deals', ['public_id'], unique=True)
    op.create_index('ix_deals_status', 'deals', ['status'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('transaction_type', sa.String(length=64), nullable=False),
    sa.Column('debit_account_id', sa.UUID(), nullable=True),
    sa.Column('credit_account_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credit_account_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_transactions_reference', 'finance_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_finance_transactions_status', 'finance_transactions', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('is_reminder', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_category', 'notifications', ['category'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_module', 'notifications', ['module'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('partners',
    sa.Column('partner_type', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_partners_active', 'partners', ['active'], unique=False)
    op.create_index('ix_partners_company', 'partners', ['company_name'], unique=False)
    op.create_index('ix_partners_public_id', 'partners', ['public_id'], unique=True)
    op.create_index('ix_partners_telegram_id', 'partners', ['telegram_id'], unique=False)
    op.create_index('ix_partners_type', 'partners', ['partner_type'], unique=False)
    op.create_table('platform_events',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_errors', sa.Text(), nullable=True),
    sa.Column('replay_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replay_of_id'], ['platform_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_events_created_at', 'platform_events', ['created_at'], unique=False)
    op.create_index('ix_platform_events_entity', 'platform_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_platform_events_module', 'platform_events', ['module'], unique=False)
    op.create_index('ix_platform_events_status', 'platform_events', ['status'], unique=False)
    op.create_index('ix_platform_events_type', 'platform_events', ['event_type'], unique=False)
    op.create_index('ix_platform_events_user_id', 'platform_events', ['user_id'], unique=False)
    op.create_table('rbac_role_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['rbac_permissions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_code', name='uq_rbac_role_grants')
    )
    op.create_index('ix_rbac_role_grants_role_id', 'rbac_role_grants', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('commissions',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(length=64), nullable=False),
    sa.Column('commission_type', sa.String(length=32), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_commissions_amount_non_negative'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['commission_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commissions_deal_id', 'commissions', ['deal_id'], unique=False)
    op.create_index('ix_commissions_recipient', 'commissions', ['recipient_id'], unique=False)
    op.create_index('ix_commissions_status', 'commissions', ['status'], unique=False)
    op.create_index('ix_commissions_type', 'commissions', ['commission_type'], unique=False)
    op.create_table('deal_agro_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('erp_status', sa.String(length=64), nullable=True),
    sa.Column('legacy_agro_deal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('deal_auto_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True),
    sa.Column('tradein_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('deal_drone_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('drone_model', sa.String(length=128), nullable=True),
    sa.Column('delivery_date', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('deal_finance_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('finance_account_id', sa.UUID(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finance_account_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('deal_legal_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=128), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('deal_logistics_ext',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(length=512), nullable=True),
    sa.Column('shipment_id', sa.String(length=128), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.String(length=32), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index('ix_ledger_entries_deal_id', 'ledger_entries', ['deal_id'], unique=False)
    op.create_index('ix_ledger_entries_entry_id', 'ledger_entries', ['entry_id'], unique=True)
    op.create_index('ix_ledger_entries_entry_type', 'ledger_entries', ['entry_type'], unique=False)
    op.create_index('ix_ledger_entries_module', 'ledger_entries', ['module'], unique=False)
    op.create_index('ix_ledger_entries_status', 'ledger_entries', ['status'], unique=False)
    op.create_table('partner_deal_assignments',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('assignment_role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'deal_id', name='uq_partner_deal_assignments')
    )
    op.create_index('ix_partner_deal_assignments_deal_id', 'partner_deal_assignments', ['deal_id'], unique=False)
    op.create_table('partner_kpi',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('deals_count', sa.Integer(), nullable=False),
    sa.Column('deals_completed', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'period', name='uq_partner_kpi_period')
    )
    op.create_index('ix_partner_kpi_partner_id', 'partner_kpi', ['partner_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('calendar_event_id', sa.UUID(), nullable=True),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('ix_tasks_creator_id', 'tasks', ['creator_id'], unique=False)
    op.create_index('ix_tasks_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('ix_tasks_module', 'tasks', ['module'], unique=False)
    op.create_index('ix_tasks_public_id', 'tasks', ['public_id'], unique=True)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('commission_payments',
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('finance_transaction_id', sa.UUID(), nullable=True),
    sa.Column('paid_by_id', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_commission_payments_amount_positive'),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finance_transaction_id'], ['finance_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_payments_commission_id', 'commission_payments', ['commission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commission_payments_commission_id', table_name='commission_payments')
    op.drop_table('commission_payments')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_public_id', table_name='tasks')
    op.drop_index('ix_tasks_module', table_name='tasks')
    op.drop_index('ix_tasks_deadline', table_name='tasks')
    op.drop_index('ix_tasks_creator_id', table_name='tasks')
    op.drop_index('ix_tasks_assignee_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_partner_kpi_partner_id', table_name='partner_kpi')
    op.drop_table('partner_kpi')
    op.drop_index('ix_partner_deal_assignments_deal_id', table_name='partner_deal_assignments')
    op.drop_table('partner_deal_assignments')
    op.drop_index('ix_ledger_entries_status', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_module', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_entry_type', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_entry_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_deal_id', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('deal_logistics_ext')
    op.drop_table('deal_legal_ext')
    op.drop_table('deal_finance_ext')
    op.drop_table('deal_drone_ext')
    op.drop_table('deal_auto_ext')
    op.drop_table('deal_agro_ext')
    op.drop_index('ix_commissions_type', table_name='commissions')
    op.drop_index('ix_commissions_status', table_name='commissions')
    op.drop_index('ix_commissions_recipient', table_name='commissions')
    op.drop_index('ix_commissions_deal_id', table_name='commissions')
    op.drop_table('commissions')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_rbac_role_grants_role_id', table_name='rbac_role_grants')
    op.drop_table('rbac_role_grants')
    op.drop_index('ix_platform_events_user_id', table_name='platform_events')
    op.drop_index('ix_platform_events_type', table_name='platform_events')
    op.drop_index('ix_platform_events_status', table_name='platform_events')
    op.drop_index('ix_platform_events_module', table_name='platform_events')
    op.drop_index('ix_platform_events_entity', table_name='platform_events')
    op.drop_index('ix_platform_events_created_at', table_name='platform_events')
    op.drop_table('platform_events')
    op.drop_index('ix_partners_type', table_name='partners')
    op.drop_index('ix_partners_telegram_id', table_name='partners')
    op.drop_index('ix_partners_public_id', table_name='partners')
    op.drop_index('ix_partners_company', table_name='partners')
    op.drop_index('ix_partners_active', table_name='partners')
    op.drop_table('partners')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_module', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_finance_transactions_status', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_reference', table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index('ix_deals_status', table_name='deals')
    op.drop_index('ix_deals_public_id', table_name='deals')
    op.drop_index('ix_deals_owner_id', table_name='deals')
    op.drop_index('ix_deals_module', table_name='deals')
    op.drop_index('ix_deals_manager_id', table_name='deals')
    op.drop_index('ix_deals_legacy_ref', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_calendar_events_visibility', table_name='calendar_events')
    op.drop_index('ix_calendar_events_status', table_name='calendar_events')
    op.drop_index('ix_calendar_events_start', table_name='calendar_events')
    op.drop_index('ix_calendar_events_public_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_owner_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_module', table_name='calendar_events')
    op.drop_index('ix_calendar_events_department', table_name='calendar_events')
    op.drop_index('ix_calendar_events_creator_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_module', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_dialogs_user_id', table_name='ai_dialogs')
    op.drop_index('ix_ai_dialogs_agent_id', table_name='ai_dialogs')
    op.drop_table('ai_dialogs')
    op.drop_index('ix_ai_agent_settings_user_id', table_name='ai_agent_settings')
    op.drop_table('ai_agent_settings')
    op.drop_index('ix_ai_agent_memory_user_id', table_name='ai_agent_memory')
    op.drop_table('ai_agent_memory')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles_role_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_rbac_permissions_module', table_name='rbac_permissions')
    op.drop_index('ix_rbac_permissions_level', table_name='rbac_permissions')
    op.drop_table('rbac_permissions')
    op.drop_index('ix_finance_accounts_type', table_name='finance_accounts')
    op.drop_index('ix_finance_accounts_status', table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_index('ix_commission_rules_type', table_name='commission_rules')
    op.drop_index('ix_commission_rules_active', table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index('ix_ai_agents_code', table_name='ai_agents')
    op.drop_index('ix_ai_agents_active', table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
