"""event_bus_foundation

Revision ID: 411b8f2abda8
Revises: a1f3c8d29e04
Create Date: 2026-07-12 16:43:18.367484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '411b8f2abda8'
down_revision: Union[str, None] = 'a1f3c8d29e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=128), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'aggregate_type', 'aggregate_id', 'correlation_id', name='uq_events_idempotency')
    )
    op.create_index('ix_events_aggregate_id', 'events', ['aggregate_id'], unique=False)
    op.create_index('ix_events_correlation_id', 'events', ['correlation_id'], unique=False)
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_index('ix_events_correlation_id', table_name='events')
    op.drop_index('ix_events_aggregate_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
