"""notification_engine_foundation

Revision ID: 549c82229f93
Revises: 1ff9e7e214f5
Create Date: 2026-07-12 17:06:19.426572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549c82229f93'
down_revision: Union[str, None] = '1ff9e7e214f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_engine_notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retries >= 0', name='ck_notification_engine_retries_non_negative'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_engine_deal_id', 'notification_engine_notifications', ['deal_id'], unique=False)
    op.create_index('ix_notification_engine_notification_type', 'notification_engine_notifications', ['notification_type'], unique=False)
    op.create_index('ix_notification_engine_status', 'notification_engine_notifications', ['status'], unique=False)
    op.create_index('ix_notification_engine_user_id', 'notification_engine_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_engine_user_id', table_name='notification_engine_notifications')
    op.drop_index('ix_notification_engine_status', table_name='notification_engine_notifications')
    op.drop_index('ix_notification_engine_notification_type', table_name='notification_engine_notifications')
    op.drop_index('ix_notification_engine_deal_id', table_name='notification_engine_notifications')
    op.drop_table('notification_engine_notifications')
    # ### end Alembic commands ###
