"""audit_log_engine_foundation

Revision ID: 59ed827af999
Revises: 549c82229f93
Create Date: 2026-07-12 17:11:10.720931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ed827af999'
down_revision: Union[str, None] = '549c82229f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_engine_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_engine_logs_created_at', 'audit_engine_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_engine_logs_entity_id', 'audit_engine_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_engine_logs_entity_type', 'audit_engine_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_engine_logs_user_id', 'audit_engine_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_engine_logs_user_id', table_name='audit_engine_logs')
    op.drop_index('ix_audit_engine_logs_entity_type', table_name='audit_engine_logs')
    op.drop_index('ix_audit_engine_logs_entity_id', table_name='audit_engine_logs')
    op.drop_index('ix_audit_engine_logs_created_at', table_name='audit_engine_logs')
    op.drop_table('audit_engine_logs')
    # ### end Alembic commands ###
