"""dealer_portal_engine_v1

Revision ID: 61b6d9c53056
Revises: a7f71b77645a
Create Date: 2026-07-13 11:27:21.172534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b6d9c53056'
down_revision: Union[str, None] = 'a7f71b77645a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_portal_engine_v1_recommendations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dealer_portal_engine_v1_reco_priority', 'dealer_portal_engine_v1_recommendations', ['priority'], unique=False)
    op.create_index('ix_dealer_portal_engine_v1_reco_status', 'dealer_portal_engine_v1_recommendations', ['status'], unique=False)
    op.create_index('ix_dealer_portal_engine_v1_reco_tenant', 'dealer_portal_engine_v1_recommendations', ['tenant_id'], unique=False)
    op.create_table('dealer_portal_engine_v1_snapshots',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('widgets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_dealer_portal_engine_v1_snapshots_tenant_date')
    )
    op.create_index('ix_dealer_portal_engine_v1_snapshots_date', 'dealer_portal_engine_v1_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_dealer_portal_engine_v1_snapshots_tenant', 'dealer_portal_engine_v1_snapshots', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dealer_portal_engine_v1_snapshots_tenant', table_name='dealer_portal_engine_v1_snapshots')
    op.drop_index('ix_dealer_portal_engine_v1_snapshots_date', table_name='dealer_portal_engine_v1_snapshots')
    op.drop_table('dealer_portal_engine_v1_snapshots')
    op.drop_index('ix_dealer_portal_engine_v1_reco_tenant', table_name='dealer_portal_engine_v1_recommendations')
    op.drop_index('ix_dealer_portal_engine_v1_reco_status', table_name='dealer_portal_engine_v1_recommendations')
    op.drop_index('ix_dealer_portal_engine_v1_reco_priority', table_name='dealer_portal_engine_v1_recommendations')
    op.drop_table('dealer_portal_engine_v1_recommendations')
    # ### end Alembic commands ###
