"""lead_marketplace_engine_v1

Revision ID: 6936f241c881
Revises: 61b6d9c53056
Create Date: 2026-07-13 11:34:54.897027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6936f241c881'
down_revision: Union[str, None] = '61b6d9c53056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_marketplace_engine_v1_listings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('automation_lead_id', sa.UUID(), nullable=False),
    sa.Column('distribution_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('quality_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buyer_tenant_id', sa.UUID(), nullable=True),
    sa.Column('exclusive_buyer_tenant_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_lead_marketplace_v1_listing_base_price'),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 100', name='ck_lead_marketplace_v1_listing_score'),
    sa.ForeignKeyConstraint(['automation_lead_id'], ['lead_automation_engine_v1_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exclusive_buyer_tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_marketplace_v1_listings_company', 'lead_marketplace_engine_v1_listings', ['company_id'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_expires', 'lead_marketplace_engine_v1_listings', ['expires_at'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_lead', 'lead_marketplace_engine_v1_listings', ['automation_lead_id'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_mode', 'lead_marketplace_engine_v1_listings', ['distribution_mode'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_score', 'lead_marketplace_engine_v1_listings', ['quality_score'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_status', 'lead_marketplace_engine_v1_listings', ['status'], unique=False)
    op.create_index('ix_lead_marketplace_v1_listings_tenant', 'lead_marketplace_engine_v1_listings', ['tenant_id'], unique=False)
    op.create_table('lead_marketplace_engine_v1_pricing_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_quality_score', sa.Integer(), nullable=False),
    sa.Column('max_quality_score', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price_per_score_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('auction_premium_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('exclusive_multiplier', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('default_distribution_mode', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_lead_marketplace_v1_pricing_base'),
    sa.CheckConstraint('min_quality_score >= 0 AND max_quality_score <= 100', name='ck_lead_marketplace_v1_pricing_score_range'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_lead_marketplace_v1_pricing_tenant_code')
    )
    op.create_index('ix_lead_marketplace_v1_pricing_active', 'lead_marketplace_engine_v1_pricing_rules', ['is_active'], unique=False)
    op.create_index('ix_lead_marketplace_v1_pricing_tenant', 'lead_marketplace_engine_v1_pricing_rules', ['tenant_id'], unique=False)
    op.create_table('lead_marketplace_engine_v1_offers',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_lead_marketplace_v1_offer_amount'),
    sa.ForeignKeyConstraint(['buyer_tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['lead_marketplace_engine_v1_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_marketplace_v1_offers_amount', 'lead_marketplace_engine_v1_offers', ['amount'], unique=False)
    op.create_index('ix_lead_marketplace_v1_offers_buyer', 'lead_marketplace_engine_v1_offers', ['buyer_tenant_id'], unique=False)
    op.create_index('ix_lead_marketplace_v1_offers_listing', 'lead_marketplace_engine_v1_offers', ['listing_id'], unique=False)
    op.create_index('ix_lead_marketplace_v1_offers_status', 'lead_marketplace_engine_v1_offers', ['status'], unique=False)
    op.create_index('ix_lead_marketplace_v1_offers_type', 'lead_marketplace_engine_v1_offers', ['offer_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_marketplace_v1_offers_type', table_name='lead_marketplace_engine_v1_offers')
    op.drop_index('ix_lead_marketplace_v1_offers_status', table_name='lead_marketplace_engine_v1_offers')
    op.drop_index('ix_lead_marketplace_v1_offers_listing', table_name='lead_marketplace_engine_v1_offers')
    op.drop_index('ix_lead_marketplace_v1_offers_buyer', table_name='lead_marketplace_engine_v1_offers')
    op.drop_index('ix_lead_marketplace_v1_offers_amount', table_name='lead_marketplace_engine_v1_offers')
    op.drop_table('lead_marketplace_engine_v1_offers')
    op.drop_index('ix_lead_marketplace_v1_pricing_tenant', table_name='lead_marketplace_engine_v1_pricing_rules')
    op.drop_index('ix_lead_marketplace_v1_pricing_active', table_name='lead_marketplace_engine_v1_pricing_rules')
    op.drop_table('lead_marketplace_engine_v1_pricing_rules')
    op.drop_index('ix_lead_marketplace_v1_listings_tenant', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_status', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_score', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_mode', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_lead', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_expires', table_name='lead_marketplace_engine_v1_listings')
    op.drop_index('ix_lead_marketplace_v1_listings_company', table_name='lead_marketplace_engine_v1_listings')
    op.drop_table('lead_marketplace_engine_v1_listings')
    # ### end Alembic commands ###
