"""event_bus_production_upgrade

Revision ID: 6b20bbb2d338
Revises: 32c851505370
Create Date: 2026-07-12 17:30:58.870669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b20bbb2d338'
down_revision: Union[str, None] = '32c851505370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_dead_letters',
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_dead_letters_created_at', 'event_dead_letters', ['created_at'], unique=False)
    op.create_index('ix_event_dead_letters_event_name', 'event_dead_letters', ['event_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_dead_letters_event_name', table_name='event_dead_letters')
    op.drop_index('ix_event_dead_letters_created_at', table_name='event_dead_letters')
    op.drop_table('event_dead_letters')
    # ### end Alembic commands ###
