"""lead_automation_engine_v1

Revision ID: 6d3b487773e2
Revises: be831891e9d4
Create Date: 2026-07-13 09:38:21.097790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3b487773e2'
down_revision: Union[str, None] = 'be831891e9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_automation_engine_v1_leads',
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_normalized', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_normalized', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('assigned_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scoring_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['lead_automation_engine_v1_leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_automation_engine_v1_leads_car', 'lead_automation_engine_v1_leads', ['car_id'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_duplicate', 'lead_automation_engine_v1_leads', ['is_duplicate'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_email', 'lead_automation_engine_v1_leads', ['email_normalized'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_manager', 'lead_automation_engine_v1_leads', ['assigned_manager_id'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_phone', 'lead_automation_engine_v1_leads', ['phone_normalized'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_score', 'lead_automation_engine_v1_leads', ['score'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_source', 'lead_automation_engine_v1_leads', ['source'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_status', 'lead_automation_engine_v1_leads', ['status'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_leads_telegram', 'lead_automation_engine_v1_leads', ['telegram_user_id'], unique=False)
    op.create_table('lead_automation_engine_v1_source_events',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_automation_engine_v1_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_automation_engine_v1_events_lead', 'lead_automation_engine_v1_source_events', ['lead_id'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_events_source', 'lead_automation_engine_v1_source_events', ['source'], unique=False)
    op.create_index('ix_lead_automation_engine_v1_events_type', 'lead_automation_engine_v1_source_events', ['event_type'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_lead_automation_engine_v1_events_type', table_name='lead_automation_engine_v1_source_events')
    op.drop_index('ix_lead_automation_engine_v1_events_source', table_name='lead_automation_engine_v1_source_events')
    op.drop_index('ix_lead_automation_engine_v1_events_lead', table_name='lead_automation_engine_v1_source_events')
    op.drop_table('lead_automation_engine_v1_source_events')
    op.drop_index('ix_lead_automation_engine_v1_leads_telegram', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_status', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_source', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_score', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_phone', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_manager', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_email', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_duplicate', table_name='lead_automation_engine_v1_leads')
    op.drop_index('ix_lead_automation_engine_v1_leads_car', table_name='lead_automation_engine_v1_leads')
    op.drop_table('lead_automation_engine_v1_leads')
    # ### end Alembic commands ###
