"""kyc_engine_foundation

Revision ID: 78f8082b992e
Revises: 0d20fc677b5d
Create Date: 2026-07-12 17:37:31.844927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f8082b992e'
down_revision: Union[str, None] = '0d20fc677b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_engine_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('verification_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_kyc_engine_profiles_user_id')
    )
    op.create_index('ix_kyc_engine_profiles_country', 'kyc_engine_profiles', ['country'], unique=False)
    op.create_index('ix_kyc_engine_profiles_status', 'kyc_engine_profiles', ['status'], unique=False)
    op.create_index('ix_kyc_engine_profiles_verification_level', 'kyc_engine_profiles', ['verification_level'], unique=False)
    op.create_table('kyc_engine_documents',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('issuing_country', sa.String(length=3), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['kyc_engine_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_engine_documents_document_type', 'kyc_engine_documents', ['document_type'], unique=False)
    op.create_index('ix_kyc_engine_documents_expires_at', 'kyc_engine_documents', ['expires_at'], unique=False)
    op.create_index('ix_kyc_engine_documents_profile_id', 'kyc_engine_documents', ['profile_id'], unique=False)
    op.create_index('ix_kyc_engine_documents_status', 'kyc_engine_documents', ['status'], unique=False)
    op.create_table('kyc_engine_risk_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('aml_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pep_status', sa.Boolean(), nullable=False),
    sa.Column('sanctions_hit', sa.Boolean(), nullable=False),
    sa.Column('adverse_media', sa.Boolean(), nullable=False),
    sa.Column('source_of_funds_verified', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_kyc_engine_risk_profiles_score_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['kyc_engine_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_kyc_engine_risk_profiles_profile_id')
    )
    op.create_index('ix_kyc_engine_risk_profiles_risk_level', 'kyc_engine_risk_profiles', ['risk_level'], unique=False)
    op.create_table('kyc_engine_sanctions_checks',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('matched_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['kyc_engine_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_engine_sanctions_checks_check_type', 'kyc_engine_sanctions_checks', ['check_type'], unique=False)
    op.create_index('ix_kyc_engine_sanctions_checks_checked_at', 'kyc_engine_sanctions_checks', ['checked_at'], unique=False)
    op.create_index('ix_kyc_engine_sanctions_checks_profile_id', 'kyc_engine_sanctions_checks', ['profile_id'], unique=False)
    op.create_index('ix_kyc_engine_sanctions_checks_status', 'kyc_engine_sanctions_checks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kyc_engine_sanctions_checks_status', table_name='kyc_engine_sanctions_checks')
    op.drop_index('ix_kyc_engine_sanctions_checks_profile_id', table_name='kyc_engine_sanctions_checks')
    op.drop_index('ix_kyc_engine_sanctions_checks_checked_at', table_name='kyc_engine_sanctions_checks')
    op.drop_index('ix_kyc_engine_sanctions_checks_check_type', table_name='kyc_engine_sanctions_checks')
    op.drop_table('kyc_engine_sanctions_checks')
    op.drop_index('ix_kyc_engine_risk_profiles_risk_level', table_name='kyc_engine_risk_profiles')
    op.drop_table('kyc_engine_risk_profiles')
    op.drop_index('ix_kyc_engine_documents_status', table_name='kyc_engine_documents')
    op.drop_index('ix_kyc_engine_documents_profile_id', table_name='kyc_engine_documents')
    op.drop_index('ix_kyc_engine_documents_expires_at', table_name='kyc_engine_documents')
    op.drop_index('ix_kyc_engine_documents_document_type', table_name='kyc_engine_documents')
    op.drop_table('kyc_engine_documents')
    op.drop_index('ix_kyc_engine_profiles_verification_level', table_name='kyc_engine_profiles')
    op.drop_index('ix_kyc_engine_profiles_status', table_name='kyc_engine_profiles')
    op.drop_index('ix_kyc_engine_profiles_country', table_name='kyc_engine_profiles')
    op.drop_table('kyc_engine_profiles')
    # ### end Alembic commands ###
