"""automotive_parts_warehouse_engine_v1

Revision ID: 85c051138273
Revises: cbdccd98e019
Create Date: 2026-07-12 22:51:15.004596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c051138273'
down_revision: Union[str, None] = 'cbdccd98e019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_warehouse_v1_suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_warehouse_v1_suppliers_is_active', 'automotive_warehouse_v1_suppliers', ['is_active'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_suppliers_name', 'automotive_warehouse_v1_suppliers', ['name'], unique=False)
    op.create_table('automotive_warehouse_v1_parts',
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('min_stock_level', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_stock_level >= 0', name='ck_automotive_warehouse_v1_parts_min'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_automotive_warehouse_v1_parts_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_automotive_warehouse_v1_parts_reserved'),
    sa.ForeignKeyConstraint(['supplier_id'], ['automotive_warehouse_v1_suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number', name='uq_automotive_warehouse_v1_parts_part_number')
    )
    op.create_index('ix_automotive_warehouse_v1_parts_is_active', 'automotive_warehouse_v1_parts', ['is_active'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_parts_supplier_id', 'automotive_warehouse_v1_parts', ['supplier_id'], unique=False)
    op.create_table('automotive_warehouse_v1_reorder_rules',
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_quantity >= 0', name='ck_automotive_warehouse_v1_rr_min'),
    sa.CheckConstraint('reorder_quantity > 0', name='ck_automotive_warehouse_v1_rr_reorder'),
    sa.ForeignKeyConstraint(['part_id'], ['automotive_warehouse_v1_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['automotive_warehouse_v1_suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', name='uq_automotive_warehouse_v1_reorder_rules_part_id')
    )
    op.create_index('ix_automotive_warehouse_v1_rr_is_active', 'automotive_warehouse_v1_reorder_rules', ['is_active'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_rr_supplier_id', 'automotive_warehouse_v1_reorder_rules', ['supplier_id'], unique=False)
    op.create_table('automotive_warehouse_v1_reservations',
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_automotive_warehouse_v1_res_qty'),
    sa.ForeignKeyConstraint(['part_id'], ['automotive_warehouse_v1_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_warehouse_v1_res_part_id', 'automotive_warehouse_v1_reservations', ['part_id'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_res_service_order_id', 'automotive_warehouse_v1_reservations', ['service_order_id'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_res_status', 'automotive_warehouse_v1_reservations', ['status'], unique=False)
    op.create_table('automotive_warehouse_v1_stock_movements',
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_automotive_warehouse_v1_sm_qty'),
    sa.ForeignKeyConstraint(['part_id'], ['automotive_warehouse_v1_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_warehouse_v1_sm_movement_type', 'automotive_warehouse_v1_stock_movements', ['movement_type'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_sm_part_id', 'automotive_warehouse_v1_stock_movements', ['part_id'], unique=False)
    op.create_index('ix_automotive_warehouse_v1_sm_service_order_id', 'automotive_warehouse_v1_stock_movements', ['service_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automotive_warehouse_v1_sm_service_order_id', table_name='automotive_warehouse_v1_stock_movements')
    op.drop_index('ix_automotive_warehouse_v1_sm_part_id', table_name='automotive_warehouse_v1_stock_movements')
    op.drop_index('ix_automotive_warehouse_v1_sm_movement_type', table_name='automotive_warehouse_v1_stock_movements')
    op.drop_table('automotive_warehouse_v1_stock_movements')
    op.drop_index('ix_automotive_warehouse_v1_res_status', table_name='automotive_warehouse_v1_reservations')
    op.drop_index('ix_automotive_warehouse_v1_res_service_order_id', table_name='automotive_warehouse_v1_reservations')
    op.drop_index('ix_automotive_warehouse_v1_res_part_id', table_name='automotive_warehouse_v1_reservations')
    op.drop_table('automotive_warehouse_v1_reservations')
    op.drop_index('ix_automotive_warehouse_v1_rr_supplier_id', table_name='automotive_warehouse_v1_reorder_rules')
    op.drop_index('ix_automotive_warehouse_v1_rr_is_active', table_name='automotive_warehouse_v1_reorder_rules')
    op.drop_table('automotive_warehouse_v1_reorder_rules')
    op.drop_index('ix_automotive_warehouse_v1_parts_supplier_id', table_name='automotive_warehouse_v1_parts')
    op.drop_index('ix_automotive_warehouse_v1_parts_is_active', table_name='automotive_warehouse_v1_parts')
    op.drop_table('automotive_warehouse_v1_parts')
    op.drop_index('ix_automotive_warehouse_v1_suppliers_name', table_name='automotive_warehouse_v1_suppliers')
    op.drop_index('ix_automotive_warehouse_v1_suppliers_is_active', table_name='automotive_warehouse_v1_suppliers')
    op.drop_table('automotive_warehouse_v1_suppliers')
    # ### end Alembic commands ###
