"""pricing_engine_foundation

Revision ID: 90b2429b0170
Revises: 78f8082b992e
Create Date: 2026-07-12 17:39:39.240338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90b2429b0170'
down_revision: Union[str, None] = '78f8082b992e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_engine_sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('asset_in', sa.String(length=20), nullable=False),
    sa.Column('asset_out', sa.String(length=20), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_rate > 0', name='ck_pricing_engine_sources_base_rate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_pricing_engine_sources_code')
    )
    op.create_index('ix_pricing_engine_sources_asset_pair', 'pricing_engine_sources', ['asset_in', 'asset_out'], unique=False)
    op.create_index('ix_pricing_engine_sources_is_active', 'pricing_engine_sources', ['is_active'], unique=False)
    op.create_table('pricing_engine_rules',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('asset_in', sa.String(length=20), nullable=False),
    sa.Column('asset_out', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('vip_user_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['pricing_engine_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_pricing_engine_rules_code')
    )
    op.create_index('ix_pricing_engine_rules_asset_pair', 'pricing_engine_rules', ['asset_in', 'asset_out'], unique=False)
    op.create_index('ix_pricing_engine_rules_is_active', 'pricing_engine_rules', ['is_active'], unique=False)
    op.create_index('ix_pricing_engine_rules_manager_id', 'pricing_engine_rules', ['manager_id'], unique=False)
    op.create_index('ix_pricing_engine_rules_partner_id', 'pricing_engine_rules', ['partner_id'], unique=False)
    op.create_index('ix_pricing_engine_rules_rule_type', 'pricing_engine_rules', ['rule_type'], unique=False)
    op.create_index('ix_pricing_engine_rules_vip_user_id', 'pricing_engine_rules', ['vip_user_id'], unique=False)
    op.create_table('pricing_engine_markups',
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('applies_to', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('markup_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('asset_in', sa.String(length=20), nullable=True),
    sa.Column('asset_out', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_engine_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_engine_markups_applies_to', 'pricing_engine_markups', ['applies_to'], unique=False)
    op.create_index('ix_pricing_engine_markups_is_active', 'pricing_engine_markups', ['is_active'], unique=False)
    op.create_index('ix_pricing_engine_markups_rule_id', 'pricing_engine_markups', ['rule_id'], unique=False)
    op.create_index('ix_pricing_engine_markups_target_id', 'pricing_engine_markups', ['target_id'], unique=False)
    op.create_table('pricing_engine_spreads',
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('asset_in', sa.String(length=20), nullable=False),
    sa.Column('asset_out', sa.String(length=20), nullable=False),
    sa.Column('spread_type', sa.String(length=20), nullable=False),
    sa.Column('bid_spread', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('ask_spread', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ask_spread >= 0', name='ck_pricing_engine_spreads_ask'),
    sa.CheckConstraint('bid_spread >= 0', name='ck_pricing_engine_spreads_bid'),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_engine_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['pricing_engine_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_engine_spreads_asset_pair', 'pricing_engine_spreads', ['asset_in', 'asset_out'], unique=False)
    op.create_index('ix_pricing_engine_spreads_is_active', 'pricing_engine_spreads', ['is_active'], unique=False)
    op.create_index('ix_pricing_engine_spreads_rule_id', 'pricing_engine_spreads', ['rule_id'], unique=False)
    op.create_index('ix_pricing_engine_spreads_source_id', 'pricing_engine_spreads', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_engine_spreads_source_id', table_name='pricing_engine_spreads')
    op.drop_index('ix_pricing_engine_spreads_rule_id', table_name='pricing_engine_spreads')
    op.drop_index('ix_pricing_engine_spreads_is_active', table_name='pricing_engine_spreads')
    op.drop_index('ix_pricing_engine_spreads_asset_pair', table_name='pricing_engine_spreads')
    op.drop_table('pricing_engine_spreads')
    op.drop_index('ix_pricing_engine_markups_target_id', table_name='pricing_engine_markups')
    op.drop_index('ix_pricing_engine_markups_rule_id', table_name='pricing_engine_markups')
    op.drop_index('ix_pricing_engine_markups_is_active', table_name='pricing_engine_markups')
    op.drop_index('ix_pricing_engine_markups_applies_to', table_name='pricing_engine_markups')
    op.drop_table('pricing_engine_markups')
    op.drop_index('ix_pricing_engine_rules_vip_user_id', table_name='pricing_engine_rules')
    op.drop_index('ix_pricing_engine_rules_rule_type', table_name='pricing_engine_rules')
    op.drop_index('ix_pricing_engine_rules_partner_id', table_name='pricing_engine_rules')
    op.drop_index('ix_pricing_engine_rules_manager_id', table_name='pricing_engine_rules')
    op.drop_index('ix_pricing_engine_rules_is_active', table_name='pricing_engine_rules')
    op.drop_index('ix_pricing_engine_rules_asset_pair', table_name='pricing_engine_rules')
    op.drop_table('pricing_engine_rules')
    op.drop_index('ix_pricing_engine_sources_is_active', table_name='pricing_engine_sources')
    op.drop_index('ix_pricing_engine_sources_asset_pair', table_name='pricing_engine_sources')
    op.drop_table('pricing_engine_sources')
    # ### end Alembic commands ###
