"""liquidity_engine_v1

Revision ID: 9bb577bff163
Revises: df6980c1c483
Create Date: 2026-07-12 18:00:31.404024

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "9bb577bff163"
down_revision: Union[str, None] = "df6980c1c483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("liquidity.reserved", "Emit or subscribe to liquidity reserved events"),
    ("liquidity.released", "Emit or subscribe to liquidity released events"),
    ("liquidity.shortage", "Emit or subscribe to liquidity shortage events"),
    ("liquidity.consumed", "Emit or subscribe to liquidity consumed events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
}


def _seed_liquidity_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidity_v1_pools',
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('available_amount >= 0', name='ck_liquidity_v1_pools_available'),
    sa.CheckConstraint('reserved_amount >= 0', name='ck_liquidity_v1_pools_reserved'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset', 'location', name='uq_liquidity_v1_pools_asset_location')
    )
    op.create_index('ix_liquidity_v1_pools_asset', 'liquidity_v1_pools', ['asset'], unique=False)
    op.create_index('ix_liquidity_v1_pools_location', 'liquidity_v1_pools', ['location'], unique=False)
    op.create_table('liquidity_v1_alerts',
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['liquidity_v1_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_liquidity_v1_alerts_alert_type', 'liquidity_v1_alerts', ['alert_type'], unique=False)
    op.create_index('ix_liquidity_v1_alerts_asset', 'liquidity_v1_alerts', ['asset'], unique=False)
    op.create_index('ix_liquidity_v1_alerts_is_resolved', 'liquidity_v1_alerts', ['is_resolved'], unique=False)
    op.create_table('liquidity_v1_reservations',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_liquidity_v1_reservations_amount'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['liquidity_v1_pools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_liquidity_v1_reservations_asset', 'liquidity_v1_reservations', ['asset'], unique=False)
    op.create_index('ix_liquidity_v1_reservations_deal_id', 'liquidity_v1_reservations', ['deal_id'], unique=False)
    op.create_index('ix_liquidity_v1_reservations_pool_id', 'liquidity_v1_reservations', ['pool_id'], unique=False)
    op.create_index('ix_liquidity_v1_reservations_status', 'liquidity_v1_reservations', ['status'], unique=False)
    _seed_liquidity_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_liquidity_v1_reservations_status', table_name='liquidity_v1_reservations')
    op.drop_index('ix_liquidity_v1_reservations_pool_id', table_name='liquidity_v1_reservations')
    op.drop_index('ix_liquidity_v1_reservations_deal_id', table_name='liquidity_v1_reservations')
    op.drop_index('ix_liquidity_v1_reservations_asset', table_name='liquidity_v1_reservations')
    op.drop_table('liquidity_v1_reservations')
    op.drop_index('ix_liquidity_v1_alerts_is_resolved', table_name='liquidity_v1_alerts')
    op.drop_index('ix_liquidity_v1_alerts_asset', table_name='liquidity_v1_alerts')
    op.drop_index('ix_liquidity_v1_alerts_alert_type', table_name='liquidity_v1_alerts')
    op.drop_table('liquidity_v1_alerts')
    op.drop_index('ix_liquidity_v1_pools_location', table_name='liquidity_v1_pools')
    op.drop_index('ix_liquidity_v1_pools_asset', table_name='liquidity_v1_pools')
    op.drop_table('liquidity_v1_pools')
    # ### end Alembic commands ###
