"""scheduler_engine_v1

Revision ID: a36e79485609
Revises: c67bf764611d
Create Date: 2026-07-12 23:56:05.455220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a36e79485609'
down_revision: Union[str, None] = 'c67bf764611d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_engine_v1_scheduled_jobs',
    sa.Column('job_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=64), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_one_shot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key', name='uq_scheduler_engine_v1_jobs_job_key')
    )
    op.create_index('ix_scheduler_engine_v1_jobs_job_key', 'scheduler_engine_v1_scheduled_jobs', ['job_key'], unique=False)
    op.create_index('ix_scheduler_engine_v1_jobs_lock', 'scheduler_engine_v1_scheduled_jobs', ['lock_owner'], unique=False)
    op.create_index('ix_scheduler_engine_v1_jobs_next_run', 'scheduler_engine_v1_scheduled_jobs', ['next_run_at'], unique=False)
    op.create_index('ix_scheduler_engine_v1_jobs_status', 'scheduler_engine_v1_scheduled_jobs', ['status'], unique=False)
    op.create_table('scheduler_engine_v1_job_executions',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scheduler_engine_v1_scheduled_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_engine_v1_exec_job', 'scheduler_engine_v1_job_executions', ['job_id'], unique=False)
    op.create_index('ix_scheduler_engine_v1_exec_retry', 'scheduler_engine_v1_job_executions', ['next_retry_at'], unique=False)
    op.create_index('ix_scheduler_engine_v1_exec_scheduled', 'scheduler_engine_v1_job_executions', ['scheduled_at'], unique=False)
    op.create_index('ix_scheduler_engine_v1_exec_status', 'scheduler_engine_v1_job_executions', ['status'], unique=False)
    op.create_table('scheduler_engine_v1_job_failures',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['scheduler_engine_v1_job_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['scheduler_engine_v1_scheduled_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_engine_v1_fail_exec', 'scheduler_engine_v1_job_failures', ['execution_id'], unique=False)
    op.create_index('ix_scheduler_engine_v1_fail_job', 'scheduler_engine_v1_job_failures', ['job_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_scheduler_engine_v1_fail_job', table_name='scheduler_engine_v1_job_failures')
    op.drop_index('ix_scheduler_engine_v1_fail_exec', table_name='scheduler_engine_v1_job_failures')
    op.drop_table('scheduler_engine_v1_job_failures')
    op.drop_index('ix_scheduler_engine_v1_exec_status', table_name='scheduler_engine_v1_job_executions')
    op.drop_index('ix_scheduler_engine_v1_exec_scheduled', table_name='scheduler_engine_v1_job_executions')
    op.drop_index('ix_scheduler_engine_v1_exec_retry', table_name='scheduler_engine_v1_job_executions')
    op.drop_index('ix_scheduler_engine_v1_exec_job', table_name='scheduler_engine_v1_job_executions')
    op.drop_table('scheduler_engine_v1_job_executions')
    op.drop_index('ix_scheduler_engine_v1_jobs_status', table_name='scheduler_engine_v1_scheduled_jobs')
    op.drop_index('ix_scheduler_engine_v1_jobs_next_run', table_name='scheduler_engine_v1_scheduled_jobs')
    op.drop_index('ix_scheduler_engine_v1_jobs_lock', table_name='scheduler_engine_v1_scheduled_jobs')
    op.drop_index('ix_scheduler_engine_v1_jobs_job_key', table_name='scheduler_engine_v1_scheduled_jobs')
    op.drop_table('scheduler_engine_v1_scheduled_jobs')
