"""revenue_sharing_engine_v1

Revision ID: a7f71b77645a
Revises: fd2f30a57d28
Create Date: 2026-07-13 11:18:31.441465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f71b77645a'
down_revision: Union[str, None] = 'fd2f30a57d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_sharing_engine_v1_agreements',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('partner_ref', sa.String(length=120), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'partner_ref', name='uq_revenue_sharing_engine_v1_agreements_tenant_partner')
    )
    op.create_index('ix_revenue_sharing_engine_v1_agreements_company', 'revenue_sharing_engine_v1_agreements', ['company_id'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_agreements_model', 'revenue_sharing_engine_v1_agreements', ['model_type'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_agreements_status', 'revenue_sharing_engine_v1_agreements', ['status'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_agreements_tenant', 'revenue_sharing_engine_v1_agreements', ['tenant_id'], unique=False)
    op.create_table('revenue_sharing_engine_v1_calculations',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_revenue_sharing_engine_v1_calc_total'),
    sa.ForeignKeyConstraint(['agreement_id'], ['revenue_sharing_engine_v1_agreements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id', 'period_start', 'period_end', name='uq_revenue_sharing_engine_v1_calc_agreement_period')
    )
    op.create_index('ix_revenue_sharing_engine_v1_calc_agreement', 'revenue_sharing_engine_v1_calculations', ['agreement_id'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_calc_period', 'revenue_sharing_engine_v1_calculations', ['period_start', 'period_end'], unique=False)
    op.create_table('revenue_sharing_engine_v1_reports',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['revenue_sharing_engine_v1_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['calculation_id'], ['revenue_sharing_engine_v1_calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id', 'report_month', name='uq_revenue_sharing_engine_v1_reports_agreement_month')
    )
    op.create_index('ix_revenue_sharing_engine_v1_reports_agreement', 'revenue_sharing_engine_v1_reports', ['agreement_id'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_reports_month', 'revenue_sharing_engine_v1_reports', ['report_month'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_reports_status', 'revenue_sharing_engine_v1_reports', ['status'], unique=False)
    op.create_table('revenue_sharing_engine_v1_settlements',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['revenue_sharing_engine_v1_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['revenue_sharing_engine_v1_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revenue_sharing_engine_v1_settlements_agreement', 'revenue_sharing_engine_v1_settlements', ['agreement_id'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_settlements_report', 'revenue_sharing_engine_v1_settlements', ['report_id'], unique=False)
    op.create_index('ix_revenue_sharing_engine_v1_settlements_status', 'revenue_sharing_engine_v1_settlements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revenue_sharing_engine_v1_settlements_status', table_name='revenue_sharing_engine_v1_settlements')
    op.drop_index('ix_revenue_sharing_engine_v1_settlements_report', table_name='revenue_sharing_engine_v1_settlements')
    op.drop_index('ix_revenue_sharing_engine_v1_settlements_agreement', table_name='revenue_sharing_engine_v1_settlements')
    op.drop_table('revenue_sharing_engine_v1_settlements')
    op.drop_index('ix_revenue_sharing_engine_v1_reports_status', table_name='revenue_sharing_engine_v1_reports')
    op.drop_index('ix_revenue_sharing_engine_v1_reports_month', table_name='revenue_sharing_engine_v1_reports')
    op.drop_index('ix_revenue_sharing_engine_v1_reports_agreement', table_name='revenue_sharing_engine_v1_reports')
    op.drop_table('revenue_sharing_engine_v1_reports')
    op.drop_index('ix_revenue_sharing_engine_v1_calc_period', table_name='revenue_sharing_engine_v1_calculations')
    op.drop_index('ix_revenue_sharing_engine_v1_calc_agreement', table_name='revenue_sharing_engine_v1_calculations')
    op.drop_table('revenue_sharing_engine_v1_calculations')
    op.drop_index('ix_revenue_sharing_engine_v1_agreements_tenant', table_name='revenue_sharing_engine_v1_agreements')
    op.drop_index('ix_revenue_sharing_engine_v1_agreements_status', table_name='revenue_sharing_engine_v1_agreements')
    op.drop_index('ix_revenue_sharing_engine_v1_agreements_model', table_name='revenue_sharing_engine_v1_agreements')
    op.drop_index('ix_revenue_sharing_engine_v1_agreements_company', table_name='revenue_sharing_engine_v1_agreements')
    op.drop_table('revenue_sharing_engine_v1_agreements')
    # ### end Alembic commands ###
