"""car_entity_engine_v1

Revision ID: aada79cbcac2
Revises: b8f2c91d4e03
Create Date: 2026-07-13 09:07:00.838571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aada79cbcac2'
down_revision: Union[str, None] = 'b8f2c91d4e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_engine_v1_cars',
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delivery_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('customs_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('repair_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('advertising_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expected_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mileage >= 0', name='ck_car_engine_v1_cars_mileage'),
    sa.CheckConstraint('year >= 1900', name='ck_car_engine_v1_cars_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', name='uq_car_engine_v1_cars_vin')
    )
    op.create_index('ix_car_engine_v1_cars_client', 'car_engine_v1_cars', ['client_id'], unique=False)
    op.create_index('ix_car_engine_v1_cars_make_model', 'car_engine_v1_cars', ['make', 'model'], unique=False)
    op.create_index('ix_car_engine_v1_cars_manager', 'car_engine_v1_cars', ['manager_id'], unique=False)
    op.create_index('ix_car_engine_v1_cars_status', 'car_engine_v1_cars', ['status'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_car_engine_v1_cars_status', table_name='car_engine_v1_cars')
    op.drop_index('ix_car_engine_v1_cars_manager', table_name='car_engine_v1_cars')
    op.drop_index('ix_car_engine_v1_cars_make_model', table_name='car_engine_v1_cars')
    op.drop_index('ix_car_engine_v1_cars_client', table_name='car_engine_v1_cars')
    op.drop_table('car_engine_v1_cars')
