"""ai_procurement_agent_v1

Revision ID: ab1a2593ea2e
Revises: 6936f241c881
Create Date: 2026-07-13 11:39:49.040645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab1a2593ea2e'
down_revision: Union[str, None] = '6936f241c881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_procurement_agent_v1_analyses',
    sa.Column('analysis_type', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_ai_procurement_agent_v1_analysis_confidence'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_procurement_agent_v1_analyses_actor', 'ai_procurement_agent_v1_analyses', ['created_by'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_analyses_model', 'ai_procurement_agent_v1_analyses', ['model_version'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_analyses_subject', 'ai_procurement_agent_v1_analyses', ['subject_type', 'subject_id'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_analyses_type', 'ai_procurement_agent_v1_analyses', ['analysis_type'], unique=False)
    op.create_table('ai_procurement_agent_v1_opportunities',
    sa.Column('auction_lot_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('acquisition_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('estimated_market_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('undervaluation_score', sa.Integer(), nullable=False),
    sa.Column('repair_cost_estimate', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sale_price_estimate', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('roi_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0', name='ck_ai_procurement_agent_v1_opp_discount'),
    sa.CheckConstraint('undervaluation_score >= 0 AND undervaluation_score <= 100', name='ck_ai_procurement_agent_v1_opp_score'),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_procurement_agent_v1_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['auction_lot_id'], ['automotive_procurement_v1_auction_lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_procurement_agent_v1_opp_lot', 'ai_procurement_agent_v1_opportunities', ['auction_lot_id'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_opp_make_model', 'ai_procurement_agent_v1_opportunities', ['make', 'model'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_opp_score', 'ai_procurement_agent_v1_opportunities', ['undervaluation_score'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_opp_status', 'ai_procurement_agent_v1_opportunities', ['status'], unique=False)
    op.create_index('ix_ai_procurement_agent_v1_opp_vehicle', 'ai_procurement_agent_v1_opportunities', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_procurement_agent_v1_opp_vehicle', table_name='ai_procurement_agent_v1_opportunities')
    op.drop_index('ix_ai_procurement_agent_v1_opp_status', table_name='ai_procurement_agent_v1_opportunities')
    op.drop_index('ix_ai_procurement_agent_v1_opp_score', table_name='ai_procurement_agent_v1_opportunities')
    op.drop_index('ix_ai_procurement_agent_v1_opp_make_model', table_name='ai_procurement_agent_v1_opportunities')
    op.drop_index('ix_ai_procurement_agent_v1_opp_lot', table_name='ai_procurement_agent_v1_opportunities')
    op.drop_table('ai_procurement_agent_v1_opportunities')
    op.drop_index('ix_ai_procurement_agent_v1_analyses_type', table_name='ai_procurement_agent_v1_analyses')
    op.drop_index('ix_ai_procurement_agent_v1_analyses_subject', table_name='ai_procurement_agent_v1_analyses')
    op.drop_index('ix_ai_procurement_agent_v1_analyses_model', table_name='ai_procurement_agent_v1_analyses')
    op.drop_index('ix_ai_procurement_agent_v1_analyses_actor', table_name='ai_procurement_agent_v1_analyses')
    op.drop_table('ai_procurement_agent_v1_analyses')
    # ### end Alembic commands ###
