"""channel_integration_engine_v1

Revision ID: ac3f059af508
Revises: b3f965bee1f1
Create Date: 2026-07-13 11:04:24.950306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac3f059af508'
down_revision: Union[str, None] = 'b3f965bee1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_integration_engine_v1_channels',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=120), nullable=False),
    sa.Column('channel_type', sa.String(length=40), nullable=False),
    sa.Column('permissions', sa.String(length=40), nullable=False),
    sa.Column('token_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel_type', 'channel_id', name='uq_channel_integration_engine_v1_channels_tenant_type_id')
    )
    op.create_index('ix_channel_integration_engine_v1_channels_channel_id', 'channel_integration_engine_v1_channels', ['channel_id'], unique=False)
    op.create_index('ix_channel_integration_engine_v1_channels_company', 'channel_integration_engine_v1_channels', ['company_id'], unique=False)
    op.create_index('ix_channel_integration_engine_v1_channels_status', 'channel_integration_engine_v1_channels', ['status'], unique=False)
    op.create_index('ix_channel_integration_engine_v1_channels_tenant', 'channel_integration_engine_v1_channels', ['tenant_id'], unique=False)
    op.create_index('ix_channel_integration_engine_v1_channels_type', 'channel_integration_engine_v1_channels', ['channel_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channel_integration_engine_v1_channels_type', table_name='channel_integration_engine_v1_channels')
    op.drop_index('ix_channel_integration_engine_v1_channels_tenant', table_name='channel_integration_engine_v1_channels')
    op.drop_index('ix_channel_integration_engine_v1_channels_status', table_name='channel_integration_engine_v1_channels')
    op.drop_index('ix_channel_integration_engine_v1_channels_company', table_name='channel_integration_engine_v1_channels')
    op.drop_index('ix_channel_integration_engine_v1_channels_channel_id', table_name='channel_integration_engine_v1_channels')
    op.drop_table('channel_integration_engine_v1_channels')
    # ### end Alembic commands ###
