"""tenant_billing_engine_v1

Revision ID: b3f965bee1f1
Revises: f516fd3fbebe
Create Date: 2026-07-13 11:01:24.637376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3f965bee1f1'
down_revision: Union[str, None] = 'f516fd3fbebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_billing_engine_v1_invoices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_tenant_billing_engine_v1_invoices_subtotal'),
    sa.CheckConstraint('total >= 0', name='ck_tenant_billing_engine_v1_invoices_total'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_tenant_billing_engine_v1_invoices_number')
    )
    op.create_index('ix_tenant_billing_engine_v1_invoices_company', 'tenant_billing_engine_v1_invoices', ['company_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_invoices_period', 'tenant_billing_engine_v1_invoices', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_invoices_status', 'tenant_billing_engine_v1_invoices', ['status'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_invoices_tenant', 'tenant_billing_engine_v1_invoices', ['tenant_id'], unique=False)
    op.create_table('tenant_billing_engine_v1_subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_billing_engine_v1_subscriptions_tenant')
    )
    op.create_index('ix_tenant_billing_engine_v1_subscriptions_company', 'tenant_billing_engine_v1_subscriptions', ['company_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_subscriptions_plan', 'tenant_billing_engine_v1_subscriptions', ['plan_code'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_subscriptions_status', 'tenant_billing_engine_v1_subscriptions', ['status'], unique=False)
    op.create_table('tenant_billing_engine_v1_invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_tenant_billing_engine_v1_lines_amount'),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant_billing_engine_v1_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_billing_engine_v1_lines_invoice', 'tenant_billing_engine_v1_invoice_lines', ['invoice_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_lines_type', 'tenant_billing_engine_v1_invoice_lines', ['line_type'], unique=False)
    op.create_table('tenant_billing_engine_v1_usage_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('billing_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_key', sa.String(length=120), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_tenant_billing_engine_v1_usage_amount'),
    sa.CheckConstraint('quantity >= 0', name='ck_tenant_billing_engine_v1_usage_qty'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['tenant_billing_engine_v1_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'billing_type', 'reference_key', name='uq_tenant_billing_engine_v1_usage_tenant_type_ref')
    )
    op.create_index('ix_tenant_billing_engine_v1_usage_company', 'tenant_billing_engine_v1_usage_records', ['company_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_usage_invoice', 'tenant_billing_engine_v1_usage_records', ['invoice_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_usage_recorded', 'tenant_billing_engine_v1_usage_records', ['recorded_at'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_usage_tenant', 'tenant_billing_engine_v1_usage_records', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_billing_engine_v1_usage_type', 'tenant_billing_engine_v1_usage_records', ['billing_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenant_billing_engine_v1_usage_type', table_name='tenant_billing_engine_v1_usage_records')
    op.drop_index('ix_tenant_billing_engine_v1_usage_tenant', table_name='tenant_billing_engine_v1_usage_records')
    op.drop_index('ix_tenant_billing_engine_v1_usage_recorded', table_name='tenant_billing_engine_v1_usage_records')
    op.drop_index('ix_tenant_billing_engine_v1_usage_invoice', table_name='tenant_billing_engine_v1_usage_records')
    op.drop_index('ix_tenant_billing_engine_v1_usage_company', table_name='tenant_billing_engine_v1_usage_records')
    op.drop_table('tenant_billing_engine_v1_usage_records')
    op.drop_index('ix_tenant_billing_engine_v1_lines_type', table_name='tenant_billing_engine_v1_invoice_lines')
    op.drop_index('ix_tenant_billing_engine_v1_lines_invoice', table_name='tenant_billing_engine_v1_invoice_lines')
    op.drop_table('tenant_billing_engine_v1_invoice_lines')
    op.drop_index('ix_tenant_billing_engine_v1_subscriptions_status', table_name='tenant_billing_engine_v1_subscriptions')
    op.drop_index('ix_tenant_billing_engine_v1_subscriptions_plan', table_name='tenant_billing_engine_v1_subscriptions')
    op.drop_index('ix_tenant_billing_engine_v1_subscriptions_company', table_name='tenant_billing_engine_v1_subscriptions')
    op.drop_table('tenant_billing_engine_v1_subscriptions')
    op.drop_index('ix_tenant_billing_engine_v1_invoices_tenant', table_name='tenant_billing_engine_v1_invoices')
    op.drop_index('ix_tenant_billing_engine_v1_invoices_status', table_name='tenant_billing_engine_v1_invoices')
    op.drop_index('ix_tenant_billing_engine_v1_invoices_period', table_name='tenant_billing_engine_v1_invoices')
    op.drop_index('ix_tenant_billing_engine_v1_invoices_company', table_name='tenant_billing_engine_v1_invoices')
    op.drop_table('tenant_billing_engine_v1_invoices')
    # ### end Alembic commands ###
