"""automotive_inventory_engine_v1

Revision ID: bab0e9908d23
Revises: 2cd3604be971
Create Date: 2026-07-12 20:14:11.976824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab0e9908d23'
down_revision: Union[str, None] = '2cd3604be971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_v1_vehicles',
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('drivetrain', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mileage >= 0', name='ck_automotive_v1_vehicles_mileage'),
    sa.CheckConstraint('year >= 1900', name='ck_automotive_v1_vehicles_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_number', name='uq_automotive_v1_vehicles_stock_number'),
    sa.UniqueConstraint('vin', name='uq_automotive_v1_vehicles_vin')
    )
    op.create_index('ix_automotive_v1_vehicles_make_model', 'automotive_v1_vehicles', ['make', 'model'], unique=False)
    op.create_index('ix_automotive_v1_vehicles_status', 'automotive_v1_vehicles', ['status'], unique=False)
    op.create_index('ix_automotive_v1_vehicles_year', 'automotive_v1_vehicles', ['year'], unique=False)
    op.create_table('automotive_v1_status_history',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_v1_status_history_to_status', 'automotive_v1_status_history', ['to_status'], unique=False)
    op.create_index('ix_automotive_v1_status_history_vehicle_id', 'automotive_v1_status_history', ['vehicle_id'], unique=False)
    op.create_table('automotive_v1_vehicle_documents',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_v1_vehicle_documents_document_type', 'automotive_v1_vehicle_documents', ['document_type'], unique=False)
    op.create_index('ix_automotive_v1_vehicle_documents_status', 'automotive_v1_vehicle_documents', ['status'], unique=False)
    op.create_index('ix_automotive_v1_vehicle_documents_vehicle_id', 'automotive_v1_vehicle_documents', ['vehicle_id'], unique=False)
    op.create_table('automotive_v1_vehicle_images',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_v1_vehicle_images_sort_order', 'automotive_v1_vehicle_images', ['sort_order'], unique=False)
    op.create_index('ix_automotive_v1_vehicle_images_vehicle_id', 'automotive_v1_vehicle_images', ['vehicle_id'], unique=False)
    op.create_table('automotive_v1_vehicle_locations',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_v1_vehicle_locations_is_current', 'automotive_v1_vehicle_locations', ['is_current'], unique=False)
    op.create_index('ix_automotive_v1_vehicle_locations_location_type', 'automotive_v1_vehicle_locations', ['location_type'], unique=False)
    op.create_index('ix_automotive_v1_vehicle_locations_vehicle_id', 'automotive_v1_vehicle_locations', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automotive_v1_vehicle_locations_vehicle_id', table_name='automotive_v1_vehicle_locations')
    op.drop_index('ix_automotive_v1_vehicle_locations_location_type', table_name='automotive_v1_vehicle_locations')
    op.drop_index('ix_automotive_v1_vehicle_locations_is_current', table_name='automotive_v1_vehicle_locations')
    op.drop_table('automotive_v1_vehicle_locations')
    op.drop_index('ix_automotive_v1_vehicle_images_vehicle_id', table_name='automotive_v1_vehicle_images')
    op.drop_index('ix_automotive_v1_vehicle_images_sort_order', table_name='automotive_v1_vehicle_images')
    op.drop_table('automotive_v1_vehicle_images')
    op.drop_index('ix_automotive_v1_vehicle_documents_vehicle_id', table_name='automotive_v1_vehicle_documents')
    op.drop_index('ix_automotive_v1_vehicle_documents_status', table_name='automotive_v1_vehicle_documents')
    op.drop_index('ix_automotive_v1_vehicle_documents_document_type', table_name='automotive_v1_vehicle_documents')
    op.drop_table('automotive_v1_vehicle_documents')
    op.drop_index('ix_automotive_v1_status_history_vehicle_id', table_name='automotive_v1_status_history')
    op.drop_index('ix_automotive_v1_status_history_to_status', table_name='automotive_v1_status_history')
    op.drop_table('automotive_v1_status_history')
    op.drop_index('ix_automotive_v1_vehicles_year', table_name='automotive_v1_vehicles')
    op.drop_index('ix_automotive_v1_vehicles_status', table_name='automotive_v1_vehicles')
    op.drop_index('ix_automotive_v1_vehicles_make_model', table_name='automotive_v1_vehicles')
    op.drop_table('automotive_v1_vehicles')
    # ### end Alembic commands ###
