"""auto_marketing_engine_v1

Revision ID: be831891e9d4
Revises: 16a1147c7485
Create Date: 2026-07-13 09:34:22.433501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be831891e9d4'
down_revision: Union[str, None] = '16a1147c7485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_marketing_engine_v1_post_templates',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('default_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_auto_marketing_engine_v1_templates_code')
    )
    op.create_index('ix_auto_marketing_engine_v1_templates_active', 'auto_marketing_engine_v1_post_templates', ['is_active'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_templates_channel', 'auto_marketing_engine_v1_post_templates', ['channel'], unique=False)
    op.create_table('auto_marketing_engine_v1_campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_marketing_engine_v1_campaigns_car', 'auto_marketing_engine_v1_campaigns', ['car_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_campaigns_owner', 'auto_marketing_engine_v1_campaigns', ['owner_user_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_campaigns_status', 'auto_marketing_engine_v1_campaigns', ['status'], unique=False)
    op.create_table('auto_marketing_engine_v1_media_assets',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['auto_marketing_engine_v1_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_marketing_engine_v1_media_campaign', 'auto_marketing_engine_v1_media_assets', ['campaign_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_media_car', 'auto_marketing_engine_v1_media_assets', ['car_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_media_type', 'auto_marketing_engine_v1_media_assets', ['media_type'], unique=False)
    op.create_table('auto_marketing_engine_v1_publications',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['auto_marketing_engine_v1_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['auto_marketing_engine_v1_post_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_marketing_engine_v1_pub_campaign', 'auto_marketing_engine_v1_publications', ['campaign_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_pub_car', 'auto_marketing_engine_v1_publications', ['car_id'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_pub_channel', 'auto_marketing_engine_v1_publications', ['channel'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_pub_scheduled', 'auto_marketing_engine_v1_publications', ['scheduled_at'], unique=False)
    op.create_index('ix_auto_marketing_engine_v1_pub_status', 'auto_marketing_engine_v1_publications', ['status'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_auto_marketing_engine_v1_pub_status', table_name='auto_marketing_engine_v1_publications')
    op.drop_index('ix_auto_marketing_engine_v1_pub_scheduled', table_name='auto_marketing_engine_v1_publications')
    op.drop_index('ix_auto_marketing_engine_v1_pub_channel', table_name='auto_marketing_engine_v1_publications')
    op.drop_index('ix_auto_marketing_engine_v1_pub_car', table_name='auto_marketing_engine_v1_publications')
    op.drop_index('ix_auto_marketing_engine_v1_pub_campaign', table_name='auto_marketing_engine_v1_publications')
    op.drop_table('auto_marketing_engine_v1_publications')
    op.drop_index('ix_auto_marketing_engine_v1_media_type', table_name='auto_marketing_engine_v1_media_assets')
    op.drop_index('ix_auto_marketing_engine_v1_media_car', table_name='auto_marketing_engine_v1_media_assets')
    op.drop_index('ix_auto_marketing_engine_v1_media_campaign', table_name='auto_marketing_engine_v1_media_assets')
    op.drop_table('auto_marketing_engine_v1_media_assets')
    op.drop_index('ix_auto_marketing_engine_v1_campaigns_status', table_name='auto_marketing_engine_v1_campaigns')
    op.drop_index('ix_auto_marketing_engine_v1_campaigns_owner', table_name='auto_marketing_engine_v1_campaigns')
    op.drop_index('ix_auto_marketing_engine_v1_campaigns_car', table_name='auto_marketing_engine_v1_campaigns')
    op.drop_table('auto_marketing_engine_v1_campaigns')
    op.drop_index('ix_auto_marketing_engine_v1_templates_channel', table_name='auto_marketing_engine_v1_post_templates')
    op.drop_index('ix_auto_marketing_engine_v1_templates_active', table_name='auto_marketing_engine_v1_post_templates')
    op.drop_table('auto_marketing_engine_v1_post_templates')
    # ### end Alembic commands ###
