"""public_api_gateway_v1

Revision ID: c445e3eba5e8
Revises: c4f1e8b23a01
Create Date: 2026-07-12 23:41:36.333306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c445e3eba5e8'
down_revision: Union[str, None] = 'c4f1e8b23a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_gateway_v1_api_clients',
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_api_gateway_v1_clients_client_id')
    )
    op.create_index('ix_api_gateway_v1_clients_status', 'api_gateway_v1_api_clients', ['status'], unique=False)
    op.create_table('api_gateway_v1_api_keys',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_gateway_v1_api_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_gateway_v1_keys_client_id', 'api_gateway_v1_api_keys', ['client_id'], unique=False)
    op.create_index('ix_api_gateway_v1_keys_prefix', 'api_gateway_v1_api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_gateway_v1_keys_status', 'api_gateway_v1_api_keys', ['status'], unique=False)
    op.create_table('api_gateway_v1_api_rate_limits',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('endpoint_pattern', sa.String(length=200), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('burst_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requests_per_hour > 0', name='ck_api_gateway_v1_rl_rph'),
    sa.CheckConstraint('requests_per_minute > 0', name='ck_api_gateway_v1_rl_rpm'),
    sa.ForeignKeyConstraint(['client_id'], ['api_gateway_v1_api_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_id'], ['api_gateway_v1_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_gateway_v1_rl_client_id', 'api_gateway_v1_api_rate_limits', ['client_id'], unique=False)
    op.create_index('ix_api_gateway_v1_rl_endpoint', 'api_gateway_v1_api_rate_limits', ['endpoint_pattern'], unique=False)
    op.create_table('api_gateway_v1_api_usage_logs',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('api_version', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_gateway_v1_api_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['key_id'], ['api_gateway_v1_api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_gateway_v1_usage_client_id', 'api_gateway_v1_api_usage_logs', ['client_id'], unique=False)
    op.create_index('ix_api_gateway_v1_usage_created_at', 'api_gateway_v1_api_usage_logs', ['created_at'], unique=False)
    op.create_index('ix_api_gateway_v1_usage_key_id', 'api_gateway_v1_api_usage_logs', ['key_id'], unique=False)
    op.create_index('ix_api_gateway_v1_usage_path', 'api_gateway_v1_api_usage_logs', ['path'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_api_gateway_v1_usage_path', table_name='api_gateway_v1_api_usage_logs')
    op.drop_index('ix_api_gateway_v1_usage_key_id', table_name='api_gateway_v1_api_usage_logs')
    op.drop_index('ix_api_gateway_v1_usage_created_at', table_name='api_gateway_v1_api_usage_logs')
    op.drop_index('ix_api_gateway_v1_usage_client_id', table_name='api_gateway_v1_api_usage_logs')
    op.drop_table('api_gateway_v1_api_usage_logs')
    op.drop_index('ix_api_gateway_v1_rl_endpoint', table_name='api_gateway_v1_api_rate_limits')
    op.drop_index('ix_api_gateway_v1_rl_client_id', table_name='api_gateway_v1_api_rate_limits')
    op.drop_table('api_gateway_v1_api_rate_limits')
    op.drop_index('ix_api_gateway_v1_keys_status', table_name='api_gateway_v1_api_keys')
    op.drop_index('ix_api_gateway_v1_keys_prefix', table_name='api_gateway_v1_api_keys')
    op.drop_index('ix_api_gateway_v1_keys_client_id', table_name='api_gateway_v1_api_keys')
    op.drop_table('api_gateway_v1_api_keys')
    op.drop_index('ix_api_gateway_v1_clients_status', table_name='api_gateway_v1_api_clients')
    op.drop_table('api_gateway_v1_api_clients')
    # ### end Alembic commands ###
