"""ledger_engine_foundation

Revision ID: caddeea0c765
Revises: 2d87a4df926e
Create Date: 2026-07-12 17:00:28.439891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caddeea0c765'
down_revision: Union[str, None] = '2d87a4df926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_engine_entries',
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('DEBIT', 'CREDIT')", name='ck_ledger_engine_entries_direction'),
    sa.CheckConstraint('amount > 0', name='ck_ledger_engine_entries_amount_positive'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_engine_deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_engine_entries_account_id', 'ledger_engine_entries', ['account_id'], unique=False)
    op.create_index('ix_ledger_engine_entries_account_type', 'ledger_engine_entries', ['account_type'], unique=False)
    op.create_index('ix_ledger_engine_entries_asset', 'ledger_engine_entries', ['asset'], unique=False)
    op.create_index('ix_ledger_engine_entries_deal_id', 'ledger_engine_entries', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_engine_entries_deal_id', table_name='ledger_engine_entries')
    op.drop_index('ix_ledger_engine_entries_asset', table_name='ledger_engine_entries')
    op.drop_index('ix_ledger_engine_entries_account_type', table_name='ledger_engine_entries')
    op.drop_index('ix_ledger_engine_entries_account_id', table_name='ledger_engine_entries')
    op.drop_table('ledger_engine_entries')
    # ### end Alembic commands ###
