"""automotive_service_engine_v1

Revision ID: cbdccd98e019
Revises: b9e4f1a23c07
Create Date: 2026-07-12 22:48:56.423700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdccd98e019'
down_revision: Union[str, None] = 'b9e4f1a23c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automotive_service_v1_service_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('labor_total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('parts_total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('diagnosis_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('labor_total >= 0', name='ck_automotive_service_v1_so_labor'),
    sa.CheckConstraint('parts_total >= 0', name='ck_automotive_service_v1_so_parts'),
    sa.CheckConstraint('total_cost >= 0', name='ck_automotive_service_v1_so_total'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number', name='uq_automotive_service_v1_service_orders_order_number')
    )
    op.create_index('ix_automotive_service_v1_so_status', 'automotive_service_v1_service_orders', ['status'], unique=False)
    op.create_index('ix_automotive_service_v1_so_vehicle_id', 'automotive_service_v1_service_orders', ['vehicle_id'], unique=False)
    op.create_table('automotive_service_v1_service_history',
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_service_v1_sh_order_id', 'automotive_service_v1_service_history', ['service_order_id'], unique=False)
    op.create_index('ix_automotive_service_v1_sh_to_status', 'automotive_service_v1_service_history', ['to_status'], unique=False)
    op.create_table('automotive_service_v1_service_operations',
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('labor_rate', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('technician_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('labor_cost >= 0', name='ck_automotive_service_v1_op_cost'),
    sa.CheckConstraint('labor_hours >= 0', name='ck_automotive_service_v1_op_hours'),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_service_v1_op_order_id', 'automotive_service_v1_service_operations', ['service_order_id'], unique=False)
    op.create_index('ix_automotive_service_v1_op_status', 'automotive_service_v1_service_operations', ['status'], unique=False)
    op.create_index('ix_automotive_service_v1_op_type', 'automotive_service_v1_service_operations', ['operation_type'], unique=False)
    op.create_table('automotive_service_v1_warranty_records',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('service_order_id', sa.UUID(), nullable=True),
    sa.Column('warranty_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mileage_limit', sa.Integer(), nullable=True),
    sa.Column('coverage_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['automotive_v1_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_service_v1_wr_expires_at', 'automotive_service_v1_warranty_records', ['expires_at'], unique=False)
    op.create_index('ix_automotive_service_v1_wr_order_id', 'automotive_service_v1_warranty_records', ['service_order_id'], unique=False)
    op.create_index('ix_automotive_service_v1_wr_status', 'automotive_service_v1_warranty_records', ['status'], unique=False)
    op.create_index('ix_automotive_service_v1_wr_vehicle_id', 'automotive_service_v1_warranty_records', ['vehicle_id'], unique=False)
    op.create_table('automotive_service_v1_service_parts',
    sa.Column('service_order_id', sa.UUID(), nullable=False),
    sa.Column('service_operation_id', sa.UUID(), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_automotive_service_v1_part_qty'),
    sa.CheckConstraint('total_price >= 0', name='ck_automotive_service_v1_part_total'),
    sa.ForeignKeyConstraint(['service_operation_id'], ['automotive_service_v1_service_operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_order_id'], ['automotive_service_v1_service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automotive_service_v1_part_operation_id', 'automotive_service_v1_service_parts', ['service_operation_id'], unique=False)
    op.create_index('ix_automotive_service_v1_part_order_id', 'automotive_service_v1_service_parts', ['service_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automotive_service_v1_part_order_id', table_name='automotive_service_v1_service_parts')
    op.drop_index('ix_automotive_service_v1_part_operation_id', table_name='automotive_service_v1_service_parts')
    op.drop_table('automotive_service_v1_service_parts')
    op.drop_index('ix_automotive_service_v1_wr_vehicle_id', table_name='automotive_service_v1_warranty_records')
    op.drop_index('ix_automotive_service_v1_wr_status', table_name='automotive_service_v1_warranty_records')
    op.drop_index('ix_automotive_service_v1_wr_order_id', table_name='automotive_service_v1_warranty_records')
    op.drop_index('ix_automotive_service_v1_wr_expires_at', table_name='automotive_service_v1_warranty_records')
    op.drop_table('automotive_service_v1_warranty_records')
    op.drop_index('ix_automotive_service_v1_op_type', table_name='automotive_service_v1_service_operations')
    op.drop_index('ix_automotive_service_v1_op_status', table_name='automotive_service_v1_service_operations')
    op.drop_index('ix_automotive_service_v1_op_order_id', table_name='automotive_service_v1_service_operations')
    op.drop_table('automotive_service_v1_service_operations')
    op.drop_index('ix_automotive_service_v1_sh_to_status', table_name='automotive_service_v1_service_history')
    op.drop_index('ix_automotive_service_v1_sh_order_id', table_name='automotive_service_v1_service_history')
    op.drop_table('automotive_service_v1_service_history')
    op.drop_index('ix_automotive_service_v1_so_vehicle_id', table_name='automotive_service_v1_service_orders')
    op.drop_index('ix_automotive_service_v1_so_status', table_name='automotive_service_v1_service_orders')
    op.drop_table('automotive_service_v1_service_orders')
    # ### end Alembic commands ###
