"""partner_engine_v1

Revision ID: d6adea147595
Revises: 90b2429b0170
Create Date: 2026-07-12 17:43:13.256804

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d6adea147595"
down_revision: Union[str, None] = "90b2429b0170"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("partner.created", "Emit or subscribe to partner created events"),
    ("partner.updated", "Emit or subscribe to partner updated events"),
    ("partner.blocked", "Emit or subscribe to partner blocked events"),
    ("partner.limit_exceeded", "Emit or subscribe to partner limit exceeded events"),
    ("partner.kyc_approved", "Emit or subscribe to partner KYC approved events"),
    ("partner.kyc_rejected", "Emit or subscribe to partner KYC rejected events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset(
        {
            "partner.created",
            "partner.updated",
            "partner.blocked",
            "partner.limit_exceeded",
            "partner.kyc_approved",
            "partner.kyc_rejected",
        }
    ),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "PARTNER": frozenset({"partner.updated", "partner.kyc_approved"}),
}


def _seed_partner_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_engine_partners',
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.String(length=30), nullable=False),
    sa.Column('aml_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_engine_partners_aml_status', 'partner_engine_partners', ['aml_status'], unique=False)
    op.create_index('ix_partner_engine_partners_company_name', 'partner_engine_partners', ['company_name'], unique=False)
    op.create_index('ix_partner_engine_partners_country', 'partner_engine_partners', ['country'], unique=False)
    op.create_index('ix_partner_engine_partners_kyc_status', 'partner_engine_partners', ['kyc_status'], unique=False)
    op.create_index('ix_partner_engine_partners_partner_type', 'partner_engine_partners', ['partner_type'], unique=False)
    op.create_index('ix_partner_engine_partners_risk_level', 'partner_engine_partners', ['risk_level'], unique=False)
    op.create_index('ix_partner_engine_partners_status', 'partner_engine_partners', ['status'], unique=False)
    op.create_table('partner_engine_commissions',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_partner_engine_commissions_value'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'asset', 'commission_type', name='uq_partner_engine_commissions_partner_asset_type')
    )
    op.create_index('ix_partner_engine_commissions_asset', 'partner_engine_commissions', ['asset'], unique=False)
    op.create_index('ix_partner_engine_commissions_partner_id', 'partner_engine_commissions', ['partner_id'], unique=False)
    op.create_table('partner_engine_contacts',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_engine_contacts_is_primary', 'partner_engine_contacts', ['is_primary'], unique=False)
    op.create_index('ix_partner_engine_contacts_partner_id', 'partner_engine_contacts', ['partner_id'], unique=False)
    op.create_table('partner_engine_limits',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_daily_volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_monthly_volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_daily_volume >= 0', name='ck_partner_engine_limits_daily_volume'),
    sa.CheckConstraint('current_monthly_volume >= 0', name='ck_partner_engine_limits_monthly_volume'),
    sa.CheckConstraint('daily_limit >= 0', name='ck_partner_engine_limits_daily_limit'),
    sa.CheckConstraint('monthly_limit >= 0', name='ck_partner_engine_limits_monthly_limit'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', name='uq_partner_engine_limits_partner_id')
    )
    op.create_table('partner_engine_wallets',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('wallet_type', sa.String(length=50), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_engine_wallets_asset', 'partner_engine_wallets', ['asset'], unique=False)
    op.create_index('ix_partner_engine_wallets_is_active', 'partner_engine_wallets', ['is_active'], unique=False)
    op.create_index('ix_partner_engine_wallets_partner_id', 'partner_engine_wallets', ['partner_id'], unique=False)
    _seed_partner_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partner_engine_wallets_partner_id', table_name='partner_engine_wallets')
    op.drop_index('ix_partner_engine_wallets_is_active', table_name='partner_engine_wallets')
    op.drop_index('ix_partner_engine_wallets_asset', table_name='partner_engine_wallets')
    op.drop_table('partner_engine_wallets')
    op.drop_table('partner_engine_limits')
    op.drop_index('ix_partner_engine_contacts_partner_id', table_name='partner_engine_contacts')
    op.drop_index('ix_partner_engine_contacts_is_primary', table_name='partner_engine_contacts')
    op.drop_table('partner_engine_contacts')
    op.drop_index('ix_partner_engine_commissions_partner_id', table_name='partner_engine_commissions')
    op.drop_index('ix_partner_engine_commissions_asset', table_name='partner_engine_commissions')
    op.drop_table('partner_engine_commissions')
    op.drop_index('ix_partner_engine_partners_status', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_risk_level', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_partner_type', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_kyc_status', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_country', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_company_name', table_name='partner_engine_partners')
    op.drop_index('ix_partner_engine_partners_aml_status', table_name='partner_engine_partners')
    op.drop_table('partner_engine_partners')
    # ### end Alembic commands ###
