"""ai_advertising_agent_v1

Revision ID: d7506c3a0146
Revises: ab1a2593ea2e
Create Date: 2026-07-13 11:44:54.823910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7506c3a0146'
down_revision: Union[str, None] = 'ab1a2593ea2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_advertising_agent_v1_campaigns',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('marketing_campaign_id', sa.UUID(), nullable=True),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('budget_allocated', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('budget_spent', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('audience_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bid_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ad_creative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_monitored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_spent >= 0', name='ck_ai_advertising_agent_v1_budget_spent'),
    sa.CheckConstraint('budget_total >= 0', name='ck_ai_advertising_agent_v1_budget_total'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketing_campaign_id'], ['auto_marketing_engine_v1_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_advertising_agent_v1_campaigns_car', 'ai_advertising_agent_v1_campaigns', ['car_id'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_campaigns_company', 'ai_advertising_agent_v1_campaigns', ['company_id'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_campaigns_marketing', 'ai_advertising_agent_v1_campaigns', ['marketing_campaign_id'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_campaigns_status', 'ai_advertising_agent_v1_campaigns', ['status'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_campaigns_tenant', 'ai_advertising_agent_v1_campaigns', ['tenant_id'], unique=False)
    op.create_table('ai_advertising_agent_v1_actions',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_ai_advertising_agent_v1_action_confidence'),
    sa.ForeignKeyConstraint(['campaign_id'], ['ai_advertising_agent_v1_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_advertising_agent_v1_actions_campaign', 'ai_advertising_agent_v1_actions', ['campaign_id'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_actions_tenant', 'ai_advertising_agent_v1_actions', ['tenant_id'], unique=False)
    op.create_index('ix_ai_advertising_agent_v1_actions_type', 'ai_advertising_agent_v1_actions', ['action_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_advertising_agent_v1_actions_type', table_name='ai_advertising_agent_v1_actions')
    op.drop_index('ix_ai_advertising_agent_v1_actions_tenant', table_name='ai_advertising_agent_v1_actions')
    op.drop_index('ix_ai_advertising_agent_v1_actions_campaign', table_name='ai_advertising_agent_v1_actions')
    op.drop_table('ai_advertising_agent_v1_actions')
    op.drop_index('ix_ai_advertising_agent_v1_campaigns_tenant', table_name='ai_advertising_agent_v1_campaigns')
    op.drop_index('ix_ai_advertising_agent_v1_campaigns_status', table_name='ai_advertising_agent_v1_campaigns')
    op.drop_index('ix_ai_advertising_agent_v1_campaigns_marketing', table_name='ai_advertising_agent_v1_campaigns')
    op.drop_index('ix_ai_advertising_agent_v1_campaigns_company', table_name='ai_advertising_agent_v1_campaigns')
    op.drop_index('ix_ai_advertising_agent_v1_campaigns_car', table_name='ai_advertising_agent_v1_campaigns')
    op.drop_table('ai_advertising_agent_v1_campaigns')
    # ### end Alembic commands ###
