"""settlement_engine_v1

Revision ID: d85e4567bcf9
Revises: 9bb577bff163
Create Date: 2026-07-12 18:08:25.127045

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d85e4567bcf9"
down_revision: Union[str, None] = "9bb577bff163"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("settlement.created", "Emit or subscribe to settlement created events"),
    ("settlement.started", "Emit or subscribe to settlement started events"),
    ("settlement.completed", "Emit or subscribe to settlement completed events"),
    ("settlement.failed", "Emit or subscribe to settlement failed events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ACCOUNTANT": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
}


def _seed_settlement_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlement_v1_settlements",
        sa.Column("deal_id", sa.UUID(), nullable=True),
        sa.Column("settlement_type", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_settlement_v1_settlements_amount"),
        sa.ForeignKeyConstraint(["deal_id"], ["deal_engine_deals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_settlement_v1_settlements_deal_id",
        "settlement_v1_settlements",
        ["deal_id"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_v1_settlements_settlement_type",
        "settlement_v1_settlements",
        ["settlement_type"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_v1_settlements_status",
        "settlement_v1_settlements",
        ["status"],
        unique=False,
    )
    op.create_table(
        "settlement_v1_routes",
        sa.Column("settlement_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlement_v1_settlements.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_settlement_v1_routes_settlement_id",
        "settlement_v1_routes",
        ["settlement_id"],
        unique=False,
    )
    op.create_table(
        "settlement_v1_steps",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_location", sa.String(length=100), nullable=True),
        sa.Column("destination_location", sa.String(length=100), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_settlement_v1_steps_amount"),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["settlement_v1_routes.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_settlement_v1_steps_route_id",
        "settlement_v1_steps",
        ["route_id"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_v1_steps_status",
        "settlement_v1_steps",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_v1_steps_step_order",
        "settlement_v1_steps",
        ["step_order"],
        unique=False,
    )
    op.create_table(
        "settlement_v1_status_history",
        sa.Column("settlement_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlement_v1_settlements.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["settlement_v1_steps.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_settlement_v1_status_history_settlement_id",
        "settlement_v1_status_history",
        ["settlement_id"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_v1_status_history_step_id",
        "settlement_v1_status_history",
        ["step_id"],
        unique=False,
    )
    _seed_settlement_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_settlement_v1_status_history_step_id",
        table_name="settlement_v1_status_history",
    )
    op.drop_index(
        "ix_settlement_v1_status_history_settlement_id",
        table_name="settlement_v1_status_history",
    )
    op.drop_table("settlement_v1_status_history")
    op.drop_index("ix_settlement_v1_steps_step_order", table_name="settlement_v1_steps")
    op.drop_index("ix_settlement_v1_steps_status", table_name="settlement_v1_steps")
    op.drop_index("ix_settlement_v1_steps_route_id", table_name="settlement_v1_steps")
    op.drop_table("settlement_v1_steps")
    op.drop_index("ix_settlement_v1_routes_settlement_id", table_name="settlement_v1_routes")
    op.drop_table("settlement_v1_routes")
    op.drop_index("ix_settlement_v1_settlements_status", table_name="settlement_v1_settlements")
    op.drop_index(
        "ix_settlement_v1_settlements_settlement_type",
        table_name="settlement_v1_settlements",
    )
    op.drop_index("ix_settlement_v1_settlements_deal_id", table_name="settlement_v1_settlements")
    op.drop_table("settlement_v1_settlements")
    # ### end Alembic commands ###
