"""document_engine_v1

Revision ID: df23cfb47bd6
Revises: 59c60a09395b
Create Date: 2026-07-12 23:16:54.259218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df23cfb47bd6'
down_revision: Union[str, None] = '59c60a09395b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_engine_v1_document_templates',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('default_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_document_engine_v1_templates_code')
    )
    op.create_index('ix_document_engine_v1_templates_is_active', 'document_engine_v1_document_templates', ['is_active'], unique=False)
    op.create_index('ix_document_engine_v1_templates_type', 'document_engine_v1_document_templates', ['document_type'], unique=False)
    op.create_table('document_engine_v1_documents',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['document_engine_v1_document_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_document_engine_v1_documents_reference_number')
    )
    op.create_index('ix_document_engine_v1_documents_entity', 'document_engine_v1_documents', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_document_engine_v1_documents_status', 'document_engine_v1_documents', ['status'], unique=False)
    op.create_index('ix_document_engine_v1_documents_type', 'document_engine_v1_documents', ['document_type'], unique=False)
    op.create_table('document_engine_v1_document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('generated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_engine_v1_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_engine_v1_versions_doc_version')
    )
    op.create_index('ix_document_engine_v1_versions_document_id', 'document_engine_v1_document_versions', ['document_id'], unique=False)
    op.create_table('document_engine_v1_document_signatures',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_role', sa.String(length=30), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_hash', sa.String(length=128), nullable=True),
    sa.Column('signed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_engine_v1_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_engine_v1_document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_engine_v1_signatures_document_id', 'document_engine_v1_document_signatures', ['document_id'], unique=False)
    op.create_index('ix_document_engine_v1_signatures_version_id', 'document_engine_v1_document_signatures', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_engine_v1_signatures_version_id', table_name='document_engine_v1_document_signatures')
    op.drop_index('ix_document_engine_v1_signatures_document_id', table_name='document_engine_v1_document_signatures')
    op.drop_table('document_engine_v1_document_signatures')
    op.drop_index('ix_document_engine_v1_versions_document_id', table_name='document_engine_v1_document_versions')
    op.drop_table('document_engine_v1_document_versions')
    op.drop_index('ix_document_engine_v1_documents_type', table_name='document_engine_v1_documents')
    op.drop_index('ix_document_engine_v1_documents_status', table_name='document_engine_v1_documents')
    op.drop_index('ix_document_engine_v1_documents_entity', table_name='document_engine_v1_documents')
    op.drop_table('document_engine_v1_documents')
    op.drop_index('ix_document_engine_v1_templates_type', table_name='document_engine_v1_document_templates')
    op.drop_index('ix_document_engine_v1_templates_is_active', table_name='document_engine_v1_document_templates')
    op.drop_table('document_engine_v1_document_templates')
    # ### end Alembic commands ###
