"""pricing_engine_v1

Revision ID: df6980c1c483
Revises: ecaaa726f29f
Create Date: 2026-07-12 17:54:15.952939

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "df6980c1c483"
down_revision: Union[str, None] = "ecaaa726f29f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("price.updated", "Emit or subscribe to price updated events"),
    ("spread.changed", "Emit or subscribe to spread changed events"),
    ("partner.price.updated", "Emit or subscribe to partner price updated events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
}


def _seed_pricing_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_v1_manager_pricing',
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('custom_margin', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('custom_margin >= 0', name='ck_pricing_v1_manager_pricing_margin'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'asset', name='uq_pricing_v1_manager_pricing_manager_asset')
    )
    op.create_index('ix_pricing_v1_manager_pricing_asset', 'pricing_v1_manager_pricing', ['asset'], unique=False)
    op.create_index('ix_pricing_v1_manager_pricing_manager_id', 'pricing_v1_manager_pricing', ['manager_id'], unique=False)
    op.create_table('pricing_v1_price_sources',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ask_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('ask_price > 0', name='ck_pricing_v1_price_sources_ask'),
    sa.CheckConstraint('bid_price > 0', name='ck_pricing_v1_price_sources_bid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'asset', name='uq_pricing_v1_price_sources_name_asset')
    )
    op.create_index('ix_pricing_v1_price_sources_asset', 'pricing_v1_price_sources', ['asset'], unique=False)
    op.create_index('ix_pricing_v1_price_sources_source_name', 'pricing_v1_price_sources', ['source_name'], unique=False)
    op.create_table('pricing_v1_spread_rules',
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('spread_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_pricing_v1_spread_rules_value'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_v1_spread_rules_asset', 'pricing_v1_spread_rules', ['asset'], unique=False)
    op.create_index('ix_pricing_v1_spread_rules_priority', 'pricing_v1_spread_rules', ['priority'], unique=False)
    op.create_table('pricing_v1_partner_pricing',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('custom_spread', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('custom_spread >= 0', name='ck_pricing_v1_partner_pricing_spread'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'asset', name='uq_pricing_v1_partner_pricing_partner_asset')
    )
    op.create_index('ix_pricing_v1_partner_pricing_asset', 'pricing_v1_partner_pricing', ['asset'], unique=False)
    op.create_index('ix_pricing_v1_partner_pricing_partner_id', 'pricing_v1_partner_pricing', ['partner_id'], unique=False)
    _seed_pricing_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_v1_partner_pricing_partner_id', table_name='pricing_v1_partner_pricing')
    op.drop_index('ix_pricing_v1_partner_pricing_asset', table_name='pricing_v1_partner_pricing')
    op.drop_table('pricing_v1_partner_pricing')
    op.drop_index('ix_pricing_v1_spread_rules_priority', table_name='pricing_v1_spread_rules')
    op.drop_index('ix_pricing_v1_spread_rules_asset', table_name='pricing_v1_spread_rules')
    op.drop_table('pricing_v1_spread_rules')
    op.drop_index('ix_pricing_v1_price_sources_source_name', table_name='pricing_v1_price_sources')
    op.drop_index('ix_pricing_v1_price_sources_asset', table_name='pricing_v1_price_sources')
    op.drop_table('pricing_v1_price_sources')
    op.drop_index('ix_pricing_v1_manager_pricing_manager_id', table_name='pricing_v1_manager_pricing')
    op.drop_index('ix_pricing_v1_manager_pricing_asset', table_name='pricing_v1_manager_pricing')
    op.drop_table('pricing_v1_manager_pricing')
    # ### end Alembic commands ###
