"""sales_pipeline_automation_engine_v1

Revision ID: eaf2c97f2297
Revises: 1c972a907102
Create Date: 2026-07-13 10:01:19.286343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaf2c97f2297'
down_revision: Union[str, None] = '1c972a907102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_automation_engine_v1_snapshots',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'period', name='uq_analytics_automation_engine_v1_snapshots_date_period')
    )
    op.create_index('ix_analytics_automation_engine_v1_snapshots_date', 'analytics_automation_engine_v1_snapshots', ['metric_date'], unique=False)
    op.create_index('ix_analytics_automation_engine_v1_snapshots_period', 'analytics_automation_engine_v1_snapshots', ['period'], unique=False)
    op.create_table('content_factory_engine_v1_content_items',
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'content_type', 'version', name='uq_content_factory_engine_v1_items_car_type_version')
    )
    op.create_index('ix_content_factory_engine_v1_items_car', 'content_factory_engine_v1_content_items', ['car_id'], unique=False)
    op.create_index('ix_content_factory_engine_v1_items_type', 'content_factory_engine_v1_content_items', ['content_type'], unique=False)
    op.create_table('sales_pipeline_automation_engine_v1_pipeline_leads',
    sa.Column('automation_lead_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('assigned_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automation_lead_id'], ['lead_automation_engine_v1_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['car_engine_v1_cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_pipeline_automation_engine_v1_pl_activity', 'sales_pipeline_automation_engine_v1_pipeline_leads', ['last_activity_at'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_pl_lead', 'sales_pipeline_automation_engine_v1_pipeline_leads', ['automation_lead_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_pl_manager', 'sales_pipeline_automation_engine_v1_pipeline_leads', ['assigned_manager_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_pl_stage', 'sales_pipeline_automation_engine_v1_pipeline_leads', ['stage'], unique=False)
    op.create_table('sales_pipeline_automation_engine_v1_follow_up_tasks',
    sa.Column('pipeline_lead_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_lead_id'], ['sales_pipeline_automation_engine_v1_pipeline_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_pipeline_automation_engine_v1_task_due', 'sales_pipeline_automation_engine_v1_follow_up_tasks', ['due_at'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_task_pl', 'sales_pipeline_automation_engine_v1_follow_up_tasks', ['pipeline_lead_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_task_status', 'sales_pipeline_automation_engine_v1_follow_up_tasks', ['status'], unique=False)
    op.create_table('sales_pipeline_automation_engine_v1_inactivity_alerts',
    sa.Column('pipeline_lead_id', sa.UUID(), nullable=False),
    sa.Column('inactive_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_lead_id'], ['sales_pipeline_automation_engine_v1_pipeline_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_pipeline_automation_engine_v1_alert_pl', 'sales_pipeline_automation_engine_v1_inactivity_alerts', ['pipeline_lead_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_alert_status', 'sales_pipeline_automation_engine_v1_inactivity_alerts', ['status'], unique=False)
    op.create_table('sales_pipeline_automation_engine_v1_reminders',
    sa.Column('pipeline_lead_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_lead_id'], ['sales_pipeline_automation_engine_v1_pipeline_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_pipeline_automation_engine_v1_rem_due', 'sales_pipeline_automation_engine_v1_reminders', ['due_at'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_rem_pl', 'sales_pipeline_automation_engine_v1_reminders', ['pipeline_lead_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_rem_status', 'sales_pipeline_automation_engine_v1_reminders', ['status'], unique=False)
    op.create_table('sales_pipeline_automation_engine_v1_stage_transitions',
    sa.Column('pipeline_lead_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=40), nullable=True),
    sa.Column('to_stage', sa.String(length=40), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_lead_id'], ['sales_pipeline_automation_engine_v1_pipeline_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_pipeline_automation_engine_v1_st_pl', 'sales_pipeline_automation_engine_v1_stage_transitions', ['pipeline_lead_id'], unique=False)
    op.create_index('ix_sales_pipeline_automation_engine_v1_st_to', 'sales_pipeline_automation_engine_v1_stage_transitions', ['to_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_pipeline_automation_engine_v1_st_to', table_name='sales_pipeline_automation_engine_v1_stage_transitions')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_st_pl', table_name='sales_pipeline_automation_engine_v1_stage_transitions')
    op.drop_table('sales_pipeline_automation_engine_v1_stage_transitions')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_rem_status', table_name='sales_pipeline_automation_engine_v1_reminders')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_rem_pl', table_name='sales_pipeline_automation_engine_v1_reminders')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_rem_due', table_name='sales_pipeline_automation_engine_v1_reminders')
    op.drop_table('sales_pipeline_automation_engine_v1_reminders')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_alert_status', table_name='sales_pipeline_automation_engine_v1_inactivity_alerts')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_alert_pl', table_name='sales_pipeline_automation_engine_v1_inactivity_alerts')
    op.drop_table('sales_pipeline_automation_engine_v1_inactivity_alerts')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_task_status', table_name='sales_pipeline_automation_engine_v1_follow_up_tasks')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_task_pl', table_name='sales_pipeline_automation_engine_v1_follow_up_tasks')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_task_due', table_name='sales_pipeline_automation_engine_v1_follow_up_tasks')
    op.drop_table('sales_pipeline_automation_engine_v1_follow_up_tasks')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_pl_stage', table_name='sales_pipeline_automation_engine_v1_pipeline_leads')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_pl_manager', table_name='sales_pipeline_automation_engine_v1_pipeline_leads')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_pl_lead', table_name='sales_pipeline_automation_engine_v1_pipeline_leads')
    op.drop_index('ix_sales_pipeline_automation_engine_v1_pl_activity', table_name='sales_pipeline_automation_engine_v1_pipeline_leads')
    op.drop_table('sales_pipeline_automation_engine_v1_pipeline_leads')
    op.drop_index('ix_content_factory_engine_v1_items_type', table_name='content_factory_engine_v1_content_items')
    op.drop_index('ix_content_factory_engine_v1_items_car', table_name='content_factory_engine_v1_content_items')
    op.drop_table('content_factory_engine_v1_content_items')
    op.drop_index('ix_analytics_automation_engine_v1_snapshots_period', table_name='analytics_automation_engine_v1_snapshots')
    op.drop_index('ix_analytics_automation_engine_v1_snapshots_date', table_name='analytics_automation_engine_v1_snapshots')
    op.drop_table('analytics_automation_engine_v1_snapshots')
    # ### end Alembic commands ###
