"""kyc_aml_engine_v1

Revision ID: ecaaa726f29f
Revises: d6adea147595
Create Date: 2026-07-12 17:49:49.016250

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "ecaaa726f29f"
down_revision: Union[str, None] = "d6adea147595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_EVENT_PERMISSIONS: tuple[tuple[str, str], ...] = (
    ("kyc.started", "Emit or subscribe to KYC started events"),
    ("kyc.approved", "Emit or subscribe to KYC approved events"),
    ("kyc.rejected", "Emit or subscribe to KYC rejected events"),
    ("aml.review_required", "Emit or subscribe to AML review required events"),
)

NEW_ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    "MANAGER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "ADMIN": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "OWNER": frozenset({code for code, _ in NEW_EVENT_PERMISSIONS}),
    "LAWYER": frozenset({"kyc.started", "kyc.approved", "kyc.rejected", "aml.review_required"}),
}


def _seed_compliance_event_permissions() -> None:
    bind = op.get_bind()
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    permission_ids: dict[str, uuid.UUID] = {}
    for code, description in NEW_EVENT_PERMISSIONS:
        existing = bind.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"),
            {"code": code},
        ).first()
        if existing:
            permission_ids[code] = existing[0]
            continue
        permission_id = uuid.uuid4()
        bind.execute(
            permissions_table.insert().values(
                id=permission_id,
                code=code,
                description=description,
            )
        )
        permission_ids[code] = permission_id

    for role_code, permission_codes in NEW_ROLE_PERMISSIONS.items():
        role_row = bind.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"),
            {"code": role_code},
        ).first()
        if not role_row:
            continue
        role_id = role_row[0]
        for permission_code in permission_codes:
            permission_id = permission_ids.get(permission_code)
            if permission_id is None:
                perm_row = bind.execute(
                    sa.text("SELECT id FROM permissions WHERE code = :code"),
                    {"code": permission_code},
                ).first()
                if not perm_row:
                    continue
                permission_id = perm_row[0]
            exists = bind.execute(
                sa.text(
                    "SELECT 1 FROM role_permissions "
                    "WHERE role_id = :role_id AND permission_id = :permission_id"
                ),
                {"role_id": role_id, "permission_id": permission_id},
            ).first()
            if exists:
                continue
            bind.execute(
                role_permissions_table.insert().values(
                    role_id=role_id,
                    permission_id=permission_id,
                )
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_engine_aml_checks',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_engine_aml_checks_check_type', 'compliance_engine_aml_checks', ['check_type'], unique=False)
    op.create_index('ix_compliance_engine_aml_checks_checked_at', 'compliance_engine_aml_checks', ['checked_at'], unique=False)
    op.create_index('ix_compliance_engine_aml_checks_partner_id', 'compliance_engine_aml_checks', ['partner_id'], unique=False)
    op.create_index('ix_compliance_engine_aml_checks_result', 'compliance_engine_aml_checks', ['result'], unique=False)
    op.create_table('compliance_engine_kyc_profiles',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('verification_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', name='uq_compliance_engine_kyc_profiles_partner_id')
    )
    op.create_index('ix_compliance_engine_kyc_profiles_entity_type', 'compliance_engine_kyc_profiles', ['entity_type'], unique=False)
    op.create_index('ix_compliance_engine_kyc_profiles_status', 'compliance_engine_kyc_profiles', ['status'], unique=False)
    op.create_index('ix_compliance_engine_kyc_profiles_verification_level', 'compliance_engine_kyc_profiles', ['verification_level'], unique=False)
    op.create_table('compliance_engine_risk_profiles',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_compliance_engine_risk_profiles_score_range'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_engine_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', name='uq_compliance_engine_risk_profiles_partner_id')
    )
    op.create_index('ix_compliance_engine_risk_profiles_risk_level', 'compliance_engine_risk_profiles', ['risk_level'], unique=False)
    op.create_table('compliance_engine_kyc_documents',
    sa.Column('kyc_profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('issue_country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['compliance_engine_kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_engine_kyc_documents_document_type', 'compliance_engine_kyc_documents', ['document_type'], unique=False)
    op.create_index('ix_compliance_engine_kyc_documents_profile_id', 'compliance_engine_kyc_documents', ['kyc_profile_id'], unique=False)
    op.create_index('ix_compliance_engine_kyc_documents_status', 'compliance_engine_kyc_documents', ['status'], unique=False)
    _seed_compliance_event_permissions()
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    codes = [code for code, _ in NEW_EVENT_PERMISSIONS]
    bind.execute(
        sa.text(
            "DELETE FROM role_permissions "
            "WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": codes},
    )
    bind.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": codes},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compliance_engine_kyc_documents_status', table_name='compliance_engine_kyc_documents')
    op.drop_index('ix_compliance_engine_kyc_documents_profile_id', table_name='compliance_engine_kyc_documents')
    op.drop_index('ix_compliance_engine_kyc_documents_document_type', table_name='compliance_engine_kyc_documents')
    op.drop_table('compliance_engine_kyc_documents')
    op.drop_index('ix_compliance_engine_risk_profiles_risk_level', table_name='compliance_engine_risk_profiles')
    op.drop_table('compliance_engine_risk_profiles')
    op.drop_index('ix_compliance_engine_kyc_profiles_verification_level', table_name='compliance_engine_kyc_profiles')
    op.drop_index('ix_compliance_engine_kyc_profiles_status', table_name='compliance_engine_kyc_profiles')
    op.drop_index('ix_compliance_engine_kyc_profiles_entity_type', table_name='compliance_engine_kyc_profiles')
    op.drop_table('compliance_engine_kyc_profiles')
    op.drop_index('ix_compliance_engine_aml_checks_result', table_name='compliance_engine_aml_checks')
    op.drop_index('ix_compliance_engine_aml_checks_partner_id', table_name='compliance_engine_aml_checks')
    op.drop_index('ix_compliance_engine_aml_checks_checked_at', table_name='compliance_engine_aml_checks')
    op.drop_index('ix_compliance_engine_aml_checks_check_type', table_name='compliance_engine_aml_checks')
    op.drop_table('compliance_engine_aml_checks')
    # ### end Alembic commands ###
