"""partner_tenant_engine_v1

Revision ID: f516fd3fbebe
Revises: eaf2c97f2297
Create Date: 2026-07-13 10:56:43.168120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f516fd3fbebe'
down_revision: Union[str, None] = 'eaf2c97f2297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_tenant_engine_v1_tenants',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_partner_tenant_engine_v1_tenants_company_code')
    )
    op.create_index('ix_partner_tenant_engine_v1_tenants_company', 'partner_tenant_engine_v1_tenants', ['company_id'], unique=False)
    op.create_index('ix_partner_tenant_engine_v1_tenants_status', 'partner_tenant_engine_v1_tenants', ['status'], unique=False)
    op.create_table('partner_tenant_engine_v1_billing_accounts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('treasury_code', sa.String(length=64), nullable=False),
    sa.Column('billing_plan', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_engine_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_type', 'asset', name='uq_partner_tenant_engine_v1_billing_tenant_type_asset')
    )
    op.create_index('ix_partner_tenant_engine_v1_billing_company', 'partner_tenant_engine_v1_billing_accounts', ['company_id'], unique=False)
    op.create_index('ix_partner_tenant_engine_v1_billing_tenant', 'partner_tenant_engine_v1_billing_accounts', ['tenant_id'], unique=False)
    op.create_table('partner_tenant_engine_v1_resource_bindings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'resource_type', 'resource_id', name='uq_partner_tenant_engine_v1_bindings_tenant_resource')
    )
    op.create_index('ix_partner_tenant_engine_v1_bindings_company', 'partner_tenant_engine_v1_resource_bindings', ['company_id'], unique=False)
    op.create_index('ix_partner_tenant_engine_v1_bindings_tenant', 'partner_tenant_engine_v1_resource_bindings', ['tenant_id'], unique=False)
    op.create_index('ix_partner_tenant_engine_v1_bindings_type', 'partner_tenant_engine_v1_resource_bindings', ['resource_type'], unique=False)
    op.create_table('partner_tenant_engine_v1_user_roles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['multi_company_v1_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['partner_tenant_engine_v1_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_partner_tenant_engine_v1_user_roles_tenant_user')
    )
    op.create_index('ix_partner_tenant_engine_v1_user_roles_tenant', 'partner_tenant_engine_v1_user_roles', ['tenant_id'], unique=False)
    op.create_index('ix_partner_tenant_engine_v1_user_roles_user', 'partner_tenant_engine_v1_user_roles', ['user_id'], unique=False)
    op.add_column('audit_engine_logs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('audit_engine_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index('ix_audit_engine_logs_company_id', 'audit_engine_logs', ['company_id'], unique=False)
    op.create_index('ix_audit_engine_logs_tenant_created', 'audit_engine_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_engine_logs_tenant_id', 'audit_engine_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_engine_logs_tenant_id', table_name='audit_engine_logs')
    op.drop_index('ix_audit_engine_logs_tenant_created', table_name='audit_engine_logs')
    op.drop_index('ix_audit_engine_logs_company_id', table_name='audit_engine_logs')
    op.drop_column('audit_engine_logs', 'tenant_id')
    op.drop_column('audit_engine_logs', 'company_id')
    op.drop_index('ix_partner_tenant_engine_v1_user_roles_user', table_name='partner_tenant_engine_v1_user_roles')
    op.drop_index('ix_partner_tenant_engine_v1_user_roles_tenant', table_name='partner_tenant_engine_v1_user_roles')
    op.drop_table('partner_tenant_engine_v1_user_roles')
    op.drop_index('ix_partner_tenant_engine_v1_bindings_type', table_name='partner_tenant_engine_v1_resource_bindings')
    op.drop_index('ix_partner_tenant_engine_v1_bindings_tenant', table_name='partner_tenant_engine_v1_resource_bindings')
    op.drop_index('ix_partner_tenant_engine_v1_bindings_company', table_name='partner_tenant_engine_v1_resource_bindings')
    op.drop_table('partner_tenant_engine_v1_resource_bindings')
    op.drop_index('ix_partner_tenant_engine_v1_billing_tenant', table_name='partner_tenant_engine_v1_billing_accounts')
    op.drop_index('ix_partner_tenant_engine_v1_billing_company', table_name='partner_tenant_engine_v1_billing_accounts')
    op.drop_table('partner_tenant_engine_v1_billing_accounts')
    op.drop_index('ix_partner_tenant_engine_v1_tenants_status', table_name='partner_tenant_engine_v1_tenants')
    op.drop_index('ix_partner_tenant_engine_v1_tenants_company', table_name='partner_tenant_engine_v1_tenants')
    op.drop_table('partner_tenant_engine_v1_tenants')
    # ### end Alembic commands ###
