"""trust_security_engine_v1

Revision ID: fd2f30a57d28
Revises: 0f9ead96c805
Create Date: 2026-07-13 11:10:57.898628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd2f30a57d28'
down_revision: Union[str, None] = '0f9ead96c805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_security_engine_v1_access_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_access_company', 'trust_security_engine_v1_access_logs', ['company_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_access_created', 'trust_security_engine_v1_access_logs', ['created_at'], unique=False)
    op.create_index('ix_trust_security_engine_v1_access_resource', 'trust_security_engine_v1_access_logs', ['resource_type'], unique=False)
    op.create_index('ix_trust_security_engine_v1_access_tenant', 'trust_security_engine_v1_access_logs', ['tenant_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_access_user', 'trust_security_engine_v1_access_logs', ['user_id'], unique=False)
    op.create_table('trust_security_engine_v1_api_access_logs',
    sa.Column('api_client_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_api_client', 'trust_security_engine_v1_api_access_logs', ['api_client_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_api_created', 'trust_security_engine_v1_api_access_logs', ['created_at'], unique=False)
    op.create_index('ix_trust_security_engine_v1_api_key', 'trust_security_engine_v1_api_access_logs', ['api_key_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_api_path', 'trust_security_engine_v1_api_access_logs', ['path'], unique=False)
    op.create_index('ix_trust_security_engine_v1_api_tenant', 'trust_security_engine_v1_api_access_logs', ['tenant_id'], unique=False)
    op.create_table('trust_security_engine_v1_content_approvals',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_ref', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_by', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_content_status', 'trust_security_engine_v1_content_approvals', ['status'], unique=False)
    op.create_index('ix_trust_security_engine_v1_content_submitter', 'trust_security_engine_v1_content_approvals', ['submitted_by'], unique=False)
    op.create_index('ix_trust_security_engine_v1_content_tenant', 'trust_security_engine_v1_content_approvals', ['tenant_id'], unique=False)
    op.create_table('trust_security_engine_v1_emergency_revokes',
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('target_ref', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('revoked_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('released_by', sa.BigInteger(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_revoke_scope', 'trust_security_engine_v1_emergency_revokes', ['scope'], unique=False)
    op.create_index('ix_trust_security_engine_v1_revoke_status', 'trust_security_engine_v1_emergency_revokes', ['status'], unique=False)
    op.create_index('ix_trust_security_engine_v1_revoke_target', 'trust_security_engine_v1_emergency_revokes', ['target_ref'], unique=False)
    op.create_index('ix_trust_security_engine_v1_revoke_tenant', 'trust_security_engine_v1_emergency_revokes', ['tenant_id'], unique=False)
    op.create_table('trust_security_engine_v1_export_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_export_resource', 'trust_security_engine_v1_export_logs', ['resource_type'], unique=False)
    op.create_index('ix_trust_security_engine_v1_export_tenant', 'trust_security_engine_v1_export_logs', ['tenant_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_export_user', 'trust_security_engine_v1_export_logs', ['user_id'], unique=False)
    op.create_table('trust_security_engine_v1_permission_audits',
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.Column('audit_action', sa.String(length=30), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_security_engine_v1_perm_action', 'trust_security_engine_v1_permission_audits', ['audit_action'], unique=False)
    op.create_index('ix_trust_security_engine_v1_perm_actor', 'trust_security_engine_v1_permission_audits', ['actor_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_perm_subject', 'trust_security_engine_v1_permission_audits', ['subject_user_id'], unique=False)
    op.create_index('ix_trust_security_engine_v1_perm_tenant', 'trust_security_engine_v1_permission_audits', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trust_security_engine_v1_perm_tenant', table_name='trust_security_engine_v1_permission_audits')
    op.drop_index('ix_trust_security_engine_v1_perm_subject', table_name='trust_security_engine_v1_permission_audits')
    op.drop_index('ix_trust_security_engine_v1_perm_actor', table_name='trust_security_engine_v1_permission_audits')
    op.drop_index('ix_trust_security_engine_v1_perm_action', table_name='trust_security_engine_v1_permission_audits')
    op.drop_table('trust_security_engine_v1_permission_audits')
    op.drop_index('ix_trust_security_engine_v1_export_user', table_name='trust_security_engine_v1_export_logs')
    op.drop_index('ix_trust_security_engine_v1_export_tenant', table_name='trust_security_engine_v1_export_logs')
    op.drop_index('ix_trust_security_engine_v1_export_resource', table_name='trust_security_engine_v1_export_logs')
    op.drop_table('trust_security_engine_v1_export_logs')
    op.drop_index('ix_trust_security_engine_v1_revoke_tenant', table_name='trust_security_engine_v1_emergency_revokes')
    op.drop_index('ix_trust_security_engine_v1_revoke_target', table_name='trust_security_engine_v1_emergency_revokes')
    op.drop_index('ix_trust_security_engine_v1_revoke_status', table_name='trust_security_engine_v1_emergency_revokes')
    op.drop_index('ix_trust_security_engine_v1_revoke_scope', table_name='trust_security_engine_v1_emergency_revokes')
    op.drop_table('trust_security_engine_v1_emergency_revokes')
    op.drop_index('ix_trust_security_engine_v1_content_tenant', table_name='trust_security_engine_v1_content_approvals')
    op.drop_index('ix_trust_security_engine_v1_content_submitter', table_name='trust_security_engine_v1_content_approvals')
    op.drop_index('ix_trust_security_engine_v1_content_status', table_name='trust_security_engine_v1_content_approvals')
    op.drop_table('trust_security_engine_v1_content_approvals')
    op.drop_index('ix_trust_security_engine_v1_api_tenant', table_name='trust_security_engine_v1_api_access_logs')
    op.drop_index('ix_trust_security_engine_v1_api_path', table_name='trust_security_engine_v1_api_access_logs')
    op.drop_index('ix_trust_security_engine_v1_api_key', table_name='trust_security_engine_v1_api_access_logs')
    op.drop_index('ix_trust_security_engine_v1_api_created', table_name='trust_security_engine_v1_api_access_logs')
    op.drop_index('ix_trust_security_engine_v1_api_client', table_name='trust_security_engine_v1_api_access_logs')
    op.drop_table('trust_security_engine_v1_api_access_logs')
    op.drop_index('ix_trust_security_engine_v1_access_user', table_name='trust_security_engine_v1_access_logs')
    op.drop_index('ix_trust_security_engine_v1_access_tenant', table_name='trust_security_engine_v1_access_logs')
    op.drop_index('ix_trust_security_engine_v1_access_resource', table_name='trust_security_engine_v1_access_logs')
    op.drop_index('ix_trust_security_engine_v1_access_created', table_name='trust_security_engine_v1_access_logs')
    op.drop_index('ix_trust_security_engine_v1_access_company', table_name='trust_security_engine_v1_access_logs')
    op.drop_table('trust_security_engine_v1_access_logs')
    # ### end Alembic commands ###
