"""Register Agro Enterprise routes (Sprint 14.0 + 14.1)."""

from __future__ import annotations

from aiohttp import web

from applications.agro_enterprise.api import (
    agro_finance_handlers,
    ai_agronomist_handlers,
    controlled_environment_handlers,
    crop_ai_handlers,
    enterprise_certification_handlers,
    handlers,
    irrigation_handlers,
    precision_handlers,
    supply_chain_handlers,
)
from applications.agro_enterprise.api.middleware import auth_middleware
from applications.agro_enterprise.config import DEFAULT_CONFIG


def register_agro_enterprise_routes(app: web.Application) -> None:
    prefix = DEFAULT_CONFIG.api_prefix
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    app.router.add_get(f"{prefix}/health", handlers.health_handler)
    app.router.add_post(f"{prefix}/bootstrap", handlers.bootstrap_handler)
    app.router.add_get(f"{prefix}/marketplace", handlers.marketplace_handler)
    app.router.add_post(f"{prefix}/marketplace", handlers.marketplace_handler)
    app.router.add_get(f"{prefix}/farms", handlers.farms_handler)
    app.router.add_post(f"{prefix}/farms", handlers.farms_handler)
    app.router.add_get(f"{prefix}/crops", handlers.crops_handler)
    app.router.add_post(f"{prefix}/crops", handlers.crops_handler)
    app.router.add_get(f"{prefix}/crm", handlers.crm_handler)
    app.router.add_post(f"{prefix}/crm", handlers.crm_handler)
    app.router.add_get(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_post(f"{prefix}/knowledge", handlers.knowledge_handler)
    app.router.add_get(f"{prefix}/dashboard", handlers.dashboard_handler)
    app.router.add_post(f"{prefix}/dashboard", handlers.dashboard_handler)

    # Sprint 14.1 — Precision Agriculture (additive)
    pa = DEFAULT_CONFIG.precision_agriculture_api_prefix
    app.router.add_get(f"{pa}/health", precision_handlers.pa_health_handler)
    app.router.add_post(f"{pa}/bootstrap", precision_handlers.pa_bootstrap_handler)
    app.router.add_get(f"{pa}/fields", precision_handlers.pa_fields_handler)
    app.router.add_post(f"{pa}/fields", precision_handlers.pa_fields_handler)
    app.router.add_get(f"{pa}/gis", precision_handlers.pa_gis_handler)
    app.router.add_post(f"{pa}/gis", precision_handlers.pa_gis_handler)
    app.router.add_get(f"{pa}/drone", precision_handlers.pa_drone_handler)
    app.router.add_post(f"{pa}/drone", precision_handlers.pa_drone_handler)
    app.router.add_get(f"{pa}/satellite", precision_handlers.pa_satellite_handler)
    app.router.add_post(f"{pa}/satellite", precision_handlers.pa_satellite_handler)
    app.router.add_get(f"{pa}/iot", precision_handlers.pa_iot_handler)
    app.router.add_post(f"{pa}/iot", precision_handlers.pa_iot_handler)
    app.router.add_get(f"{pa}/ai", precision_handlers.pa_ai_handler)
    app.router.add_post(f"{pa}/ai", precision_handlers.pa_ai_handler)
    app.router.add_get(f"{pa}/dashboard", precision_handlers.pa_dashboard_handler)
    app.router.add_post(f"{pa}/dashboard", precision_handlers.pa_dashboard_handler)
    app.router.add_get(f"{pa}/knowledge", precision_handlers.pa_knowledge_handler)
    app.router.add_post(f"{pa}/knowledge", precision_handlers.pa_knowledge_handler)

    # Sprint 14.2 — Smart Irrigation (additive; prior sprint routes unchanged)
    si = DEFAULT_CONFIG.smart_irrigation_api_prefix
    app.router.add_get(f"{si}/health", irrigation_handlers.si_health_handler)
    app.router.add_post(f"{si}/bootstrap", irrigation_handlers.si_bootstrap_handler)
    app.router.add_get(f"{si}/soil", irrigation_handlers.si_soil_handler)
    app.router.add_post(f"{si}/soil", irrigation_handlers.si_soil_handler)
    app.router.add_get(f"{si}/water", irrigation_handlers.si_water_handler)
    app.router.add_post(f"{si}/water", irrigation_handlers.si_water_handler)
    app.router.add_get(f"{si}/irrigation", irrigation_handlers.si_irrigation_handler)
    app.router.add_post(f"{si}/irrigation", irrigation_handlers.si_irrigation_handler)
    app.router.add_get(f"{si}/iot", irrigation_handlers.si_iot_handler)
    app.router.add_post(f"{si}/iot", irrigation_handlers.si_iot_handler)
    app.router.add_get(f"{si}/ai", irrigation_handlers.si_ai_handler)
    app.router.add_post(f"{si}/ai", irrigation_handlers.si_ai_handler)
    app.router.add_get(f"{si}/environment", irrigation_handlers.si_environment_handler)
    app.router.add_post(f"{si}/environment", irrigation_handlers.si_environment_handler)
    app.router.add_get(f"{si}/dashboard", irrigation_handlers.si_dashboard_handler)
    app.router.add_post(f"{si}/dashboard", irrigation_handlers.si_dashboard_handler)
    app.router.add_get(f"{si}/knowledge", irrigation_handlers.si_knowledge_handler)
    app.router.add_post(f"{si}/knowledge", irrigation_handlers.si_knowledge_handler)

    # Sprint 14.3 — Crop AI (additive; prior sprint routes unchanged)
    ca = DEFAULT_CONFIG.crop_ai_api_prefix
    app.router.add_get(f"{ca}/health", crop_ai_handlers.ca_health_handler)
    app.router.add_post(f"{ca}/bootstrap", crop_ai_handlers.ca_bootstrap_handler)
    app.router.add_get(f"{ca}/crops", crop_ai_handlers.ca_crops_handler)
    app.router.add_post(f"{ca}/crops", crop_ai_handlers.ca_crops_handler)
    app.router.add_get(f"{ca}/disease", crop_ai_handlers.ca_disease_handler)
    app.router.add_post(f"{ca}/disease", crop_ai_handlers.ca_disease_handler)
    app.router.add_get(f"{ca}/pests", crop_ai_handlers.ca_pest_handler)
    app.router.add_post(f"{ca}/pests", crop_ai_handlers.ca_pest_handler)
    app.router.add_get(f"{ca}/yield", crop_ai_handlers.ca_yield_handler)
    app.router.add_post(f"{ca}/yield", crop_ai_handlers.ca_yield_handler)
    app.router.add_get(f"{ca}/ops", crop_ai_handlers.ca_ops_handler)
    app.router.add_post(f"{ca}/ops", crop_ai_handlers.ca_ops_handler)
    app.router.add_get(f"{ca}/decisions", crop_ai_handlers.ca_decisions_handler)
    app.router.add_post(f"{ca}/decisions", crop_ai_handlers.ca_decisions_handler)
    app.router.add_get(f"{ca}/dashboard", crop_ai_handlers.ca_dashboard_handler)
    app.router.add_post(f"{ca}/dashboard", crop_ai_handlers.ca_dashboard_handler)
    app.router.add_get(f"{ca}/knowledge", crop_ai_handlers.ca_knowledge_handler)
    app.router.add_post(f"{ca}/knowledge", crop_ai_handlers.ca_knowledge_handler)

    # Sprint 14.4 — Controlled Environment (additive; prior sprint routes unchanged)
    ce = DEFAULT_CONFIG.controlled_environment_api_prefix
    app.router.add_get(f"{ce}/health", controlled_environment_handlers.ce_health_handler)
    app.router.add_post(f"{ce}/bootstrap", controlled_environment_handlers.ce_bootstrap_handler)
    app.router.add_get(f"{ce}/greenhouse", controlled_environment_handlers.ce_greenhouse_handler)
    app.router.add_post(f"{ce}/greenhouse", controlled_environment_handlers.ce_greenhouse_handler)
    app.router.add_get(f"{ce}/climate-ai", controlled_environment_handlers.ce_climate_ai_handler)
    app.router.add_post(f"{ce}/climate-ai", controlled_environment_handlers.ce_climate_ai_handler)
    app.router.add_get(f"{ce}/livestock", controlled_environment_handlers.ce_livestock_handler)
    app.router.add_post(f"{ce}/livestock", controlled_environment_handlers.ce_livestock_handler)
    app.router.add_get(f"{ce}/poultry", controlled_environment_handlers.ce_poultry_handler)
    app.router.add_post(f"{ce}/poultry", controlled_environment_handlers.ce_poultry_handler)
    app.router.add_get(f"{ce}/aquaculture", controlled_environment_handlers.ce_aquaculture_handler)
    app.router.add_post(f"{ce}/aquaculture", controlled_environment_handlers.ce_aquaculture_handler)
    app.router.add_get(f"{ce}/biosecurity", controlled_environment_handlers.ce_biosecurity_handler)
    app.router.add_post(f"{ce}/biosecurity", controlled_environment_handlers.ce_biosecurity_handler)
    app.router.add_get(f"{ce}/dashboard", controlled_environment_handlers.ce_dashboard_handler)
    app.router.add_post(f"{ce}/dashboard", controlled_environment_handlers.ce_dashboard_handler)
    app.router.add_get(f"{ce}/knowledge", controlled_environment_handlers.ce_knowledge_handler)
    app.router.add_post(f"{ce}/knowledge", controlled_environment_handlers.ce_knowledge_handler)

    # Sprint 14.5 — Agro Supply Chain (additive; prior sprint routes unchanged)
    sc = DEFAULT_CONFIG.supply_chain_api_prefix
    app.router.add_get(f"{sc}/health", supply_chain_handlers.sc_health_handler)
    app.router.add_post(f"{sc}/bootstrap", supply_chain_handlers.sc_bootstrap_handler)
    app.router.add_get(f"{sc}/supply", supply_chain_handlers.sc_supply_handler)
    app.router.add_post(f"{sc}/supply", supply_chain_handlers.sc_supply_handler)
    app.router.add_get(f"{sc}/elevator", supply_chain_handlers.sc_elevator_handler)
    app.router.add_post(f"{sc}/elevator", supply_chain_handlers.sc_elevator_handler)
    app.router.add_get(f"{sc}/quality", supply_chain_handlers.sc_quality_handler)
    app.router.add_post(f"{sc}/quality", supply_chain_handlers.sc_quality_handler)
    app.router.add_get(f"{sc}/warehouse", supply_chain_handlers.sc_warehouse_handler)
    app.router.add_post(f"{sc}/warehouse", supply_chain_handlers.sc_warehouse_handler)
    app.router.add_get(f"{sc}/logistics", supply_chain_handlers.sc_logistics_handler)
    app.router.add_post(f"{sc}/logistics", supply_chain_handlers.sc_logistics_handler)
    app.router.add_get(f"{sc}/export", supply_chain_handlers.sc_export_handler)
    app.router.add_post(f"{sc}/export", supply_chain_handlers.sc_export_handler)
    app.router.add_get(f"{sc}/dashboard", supply_chain_handlers.sc_dashboard_handler)
    app.router.add_post(f"{sc}/dashboard", supply_chain_handlers.sc_dashboard_handler)
    app.router.add_get(f"{sc}/knowledge", supply_chain_handlers.sc_knowledge_handler)
    app.router.add_post(f"{sc}/knowledge", supply_chain_handlers.sc_knowledge_handler)

    # Sprint 14.6 — Agro Finance (additive; prior sprint routes unchanged)
    af = DEFAULT_CONFIG.agro_finance_api_prefix
    app.router.add_get(f"{af}/health", agro_finance_handlers.af_health_handler)
    app.router.add_post(f"{af}/bootstrap", agro_finance_handlers.af_bootstrap_handler)
    app.router.add_get(f"{af}/exchange", agro_finance_handlers.af_exchange_handler)
    app.router.add_post(f"{af}/exchange", agro_finance_handlers.af_exchange_handler)
    app.router.add_get(f"{af}/contracts", agro_finance_handlers.af_contracts_handler)
    app.router.add_post(f"{af}/contracts", agro_finance_handlers.af_contracts_handler)
    app.router.add_get(f"{af}/finance", agro_finance_handlers.af_finance_handler)
    app.router.add_post(f"{af}/finance", agro_finance_handlers.af_finance_handler)
    app.router.add_get(f"{af}/insurance", agro_finance_handlers.af_insurance_handler)
    app.router.add_post(f"{af}/insurance", agro_finance_handlers.af_insurance_handler)
    app.router.add_get(f"{af}/risk", agro_finance_handlers.af_risk_handler)
    app.router.add_post(f"{af}/risk", agro_finance_handlers.af_risk_handler)
    app.router.add_get(f"{af}/market", agro_finance_handlers.af_market_handler)
    app.router.add_post(f"{af}/market", agro_finance_handlers.af_market_handler)
    app.router.add_get(f"{af}/dashboard", agro_finance_handlers.af_dashboard_handler)
    app.router.add_post(f"{af}/dashboard", agro_finance_handlers.af_dashboard_handler)
    app.router.add_get(f"{af}/knowledge", agro_finance_handlers.af_knowledge_handler)
    app.router.add_post(f"{af}/knowledge", agro_finance_handlers.af_knowledge_handler)

    # Sprint 14.7 — AI Agronomist (additive; prior sprint routes unchanged)
    aa = DEFAULT_CONFIG.ai_agronomist_api_prefix
    app.router.add_get(f"{aa}/health", ai_agronomist_handlers.aa_health_handler)
    app.router.add_post(f"{aa}/bootstrap", ai_agronomist_handlers.aa_bootstrap_handler)
    app.router.add_get(f"{aa}/agronomist", ai_agronomist_handlers.aa_agronomist_handler)
    app.router.add_post(f"{aa}/agronomist", ai_agronomist_handlers.aa_agronomist_handler)
    app.router.add_get(f"{aa}/decisions", ai_agronomist_handlers.aa_decisions_handler)
    app.router.add_post(f"{aa}/decisions", ai_agronomist_handlers.aa_decisions_handler)
    app.router.add_get(f"{aa}/planning", ai_agronomist_handlers.aa_planning_handler)
    app.router.add_post(f"{aa}/planning", ai_agronomist_handlers.aa_planning_handler)
    app.router.add_get(f"{aa}/forecast", ai_agronomist_handlers.aa_forecast_handler)
    app.router.add_post(f"{aa}/forecast", ai_agronomist_handlers.aa_forecast_handler)
    app.router.add_get(f"{aa}/optimization", ai_agronomist_handlers.aa_optimization_handler)
    app.router.add_post(f"{aa}/optimization", ai_agronomist_handlers.aa_optimization_handler)
    app.router.add_get(f"{aa}/executive", ai_agronomist_handlers.aa_executive_handler)
    app.router.add_post(f"{aa}/executive", ai_agronomist_handlers.aa_executive_handler)
    app.router.add_get(f"{aa}/dashboard", ai_agronomist_handlers.aa_dashboard_handler)
    app.router.add_post(f"{aa}/dashboard", ai_agronomist_handlers.aa_dashboard_handler)
    app.router.add_get(f"{aa}/knowledge", ai_agronomist_handlers.aa_knowledge_handler)
    app.router.add_post(f"{aa}/knowledge", ai_agronomist_handlers.aa_knowledge_handler)

    # Sprint 14.8 — Agro Enterprise Certification (additive; prior sprint routes unchanged)
    aec = DEFAULT_CONFIG.enterprise_certification_api_prefix
    app.router.add_get(f"{aec}/health", enterprise_certification_handlers.aec_health_handler)
    app.router.add_post(f"{aec}/bootstrap", enterprise_certification_handlers.aec_bootstrap_handler)
    app.router.add_get(f"{aec}/architecture", enterprise_certification_handlers.aec_architecture_handler)
    app.router.add_get(f"{aec}/integration", enterprise_certification_handlers.aec_integration_handler)
    app.router.add_get(f"{aec}/performance", enterprise_certification_handlers.aec_performance_handler)
    app.router.add_get(f"{aec}/security", enterprise_certification_handlers.aec_security_handler)
    app.router.add_get(f"{aec}/documentation", enterprise_certification_handlers.aec_documentation_handler)
    app.router.add_get(f"{aec}/quality", enterprise_certification_handlers.aec_quality_handler)
    app.router.add_post(f"{aec}/quality", enterprise_certification_handlers.aec_quality_handler)
    app.router.add_get(f"{aec}/release", enterprise_certification_handlers.aec_release_handler)
    app.router.add_get(f"{aec}/executive", enterprise_certification_handlers.aec_executive_handler)
    app.router.add_get(f"{aec}/dashboard", enterprise_certification_handlers.aec_dashboard_handler)
    app.router.add_post(f"{aec}/dashboard", enterprise_certification_handlers.aec_dashboard_handler)

    # AGRO Production 1.0 — durable ops desk (additive; prior routes unchanged)
    from applications.agro_enterprise.api import ops_handlers

    ops = "/api/agro-ops/v1"
    app.router.add_get(f"{ops}/health", ops_handlers.ops_health_handler)
    app.router.add_get(f"{ops}/roles", ops_handlers.ops_roles_handler)
    app.router.add_get(f"{ops}/catalogs", ops_handlers.ops_catalogs_handler)
    app.router.add_get(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_post(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_get(f"{ops}/command-center", ops_handlers.ops_command_center_handler)
    app.router.add_get(f"{ops}/command-center/report", ops_handlers.ops_management_report_handler)
    app.router.add_get(f"{ops}/search", ops_handlers.ops_search_handler)
    app.router.add_get(f"{ops}/crm/list", ops_handlers.ops_crm_list_handler)
    app.router.add_get(f"{ops}/crm/counterparty/{{item_id}}", ops_handlers.ops_crm_counterparty_handler)
    app.router.add_get(f"{ops}/crm/deal/{{item_id}}", ops_handlers.ops_crm_deal_handler)
    app.router.add_post(f"{ops}/crm/deal/{{item_id}}/status", ops_handlers.ops_crm_deal_status_handler)
    app.router.add_get(f"{ops}/crm/duplicates", ops_handlers.ops_crm_duplicates_handler)
    app.router.add_post(f"{ops}/crm/import", ops_handlers.ops_crm_import_handler)
    app.router.add_get(f"{ops}/crm/export", ops_handlers.ops_crm_export_handler)
    app.router.add_post(f"{ops}/crm/communication", ops_handlers.ops_crm_communication_handler)
    app.router.add_post(f"{ops}/crm/note", ops_handlers.ops_crm_note_handler)
    app.router.add_post(f"{ops}/crm/follow-up", ops_handlers.ops_crm_followup_handler)
    app.router.add_get(f"{ops}/crm/analytics", ops_handlers.ops_crm_analytics_handler)
    app.router.add_get(f"{ops}/operations/today", ops_handlers.ops_operations_today_handler)
    app.router.add_get(f"{ops}/operations/stock", ops_handlers.ops_operations_stock_handler)
    app.router.add_post(f"{ops}/operations/fifo-suggest", ops_handlers.ops_operations_fifo_handler)
    app.router.add_post(f"{ops}/operations/truck/{{item_id}}/status", ops_handlers.ops_truck_status_handler)
    app.router.add_post(f"{ops}/operations/exceptions/{{item_id}}", ops_handlers.ops_exception_status_handler)
    app.router.add_get(f"{ops}/operations", ops_handlers.ops_operations_list_handler)
    app.router.add_post(f"{ops}/operations", ops_handlers.ops_operations_list_handler)
    app.router.add_get(f"{ops}/operations/{{item_id}}", ops_handlers.ops_operation_get_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/status", ops_handlers.ops_operation_status_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/weighing", ops_handlers.ops_operation_weighing_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/quality", ops_handlers.ops_operation_quality_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/quality-decision", ops_handlers.ops_operation_quality_decision_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/receive", ops_handlers.ops_operation_receive_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/process", ops_handlers.ops_operation_process_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/allocate", ops_handlers.ops_operation_allocate_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/sale", ops_handlers.ops_operation_allocate_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/expense", ops_handlers.ops_operation_expense_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/truck", ops_handlers.ops_operation_truck_handler)
    app.router.add_post(f"{ops}/operations/{{item_id}}/transfer", ops_handlers.ops_operation_transfer_handler)
    app.router.add_get(f"{ops}/fields/map", ops_handlers.ops_fields_map_handler)
    app.router.add_get(f"{ops}/fields/today", ops_handlers.ops_fields_today_handler)
    app.router.add_get(f"{ops}/fields/director", ops_handlers.ops_fields_director_handler)
    app.router.add_get(f"{ops}/fields/crop-structure", ops_handlers.ops_crop_structure_handler)
    app.router.add_get(f"{ops}/fields/crop-costs", ops_handlers.ops_crop_costs_handler)
    app.router.add_get(f"{ops}/fields", ops_handlers.ops_fields_handler)
    app.router.add_post(f"{ops}/fields", ops_handlers.ops_fields_handler)
    app.router.add_post(f"{ops}/fields/works/{{item_id}}/status", ops_handlers.ops_work_status_handler)
    app.router.add_get(f"{ops}/fields/{{item_id}}", ops_handlers.ops_field_360_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}", ops_handlers.ops_field_update_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}/archive", ops_handlers.ops_field_archive_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}/season", ops_handlers.ops_field_season_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}/work", ops_handlers.ops_field_work_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}/harvest", ops_handlers.ops_field_harvest_handler)
    app.router.add_post(f"{ops}/fields/{{item_id}}/issue", ops_handlers.ops_field_issue_handler)
    # AGRO 2.6 modules
    app.router.add_get(f"{ops}/agro-crops", ops_handlers.ops_agro_crops_handler)
    app.router.add_post(f"{ops}/agro-crops", ops_handlers.ops_agro_crops_handler)
    app.router.add_post(f"{ops}/agro-crops/{{item_id}}", ops_handlers.ops_agro_crop_item_handler)
    app.router.add_get(f"{ops}/sowings", ops_handlers.ops_sowings_handler)
    app.router.add_post(f"{ops}/sowings", ops_handlers.ops_sowings_handler)
    app.router.add_post(f"{ops}/sowings/{{item_id}}/status", ops_handlers.ops_sowing_status_handler)
    app.router.add_get(f"{ops}/works", ops_handlers.ops_works_handler)
    app.router.add_post(f"{ops}/works", ops_handlers.ops_works_handler)
    app.router.add_get(f"{ops}/machines", ops_handlers.ops_machines_list_handler)
    app.router.add_post(f"{ops}/machines", ops_handlers.ops_machines_list_handler)
    app.router.add_get(f"{ops}/machines/{{item_id}}", ops_handlers.ops_machine_360_handler)
    app.router.add_post(f"{ops}/machines/{{item_id}}", ops_handlers.ops_machine_update_handler)
    app.router.add_get(f"{ops}/harvests", ops_handlers.ops_harvests_list_handler)
    app.router.add_post(f"{ops}/harvests", ops_handlers.ops_harvests_list_handler)
    app.router.add_get(f"{ops}/production/kpis-26", ops_handlers.ops_kpis_26_handler)
    app.router.add_post(f"{ops}/implements", ops_handlers.ops_implement_handler)
    app.router.add_post(f"{ops}/materials", ops_handlers.ops_material_handler)
    app.router.add_post(f"{ops}/materials/move", ops_handlers.ops_material_move_handler)
    app.router.add_post(f"{ops}/materials/issue", ops_handlers.ops_material_issue_handler)
    app.router.add_post(f"{ops}/maintenance", ops_handlers.ops_maintenance_handler)
    app.router.add_post(f"{ops}/harvest/plan", ops_handlers.ops_harvest_plan_handler)
    app.router.add_post(f"{ops}/harvest/actual", ops_handlers.ops_harvest_actual_handler)
    app.router.add_post(f"{ops}/harvest/to-warehouse", ops_handlers.ops_harvest_warehouse_handler)
    app.router.add_post(f"{ops}/fields/costs", ops_handlers.ops_field_cost_handler)
    app.router.add_post(f"{ops}/production/bootstrap", ops_handlers.ops_production_bootstrap_handler)
    app.router.add_post(f"{ops}/production/alerts", ops_handlers.ops_production_alerts_handler)
    app.router.add_get(f"{ops}/finance/summary", ops_handlers.ops_finance_summary_handler)
    app.router.add_post(f"{ops}/calculations/preview", ops_handlers.ops_calc_preview_handler)
    app.router.add_get(f"{ops}/export/{{section}}", ops_handlers.ops_export_handler)
    app.router.add_get(f"{ops}/providers", ops_handlers.ops_providers_handler)
    app.router.add_post(f"{ops}/providers/custom", ops_handlers.ops_providers_custom_handler)
    app.router.add_post(f"{ops}/providers/ingest", ops_handlers.ops_providers_ingest_handler)
    app.router.add_post(f"{ops}/providers/refresh-all", ops_handlers.ops_providers_refresh_all_handler)
    app.router.add_get(f"{ops}/providers/observations", ops_handlers.ops_provider_observations_handler)
    app.router.add_get(f"{ops}/providers/{{provider_id}}", ops_handlers.ops_provider_detail_handler)
    app.router.add_post(f"{ops}/providers/{{provider_id}}/probe", ops_handlers.ops_provider_probe_handler)
    app.router.add_get(f"{ops}/logistics/dashboard", ops_handlers.ops_logistics_dashboard_handler)
    app.router.add_get(f"{ops}/markets/dashboard", ops_handlers.ops_markets_dashboard_handler)
    app.router.add_get(f"{ops}/markets/history", ops_handlers.ops_markets_history_handler)
    app.router.add_post(f"{ops}/markets/compare", ops_handlers.ops_markets_compare_handler)
    app.router.add_post(f"{ops}/markets/landed-cost", ops_handlers.ops_landed_cost_handler)
    app.router.add_get(f"{ops}/warehouses/dashboard", ops_handlers.ops_warehouse_dashboard_handler)
    app.router.add_post(f"{ops}/warehouses/operations", ops_handlers.ops_warehouse_operation_handler)
    app.router.add_post(f"{ops}/warehouses/receive", ops_handlers.ops_warehouse_receive_handler)
    app.router.add_post(f"{ops}/warehouses/issue", ops_handlers.ops_warehouse_issue_handler)
    app.router.add_get(f"{ops}/crops/directory", ops_handlers.ops_crop_directory_handler)
    app.router.add_get(f"{ops}/crops/{{item_id}}/balance", ops_handlers.ops_crop_balance_handler)
    app.router.add_post(f"{ops}/deliveries/{{item_id}}/progress", ops_handlers.ops_delivery_progress_handler)
    app.router.add_post(f"{ops}/alerts/evaluate", ops_handlers.ops_alerts_evaluate_handler)
    app.router.add_post(f"{ops}/reminders/evaluate", ops_handlers.ops_reminders_evaluate_handler)
    app.router.add_post(f"{ops}/calendar/{{item_id}}/remind", ops_handlers.ops_calendar_remind_handler)
    app.router.add_post(f"{ops}/notifications/{{item_id}}/actions", ops_handlers.ops_notification_action_handler)
    app.router.add_post(f"{ops}/tasks/from-entity", ops_handlers.ops_task_from_entity_handler)
    app.router.add_post(f"{ops}/bootstrap", ops_handlers.ops_bootstrap_handler)
    app.router.add_get(f"{ops}/scheduler", ops_handlers.ops_scheduler_handler)
    app.router.add_put(f"{ops}/scheduler", ops_handlers.ops_scheduler_handler)
    app.router.add_post(f"{ops}/scheduler", ops_handlers.ops_scheduler_handler)
    app.router.add_get(f"{ops}/channels", ops_handlers.ops_channels_handler)
    app.router.add_post(f"{ops}/intel/import", ops_handlers.ops_intel_import_handler)
    app.router.add_get(f"{ops}/reports", ops_handlers.ops_reports_handler)
    app.router.add_get(f"{ops}/reports/{{report_id}}", ops_handlers.ops_report_get_handler)
    app.router.add_post(f"{ops}/reports/generate", ops_handlers.ops_report_generate_handler)
    app.router.add_post(f"{ops}/reports/{{kind}}", ops_handlers.ops_report_generate_handler)
    app.router.add_get(f"{ops}/agents", ops_handlers.ops_agents_handler)
    app.router.add_post(f"{ops}/agents/run", ops_handlers.ops_agents_handler)
    app.router.add_get(f"{ops}/analytics/dashboard", ops_handlers.ops_analytics_dashboard_handler)
    app.router.add_get(f"{ops}/analytics", ops_handlers.ops_analytics_list_handler)
    app.router.add_post(f"{ops}/analytics/run", ops_handlers.ops_analytics_list_handler)
    app.router.add_get(f"{ops}/analytics/{{analysis_id}}", ops_handlers.ops_analytics_get_handler)
    app.router.add_post(f"{ops}/analytics/{{analysis_id}}/notify", ops_handlers.ops_analytics_notify_handler)
    app.router.add_post(f"{ops}/analytics/{{analysis_id}}/task", ops_handlers.ops_analytics_task_handler)
    app.router.add_post(f"{ops}/analytics/{{analysis_id}}/calendar", ops_handlers.ops_analytics_calendar_handler)
    app.router.add_post(f"{ops}/pipeline/rebuild", ops_handlers.ops_pipeline_rebuild_handler)
    app.router.add_get(f"{ops}/weather/dashboard", ops_handlers.ops_weather_dashboard_handler)
    app.router.add_get(f"{ops}/weather/overview", ops_handlers.ops_weather_overview_handler)
    app.router.add_get(f"{ops}/weather/regions", ops_handlers.ops_weather_regions_index_handler)
    app.router.add_get(f"{ops}/weather/regions/{{oblast_id}}", ops_handlers.ops_weather_region_handler)
    app.router.add_get(f"{ops}/weather/oblasts/{{oblast_id}}", ops_handlers.ops_weather_region_handler)
    app.router.add_get(f"{ops}/weather/forecast", ops_handlers.ops_weather_forecast_handler)
    app.router.add_get(f"{ops}/weather/outlook", ops_handlers.ops_weather_outlook_handler)
    app.router.add_get(f"{ops}/weather/agro-risk", ops_handlers.ops_weather_agro_risk_handler)
    app.router.add_get(f"{ops}/weather/recommendations", ops_handlers.ops_weather_recommendations_handler)
    app.router.add_post(f"{ops}/weather/refresh", ops_handlers.ops_weather_refresh_handler)
    app.router.add_get(f"{ops}/settings/desk", ops_handlers.ops_desk_settings_handler)
    app.router.add_put(f"{ops}/settings/desk", ops_handlers.ops_desk_settings_handler)
    app.router.add_post(f"{ops}/settings/desk", ops_handlers.ops_desk_settings_handler)
    app.router.add_post(f"{ops}/ai/ask", ops_handlers.ops_ask_ai_handler)
    app.router.add_get(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_post(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_get(f"{ops}/files/{{file_id}}/content", ops_handlers.ops_file_content_handler)
    app.router.add_post(f"{ops}/files/{{file_id}}/rename", ops_handlers.ops_file_rename_handler)
    app.router.add_post(f"{ops}/files/{{file_id}}/link", ops_handlers.ops_file_link_handler)
    app.router.add_get(f"{ops}/entities/{{kind}}", ops_handlers.ops_list_create_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}", ops_handlers.ops_list_create_handler)
    app.router.add_get(f"{ops}/{{alias}}", ops_handlers.ops_list_create_handler)
    app.router.add_post(f"{ops}/{{alias}}", ops_handlers.ops_list_create_handler)
    app.router.add_get(f"{ops}/entities/{{kind}}/{{item_id}}", ops_handlers.ops_entity_get_handler)
    app.router.add_get(f"{ops}/entities/{{kind}}/{{item_id}}/related", ops_handlers.ops_related_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}", ops_handlers.ops_entity_update_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}/archive", ops_handlers.ops_entity_archive_handler)
    app.router.add_post(f"{ops}/entities/{{kind}}/{{item_id}}/restore", ops_handlers.ops_entity_restore_handler)
