"""Register Auto Enterprise private ops routes (AUTO 1.2)."""

from __future__ import annotations

from aiohttp import web

from applications.auto_enterprise.api import analytics_handlers, crm_handlers, customs_handlers, document_handlers, logistics_handlers, ops_handlers, telegram_handlers
from applications.auto_enterprise.api.middleware import auth_middleware
from applications.auto_enterprise.config import DEFAULT_CONFIG


def register_auto_enterprise_routes(app: web.Application) -> None:
    if auth_middleware not in app.middlewares:
        app.middlewares.append(auth_middleware)

    ops = DEFAULT_CONFIG.api_prefix
    app.router.add_get(f"{ops}/health", ops_handlers.ops_health_handler)
    app.router.add_get(f"{ops}/roles", ops_handlers.ops_roles_handler)
    app.router.add_get(f"{ops}/catalogs", ops_handlers.ops_catalogs_handler)
    app.router.add_get(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_post(f"{ops}/dashboard", ops_handlers.ops_dashboard_handler)
    app.router.add_get(f"{ops}/vehicles", ops_handlers.ops_vehicles_handler)
    app.router.add_post(f"{ops}/vehicles", ops_handlers.ops_vehicles_handler)
    app.router.add_get(f"{ops}/vehicles/{{vehicle_id}}", ops_handlers.ops_vehicle_detail_handler)
    app.router.add_post(f"{ops}/vehicles/{{vehicle_id}}", ops_handlers.ops_vehicle_detail_handler)
    app.router.add_get(f"{ops}/expenses", ops_handlers.ops_expenses_handler)
    app.router.add_post(f"{ops}/expenses", ops_handlers.ops_expenses_handler)
    app.router.add_post(f"{ops}/expenses/{{expense_id}}", ops_handlers.ops_expense_item_handler)
    app.router.add_delete(f"{ops}/expenses/{{expense_id}}", ops_handlers.ops_expense_item_handler)
    app.router.add_get(f"{ops}/clients", ops_handlers.ops_clients_handler)
    app.router.add_post(f"{ops}/clients", ops_handlers.ops_clients_handler)
    app.router.add_get(f"{ops}/clients/{{client_id}}", ops_handlers.ops_client_item_handler)
    app.router.add_post(f"{ops}/clients/{{client_id}}", ops_handlers.ops_client_item_handler)
    app.router.add_get(f"{ops}/search", ops_handlers.ops_search_handler)
    app.router.add_get(f"{ops}/documents/desk", document_handlers.documents_desk_handler)
    app.router.add_get(f"{ops}/documents/packages", document_handlers.documents_packages_handler)
    app.router.add_get(f"{ops}/documents/templates", document_handlers.documents_templates_handler)
    app.router.add_post(f"{ops}/documents/templates", document_handlers.documents_templates_handler)
    app.router.add_post(f"{ops}/documents/templates/{{template_id}}", document_handlers.documents_template_item_handler)
    app.router.add_delete(f"{ops}/documents/templates/{{template_id}}", document_handlers.documents_template_item_handler)
    app.router.add_post(f"{ops}/documents/generate", document_handlers.documents_generate_handler)
    app.router.add_get(f"{ops}/documents/export", document_handlers.documents_export_handler)
    app.router.add_get(f"{ops}/documents/zip", document_handlers.documents_zip_handler)
    app.router.add_get(f"{ops}/documents/dossiers/{{vehicle_id}}", document_handlers.documents_dossiers_handler)
    app.router.add_get(f"{ops}/documents/timeline", document_handlers.documents_timeline_handler)
    app.router.add_post(f"{ops}/documents/check", document_handlers.documents_check_handler)
    app.router.add_post(f"{ops}/documents/company", document_handlers.documents_company_handler)
    app.router.add_post(f"{ops}/documents/{{document_id}}/status", document_handlers.documents_status_handler)
    app.router.add_get(f"{ops}/documents/{{document_id}}", ops_handlers.ops_document_get_handler)
    app.router.add_get(f"{ops}/documents", ops_handlers.ops_documents_handler)
    app.router.add_post(f"{ops}/documents", ops_handlers.ops_documents_handler)
    app.router.add_post(f"{ops}/documents/{{document_id}}", logistics_handlers.document_item_update_handler)
    app.router.add_delete(f"{ops}/documents/{{document_id}}", ops_handlers.ops_document_item_handler)
    app.router.add_get(f"{ops}/photos", ops_handlers.ops_photos_handler)
    app.router.add_post(f"{ops}/photos", ops_handlers.ops_photos_handler)
    app.router.add_post(f"{ops}/photos/{{photo_id}}/cover", ops_handlers.ops_photo_item_handler)
    app.router.add_delete(f"{ops}/photos/{{photo_id}}", ops_handlers.ops_photo_item_handler)
    app.router.add_get(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks", ops_handlers.ops_tasks_handler)
    app.router.add_post(f"{ops}/tasks/{{task_id}}/complete", ops_handlers.ops_task_complete_handler)
    app.router.add_get(f"{ops}/audit", ops_handlers.ops_audit_handler)
    app.router.add_get(f"{ops}/reports", ops_handlers.ops_reports_handler)
    app.router.add_get(f"{ops}/settings", ops_handlers.ops_settings_handler)
    app.router.add_get(f"{ops}/telegram", ops_handlers.ops_telegram_handler)
    app.router.add_get(f"{ops}/telegram/status", telegram_handlers.telegram_status_handler)
    app.router.add_get(f"{ops}/telegram/members", telegram_handlers.telegram_members_handler)
    app.router.add_post(f"{ops}/telegram/members", telegram_handlers.telegram_members_handler)
    app.router.add_post(f"{ops}/telegram/inbound", telegram_handlers.telegram_inbound_handler)
    app.router.add_post(f"{ops}/telegram/summaries/{{kind}}", telegram_handlers.telegram_summary_handler)
    app.router.add_get(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_post(f"{ops}/files", ops_handlers.ops_files_handler)
    app.router.add_get(f"{ops}/files/{{file_id}}/content", ops_handlers.ops_file_content_handler)

    app.router.add_get(f"{ops}/logistics", logistics_handlers.logistics_desk_handler)
    app.router.add_get(f"{ops}/logistics/shipments", logistics_handlers.shipments_handler)
    app.router.add_post(f"{ops}/logistics/shipments", logistics_handlers.shipments_handler)
    app.router.add_get(f"{ops}/logistics/shipments/{{shipment_id}}", logistics_handlers.shipment_detail_handler)
    app.router.add_post(f"{ops}/logistics/shipments/{{shipment_id}}", logistics_handlers.shipment_detail_handler)
    app.router.add_post(f"{ops}/logistics/shipments/{{shipment_id}}/events", logistics_handlers.shipment_events_handler)
    app.router.add_get(f"{ops}/logistics/shipments/{{shipment_id}}/tracking", logistics_handlers.shipment_tracking_handler)
    app.router.add_post(f"{ops}/logistics/shipments/{{shipment_id}}/tracking", logistics_handlers.shipment_tracking_handler)
    app.router.add_get(f"{ops}/logistics/providers", logistics_handlers.logistics_providers_handler)
    app.router.add_post(f"{ops}/logistics/providers", logistics_handlers.logistics_providers_handler)
    app.router.add_post(f"{ops}/logistics/providers/{{provider_id}}", logistics_handlers.logistics_provider_item_handler)
    app.router.add_post(f"{ops}/logistics/providers/{{provider_id}}/check", logistics_handlers.logistics_provider_check_handler)
    app.router.add_get(f"{ops}/logistics/vehicles/{{vehicle_id}}/history", logistics_handlers.vehicle_logistics_history_handler)
    app.router.add_get(f"{ops}/logistics/carriers", logistics_handlers.carriers_handler)
    app.router.add_post(f"{ops}/logistics/carriers", logistics_handlers.carriers_handler)
    app.router.add_post(f"{ops}/logistics/carriers/{{carrier_id}}", logistics_handlers.carrier_item_handler)
    app.router.add_get(f"{ops}/logistics/drivers", logistics_handlers.drivers_handler)
    app.router.add_post(f"{ops}/logistics/drivers", logistics_handlers.drivers_handler)
    app.router.add_post(f"{ops}/logistics/drivers/{{driver_id}}", logistics_handlers.driver_item_handler)
    app.router.add_get(f"{ops}/logistics/trucks", logistics_handlers.trucks_handler)
    app.router.add_post(f"{ops}/logistics/trucks", logistics_handlers.trucks_handler)
    app.router.add_post(f"{ops}/logistics/trucks/{{truck_id}}", logistics_handlers.truck_item_handler)
    app.router.add_get(f"{ops}/logistics/containers", logistics_handlers.containers_handler)
    app.router.add_post(f"{ops}/logistics/containers", logistics_handlers.containers_handler)
    app.router.add_get(f"{ops}/logistics/containers/{{container_id}}", logistics_handlers.container_detail_handler)
    app.router.add_post(f"{ops}/logistics/containers/{{container_id}}", logistics_handlers.container_detail_handler)
    app.router.add_post(f"{ops}/logistics/containers/{{container_id}}/vehicles", logistics_handlers.container_vehicles_handler)
    app.router.add_get(f"{ops}/logistics/vessels", logistics_handlers.vessels_handler)
    app.router.add_post(f"{ops}/logistics/vessels", logistics_handlers.vessels_handler)
    app.router.add_post(f"{ops}/logistics/vessels/{{vessel_id}}", logistics_handlers.vessel_item_handler)
    app.router.add_get(f"{ops}/logistics/ports", logistics_handlers.ports_handler)
    app.router.add_post(f"{ops}/logistics/ports", logistics_handlers.ports_handler)
    app.router.add_get(f"{ops}/logistics/notifications", logistics_handlers.notifications_handler)
    app.router.add_get(f"{ops}/logistics/settings", logistics_handlers.logistics_settings_handler)
    app.router.add_post(f"{ops}/logistics/settings", logistics_handlers.logistics_settings_handler)
    app.router.add_post(f"{ops}/logistics/demo", logistics_handlers.logistics_demo_handler)

    app.router.add_get(f"{ops}/customs", customs_handlers.customs_desk_handler)
    app.router.add_get(f"{ops}/customs/cases", customs_handlers.cases_handler)
    app.router.add_post(f"{ops}/customs/cases", customs_handlers.cases_handler)
    app.router.add_get(f"{ops}/customs/cases/{{case_id}}", customs_handlers.case_detail_handler)
    app.router.add_post(f"{ops}/customs/cases/{{case_id}}", customs_handlers.case_detail_handler)
    app.router.add_get(f"{ops}/customs/cases/{{case_id}}/summary", customs_handlers.case_summary_handler)
    app.router.add_post(f"{ops}/customs/cases/{{case_id}}/payments", customs_handlers.case_payments_handler)
    app.router.add_post(f"{ops}/customs/cases/{{case_id}}/payments/{{expense_id}}/confirm", customs_handlers.case_payment_confirm_handler)
    app.router.add_post(f"{ops}/customs/cases/{{case_id}}/calculate", customs_handlers.case_calculate_handler)
    app.router.add_get(f"{ops}/customs/brokers", customs_handlers.brokers_handler)
    app.router.add_post(f"{ops}/customs/brokers", customs_handlers.brokers_handler)
    app.router.add_post(f"{ops}/customs/brokers/{{broker_id}}", customs_handlers.broker_item_handler)
    app.router.add_get(f"{ops}/customs/settings", customs_handlers.customs_settings_handler)
    app.router.add_post(f"{ops}/customs/settings", customs_handlers.customs_settings_handler)
    app.router.add_post(f"{ops}/customs/demo", customs_handlers.customs_demo_handler)

    app.router.add_get(f"{ops}/crm/deals", crm_handlers.deals_handler)
    app.router.add_post(f"{ops}/crm/deals", crm_handlers.deals_handler)
    app.router.add_get(f"{ops}/crm/deals/{{deal_id}}", crm_handlers.deal_detail_handler)
    app.router.add_post(f"{ops}/crm/deals/{{deal_id}}", crm_handlers.deal_detail_handler)
    app.router.add_get(f"{ops}/crm/reservations", crm_handlers.reservations_handler)
    app.router.add_post(f"{ops}/crm/reservations", crm_handlers.reservations_handler)
    app.router.add_post(f"{ops}/crm/reservations/{{reservation_id}}", crm_handlers.reservation_item_handler)
    app.router.add_get(f"{ops}/crm/sales", crm_handlers.sales_handler)
    app.router.add_post(f"{ops}/crm/sales", crm_handlers.sales_handler)
    app.router.add_post(f"{ops}/crm/sales/{{sale_id}}", crm_handlers.sale_item_handler)
    app.router.add_get(f"{ops}/crm/receipts", crm_handlers.receipts_handler)
    app.router.add_post(f"{ops}/crm/receipts", crm_handlers.receipts_handler)
    app.router.add_post(f"{ops}/crm/receipts/{{receipt_id}}", crm_handlers.receipt_item_handler)
    app.router.add_post(f"{ops}/crm/demo", crm_handlers.crm_demo_handler)

    app.router.add_get(f"{ops}/analytics/director", analytics_handlers.analytics_director_handler)
    app.router.add_get(f"{ops}/analytics/economics", analytics_handlers.analytics_economics_handler)
    app.router.add_get(f"{ops}/analytics/ranking", analytics_handlers.analytics_ranking_handler)
    app.router.add_get(f"{ops}/analytics/finance", analytics_handlers.analytics_finance_handler)
    app.router.add_get(f"{ops}/analytics/cashflow", analytics_handlers.analytics_cashflow_handler)
    app.router.add_get(f"{ops}/analytics/receivables", analytics_handlers.analytics_receivables_handler)
    app.router.add_get(f"{ops}/analytics/sales", analytics_handlers.analytics_sales_handler)
    app.router.add_get(f"{ops}/analytics/managers", analytics_handlers.analytics_managers_handler)
    app.router.add_get(f"{ops}/analytics/logistics", analytics_handlers.analytics_logistics_handler)
    app.router.add_get(f"{ops}/analytics/suppliers", analytics_handlers.analytics_suppliers_handler)
    app.router.add_get(f"{ops}/analytics/customs", analytics_handlers.analytics_customs_handler)
    app.router.add_get(f"{ops}/analytics/repair", analytics_handlers.analytics_repair_handler)
    app.router.add_get(f"{ops}/analytics/documents", analytics_handlers.analytics_documents_handler)
    app.router.add_get(f"{ops}/analytics/funnel", analytics_handlers.analytics_funnel_handler)
    app.router.add_get(f"{ops}/analytics/risks", analytics_handlers.analytics_risks_handler)
    app.router.add_get(f"{ops}/analytics/export", analytics_handlers.analytics_export_handler)
    app.router.add_post(f"{ops}/analytics/ai", analytics_handlers.analytics_ai_handler)
    app.router.add_post(f"{ops}/analytics/demo", analytics_handlers.analytics_demo_handler)
    app.router.add_post(f"{ops}/analytics/alerts", analytics_handlers.analytics_alerts_handler)
    app.router.add_get(f"{ops}/finance/accounts", analytics_handlers.finance_accounts_handler)
    app.router.add_post(f"{ops}/finance/accounts", analytics_handlers.finance_accounts_handler)
