"""Builder catalog and framework definitions — Sprint 28.1."""

from __future__ import annotations

from typing import Any

FRAMEWORK_PHASES = (
    "step",
    "explanation",
    "information",
    "example",
    "preview",
    "create",
)

AI_BUILDER_STEPS = (
    "Number of AI Agents",
    "AI Agent Name",
    "Profession",
    "Specialization",
    "Knowledge",
    "Skills",
    "Permissions",
    "Personality",
    "Summary",
    "Create",
)

CONCIERGE_STEPS = (
    "Concierge Identity",
    "Concierge Role",
    "Organization Access",
    "AI Team Center",
    "AI Orchestration",
    "Proactive Assistance",
    "Owner Relationship",
    "Smart Recommendation Engine",
    "Group AI Chat Foundation",
    "Summary",
    "Create",
)

VERTICAL_STEPS = (
    "Vertical Information",
    "Select Industry",
    "Module Selection",
    "AI Configuration",
    "AI Concierge",
    "Dashboard",
    "Workspace",
    "Live Organization Preview",
    "Summary",
    "Create",
)

UNIVERSAL_FRAMEWORK_STEPS = (
    "Universal Builder Template",
    "Universal UI Components",
    "Validation Framework",
    "Live Preview Engine",
    "Builder Registry",
    "Template Engine",
    "Extension System",
    "Builder SDK",
    "Summary",
    "Create",
)

GENERIC_STEPS = (
    "Define Scope",
    "Configure Structure",
    "Set Options",
    "Review Information",
    "Preview",
    "Create",
)

BUILDERS: list[dict[str, Any]] = [
    {
        "id": "dashboard",
        "name": "Dashboard",
        "route": "/platform-builder",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
    },
    {
        "id": "universal_framework",
        "name": "Universal Builder Framework",
        "route": "/platform-builder/framework",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "steps": list(UNIVERSAL_FRAMEWORK_STEPS),
        "purpose": "One common architecture for every Platform Builder.",
    },
    {
        "id": "vertical",
        "name": "Vertical Builder",
        "route": "/platform-builder/vertical",
        "kind": "builder",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "steps": list(VERTICAL_STEPS),
        "purpose": "Visually create complete Enterprise Verticals without programming.",
    },
    {
        "id": "ai",
        "name": "AI Builder",
        "route": "/platform-builder/ai",
        "kind": "builder",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "steps": list(AI_BUILDER_STEPS),
        "purpose": "Compose AI agent teams with clear roles and personalities.",
    },
    {
        "id": "concierge",
        "name": "Concierge Builder",
        "route": "/platform-builder/concierge",
        "kind": "builder",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "steps": list(CONCIERGE_STEPS),
        "purpose": "Configure the single organizational Concierge assistant.",
        "constraints": {"one_per_organization": True, "separate_from_ai_agents": True},
    },
    {
        "id": "ai_team",
        "name": "AI Team Center",
        "route": "/platform-builder/ai-team",
        "kind": "hub",
        "status": "operational",
        "learning_supported": False,
        "frame_only": False,
        "purpose": "Monitor and manage all AI Specialists for the organization.",
    },
    {
        "id": "crm",
        "name": "CRM Builder",
        "route": "/platform-builder/crm",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "erp",
        "name": "ERP Builder",
        "route": "/platform-builder/erp",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "workflow",
        "name": "Workflow Builder",
        "route": "/platform-builder/workflow",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "knowledge",
        "name": "Knowledge Builder",
        "route": "/platform-builder/knowledge",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "automation",
        "name": "Automation Builder",
        "route": "/platform-builder/automation",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "dashboard_builder",
        "name": "Dashboard Builder",
        "route": "/platform-builder/dashboard-builder",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "template",
        "name": "Template Builder",
        "route": "/platform-builder/template",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "marketplace",
        "name": "Marketplace Builder",
        "route": "/platform-builder/marketplace",
        "kind": "builder",
        "status": "frame",
        "learning_supported": True,
        "frame_only": True,
        "steps": list(GENERIC_STEPS),
    },
    {
        "id": "academy",
        "name": "Builder Academy 2.0",
        "route": "/platform-builder/academy",
        "kind": "academy",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Interactive learning, AI Guide, and adaptive builder guidance.",
    },
    {
        "id": "collaborative_ai",
        "name": "Collaborative AI",
        "route": "/platform-builder/collaborative-ai",
        "kind": "builder",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Coordinate AI Specialists via Concierge for collective intelligence.",
    },
    {
        "id": "operations_center",
        "name": "AI Operations Center",
        "route": "/platform-builder/operations",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Real-time visual control room for the AI Organization.",
    },
    {
        "id": "team_map",
        "name": "AI Team Map",
        "route": "/platform-builder/team-map",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Live Organization Map with Visual Event Bus and relationship engine.",
    },
    {
        "id": "visual_behavior",
        "name": "Visual Behavior Engine",
        "route": "/platform-builder/visual-behavior",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Event-bus-driven visual behaviors and animations — no business logic.",
    },
    {
        "id": "rendering",
        "name": "Visual Rendering Engine",
        "route": "/platform-builder/rendering",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "GPU-friendly rendering with LOD, viewport culling, and layer system.",
    },
    {
        "id": "themes",
        "name": "Visual Theme Engine",
        "route": "/platform-builder/themes",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Enterprise visual identity, branding, and live theme switching — appearance only.",
    },
    {
        "id": "assets",
        "name": "Visual Asset Registry",
        "route": "/platform-builder/assets",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Store, version, optimize, and browse visual assets — separated from business logic.",
    },
    {
        "id": "simulation",
        "name": "Visual Simulation Engine",
        "route": "/platform-builder/simulation",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Live enterprise simulation from Visual Event Bus only — never creates fake events.",
    },
    {
        "id": "director",
        "name": "Visual Director Engine",
        "route": "/platform-builder/director",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Scene orchestration and focus/attention direction — presentation only, no business events.",
    },
    {
        "id": "story",
        "name": "Visual Story Engine",
        "route": "/platform-builder/story",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Enterprise storytelling from verified Visual Event Bus events — never creates or reorders business events.",
    },
    {
        "id": "intelligence",
        "name": "Visual Intelligence Engine",
        "route": "/platform-builder/intelligence",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Visual analytics and recommendations from verified events — no business logic changes or business events.",
    },
    {
        "id": "experience",
        "name": "Visual Experience Engine",
        "route": "/platform-builder/experience",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Unified enterprise UX coordinating all visual subsystems — presentation only, no business logic.",
    },
    {
        "id": "workspace_os",
        "name": "Enterprise Workspace OS",
        "route": "/platform-builder/workspace-os",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Unified operating environment for every module with multi-workspace contexts — role aware.",
    },
    {
        "id": "command_center",
        "name": "Enterprise Command Center",
        "route": "/platform-builder/command-center",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Universal command interface for modules, AI, workspaces and services — interaction orchestration only.",
    },
    {
        "id": "navigation_intelligence",
        "name": "Navigation Intelligence Engine",
        "route": "/platform-builder/navigation-intelligence",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Predicts and simplifies navigation from verified context — never executes business logic.",
    },
    {
        "id": "workflow_intelligence",
        "name": "Workflow Intelligence OS",
        "route": "/platform-builder/workflow-intelligence",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Workflow visibility, dependency analysis and recommendations — never executes business logic.",
    },
    {
        "id": "digital_twin",
        "name": "Enterprise Digital Twin",
        "route": "/platform-builder/digital-twin",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Read-only realtime mirror of verified platform state — never owns business logic.",
    },
    {
        "id": "twin_intelligence",
        "name": "Digital Twin Intelligence",
        "route": "/platform-builder/twin-intelligence",
        "kind": "hub",
        "status": "operational",
        "learning_supported": True,
        "frame_only": False,
        "purpose": "Analyzes verified Digital Twin data — never changes state or executes workflows.",
    },
    {
        "id": "god_mode",
        "name": "God Mode",
        "route": "/platform-builder/god-mode",
        "kind": "god_mode",
        "status": "operational",
        "learning_supported": False,
        "frame_only": False,
        "requires_role": "platform_owner",
        "visibility": "platform_owner_only",
    },
]


def get_builder(builder_id: str) -> dict[str, Any] | None:
    return next((b for b in BUILDERS if b["id"] == builder_id), None)


def menu_for_role(role: str | None = None) -> list[dict[str, Any]]:
    items = []
    for b in BUILDERS:
        if b.get("requires_role") == "platform_owner" and role != "platform_owner":
            continue
        items.append(
            {
                "id": b["id"],
                "name": b["name"],
                "route": b["route"],
                "kind": b["kind"],
                "status": b["status"],
            }
        )
    return items
